import type { GrammarPoint } from "./types";

export const GRAMMAR_POINTS: GrammarPoint[] = [
  {
    id: "gr001",
    title: "관사 (A / An / The)",
    cefrLevel: "A1",
    brief: "셀 수 있는 명사 앞에 쓰이는 관사",
    rule: "a/an = 처음 언급하거나 특정되지 않은 것 | the = 이미 알고 있거나 특정된 것",
    examples: [
      { en: "I saw a dog in the park.", ko: "공원에서 개 한 마리를 봤어. (처음 언급)", note: "처음 보는 개 → a" },
      { en: "The dog was very friendly.", ko: "그 개는 매우 친절했어. (이미 언급됨)", note: "방금 말한 그 개 → the" },
      { en: "She is an engineer.", ko: "그녀는 엔지니어야.", note: "직업/역할 앞에 a/an 사용" },
    ],
    commonMistake: "She is the engineer. (✗ 일반적 직업일 땐 a/an)",
    tip: "모음 소리(a/e/i/o/u)로 시작하면 an: an apple, an hour",
  },
  {
    id: "gr002",
    title: "현재 단순 vs 현재 진행",
    cefrLevel: "A2",
    brief: "습관/사실 vs 지금 진행 중인 동작",
    rule: "현재 단순: I work / He works — 습관, 진실, 일정 | 현재 진행: I am working — 지금 이 순간",
    examples: [
      { en: "I work at a hospital.", ko: "나는 병원에서 일한다. (직업/습관)", note: "일반적 사실" },
      { en: "I am working from home today.", ko: "오늘은 집에서 일하고 있어. (지금)", note: "지금 이 순간" },
      { en: "He always drinks coffee in the morning.", ko: "그는 항상 아침에 커피를 마신다.", note: "always = 습관 → 현재 단순" },
    ],
    commonMistake: "I am knowing the answer. (✗ 상태동사는 진행형 ✗: know, like, want, need)",
  },
  {
    id: "gr003",
    title: "과거 단순 vs 현재 완료",
    cefrLevel: "B1",
    brief: "완료된 과거 사건 vs 현재와 연결된 경험",
    rule: "과거 단순: 특정 시점에 끝난 일 (yesterday, last week, in 2020) | 현재 완료: 경험·결과가 현재에 영향 (have + p.p.)",
    examples: [
      { en: "I visited Japan last year.", ko: "나는 작년에 일본을 방문했다. (특정 과거)", note: "last year → 과거 단순" },
      { en: "I have visited Japan twice.", ko: "나는 일본을 두 번 방문한 적 있다. (경험)", note: "twice → 현재완료" },
      { en: "She has just finished her homework.", ko: "그녀는 방금 숙제를 끝냈다.", note: "just → 현재완료" },
    ],
    commonMistake: "I have seen him yesterday. (✗ yesterday와 현재완료는 함께 못 씀)",
    tip: "ever/never/already/yet/just/recently → 현재완료와 자주 쓰임",
  },
  {
    id: "gr004",
    title: "조동사 (Must / Should / May / Might)",
    cefrLevel: "B1",
    brief: "의무·추측·허가를 나타내는 조동사",
    rule: "must = 강한 의무/강한 추측 | should = 조언/약한 의무 | may = 허가/가능성(50%) | might = 약한 가능성(30%)",
    examples: [
      { en: "You must wear a seatbelt.", ko: "안전벨트를 반드시 매야 한다. (의무)" },
      { en: "You should get more sleep.", ko: "수면을 더 취해야 할 것 같아. (조언)" },
      { en: "She might come later.", ko: "그녀는 나중에 올 수도 있어. (약한 가능성)" },
    ],
    tip: "must와 have to의 차이: must는 주관적(본인 판단), have to는 외부 규정",
  },
  {
    id: "gr005",
    title: "조건문 — 1형식 (Real Condition)",
    cefrLevel: "B1",
    brief: "현실적으로 가능한 미래 조건",
    rule: "If + 현재 단순, will + 동사원형",
    examples: [
      { en: "If it rains, I will take an umbrella.", ko: "비가 오면 우산을 챙길 것이다." },
      { en: "If you study hard, you will pass the exam.", ko: "열심히 공부하면 시험에 합격할 것이다." },
      { en: "If she calls me, I'll tell her the news.", ko: "그녀가 전화하면 소식을 전할 것이다." },
    ],
    commonMistake: "If it will rain, I will take... (✗ if절에는 will 안 씀)",
  },
  {
    id: "gr006",
    title: "조건문 — 2형식 (Unreal Condition)",
    cefrLevel: "B2",
    brief: "현실과 다른 가정",
    rule: "If + 과거 단순, would + 동사원형",
    examples: [
      { en: "If I had more time, I would learn a new language.", ko: "시간이 더 있다면 새 언어를 배울 텐데. (현실은 시간이 없음)" },
      { en: "If she were taller, she could be a model.", ko: "그녀가 더 키가 컸다면 모델이 될 수 있었을 텐데." },
      { en: "What would you do if you won the lottery?", ko: "복권에 당첨된다면 어떻게 할 것인가?" },
    ],
    tip: "If I were (not was) — 가정법에서는 be동사로 were를 씀",
  },
  {
    id: "gr007",
    title: "수동태 (Passive Voice)",
    cefrLevel: "B1",
    brief: "행위의 대상을 주어로",
    rule: "be + 과거분사 (p.p.) — 행위자보다 결과/대상이 중요할 때",
    examples: [
      { en: "The report was written by her.", ko: "그 보고서는 그녀에 의해 쓰여졌다." },
      { en: "English is spoken all over the world.", ko: "영어는 전 세계에서 사용된다." },
      { en: "The meeting has been postponed.", ko: "회의가 연기되었다." },
    ],
    tip: "by + 행위자는 중요할 때만 씀. The car was stolen. (by whom = 불필요)",
  },
  {
    id: "gr008",
    title: "관계절 (Who / Which / That)",
    cefrLevel: "B1",
    brief: "명사를 수식하는 절",
    rule: "who = 사람 | which = 사물 | that = 사람/사물 모두 (비제한적 관계절에는 that 불가)",
    examples: [
      { en: "The man who lives next door is a doctor.", ko: "옆집에 사는 그 남자는 의사이다." },
      { en: "The book which I bought is very interesting.", ko: "내가 산 그 책은 매우 흥미롭다." },
      { en: "She is the student that got the highest score.", ko: "그녀는 가장 높은 점수를 받은 학생이다." },
    ],
    commonMistake: "The book, that I bought, is... (✗ 비제한적 절에는 that 쓰지 않음)",
  },
  {
    id: "gr009",
    title: "동명사 vs 부정사",
    cefrLevel: "B1",
    brief: "동사 뒤 -ing / to + 동사원형 선택",
    rule: "enjoy/avoid/finish/consider + -ing | want/decide/hope/plan + to + V | like/love/hate/start는 둘 다 가능",
    examples: [
      { en: "I enjoy reading books.", ko: "나는 책 읽는 것을 즐긴다. (enjoy + -ing)" },
      { en: "She decided to study abroad.", ko: "그녀는 유학하기로 결심했다. (decide + to)" },
      { en: "Stop talking and start working!", ko: "말을 그만하고 일을 시작해! (stop + -ing)" },
    ],
    tip: "remember/forget/stop은 뒤에 무엇이 오느냐에 따라 의미가 달라짐: I stopped to smoke (흡연하려고 멈춤) vs I stopped smoking (흡연을 그만둠)",
  },
  {
    id: "gr010",
    title: "비교급 & 최상급",
    cefrLevel: "A2",
    brief: "두 가지를 비교하거나 가장 높은 정도 표현",
    rule: "짧은 형용사: -er / -est | 긴 형용사: more / the most | 불규칙: good→better→best, bad→worse→worst",
    examples: [
      { en: "This phone is cheaper than that one.", ko: "이 폰이 저것보다 싸다." },
      { en: "She is the most talented student in the class.", ko: "그녀는 반에서 가장 재능 있는 학생이다." },
      { en: "Today is worse than yesterday.", ko: "오늘이 어제보다 더 나쁘다." },
    ],
    commonMistake: "more cheaper (✗), more better (✗) — 이중 비교는 안 됨",
  },
  {
    id: "gr011",
    title: "가산명사 vs 불가산명사",
    cefrLevel: "A2",
    brief: "셀 수 있는 명사와 셀 수 없는 명사",
    rule: "가산: a/an, some/any, a few, many + 복수 | 불가산: some/any, a little, much + 단수",
    examples: [
      { en: "Can I have some water? / Can I have a glass of water?", ko: "물 좀 주실 수 있나요? (water는 불가산)" },
      { en: "I need some advice.", ko: "나는 조언이 필요하다. (advice는 불가산)" },
      { en: "There are a few chairs left.", ko: "의자가 몇 개 남아있다." },
    ],
    tip: "불가산명사: water, milk, information, advice, news, luggage, furniture, money, homework",
  },
  {
    id: "gr012",
    title: "간접화법 (Reported Speech)",
    cefrLevel: "B2",
    brief: "누군가가 한 말을 간접적으로 전달",
    rule: "직접화법 → 간접화법: 시제를 한 단계 뒤로 + 인칭/부사 변경",
    examples: [
      { en: "He said, 'I am tired.' → He said (that) he was tired.", ko: "'피곤해.' → 그가 피곤하다고 했다." },
      { en: "She said, 'I will call you.' → She said she would call me.", ko: "'전화할게.' → 전화하겠다고 했다." },
      { en: "He asked, 'Do you speak Korean?' → He asked if I spoke Korean.", ko: "한국어 할 줄 아느냐고 물었다." },
    ],
    commonMistake: "He said me (✗) → He told me (O). say는 간접목적어 없이 씀",
  },
  {
    id: "gr013",
    title: "미래 표현 (Will vs Going to)",
    cefrLevel: "A2",
    brief: "미래를 나타내는 두 가지 표현의 차이",
    rule: "will = 즉흥 결정, 예측, 약속 | going to = 이미 계획된 것, 근거가 있는 예측",
    examples: [
      { en: "I'll have the pasta, please. (즉흥)", ko: "파스타로 주세요. (지금 막 결정)" },
      { en: "I'm going to visit Paris next month. (계획)", ko: "다음 달에 파리를 방문할 예정이야." },
      { en: "Look at those clouds — it's going to rain.", ko: "저 구름 봐 — 비가 올 것 같아. (근거 있는 예측)" },
    ],
  },
  {
    id: "gr014",
    title: "전치사 OF / IN / ON / AT",
    cefrLevel: "A1",
    brief: "장소와 시간을 나타내는 핵심 전치사",
    rule: "AT (특정 시각/장소) | ON (날짜/표면/요일) | IN (기간/도시/건물 내부)",
    examples: [
      { en: "I'll meet you at 7 PM at the café.", ko: "오후 7시에 카페에서 만나자." },
      { en: "The meeting is on Monday / on March 15th.", ko: "회의는 월요일에 / 3월 15일에 있다." },
      { en: "She lives in Seoul / in Korea / in summer.", ko: "그녀는 서울/한국에 살고 있다 / 여름에" },
    ],
    tip: "of = 소속/구성: a cup of tea, the capital of Korea",
  },
  {
    id: "gr015",
    title: "접속사 (Because / Although / However)",
    cefrLevel: "B1",
    brief: "원인·대조를 연결하는 표현",
    rule: "because (이유절) | although/even though (대조절 — 같은 문장) | however (대조 — 새 문장)",
    examples: [
      { en: "I was late because of the traffic.", ko: "교통 때문에 늦었다." },
      { en: "Although she was tired, she kept working.", ko: "피곤했음에도 불구하고 그녀는 계속 일했다." },
      { en: "The plan is risky; however, it might work.", ko: "그 계획은 위험하다; 그러나 효과가 있을 수도 있다." },
    ],
    commonMistake: "Although it was cold, but she wore a T-shirt. (✗ although와 but는 함께 쓰지 않음)",
  },
];
