import type { EnWord, EnCategory } from "./types";

export const EN_CATEGORIES: EnCategory[] = [
  { key: "basic-verbs",   label: "기초 동사",       emoji: "⚡", cefrRange: "A1–A2" },
  { key: "daily-life",    label: "일상생활",         emoji: "🏠", cefrRange: "A1–A2" },
  { key: "emotions",      label: "감정·성격",        emoji: "❤️", cefrRange: "A2–B1" },
  { key: "travel",        label: "여행·교통",        emoji: "✈️", cefrRange: "A2–B1" },
  { key: "health",        label: "건강·신체",        emoji: "🏥", cefrRange: "A2–B1" },
  { key: "workplace",     label: "직장·비즈니스",    emoji: "💼", cefrRange: "B1–B2" },
  { key: "academic",      label: "학문·교육",        emoji: "📚", cefrRange: "B2–C1" },
  { key: "adjectives",    label: "형용사",           emoji: "🎨", cefrRange: "A1–B1" },
  { key: "society",       label: "사회·환경",        emoji: "🌍", cefrRange: "B1–B2" },
  { key: "advanced",      label: "고급 어휘",        emoji: "💎", cefrRange: "C1–C2" },
];

export const EN_VOCAB: EnWord[] = [
  // ── 기초 동사 A1 ──
  { id: "ev001", word: "achieve", pronunciation: "/əˈtʃiːv/", partOfSpeech: "verb", cefrLevel: "B1", category: "basic-verbs", meaning: "달성하다, 이루다", example: { en: "She worked hard to achieve her goals.", ko: "그녀는 목표를 달성하기 위해 열심히 일했다." }, synonyms: ["accomplish", "attain", "reach"], wordFamily: ["achievement", "achievable", "overachieve"], tip: "achieve + 목표/결과. '열심히 해서 이루다'는 뉘앙스" },
  { id: "ev002", word: "allow", pronunciation: "/əˈlaʊ/", partOfSpeech: "verb", cefrLevel: "A2", category: "basic-verbs", meaning: "허락하다, 허용하다", example: { en: "Please allow me to explain.", ko: "제가 설명할 수 있도록 허락해 주세요." }, synonyms: ["permit", "let", "enable"], antonyms: ["forbid", "prevent", "deny"] },
  { id: "ev003", word: "apply", pronunciation: "/əˈplaɪ/", partOfSpeech: "verb", cefrLevel: "A2", category: "basic-verbs", meaning: "지원하다; 적용하다", example: { en: "I applied for a job at a tech company.", ko: "나는 기술 회사에 취업 지원을 했다." }, synonyms: ["submit", "use"], wordFamily: ["application", "applicant", "applicable"] },
  { id: "ev004", word: "avoid", pronunciation: "/əˈvɔɪd/", partOfSpeech: "verb", cefrLevel: "B1", category: "basic-verbs", meaning: "피하다, 회피하다", example: { en: "Try to avoid eating too much sugar.", ko: "설탕을 너무 많이 먹는 것을 피하세요." }, synonyms: ["evade", "prevent", "escape"], antonyms: ["face", "confront"], tip: "avoid + -ing 형태로 씀 (avoid to do ✗)" },
  { id: "ev005", word: "consider", pronunciation: "/kənˈsɪdər/", partOfSpeech: "verb", cefrLevel: "B1", category: "basic-verbs", meaning: "고려하다, 생각하다", example: { en: "You should consider all your options before deciding.", ko: "결정하기 전에 모든 선택지를 고려해야 한다." }, synonyms: ["think about", "contemplate", "weigh"], wordFamily: ["consideration", "considerable", "considerably"] },
  { id: "ev006", word: "depend", pronunciation: "/dɪˈpend/", partOfSpeech: "verb", cefrLevel: "A2", category: "basic-verbs", meaning: "의존하다; 달려 있다", example: { en: "It depends on the weather.", ko: "날씨에 달려 있다." }, synonyms: ["rely on", "count on"], collocations: ["depend on", "depend upon", "it depends"] },
  { id: "ev007", word: "develop", pronunciation: "/dɪˈveləp/", partOfSpeech: "verb", cefrLevel: "A2", category: "basic-verbs", meaning: "개발하다; 발전하다", example: { en: "The company developed a new app.", ko: "회사는 새로운 앱을 개발했다." }, synonyms: ["create", "build", "grow"], wordFamily: ["development", "developer", "developing", "developed"] },
  { id: "ev008", word: "improve", pronunciation: "/ɪmˈpruːv/", partOfSpeech: "verb", cefrLevel: "A2", category: "basic-verbs", meaning: "개선하다, 향상되다", example: { en: "Practice every day to improve your English.", ko: "영어를 향상시키기 위해 매일 연습하세요." }, synonyms: ["enhance", "better", "boost"], wordFamily: ["improvement", "improved"] },
  { id: "ev009", word: "include", pronunciation: "/ɪnˈkluːd/", partOfSpeech: "verb", cefrLevel: "A2", category: "basic-verbs", meaning: "포함하다", example: { en: "The price includes breakfast.", ko: "가격에는 아침 식사가 포함됩니다." }, antonyms: ["exclude"], wordFamily: ["inclusion", "inclusive", "including"] },
  { id: "ev010", word: "provide", pronunciation: "/prəˈvaɪd/", partOfSpeech: "verb", cefrLevel: "B1", category: "basic-verbs", meaning: "제공하다, 공급하다", example: { en: "The school provides free meals.", ko: "학교는 무료 급식을 제공한다." }, synonyms: ["offer", "supply", "give"], wordFamily: ["provider", "provision"] },
  { id: "ev011", word: "require", pronunciation: "/rɪˈkwaɪər/", partOfSpeech: "verb", cefrLevel: "B1", category: "basic-verbs", meaning: "필요로 하다, 요구하다", example: { en: "This job requires good communication skills.", ko: "이 일은 좋은 의사소통 능력이 필요하다." }, synonyms: ["need", "demand", "call for"], wordFamily: ["requirement", "required"] },
  { id: "ev012", word: "suggest", pronunciation: "/səˈdʒest/", partOfSpeech: "verb", cefrLevel: "A2", category: "basic-verbs", meaning: "제안하다, 제시하다", example: { en: "Can you suggest a good restaurant?", ko: "좋은 식당을 추천해 줄 수 있어?" }, synonyms: ["recommend", "propose", "advise"], tip: "suggest + -ing OR suggest (that) + 주어 + 동사" },

  // ── 일상생활 A1–A2 ──
  { id: "ev020", word: "appointment", pronunciation: "/əˈpɔɪntmənt/", partOfSpeech: "noun", cefrLevel: "A2", category: "daily-life", meaning: "약속; 예약", example: { en: "I have a doctor's appointment at 3 PM.", ko: "오후 3시에 병원 예약이 있어요." }, collocations: ["make an appointment", "keep an appointment", "cancel an appointment"] },
  { id: "ev021", word: "neighborhood", pronunciation: "/ˈneɪbərˌhʊd/", partOfSpeech: "noun", cefrLevel: "A2", category: "daily-life", meaning: "이웃, 동네", example: { en: "It's a safe neighborhood to raise kids.", ko: "아이를 키우기에 안전한 동네입니다." }, synonyms: ["area", "community", "district"] },
  { id: "ev022", word: "routine", pronunciation: "/ruːˈtiːn/", partOfSpeech: "noun", cefrLevel: "A2", category: "daily-life", meaning: "일과, 루틴", example: { en: "My morning routine takes about an hour.", ko: "나의 아침 루틴은 약 1시간 걸린다." }, collocations: ["daily routine", "morning routine", "exercise routine"] },
  { id: "ev023", word: "schedule", pronunciation: "/ˈskedʒuːl/", partOfSpeech: "noun", cefrLevel: "A2", category: "daily-life", meaning: "일정, 스케줄", example: { en: "Let me check my schedule for next week.", ko: "다음 주 일정을 확인해 볼게요." }, synonyms: ["timetable", "plan", "agenda"], collocations: ["busy schedule", "on schedule", "ahead of schedule"] },
  { id: "ev024", word: "grocery", pronunciation: "/ˈɡroʊsəri/", partOfSpeech: "noun", cefrLevel: "A1", category: "daily-life", meaning: "식료품", example: { en: "I need to buy some groceries after work.", ko: "퇴근 후에 식료품을 좀 사야 해요." }, collocations: ["grocery store", "grocery shopping", "grocery list"] },
  { id: "ev025", word: "commute", pronunciation: "/kəˈmjuːt/", partOfSpeech: "verb", cefrLevel: "B1", category: "daily-life", meaning: "통근하다", example: { en: "She commutes two hours every day.", ko: "그녀는 매일 2시간씩 통근한다." }, wordFamily: ["commuter", "commuting"], collocations: ["daily commute", "long commute"] },
  { id: "ev026", word: "budget", pronunciation: "/ˈbʌdʒɪt/", partOfSpeech: "noun", cefrLevel: "A2", category: "daily-life", meaning: "예산", example: { en: "We have a tight budget this month.", ko: "이번 달은 예산이 빠듯하다." }, wordFamily: ["budgeting", "budgetary"], collocations: ["tight budget", "budget plan", "on a budget"] },
  { id: "ev027", word: "convenient", pronunciation: "/kənˈviːniənt/", partOfSpeech: "adj", cefrLevel: "A2", category: "daily-life", meaning: "편리한", example: { en: "Online shopping is very convenient.", ko: "온라인 쇼핑은 매우 편리하다." }, antonyms: ["inconvenient"], wordFamily: ["convenience", "conveniently"] },

  // ── 감정·성격 A2–B1 ──
  { id: "ev030", word: "anxious", pronunciation: "/ˈæŋkʃəs/", partOfSpeech: "adj", cefrLevel: "B1", category: "emotions", meaning: "불안한, 걱정스러운", example: { en: "I was anxious about the exam results.", ko: "시험 결과에 대해 불안했다." }, synonyms: ["nervous", "worried", "uneasy"], antonyms: ["calm", "relaxed"], wordFamily: ["anxiety", "anxiously"] },
  { id: "ev031", word: "confident", pronunciation: "/ˈkɒnfɪdənt/", partOfSpeech: "adj", cefrLevel: "B1", category: "emotions", meaning: "자신감 있는", example: { en: "She felt confident speaking in front of a crowd.", ko: "그녀는 군중 앞에서 말하는 것에 자신감을 느꼈다." }, synonyms: ["assured", "self-assured"], antonyms: ["insecure", "uncertain"], wordFamily: ["confidence", "confidently"] },
  { id: "ev032", word: "frustrated", pronunciation: "/ˈfrʌstreɪtɪd/", partOfSpeech: "adj", cefrLevel: "B1", category: "emotions", meaning: "좌절한, 답답한", example: { en: "He was frustrated by the lack of progress.", ko: "그는 진전이 없어서 답답했다." }, synonyms: ["annoyed", "disappointed"], wordFamily: ["frustration", "frustrating", "frustrate"] },
  { id: "ev033", word: "determined", pronunciation: "/dɪˈtɜːrmɪnd/", partOfSpeech: "adj", cefrLevel: "B1", category: "emotions", meaning: "굳게 결심한", example: { en: "She was determined to finish the marathon.", ko: "그녀는 마라톤을 완주하기로 굳게 결심했다." }, synonyms: ["resolute", "committed"], wordFamily: ["determination", "determine"] },
  { id: "ev034", word: "overwhelmed", pronunciation: "/ˌoʊvərˈwelmd/", partOfSpeech: "adj", cefrLevel: "B2", category: "emotions", meaning: "압도된, 벅찬", example: { en: "I felt overwhelmed by the amount of work.", ko: "일의 양에 압도당하는 느낌이었다." }, synonyms: ["swamped", "overloaded"], wordFamily: ["overwhelm", "overwhelming", "overwhelmingly"] },
  { id: "ev035", word: "motivated", pronunciation: "/ˈmoʊtɪveɪtɪd/", partOfSpeech: "adj", cefrLevel: "B1", category: "emotions", meaning: "동기부여 된", example: { en: "I feel motivated to study after watching that video.", ko: "그 영상을 보고 나서 공부할 의욕이 생겼다." }, wordFamily: ["motivation", "motivate", "motivating"] },
  { id: "ev036", word: "empathy", pronunciation: "/ˈempəθi/", partOfSpeech: "noun", cefrLevel: "B2", category: "emotions", meaning: "공감, 감정이입", example: { en: "Good leaders show empathy for their team.", ko: "훌륭한 리더는 팀에 공감을 보여준다." }, synonyms: ["compassion", "understanding"], antonyms: ["apathy"], wordFamily: ["empathize", "empathetic"] },

  // ── 여행·교통 A2–B1 ──
  { id: "ev040", word: "itinerary", pronunciation: "/aɪˈtɪnəreri/", partOfSpeech: "noun", cefrLevel: "B1", category: "travel", meaning: "여행 일정표", example: { en: "The travel agency prepared a detailed itinerary.", ko: "여행사가 상세한 여행 일정표를 준비했다." }, collocations: ["travel itinerary", "detailed itinerary", "follow the itinerary"] },
  { id: "ev041", word: "departure", pronunciation: "/dɪˈpɑːrtʃər/", partOfSpeech: "noun", cefrLevel: "A2", category: "travel", meaning: "출발", example: { en: "The departure time is 6:30 AM.", ko: "출발 시각은 오전 6시 30분입니다." }, antonyms: ["arrival"], collocations: ["departure gate", "departure lounge", "departure time"] },
  { id: "ev042", word: "accommodation", pronunciation: "/əˌkɒməˈdeɪʃn/", partOfSpeech: "noun", cefrLevel: "B1", category: "travel", meaning: "숙박 시설", example: { en: "We need to book accommodation in advance.", ko: "미리 숙박 시설을 예약해야 한다." }, synonyms: ["lodging", "housing"], collocations: ["book accommodation", "find accommodation"] },
  { id: "ev043", word: "navigate", pronunciation: "/ˈnævɪɡeɪt/", partOfSpeech: "verb", cefrLevel: "B1", category: "travel", meaning: "길을 찾다; 항행하다", example: { en: "I used GPS to navigate through the city.", ko: "GPS를 사용해서 도시에서 길을 찾았다." }, wordFamily: ["navigation", "navigator", "navigable"] },
  { id: "ev044", word: "customs", pronunciation: "/ˈkʌstəmz/", partOfSpeech: "noun", cefrLevel: "B1", category: "travel", meaning: "세관; 관세", example: { en: "You must declare all items at customs.", ko: "세관에서 모든 물품을 신고해야 한다." }, collocations: ["go through customs", "customs officer", "customs declaration"] },

  // ── 건강·신체 A2–B1 ──
  { id: "ev050", word: "symptom", pronunciation: "/ˈsɪmptəm/", partOfSpeech: "noun", cefrLevel: "B1", category: "health", meaning: "증상", example: { en: "Coughing is a common symptom of a cold.", ko: "기침은 감기의 흔한 증상이다." }, collocations: ["show symptoms", "common symptom", "symptom of"] },
  { id: "ev051", word: "diagnosis", pronunciation: "/ˌdaɪəɡˈnoʊsɪs/", partOfSpeech: "noun", cefrLevel: "B2", category: "health", meaning: "진단", example: { en: "The doctor gave him a diagnosis of high blood pressure.", ko: "의사는 그에게 고혈압 진단을 내렸다." }, wordFamily: ["diagnose", "diagnostic"] },
  { id: "ev052", word: "prescription", pronunciation: "/prɪˈskrɪpʃn/", partOfSpeech: "noun", cefrLevel: "B1", category: "health", meaning: "처방전", example: { en: "You need a prescription to buy this medicine.", ko: "이 약을 사려면 처방전이 필요하다." }, collocations: ["write a prescription", "fill a prescription", "prescription medicine"] },
  { id: "ev053", word: "chronic", pronunciation: "/ˈkrɒnɪk/", partOfSpeech: "adj", cefrLevel: "B2", category: "health", meaning: "만성적인", example: { en: "He suffers from chronic back pain.", ko: "그는 만성 허리 통증으로 고생한다." }, antonyms: ["acute"], collocations: ["chronic illness", "chronic pain", "chronic condition"] },
  { id: "ev054", word: "recover", pronunciation: "/rɪˈkʌvər/", partOfSpeech: "verb", cefrLevel: "A2", category: "health", meaning: "회복하다", example: { en: "It took her two weeks to recover from the flu.", ko: "독감에서 회복하는 데 2주가 걸렸다." }, synonyms: ["heal", "get better"], wordFamily: ["recovery", "recoverable"] },

  // ── 직장·비즈니스 B1–B2 ──
  { id: "ev060", word: "deadline", pronunciation: "/ˈdedlaɪn/", partOfSpeech: "noun", cefrLevel: "B1", category: "workplace", meaning: "마감 기한", example: { en: "The project deadline is next Friday.", ko: "프로젝트 마감일은 다음 주 금요일이다." }, collocations: ["meet a deadline", "miss a deadline", "tight deadline", "extend a deadline"] },
  { id: "ev061", word: "collaborate", pronunciation: "/kəˈlæbəreɪt/", partOfSpeech: "verb", cefrLevel: "B2", category: "workplace", meaning: "협력하다, 공동 작업하다", example: { en: "We collaborate with teams across different time zones.", ko: "우리는 다른 시간대의 팀들과 협력한다." }, synonyms: ["cooperate", "work together", "partner"], wordFamily: ["collaboration", "collaborative", "collaborator"] },
  { id: "ev062", word: "negotiate", pronunciation: "/nɪˈɡoʊʃieɪt/", partOfSpeech: "verb", cefrLevel: "B2", category: "workplace", meaning: "협상하다", example: { en: "She negotiated a higher salary.", ko: "그녀는 더 높은 연봉을 협상했다." }, wordFamily: ["negotiation", "negotiator", "negotiable"] },
  { id: "ev063", word: "efficient", pronunciation: "/ɪˈfɪʃnt/", partOfSpeech: "adj", cefrLevel: "B1", category: "workplace", meaning: "효율적인", example: { en: "This is a more efficient way to manage tasks.", ko: "이것은 업무를 관리하는 더 효율적인 방법이다." }, synonyms: ["effective", "productive"], antonyms: ["inefficient", "wasteful"], wordFamily: ["efficiency", "efficiently"] },
  { id: "ev064", word: "implement", pronunciation: "/ˈɪmplɪment/", partOfSpeech: "verb", cefrLevel: "B2", category: "workplace", meaning: "실행하다, 구현하다", example: { en: "The company will implement the new policy next month.", ko: "회사는 다음 달에 새 정책을 실행할 것이다." }, synonyms: ["execute", "carry out", "put into practice"], wordFamily: ["implementation"] },
  { id: "ev065", word: "initiative", pronunciation: "/ɪˈnɪʃətɪv/", partOfSpeech: "noun", cefrLevel: "B2", category: "workplace", meaning: "주도권; 새로운 계획", example: { en: "She took the initiative to solve the problem.", ko: "그녀는 문제를 해결하기 위해 주도적으로 나섰다." }, collocations: ["take initiative", "business initiative", "government initiative"] },
  { id: "ev066", word: "strategy", pronunciation: "/ˈstrætɪdʒi/", partOfSpeech: "noun", cefrLevel: "B1", category: "workplace", meaning: "전략", example: { en: "We need a new marketing strategy.", ko: "우리는 새로운 마케팅 전략이 필요하다." }, synonyms: ["plan", "approach", "tactics"], wordFamily: ["strategic", "strategically", "strategist"] },
  { id: "ev067", word: "feedback", pronunciation: "/ˈfiːdbæk/", partOfSpeech: "noun", cefrLevel: "B1", category: "workplace", meaning: "피드백, 의견", example: { en: "Please give me feedback on my presentation.", ko: "제 발표에 대해 피드백을 주세요." }, collocations: ["give feedback", "receive feedback", "constructive feedback"] },
  { id: "ev068", word: "revenue", pronunciation: "/ˈrevənjuː/", partOfSpeech: "noun", cefrLevel: "B2", category: "workplace", meaning: "수익, 매출", example: { en: "The company's revenue grew by 20% this year.", ko: "회사의 매출이 올해 20% 성장했다." }, synonyms: ["income", "earnings"], collocations: ["generate revenue", "annual revenue", "revenue growth"] },
  { id: "ev069", word: "stakeholder", pronunciation: "/ˈsteɪkhoʊldər/", partOfSpeech: "noun", cefrLevel: "B2", category: "workplace", meaning: "이해관계자", example: { en: "All stakeholders attended the meeting.", ko: "모든 이해관계자들이 회의에 참석했다." }, collocations: ["key stakeholder", "stakeholder management", "stakeholder meeting"] },

  // ── 학문·교육 B2–C1 ──
  { id: "ev070", word: "analysis", pronunciation: "/əˈnæləsɪs/", partOfSpeech: "noun", cefrLevel: "B2", category: "academic", meaning: "분석", example: { en: "A careful analysis of the data revealed several trends.", ko: "데이터를 주의깊게 분석한 결과 여러 경향이 드러났다." }, wordFamily: ["analyze", "analytical", "analyst"] },
  { id: "ev071", word: "hypothesis", pronunciation: "/haɪˈpɒθɪsɪs/", partOfSpeech: "noun", cefrLevel: "C1", category: "academic", meaning: "가설", example: { en: "The scientist proposed a hypothesis to explain the results.", ko: "과학자는 결과를 설명하기 위한 가설을 제시했다." }, wordFamily: ["hypothesize", "hypothetical", "hypothetically"] },
  { id: "ev072", word: "methodology", pronunciation: "/ˌmeθəˈdɒlədʒi/", partOfSpeech: "noun", cefrLevel: "C1", category: "academic", meaning: "방법론", example: { en: "The research methodology was clearly explained.", ko: "연구 방법론이 명확하게 설명되었다." }, wordFamily: ["methodological", "method"] },
  { id: "ev073", word: "evaluate", pronunciation: "/ɪˈvæljueɪt/", partOfSpeech: "verb", cefrLevel: "B2", category: "academic", meaning: "평가하다", example: { en: "We need to evaluate the effectiveness of this approach.", ko: "이 접근법의 효과를 평가해야 한다." }, synonyms: ["assess", "appraise", "judge"], wordFamily: ["evaluation", "evaluative"] },
  { id: "ev074", word: "evidence", pronunciation: "/ˈevɪdəns/", partOfSpeech: "noun", cefrLevel: "B1", category: "academic", meaning: "증거, 근거", example: { en: "The evidence supports the theory.", ko: "증거가 그 이론을 뒷받침한다." }, collocations: ["strong evidence", "lack of evidence", "based on evidence", "present evidence"] },
  { id: "ev075", word: "implication", pronunciation: "/ˌɪmplɪˈkeɪʃn/", partOfSpeech: "noun", cefrLevel: "C1", category: "academic", meaning: "함의, 암시; 결과", example: { en: "The implications of this decision are significant.", ko: "이 결정의 함의는 매우 중요하다." }, wordFamily: ["imply", "implicit", "implicitly"] },
  { id: "ev076", word: "perspective", pronunciation: "/pərˈspektɪv/", partOfSpeech: "noun", cefrLevel: "B2", category: "academic", meaning: "관점, 시각", example: { en: "From a historical perspective, this is quite rare.", ko: "역사적 관점에서 보면, 이것은 꽤 드문 일이다." }, synonyms: ["viewpoint", "standpoint", "angle"], collocations: ["different perspective", "from my perspective", "broader perspective"] },
  { id: "ev077", word: "significant", pronunciation: "/sɪɡˈnɪfɪkənt/", partOfSpeech: "adj", cefrLevel: "B1", category: "academic", meaning: "중요한; 상당한", example: { en: "There has been a significant improvement in results.", ko: "결과에 상당한 향상이 있었다." }, synonyms: ["important", "notable", "considerable"], wordFamily: ["significance", "significantly"] },

  // ── 형용사 A1–B1 ──
  { id: "ev080", word: "accurate", pronunciation: "/ˈækjərɪt/", partOfSpeech: "adj", cefrLevel: "B1", category: "adjectives", meaning: "정확한", example: { en: "Please give an accurate description of what happened.", ko: "일어난 일을 정확하게 설명해 주세요." }, antonyms: ["inaccurate", "wrong"], wordFamily: ["accuracy", "accurately"] },
  { id: "ev081", word: "appropriate", pronunciation: "/əˈproʊpriɪt/", partOfSpeech: "adj", cefrLevel: "B1", category: "adjectives", meaning: "적절한, 알맞은", example: { en: "Dress appropriately for the job interview.", ko: "취업 면접에 맞는 복장을 입으세요." }, antonyms: ["inappropriate"], wordFamily: ["appropriately", "appropriateness"] },
  { id: "ev082", word: "essential", pronunciation: "/ɪˈsenʃl/", partOfSpeech: "adj", cefrLevel: "B1", category: "adjectives", meaning: "필수적인, 본질적인", example: { en: "Water is essential for life.", ko: "물은 생명에 필수적이다." }, synonyms: ["vital", "necessary", "crucial"], antonyms: ["unnecessary", "optional"] },
  { id: "ev083", word: "flexible", pronunciation: "/ˈfleksɪbl/", partOfSpeech: "adj", cefrLevel: "B1", category: "adjectives", meaning: "유연한", example: { en: "Our work schedule is flexible.", ko: "우리의 근무 일정은 유연하다." }, antonyms: ["rigid", "inflexible"], wordFamily: ["flexibility", "flexibly"] },
  { id: "ev084", word: "diverse", pronunciation: "/daɪˈvɜːrs/", partOfSpeech: "adj", cefrLevel: "B2", category: "adjectives", meaning: "다양한", example: { en: "The city has a diverse population.", ko: "그 도시는 다양한 인구 구성을 가지고 있다." }, wordFamily: ["diversity", "diversify", "diversification"] },
  { id: "ev085", word: "sustainable", pronunciation: "/səˈsteɪnəbl/", partOfSpeech: "adj", cefrLevel: "B2", category: "adjectives", meaning: "지속 가능한", example: { en: "We need sustainable energy solutions.", ko: "우리는 지속 가능한 에너지 해결책이 필요하다." }, wordFamily: ["sustainability", "sustain", "sustainably"] },
  { id: "ev086", word: "reliable", pronunciation: "/rɪˈlaɪəbl/", partOfSpeech: "adj", cefrLevel: "B1", category: "adjectives", meaning: "믿을 수 있는, 신뢰할 수 있는", example: { en: "She is a reliable and hardworking employee.", ko: "그녀는 믿을 수 있고 성실한 직원이다." }, antonyms: ["unreliable"], wordFamily: ["reliability", "reliably"] },
  { id: "ev087", word: "ambitious", pronunciation: "/æmˈbɪʃəs/", partOfSpeech: "adj", cefrLevel: "B1", category: "adjectives", meaning: "야망 있는, 의욕적인", example: { en: "He has an ambitious plan to start his own business.", ko: "그는 자신만의 사업을 시작하려는 야심찬 계획을 가지고 있다." }, wordFamily: ["ambition", "ambitiously"] },

  // ── 사회·환경 B1–B2 ──
  { id: "ev090", word: "inequality", pronunciation: "/ˌɪnɪˈkwɒlɪti/", partOfSpeech: "noun", cefrLevel: "B2", category: "society", meaning: "불평등", example: { en: "Social inequality is a major challenge worldwide.", ko: "사회적 불평등은 전 세계적으로 주요 과제이다." }, antonyms: ["equality"], collocations: ["social inequality", "economic inequality", "address inequality"] },
  { id: "ev091", word: "climate change", pronunciation: "/ˈklaɪmɪt tʃeɪndʒ/", partOfSpeech: "noun", cefrLevel: "B1", category: "society", meaning: "기후 변화", example: { en: "Climate change is causing extreme weather events.", ko: "기후 변화가 극단적인 날씨를 일으키고 있다." }, collocations: ["address climate change", "combat climate change", "climate change impact"] },
  { id: "ev092", word: "policy", pronunciation: "/ˈpɒlɪsi/", partOfSpeech: "noun", cefrLevel: "B1", category: "society", meaning: "정책", example: { en: "The government introduced a new education policy.", ko: "정부는 새로운 교육 정책을 도입했다." }, collocations: ["implement policy", "government policy", "public policy"] },
  { id: "ev093", word: "democracy", pronunciation: "/dɪˈmɒkrəsi/", partOfSpeech: "noun", cefrLevel: "B2", category: "society", meaning: "민주주의", example: { en: "Freedom of speech is a core value of democracy.", ko: "언론의 자유는 민주주의의 핵심 가치이다." }, wordFamily: ["democratic", "democrat"] },
  { id: "ev094", word: "infrastructure", pronunciation: "/ˈɪnfrəstrʌktʃər/", partOfSpeech: "noun", cefrLevel: "B2", category: "society", meaning: "사회 기반 시설, 인프라", example: { en: "The country needs to invest in its infrastructure.", ko: "그 나라는 인프라에 투자해야 한다." }, collocations: ["digital infrastructure", "transport infrastructure", "build infrastructure"] },

  // ── 고급 어휘 C1–C2 ──
  { id: "ev100", word: "paradigm", pronunciation: "/ˈpærədaɪm/", partOfSpeech: "noun", cefrLevel: "C1", category: "advanced", meaning: "패러다임, 사고 방식의 틀", example: { en: "This discovery represents a paradigm shift in medicine.", ko: "이 발견은 의학의 패러다임 전환을 의미한다." }, wordFamily: ["paradigmatic", "paradigm shift"] },
  { id: "ev101", word: "pragmatic", pronunciation: "/præɡˈmætɪk/", partOfSpeech: "adj", cefrLevel: "C1", category: "advanced", meaning: "실용적인, 실질적인", example: { en: "We need a pragmatic approach to solving this problem.", ko: "이 문제를 해결하는 데 실용적인 접근이 필요하다." }, synonyms: ["practical", "realistic"], wordFamily: ["pragmatism", "pragmatically"] },
  { id: "ev102", word: "nuance", pronunciation: "/ˈnjuːɑːns/", partOfSpeech: "noun", cefrLevel: "C1", category: "advanced", meaning: "뉘앙스, 미묘한 차이", example: { en: "She understood the nuances of the language.", ko: "그녀는 언어의 뉘앙스를 이해했다." }, wordFamily: ["nuanced"] },
  { id: "ev103", word: "resilient", pronunciation: "/rɪˈzɪliənt/", partOfSpeech: "adj", cefrLevel: "B2", category: "advanced", meaning: "회복력 있는, 탄탄한", example: { en: "Children are often more resilient than adults.", ko: "아이들은 종종 어른들보다 더 회복력이 강하다." }, wordFamily: ["resilience", "resiliently"] },
  { id: "ev104", word: "scrutinize", pronunciation: "/ˈskruːtɪnaɪz/", partOfSpeech: "verb", cefrLevel: "C1", category: "advanced", meaning: "면밀히 조사하다", example: { en: "The committee scrutinized every detail of the proposal.", ko: "위원회는 제안서의 모든 세부 사항을 면밀히 조사했다." }, synonyms: ["examine", "inspect", "analyze"], wordFamily: ["scrutiny"] },
  { id: "ev105", word: "articulate", pronunciation: "/ɑːrˈtɪkjʊlɪt/", partOfSpeech: "adj", cefrLevel: "C1", category: "advanced", meaning: "명확하게 표현하는, 유창한", example: { en: "He is an articulate and persuasive speaker.", ko: "그는 명확하고 설득력 있는 연설가이다." }, wordFamily: ["articulation", "articulately"] },
  { id: "ev106", word: "unprecedented", pronunciation: "/ʌnˈpresɪdentɪd/", partOfSpeech: "adj", cefrLevel: "C1", category: "advanced", meaning: "전례 없는", example: { en: "The pandemic caused unprecedented disruption.", ko: "팬데믹은 전례 없는 혼란을 일으켰다." }, collocations: ["unprecedented growth", "unprecedented situation", "without precedent"] },
  { id: "ev107", word: "ambiguous", pronunciation: "/æmˈbɪɡjuəs/", partOfSpeech: "adj", cefrLevel: "C1", category: "advanced", meaning: "애매한, 다의적인", example: { en: "The instructions were ambiguous and hard to follow.", ko: "지시 사항이 애매해서 따라하기 어려웠다." }, antonyms: ["clear", "unambiguous"], wordFamily: ["ambiguity", "ambiguously"] },
  { id: "ev108", word: "integrity", pronunciation: "/ɪnˈteɡrɪti/", partOfSpeech: "noun", cefrLevel: "B2", category: "advanced", meaning: "성실성, 청렴; 완전성", example: { en: "Trust is built on a foundation of integrity.", ko: "신뢰는 성실성을 기반으로 쌓인다." }, synonyms: ["honesty", "principles", "virtue"] },
  { id: "ev109", word: "acknowledge", pronunciation: "/əkˈnɒlɪdʒ/", partOfSpeech: "verb", cefrLevel: "B2", category: "advanced", meaning: "인정하다; 감사를 표하다", example: { en: "He acknowledged that he had made a mistake.", ko: "그는 자신이 실수를 했다는 것을 인정했다." }, synonyms: ["admit", "recognize", "accept"], wordFamily: ["acknowledgment"] },
];
