import type { KoConversation } from "./types";

export const KO_CONVERSATIONS: KoConversation[] = [
  {
    id: "kc1",
    title: "はじめての自己紹介",
    situation: "初対面の人と挨拶して名前を伝える。",
    emoji: "👋",
    topik: 1,
    lines: [
      { speaker: "A", ko: "안녕하세요, 처음 뵙겠습니다.", romaja: "annyeonghaseyo, cheoeum boepgesseumnida.", ja: "こんにちは、はじめまして。" },
      { speaker: "B", ko: "안녕하세요. 만나서 반가워요.", romaja: "annyeonghaseyo. mannaseo bangawoyo.", ja: "こんにちは。お会いできてうれしいです。" },
      { speaker: "A", ko: "저는 다나카예요. 일본에서 왔어요.", romaja: "jeoneun danakayeyo. ilboneseo wasseoyo.", ja: "私は田中です。日本から来ました。" },
      { speaker: "B", ko: "저는 김민수예요. 잘 부탁해요.", romaja: "jeoneun gimminsuyeyo. jal butakaeyo.", ja: "私はキム・ミンスです。よろしくお願いします。" },
      { speaker: "A", ko: "네, 저도 잘 부탁드려요.", romaja: "ne, jeodo jal butakdeuryeoyo.", ja: "はい、こちらこそよろしくお願いします。" },
      { speaker: "B", ko: "앞으로 자주 봐요.", romaja: "apeuro jaju bwayo.", ja: "これからよく会いましょう。" },
    ],
  },
  {
    id: "kc2",
    title: "カフェで注文する",
    situation: "カフェでコーヒーとケーキを注文する。",
    emoji: "☕",
    topik: 1,
    lines: [
      { speaker: "A", ko: "어서 오세요. 뭐 드릴까요?", romaja: "eoseo oseyo. mwo deurilkkayo?", ja: "いらっしゃいませ。何にいたしましょうか。" },
      { speaker: "B", ko: "따뜻한 아메리카노 한 잔 주세요.", romaja: "ttatteutan amerikano han jan juseyo.", ja: "ホットのアメリカーノを一杯ください。" },
      { speaker: "A", ko: "케이크도 같이 드릴까요?", romaja: "keikeudo gachi deurilkkayo?", ja: "ケーキも一緒にいかがですか。" },
      { speaker: "B", ko: "네, 치즈 케이크 하나 주세요.", romaja: "ne, chijeu keikeu hana juseyo.", ja: "はい、チーズケーキを一つください。" },
      { speaker: "A", ko: "여기서 드세요, 가져가세요?", romaja: "yeogiseo deuseyo, gajyeogaseyo?", ja: "店内ですか、お持ち帰りですか。" },
      { speaker: "B", ko: "여기서 먹을게요.", romaja: "yeogiseo meogeulgeyo.", ja: "店内で食べます。" },
    ],
  },
  {
    id: "kc3",
    title: "買い物と会計",
    situation: "服を買って値段を聞き、カードで支払う。",
    emoji: "🛍️",
    topik: 1,
    lines: [
      { speaker: "A", ko: "이 티셔츠 얼마예요?", romaja: "i tisyeocheu eolmayeyo?", ja: "このTシャツはいくらですか。" },
      { speaker: "B", ko: "그건 이만 오천 원이에요.", romaja: "geugeon iman ocheon wonieyo.", ja: "それは二万五千ウォンです。" },
      { speaker: "A", ko: "조금 더 큰 사이즈 있어요?", romaja: "jogeum deo keun saijeu isseoyo?", ja: "もう少し大きいサイズはありますか。" },
      { speaker: "B", ko: "네, 여기 있어요. 입어 보세요.", romaja: "ne, yeogi isseoyo. ibeo boseyo.", ja: "はい、こちらです。着てみてください。" },
      { speaker: "A", ko: "이걸로 할게요. 카드 돼요?", romaja: "igeollo halgeyo. kadeu dwaeyo?", ja: "これにします。カードは使えますか。" },
      { speaker: "B", ko: "네, 카드 돼요. 여기 서명해 주세요.", romaja: "ne, kadeu dwaeyo. yeogi seomyeonghae juseyo.", ja: "はい、使えます。ここにサインしてください。" },
    ],
  },
  {
    id: "kc4",
    title: "道を尋ねる",
    situation: "駅への行き方を通りがかりの人に尋ねる。",
    emoji: "🗺️",
    topik: 1,
    lines: [
      { speaker: "A", ko: "실례지만, 지하철역이 어디예요?", romaja: "sillyejiman, jihacheollyeogi eodiyeyo?", ja: "すみませんが、地下鉄の駅はどこですか。" },
      { speaker: "B", ko: "이 길로 쭉 가세요.", romaja: "i gillo jjuk gaseyo.", ja: "この道をまっすぐ行ってください。" },
      { speaker: "A", ko: "여기서 멀어요?", romaja: "yeogiseo meoreoyo?", ja: "ここから遠いですか。" },
      { speaker: "B", ko: "아니요, 걸어서 오 분쯤 걸려요.", romaja: "aniyo, georeoseo o bunjjeum geollyeoyo.", ja: "いいえ、歩いて五分ほどかかります。" },
      { speaker: "A", ko: "고맙습니다. 정말 친절하시네요.", romaja: "gomapseumnida. jeongmal chinjeolhasineyo.", ja: "ありがとうございます。本当に親切ですね。" },
      { speaker: "B", ko: "별말씀을요. 조심히 가세요.", romaja: "byeolmalsseumeullyo. josimhi gaseyo.", ja: "とんでもないです。気をつけて行ってください。" },
    ],
  },
  {
    id: "kc5",
    title: "電話で約束する",
    situation: "友達に電話して週末に会う約束をする。",
    emoji: "📞",
    topik: 2,
    lines: [
      { speaker: "A", ko: "여보세요, 지금 통화 괜찮아요?", romaja: "yeoboseyo, jigeum tonghwa gwaenchanayo?", ja: "もしもし、今電話大丈夫ですか。" },
      { speaker: "B", ko: "네, 괜찮아요. 무슨 일이에요?", romaja: "ne, gwaenchanayo. museun irieyo?", ja: "はい、大丈夫です。どうしましたか。" },
      { speaker: "A", ko: "이번 주말에 같이 영화 볼래요?", romaja: "ibeon jumare gachi yeonghwa bollaeyo?", ja: "今週末に一緒に映画を見ませんか。" },
      { speaker: "B", ko: "좋아요. 토요일 오후 어때요?", romaja: "joayo. toyoil ohu eottaeyo?", ja: "いいですね。土曜日の午後はどうですか。" },
      { speaker: "A", ko: "그럼 두 시에 극장 앞에서 만나요.", romaja: "geureom du sie geukjang apeseo mannayo.", ja: "では二時に映画館の前で会いましょう。" },
      { speaker: "B", ko: "알겠어요. 그때 봐요!", romaja: "algesseoyo. geuttae bwayo!", ja: "わかりました。その時に会いましょう！" },
    ],
  },
  {
    id: "kc6",
    title: "薬局で薬をもらう",
    situation: "風邪をひいて薬局で薬を買う。",
    emoji: "💊",
    topik: 2,
    lines: [
      { speaker: "A", ko: "어디가 아프세요?", romaja: "eodiga apeuseyo?", ja: "どこが痛いですか（どうされましたか）。" },
      { speaker: "B", ko: "어제부터 목이 아프고 기침이 나요.", romaja: "eojebuteo mogi apeugo gichimi nayo.", ja: "昨日からのどが痛くて咳が出ます。" },
      { speaker: "A", ko: "열도 있어요?", romaja: "yeoldo isseoyo?", ja: "熱もありますか。" },
      { speaker: "B", ko: "조금 있어요. 약 좀 주세요.", romaja: "jogeum isseoyo. yak jom juseyo.", ja: "少しあります。薬をください。" },
      { speaker: "A", ko: "이 약을 하루 세 번 드세요.", romaja: "i yageul haru se beon deuseyo.", ja: "この薬を一日三回飲んでください。" },
      { speaker: "B", ko: "네, 감사합니다. 빨리 나으면 좋겠어요.", romaja: "ne, gamsahamnida. ppalli naeumyeon jokesseoyo.", ja: "はい、ありがとうございます。早く治るといいです。" },
    ],
  },
  {
    id: "kc7",
    title: "趣味について話す",
    situation: "週末の過ごし方や趣味を紹介し合う。",
    emoji: "🎸",
    topik: 1,
    lines: [
      { speaker: "A", ko: "취미가 뭐예요?", romaja: "chwimiga mwoyeyo?", ja: "趣味は何ですか。" },
      { speaker: "B", ko: "저는 음악 듣는 걸 좋아해요.", romaja: "jeoneun eumak deunneun geol joahaeyo.", ja: "私は音楽を聞くのが好きです。" },
      { speaker: "A", ko: "어떤 음악을 자주 들어요?", romaja: "eotteon eumageul jaju deureoyo?", ja: "どんな音楽をよく聞きますか。" },
      { speaker: "B", ko: "한국 노래를 자주 들어요. 다나카 씨는요?", romaja: "hanguk noraereul jaju deureoyo. danaka ssineunyo?", ja: "韓国の歌をよく聞きます。田中さんは？" },
      { speaker: "A", ko: "저는 주말에 자전거를 타요.", romaja: "jeoneun jumare jajeongeoreul tayo.", ja: "私は週末に自転車に乗ります。" },
      { speaker: "B", ko: "재미있겠네요. 다음에 같이 타요.", romaja: "jaemiitgenneyo. daeume gachi tayo.", ja: "楽しそうですね。今度一緒に乗りましょう。" },
    ],
  },
  {
    id: "kc8",
    title: "ホテルでチェックイン",
    situation: "予約したホテルでチェックインをする。",
    emoji: "🏨",
    topik: 2,
    lines: [
      { speaker: "A", ko: "안녕하세요, 체크인하려고 하는데요.", romaja: "annyeonghaseyo, chekeuinharyeogo haneundeyo.", ja: "こんにちは、チェックインしたいのですが。" },
      { speaker: "B", ko: "예약하셨어요? 성함이 어떻게 되세요?", romaja: "yeyakasyeosseoyo? seonghami eotteoke doeseyo?", ja: "ご予約されましたか。お名前は何ですか。" },
      { speaker: "A", ko: "네, 다나카로 예약했어요.", romaja: "ne, danakaro yeyakaesseoyo.", ja: "はい、田中で予約しました。" },
      { speaker: "B", ko: "확인됐어요. 방은 삼 층이에요.", romaja: "hwagindwaesseoyo. bangeun sam cheungieyo.", ja: "確認できました。お部屋は三階です。" },
      { speaker: "A", ko: "아침 식사는 몇 시예요?", romaja: "achim siksaneun myeot siyeyo?", ja: "朝食は何時ですか。" },
      { speaker: "B", ko: "일곱 시부터 아홉 시까지예요.", romaja: "ilgop sibuteo ahop sikkajiyeyo.", ja: "七時から九時までです。" },
    ],
  },
  {
    id: "kc9",
    title: "天気の雑談",
    situation: "今日の天気について軽く話す。",
    emoji: "🌤️",
    topik: 1,
    lines: [
      { speaker: "A", ko: "오늘 날씨가 정말 좋네요.", romaja: "oneul nalssiga jeongmal jonneyo.", ja: "今日は天気が本当にいいですね。" },
      { speaker: "B", ko: "네, 하늘이 맑고 따뜻해요.", romaja: "ne, haneuri makgo ttatteutaeyo.", ja: "はい、空が晴れて暖かいです。" },
      { speaker: "A", ko: "내일도 날씨가 좋을까요?", romaja: "naeildo nalssiga joeulkkayo?", ja: "明日も天気がいいでしょうか。" },
      { speaker: "B", ko: "아니요, 내일은 비가 온대요.", romaja: "aniyo, naeireun biga ondaeyo.", ja: "いいえ、明日は雨が降るそうです。" },
      { speaker: "A", ko: "그럼 우산을 가져가야겠어요.", romaja: "geureom usaneul gajyeogayagesseoyo.", ja: "では傘を持っていかなきゃいけませんね。" },
      { speaker: "B", ko: "맞아요. 감기 조심하세요.", romaja: "majayo. gamgi josimhaseyo.", ja: "そうですね。風邪に気をつけてください。" },
    ],
  },
  {
    id: "kc10",
    title: "家族の話",
    situation: "お互いの家族について紹介する。",
    emoji: "👨‍👩‍👧",
    topik: 2,
    lines: [
      { speaker: "A", ko: "가족이 몇 명이에요?", romaja: "gajogi myeot myeongieyo?", ja: "家族は何人ですか。" },
      { speaker: "B", ko: "네 명이에요. 부모님과 여동생이 있어요.", romaja: "ne myeongieyo. bumonimgwa yeodongsaengi isseoyo.", ja: "四人です。両親と妹がいます。" },
      { speaker: "A", ko: "여동생은 몇 살이에요?", romaja: "yeodongsaengeun myeot sarieyo?", ja: "妹さんは何歳ですか。" },
      { speaker: "B", ko: "스무 살이에요. 대학생이에요.", romaja: "seumu sarieyo. daehaksaengieyo.", ja: "二十歳です。大学生です。" },
      { speaker: "A", ko: "부모님은 어디에 사세요?", romaja: "bumonimeun eodie saseyo?", ja: "ご両親はどこに住んでいますか。" },
      { speaker: "B", ko: "부산에 사세요. 자주 못 봬요.", romaja: "busane saseyo. jaju mot bwaeyo.", ja: "釜山に住んでいます。あまり会えません。" },
    ],
  },
  {
    id: "kc11",
    title: "レストランの予約",
    situation: "電話でレストランの席を予約する。",
    emoji: "🍽️",
    topik: 2,
    lines: [
      { speaker: "A", ko: "여보세요, 자리 예약하고 싶은데요.", romaja: "yeoboseyo, jari yeyakago sipeundeyo.", ja: "もしもし、席を予約したいのですが。" },
      { speaker: "B", ko: "네, 몇 분이세요?", romaja: "ne, myeot buniseyo?", ja: "はい、何名様ですか。" },
      { speaker: "A", ko: "세 명이에요. 오늘 저녁 일곱 시요.", romaja: "se myeongieyo. oneul jeonyeok ilgop siyo.", ja: "三人です。今日の夜七時で。" },
      { speaker: "B", ko: "창가 자리로 드릴까요?", romaja: "changga jariro deurilkkayo?", ja: "窓際の席にいたしましょうか。" },
      { speaker: "A", ko: "네, 좋아요. 부탁드려요.", romaja: "ne, joayo. butakdeuryeoyo.", ja: "はい、いいです。お願いします。" },
      { speaker: "B", ko: "예약됐어요. 이따가 뵙겠습니다.", romaja: "yeyakdwaesseoyo. ittaga boepgesseumnida.", ja: "予約できました。後ほどお待ちしております。" },
    ],
  },
  {
    id: "kc12",
    title: "旅行の計画",
    situation: "友達と韓国旅行の計画を立てる。",
    emoji: "✈️",
    topik: 2,
    lines: [
      { speaker: "A", ko: "이번 휴가에 한국에 가고 싶어요.", romaja: "ibeon hyugae hanguge gago sipeoyo.", ja: "今度の休暇に韓国へ行きたいです。" },
      { speaker: "B", ko: "좋아요! 어디에 가고 싶어요?", romaja: "joayo! eodie gago sipeoyo?", ja: "いいですね！どこに行きたいですか。" },
      { speaker: "A", ko: "서울에서 맛있는 음식을 먹고 싶어요.", romaja: "seoureseo masinneun eumsigeul meokgo sipeoyo.", ja: "ソウルでおいしい料理を食べたいです。" },
      { speaker: "B", ko: "그럼 며칠 동안 갈까요?", romaja: "geureom myeochil dongan galkkayo?", ja: "では何日間行きましょうか。" },
      { speaker: "A", ko: "삼 박 사 일이면 좋을 것 같아요.", romaja: "sam bak sa irimyeon joeul geot gatayo.", ja: "三泊四日がいいと思います。" },
      { speaker: "B", ko: "그럼 같이 표를 예매해요.", romaja: "geureom gachi pyoreul yemaehaeyo.", ja: "ではいっしょに切符を予約しましょう。" },
    ],
  },
];
