import type { KoGrammarPoint } from "./types";

export const KO_GRAMMAR: KoGrammarPoint[] = [
  {
    id: "kg001",
    title: "助詞 은/는（主題）",
    topik: 1,
    brief: "文の主題（「~は」）を表す助詞です。",
    rule: "パッチム無し+는 / パッチム有り+은。「~は」に当たります。",
    examples: [
      { ko: "저는 학생이에요.", romaja: "jeoneun haksaengieyo.", ja: "私は学生です。", note: "저(私)が主題" },
      { ko: "이것은 책이에요.", romaja: "igeoseun chaegieyo.", ja: "これは本です。", note: "것(もの)はパッチム有り→은" },
      { ko: "오늘은 바빠요.", romaja: "oneureun bappayo.", ja: "今日は忙しいです。" },
    ],
    commonMistake: "助詞 이/가 と混同しやすい。主題・対比は 은/는 を使う。",
    tip: "母音で終わる語には 는、子音（パッチム）で終わる語には 은。",
  },
  {
    id: "kg002",
    title: "助詞 이/가（主格）",
    topik: 1,
    brief: "動作や状態の主語（「~が」）を示す助詞です。",
    rule: "パッチム無し+가 / パッチム有り+이。新情報や主語を示します。",
    examples: [
      { ko: "친구가 와요.", romaja: "chinguga wayo.", ja: "友達が来ます。", note: "친구はパッチム無し→가" },
      { ko: "시간이 없어요.", romaja: "sigani eopseoyo.", ja: "時間がありません。", note: "시간はパッチム有り→이" },
      { ko: "누가 했어요?", romaja: "nuga haesseoyo?", ja: "誰がしましたか。" },
    ],
    commonMistake: "「私が」は 저가 ではなく 제가 になる。「誰が」も 누구가 ではなく 누가。",
    tip: "初めて話題に出すものには 이/가 を使うことが多い。",
  },
  {
    id: "kg003",
    title: "助詞 을/를（目的語）",
    topik: 1,
    brief: "動作の対象（「~を」）を表す助詞です。",
    rule: "パッチム無し+를 / パッチム有り+을。他動詞の目的語に付きます。",
    examples: [
      { ko: "사과를 먹어요.", romaja: "sagwareul meogeoyo.", ja: "りんごを食べます。", note: "사과→를" },
      { ko: "책을 읽어요.", romaja: "chaegeul ilgeoyo.", ja: "本を読みます。", note: "책→을" },
      { ko: "한국어를 공부해요.", romaja: "hangugeoreul gongbuhaeyo.", ja: "韓国語を勉強します。" },
    ],
    commonMistake: "会話では省略されることもあるが、書き言葉では付ける。",
    tip: "母音終わりは 를、子音終わりは 을。",
  },
  {
    id: "kg004",
    title: "助詞 에（場所・時間）",
    topik: 1,
    brief: "存在の場所、行き先、時点（「~に」）を表します。",
    rule: "場所・時間に付く「~に」。있다/없다、移動先、時刻などと使います。",
    examples: [
      { ko: "집에 있어요.", romaja: "jibe isseoyo.", ja: "家にいます。", note: "存在の場所" },
      { ko: "학교에 가요.", romaja: "hakgyoe gayo.", ja: "学校に行きます。", note: "移動先" },
      { ko: "세 시에 만나요.", romaja: "se sie mannayo.", ja: "3時に会います。", note: "時点" },
    ],
    commonMistake: "「動作をする場所」は 에 ではなく 에서 を使う。",
    tip: "「오늘・어제・지금」など一部の時間名詞には 에 を付けない。",
  },
  {
    id: "kg005",
    title: "助詞 에서（場所・起点）",
    topik: 1,
    brief: "動作が行われる場所、または出発点（「~で・~から」）を表します。",
    rule: "動作の場所「~で」、起点「~から」を示します。",
    examples: [
      { ko: "도서관에서 공부해요.", romaja: "doseogwaneseo gongbuhaeyo.", ja: "図書館で勉強します。", note: "動作の場所" },
      { ko: "집에서 회사까지 멀어요.", romaja: "jibeseo hoesakkaji meoreoyo.", ja: "家から会社まで遠いです。", note: "起点" },
      { ko: "어디에서 왔어요?", romaja: "eodieseo wasseoyo?", ja: "どこから来ましたか。" },
    ],
    commonMistake: "存在「있다/없다」の場所は 에、動作の場所は 에서。",
    tip: "에서 は会話で 서 に縮約されることがある（집에서→집서は方言的）。",
  },
  {
    id: "kg006",
    title: "助詞 와/과・하고（と）",
    topik: 1,
    brief: "名詞を並べる「~と」を表す助詞です。",
    rule: "パッチム無し+와 / パッチム有り+과。会話では 하고 が自然。(이)랑も口語的。",
    examples: [
      { ko: "친구와 영화를 봐요.", romaja: "chinguwa yeonghwareul bwayo.", ja: "友達と映画を見ます。", note: "친구→와" },
      { ko: "빵과 우유를 사요.", romaja: "ppanggwa uyureul sayo.", ja: "パンと牛乳を買います。", note: "빵→과" },
      { ko: "동생하고 같이 가요.", romaja: "dongsaenghago gachi gayo.", ja: "弟（妹）と一緒に行きます。", note: "하고は口語的" },
    ],
    commonMistake: "와/과 は書き言葉的、하고・(이)랑 は会話的という使い分けに注意。",
    tip: "하고 はパッチムの有無に関係なく使えるので便利。",
  },
  {
    id: "kg007",
    title: "助詞 도（も）",
    topik: 1,
    brief: "「~も」を表す添加の助詞です。",
    rule: "名詞+도。은/는・이/가・을/를 を置き換えて使います。",
    examples: [
      { ko: "저도 가요.", romaja: "jeodo gayo.", ja: "私も行きます。", note: "저+도（저는도とは言わない）" },
      { ko: "이것도 주세요.", romaja: "igeotdo juseyo.", ja: "これもください。" },
      { ko: "물도 마셔요.", romaja: "muldo masyeoyo.", ja: "水も飲みます。" },
    ],
    commonMistake: "「저는도」のように 는 と 도 を重ねない。도 が 는/가/를 を吸収する。",
    tip: "「~も…も」は A도 B도 の形で並べられる。",
  },
  {
    id: "kg008",
    title: "助詞 의（所有）",
    topik: 1,
    brief: "所有・所属（「~の」）を表す助詞です。",
    rule: "名詞+의+名詞。発音は実際には [에] に近い。会話では省略も多い。",
    examples: [
      { ko: "친구의 책이에요.", romaja: "chinguui chaegieyo.", ja: "友達の本です。", note: "의は[에]と発音" },
      { ko: "한국의 음식이 맛있어요.", romaja: "hanguge eumsigi masisseoyo.", ja: "韓国の食べ物がおいしいです。" },
      { ko: "우리 학교", romaja: "uri hakgyo", ja: "私たちの学校", note: "의を省略するのが自然" },
    ],
    commonMistake: "「私の」は 저의 → 제 に縮約される（제 책 = 私の本）。",
    tip: "親しい関係や所属では 의 を省略して名詞を並べることが多い。",
  },
  {
    id: "kg009",
    title: "助詞 부터/까지（から/まで）",
    topik: 1,
    brief: "範囲の起点「~から」と終点「~まで」を表します。",
    rule: "부터=時間・順序の起点、까지=終点。場所の起点は 에서 を使う。",
    examples: [
      { ko: "아홉 시부터 시작해요.", romaja: "ahop sibuteo sijakhaeyo.", ja: "9時から始まります。", note: "時間の起点" },
      { ko: "월요일부터 금요일까지 일해요.", romaja: "woryoilbuteo geumyoilkkaji ilhaeyo.", ja: "月曜日から金曜日まで働きます。" },
      { ko: "여기까지 외우세요.", romaja: "yeogikkaji oeuseyo.", ja: "ここまで覚えてください。" },
    ],
    commonMistake: "場所の「~から」は 부터 ではなく 에서（집에서）。時間は 부터。",
    tip: "부터…까지 はセットで「~から~まで」と覚える。",
  },
  {
    id: "kg010",
    title: "助詞 으로/로（手段・方向）",
    topik: 1,
    brief: "手段・道具・方向（「~で・~へ」）を表します。",
    rule: "パッチム無し/ㄹパッチム+로 / それ以外のパッチム+으로。",
    examples: [
      { ko: "버스로 가요.", romaja: "beoseuro gayo.", ja: "バスで行きます。", note: "버스→로（手段）" },
      { ko: "젓가락으로 먹어요.", romaja: "jeotgarageuro meogeoyo.", ja: "箸で食べます。", note: "젓가락→으로（道具）" },
      { ko: "오른쪽으로 가세요.", romaja: "oreunjjogeuro gaseyo.", ja: "右の方へ行ってください。", note: "方向" },
    ],
    commonMistake: "ㄹ パッチムの語は 으로 ではなく 로 を付ける（연필로）。",
    tip: "手段・道具・方向・変化先など幅広く使える万能助詞。",
  },
  {
    id: "kg011",
    title: "이에요/예요・입니다（~です）",
    topik: 1,
    brief: "名詞に付く「~です」の丁寧表現です。",
    rule: "パッチム有り名詞+이에요 / パッチム無し名詞+예요。フォーマルは +입니다。",
    examples: [
      { ko: "학생이에요.", romaja: "haksaengieyo.", ja: "学生です。", note: "학생→이에요" },
      { ko: "의사예요.", romaja: "uisayeyo.", ja: "医者です。", note: "의사→예요" },
      { ko: "처음 뵙겠습니다. 김민수입니다.", romaja: "cheoeum boepgesseumnida. gimminsuimnida.", ja: "はじめまして。キム・ミンスです。", note: "입니다はフォーマル" },
    ],
    commonMistake: "パッチムの有無で 이에요/예요 を間違えやすい。",
    tip: "疑問は 이에요?/예요? と語尾を上げる。입니까? はフォーマルな疑問。",
  },
  {
    id: "kg012",
    title: "합니다体 と 해요体",
    topik: 1,
    brief: "二つの丁寧体（フォーマルとやわらかい丁寧）の違いです。",
    rule: "합니다体=公式・丁寧（ㅂ니다/습니다）。해요体=日常的でやわらかい丁寧（아요/어요）。",
    examples: [
      { ko: "감사합니다.", romaja: "gamsahamnida.", ja: "ありがとうございます。", note: "합니다体（公式）" },
      { ko: "어디에 가요?", romaja: "eodie gayo?", ja: "どこへ行きますか。", note: "해요体（日常）" },
      { ko: "저는 회사원입니다.", romaja: "jeoneun hoesawonimnida.", ja: "私は会社員です。", note: "합니다体" },
    ],
    commonMistake: "ニュースやスピーチは 합니다体、友人や店員との会話は 해요体が自然。",
    tip: "母音語幹は ㅂ니다、子音語幹は 습니다。",
  },
  {
    id: "kg013",
    title: "過去形 았/었어요",
    topik: 1,
    brief: "「~しました・~でした」を表す過去形です。",
    rule: "語幹の母音が ㅏ/ㅗ→았어요、それ以外→었어요。하다→했어요。",
    examples: [
      { ko: "어제 영화를 봤어요.", romaja: "eoje yeonghwareul bwasseoyo.", ja: "昨日映画を見ました。", note: "보다→봤어요" },
      { ko: "밥을 먹었어요.", romaja: "babeul meogeosseoyo.", ja: "ご飯を食べました。", note: "먹다→먹었어요" },
      { ko: "공부했어요.", romaja: "gongbuhaesseoyo.", ja: "勉強しました。", note: "하다→했어요" },
    ],
    commonMistake: "母音の調和（ㅏ/ㅗ かどうか）で 았/었 を選ぶ点に注意。",
    tip: "フォーマルな過去は 았/었습니다（갔습니다=行きました）。",
  },
  {
    id: "kg014",
    title: "否定 안 と 못",
    topik: 1,
    brief: "「~しない（안）」と「~できない（못）」の否定です。",
    rule: "안=意志的な否定「~しない」。못=能力・状況による不可「~できない」。動詞の前に置く。",
    examples: [
      { ko: "오늘은 안 가요.", romaja: "oneureun an gayo.", ja: "今日は行きません。", note: "안=しない" },
      { ko: "매워서 못 먹어요.", romaja: "maewoseo mot meogeoyo.", ja: "辛くて食べられません。", note: "못=できない" },
      { ko: "공부 안 해요.", romaja: "gongbu an haeyo.", ja: "勉強しません。", note: "공부하다は 공부 안 해요" },
    ],
    commonMistake: "「공부하다」は 안 공부해요 ではなく 공부 안 해요 が自然。",
    tip: "長い否定形は 가지 않아요（안 가요）、먹지 못해요（못 먹어요）。",
  },
  {
    id: "kg015",
    title: "未来 ㄹ/을 거예요",
    topik: 1,
    brief: "予定・推量（「~するつもりです・~でしょう」）を表します。",
    rule: "パッチム無し+ㄹ 거예요 / パッチム有り+을 거예요。",
    examples: [
      { ko: "내일 갈 거예요.", romaja: "naeil gal geoyeyo.", ja: "明日行くつもりです。", note: "가다→갈 거예요" },
      { ko: "주말에 책을 읽을 거예요.", romaja: "jumare chaegeul ilgeul geoyeyo.", ja: "週末に本を読むつもりです。", note: "읽다→읽을 거예요" },
      { ko: "아마 비가 올 거예요.", romaja: "ama biga ol geoyeyo.", ja: "たぶん雨が降るでしょう。", note: "推量" },
    ],
    commonMistake: "거예요 は 거에요 と書き間違えやすい（正しくは 거예요）。",
    tip: "意志「~します」も推量「~でしょう」も文脈で表せる。",
  },
  {
    id: "kg016",
    title: "連結 고（並列）",
    topik: 1,
    brief: "動作・事柄を並べる「~して・~で」を表します。",
    rule: "語幹+고。時間的な並列や単純な羅列に使う。",
    examples: [
      { ko: "밥을 먹고 커피를 마셔요.", romaja: "babeul meokgo keopireul masyeoyo.", ja: "ご飯を食べてコーヒーを飲みます。", note: "順序の並列" },
      { ko: "이 가방은 싸고 예뻐요.", romaja: "i gabangeun ssago yeppeoyo.", ja: "このカバンは安くてきれいです。", note: "性質の羅列" },
      { ko: "저는 학생이고 동생은 회사원이에요.", romaja: "jeoneun haksaengigo dongsaeneun hoesawonieyo.", ja: "私は学生で、弟は会社員です。" },
    ],
    commonMistake: "理由・原因には 고 ではなく 아서/어서 を使うことが多い。",
    tip: "고 は前後の主語が違ってもよく、単純な「そして」のイメージ。",
  },
  {
    id: "kg017",
    title: "連結 아서/어서（理由・順序）",
    topik: 2,
    brief: "理由「~ので」や先行動作「~して（から）」を表します。",
    rule: "語幹の母音が ㅏ/ㅗ→아서、それ以外→어서。하다→해서。",
    examples: [
      { ko: "바빠서 못 갔어요.", romaja: "bappaseo mot gasseoyo.", ja: "忙しくて行けませんでした。", note: "理由" },
      { ko: "친구를 만나서 같이 밥을 먹었어요.", romaja: "chingureul mannaseo gachi babeul meogeosseoyo.", ja: "友達に会って一緒にご飯を食べました。", note: "先行動作" },
      { ko: "비가 와서 집에 있었어요.", romaja: "biga waseo jibe isseosseoyo.", ja: "雨が降ったので家にいました。", note: "理由" },
    ],
    commonMistake: "아서/어서 の前には過去・命令・勧誘を付けない（갔어서×→가서○）。命令理由は 으니까。",
    tip: "理由の 아서/어서 は後ろに命令・勧誘が来ない点が 으니까 との違い。",
  },
  {
    id: "kg018",
    title: "連結 지만（逆接）",
    topik: 1,
    brief: "「~だが・~けれども」と逆の内容をつなぎます。",
    rule: "語幹+지만。前後で対照的な内容を述べる。過去は 았/었지만。",
    examples: [
      { ko: "비싸지만 맛있어요.", romaja: "bissajiman masisseoyo.", ja: "高いですがおいしいです。" },
      { ko: "한국어는 어렵지만 재미있어요.", romaja: "hangugeoneun eoryeopjiman jaemiisseoyo.", ja: "韓国語は難しいですが面白いです。" },
      { ko: "갔지만 못 만났어요.", romaja: "gatjiman mot mannasseoyo.", ja: "行きましたが会えませんでした。", note: "過去は았/었지만" },
    ],
    commonMistake: "「죄송하지만」「실례지만」のように前置きの丁寧表現にも使う。",
    tip: "会話では 는데 も逆接・前置きに使われる。",
  },
  {
    id: "kg019",
    title: "連結 으면/면（仮定）",
    topik: 1,
    brief: "「~れば・~たら・~なら」の仮定・条件を表します。",
    rule: "パッチム無し/ㄹ+면 / パッチム有り+으면。",
    examples: [
      { ko: "시간이 있으면 갈게요.", romaja: "sigani isseumyeon galgeyo.", ja: "時間があれば行きます。", note: "있다→있으면" },
      { ko: "날씨가 좋으면 산책해요.", romaja: "nalssiga joeumyeon sanchaekhaeyo.", ja: "天気がよければ散歩します。" },
      { ko: "이거 다 먹으면 디저트 먹어요.", romaja: "igeo da meogeumyeon dijeoteu meogeoyo.", ja: "これを全部食べたらデザートを食べます。" },
    ],
    commonMistake: "ㄹ パッチムは 으면 ではなく 면（만들면＝作れば）。",
    tip: "「~たら（~れば）いいですね」は 으면 좋겠어요 で願望を表せる。",
  },
  {
    id: "kg020",
    title: "希望 고 싶다（~したい）",
    topik: 1,
    brief: "話し手の願望「~したい」を表します。",
    rule: "動詞語幹+고 싶다。三人称は 고 싶어하다 を使う。",
    examples: [
      { ko: "한국에 가고 싶어요.", romaja: "hanguge gago sipeoyo.", ja: "韓国に行きたいです。" },
      { ko: "뭐 먹고 싶어요?", romaja: "mwo meokgo sipeoyo?", ja: "何が食べたいですか。" },
      { ko: "동생은 자고 싶어해요.", romaja: "dongsaeneun jago sipeohaeyo.", ja: "弟は寝たがっています。", note: "三人称は싶어하다" },
    ],
    commonMistake: "自分の願望は 싶어요、他人の願望は 싶어해요 と区別する。",
    tip: "目的語の助詞は 를/를 でも 이/가 でも使われる（물이 마시고 싶다 など）。",
  },
  {
    id: "kg021",
    title: "能力 ㄹ/을 수 있다/없다",
    topik: 1,
    brief: "可能「~できる」・不可能「~できない」を表します。",
    rule: "パッチム無し+ㄹ 수 있다/없다 / パッチム有り+을 수 있다/없다。",
    examples: [
      { ko: "한국어를 할 수 있어요.", romaja: "hangugeoreul hal su isseoyo.", ja: "韓国語が話せます。", note: "하다→할 수 있다" },
      { ko: "매운 음식을 먹을 수 없어요.", romaja: "maeun eumsigeul meogeul su eopseoyo.", ja: "辛い食べ物が食べられません。", note: "먹다→먹을 수 없다" },
      { ko: "내일 올 수 있어요?", romaja: "naeil ol su isseoyo?", ja: "明日来られますか。" },
    ],
    commonMistake: "「수」は分かち書きする（할수있다×→할 수 있다○）。",
    tip: "不可能は 을 수 없다 のほか 못 でも表せる（못 가요＝行けません）。",
  },
  {
    id: "kg022",
    title: "尊敬 으시/시",
    topik: 2,
    brief: "動作の主体を高める尊敬の語尾です。",
    rule: "パッチム無し+시 / パッチム有り+으시。해요体では 으세요/세요 となる。",
    examples: [
      { ko: "선생님이 오세요.", romaja: "seonsaengnimi oseyo.", ja: "先生がいらっしゃいます。", note: "오다→오세요" },
      { ko: "책을 읽으세요.", romaja: "chaegeul ilgeuseyo.", ja: "本をお読みください。", note: "읽다→읽으세요" },
      { ko: "할머니께서 주무세요.", romaja: "halmeonikkeseo jumuseyo.", ja: "おばあさんがお休みになります。", note: "자다の尊敬語주무시다" },
    ],
    commonMistake: "尊敬の主語助詞は 이/가 ではなく 께서 を使うとより丁寧。",
    tip: "있다→계시다、먹다→드시다 など特別な尊敬語に注意。",
  },
  {
    id: "kg023",
    title: "漢数詞（一・二・三…）",
    topik: 1,
    brief: "漢字由来の数字。日付・分・値段・電話番号などに使います。",
    rule: "일·이·삼·사·오·육·칠·팔·구·십…。年月日・分・金額・番号などに用いる。",
    examples: [
      { ko: "삼월 십오 일이에요.", romaja: "samwol sibo irieyo.", ja: "3月15日です。", note: "日付は漢数詞" },
      { ko: "이천 원이에요.", romaja: "icheon wonieyo.", ja: "2000ウォンです。", note: "値段は漢数詞" },
      { ko: "지금 두 시 삼십 분이에요.", romaja: "jigeum du si samsip bunieyo.", ja: "今2時30分です。", note: "「分」は漢数詞、「時」は固有数詞" },
    ],
    commonMistake: "「時」は固有数詞、「分」は漢数詞という混在に注意（두 시 삼십 분）。",
    tip: "電話番号・年・値段・分は漢数詞で読む。",
  },
  {
    id: "kg024",
    title: "固有数詞（하나・둘・셋…）",
    topik: 1,
    brief: "韓国固有の数字。個数・人数・年齢・時刻（時）などに使います。",
    rule: "하나·둘·셋·넷·다섯…。助数詞の前で 하나→한、둘→두、셋→세、넷→네 と変化。",
    examples: [
      { ko: "사과 한 개 주세요.", romaja: "sagwa han gae juseyo.", ja: "りんごを1個ください。", note: "하나→한 개" },
      { ko: "사람이 네 명 있어요.", romaja: "sarami ne myeong isseoyo.", ja: "人が4人います。", note: "넷→네 명" },
      { ko: "스무 살이에요.", romaja: "seumu sarieyo.", ja: "20歳です。", note: "스물→스무 살" },
    ],
    commonMistake: "助数詞の前では 한·두·세·네·스무 と形が変わる点に注意。",
    tip: "個数・人数・年齢・「~時」は固有数詞、「~分」は漢数詞。",
  },
];
