import type { KoWord } from "./types";

export const KO_VOCAB_K1A: KoWord[] = [
  // ===== greeting (인사) =====
  { id: "k1a_1", word: "안녕하세요", romaja: "annyeonghaseyo", pos: "감탄사", topik: 1, category: "greeting", meaning: "こんにちは（丁寧な挨拶）", example: { ko: "안녕하세요, 만나서 반갑습니다.", ja: "こんにちは、お会いできて嬉しいです。" } },
  { id: "k1a_2", word: "안녕", romaja: "annyeong", pos: "감탄사", topik: 1, category: "greeting", meaning: "やあ／バイバイ（くだけた挨拶）", example: { ko: "안녕, 내일 또 보자.", ja: "じゃあね、また明日。" } },
  { id: "k1a_3", word: "감사합니다", romaja: "gamsahamnida", pos: "감탄사", topik: 1, category: "greeting", meaning: "ありがとうございます", example: { ko: "도와주셔서 감사합니다.", ja: "手伝ってくださってありがとうございます。" } },
  { id: "k1a_4", word: "고맙습니다", romaja: "gomapseumnida", pos: "감탄사", topik: 1, category: "greeting", meaning: "ありがとうございます", example: { ko: "선물 고맙습니다.", ja: "プレゼントありがとうございます。" } },
  { id: "k1a_5", word: "죄송합니다", romaja: "joesonghamnida", pos: "감탄사", topik: 1, category: "greeting", meaning: "申し訳ありません", example: { ko: "늦어서 죄송합니다.", ja: "遅れて申し訳ありません。" } },
  { id: "k1a_6", word: "미안해요", romaja: "mianhaeyo", pos: "감탄사", topik: 1, category: "greeting", meaning: "ごめんなさい", example: { ko: "약속을 못 지켜서 미안해요.", ja: "約束を守れなくてごめんなさい。" } },
  { id: "k1a_7", word: "반갑습니다", romaja: "bangapseumnida", pos: "형용사", topik: 1, category: "greeting", meaning: "（お会いできて）嬉しいです", example: { ko: "만나서 정말 반갑습니다.", ja: "お会いできて本当に嬉しいです。" } },
  { id: "k1a_8", word: "안녕히 가세요", romaja: "annyeonghi gaseyo", pos: "감탄사", topik: 1, category: "greeting", meaning: "さようなら（去る人へ）", example: { ko: "안녕히 가세요, 조심하세요.", ja: "さようなら、お気をつけて。" } },
  { id: "k1a_9", word: "안녕히 계세요", romaja: "annyeonghi gyeseyo", pos: "감탄사", topik: 1, category: "greeting", meaning: "さようなら（残る人へ）", example: { ko: "먼저 갈게요, 안녕히 계세요.", ja: "お先に失礼します、さようなら。" } },
  { id: "k1a_10", word: "처음 뵙겠습니다", romaja: "cheoeum boepgesseumnida", pos: "감탄사", topik: 1, category: "greeting", meaning: "はじめまして", example: { ko: "처음 뵙겠습니다, 김민수입니다.", ja: "はじめまして、キム・ミンスです。" } },
  { id: "k1a_11", word: "잘 부탁합니다", romaja: "jal butakamnida", pos: "감탄사", topik: 1, category: "greeting", meaning: "よろしくお願いします", example: { ko: "앞으로 잘 부탁합니다.", ja: "これからよろしくお願いします。" } },
  { id: "k1a_12", word: "어서 오세요", romaja: "eoseo oseyo", pos: "감탄사", topik: 1, category: "greeting", meaning: "いらっしゃいませ", example: { ko: "어서 오세요, 몇 분이세요?", ja: "いらっしゃいませ、何名様ですか？" } },
  { id: "k1a_13", word: "잘 먹겠습니다", romaja: "jal meokgesseumnida", pos: "감탄사", topik: 1, category: "greeting", meaning: "いただきます", example: { ko: "맛있어 보여요, 잘 먹겠습니다.", ja: "おいしそうです、いただきます。" } },
  { id: "k1a_14", word: "축하합니다", romaja: "chukahamnida", pos: "감탄사", topik: 1, category: "greeting", meaning: "おめでとうございます", example: { ko: "졸업을 축하합니다.", ja: "卒業おめでとうございます。" } },

  // ===== people (사람·가족) =====
  { id: "k1a_15", word: "사람", romaja: "saram", pos: "명사", topik: 1, category: "people", meaning: "人", example: { ko: "이 사람은 제 친구예요.", ja: "この人は私の友達です。" } },
  { id: "k1a_16", word: "친구", romaja: "chingu", pos: "명사", topik: 1, category: "people", meaning: "友達", example: { ko: "친구하고 영화를 봤어요.", ja: "友達と映画を見ました。" } },
  { id: "k1a_17", word: "가족", romaja: "gajok", pos: "명사", topik: 1, category: "people", meaning: "家族", example: { ko: "우리 가족은 네 명이에요.", ja: "うちの家族は四人です。" } },
  { id: "k1a_18", word: "아버지", romaja: "abeoji", pos: "명사", topik: 1, category: "people", meaning: "お父さん", example: { ko: "아버지는 회사에 다니세요.", ja: "父は会社に勤めています。" } },
  { id: "k1a_19", word: "어머니", romaja: "eomeoni", pos: "명사", topik: 1, category: "people", meaning: "お母さん", example: { ko: "어머니가 요리를 하세요.", ja: "母が料理をしています。" } },
  { id: "k1a_20", word: "형", romaja: "hyeong", pos: "명사", topik: 1, category: "people", meaning: "兄（男性から見た）", example: { ko: "형은 저보다 키가 커요.", ja: "兄は私より背が高いです。" } },
  { id: "k1a_21", word: "누나", romaja: "nuna", pos: "명사", topik: 1, category: "people", meaning: "姉（男性から見た）", example: { ko: "누나는 대학생이에요.", ja: "姉は大学生です。" } },
  { id: "k1a_22", word: "오빠", romaja: "oppa", pos: "명사", topik: 1, category: "people", meaning: "兄（女性から見た）", example: { ko: "오빠가 책을 사 줬어요.", ja: "兄が本を買ってくれました。" } },
  { id: "k1a_23", word: "언니", romaja: "eonni", pos: "명사", topik: 1, category: "people", meaning: "姉（女性から見た）", example: { ko: "언니하고 같이 살아요.", ja: "姉と一緒に住んでいます。" } },
  { id: "k1a_24", word: "동생", romaja: "dongsaeng", pos: "명사", topik: 1, category: "people", meaning: "弟・妹", example: { ko: "제 동생은 고등학생이에요.", ja: "私の弟は高校生です。" } },
  { id: "k1a_25", word: "선생님", romaja: "seonsaengnim", pos: "명사", topik: 1, category: "people", meaning: "先生", example: { ko: "선생님께 질문을 했어요.", ja: "先生に質問をしました。" } },
  { id: "k1a_26", word: "학생", romaja: "haksaeng", pos: "명사", topik: 1, category: "people", meaning: "学生", example: { ko: "저는 한국어 학생이에요.", ja: "私は韓国語の学生です。" } },
  { id: "k1a_27", word: "아이", romaja: "ai", pos: "명사", topik: 1, category: "people", meaning: "子供", example: { ko: "아이가 공원에서 놀아요.", ja: "子供が公園で遊んでいます。" } },
  { id: "k1a_28", word: "남자", romaja: "namja", pos: "명사", topik: 1, category: "people", meaning: "男・男性", example: { ko: "저 남자는 의사예요.", ja: "あの男の人は医者です。" } },
  { id: "k1a_29", word: "여자", romaja: "yeoja", pos: "명사", topik: 1, category: "people", meaning: "女・女性", example: { ko: "그 여자는 가수예요.", ja: "その女の人は歌手です。" } },
  { id: "k1a_30", word: "이름", romaja: "ireum", pos: "명사", topik: 1, category: "people", meaning: "名前", example: { ko: "이름이 뭐예요?", ja: "名前は何ですか？" } },

  // ===== number (숫자·수사) =====
  { id: "k1a_31", word: "하나", romaja: "hana", pos: "수사", topik: 1, category: "number", meaning: "一つ", example: { ko: "사과 하나 주세요.", ja: "りんごを一つください。" } },
  { id: "k1a_32", word: "둘", romaja: "dul", pos: "수사", topik: 1, category: "number", meaning: "二つ", example: { ko: "커피 둘 주세요.", ja: "コーヒーを二つください。" } },
  { id: "k1a_33", word: "셋", romaja: "set", pos: "수사", topik: 1, category: "number", meaning: "三つ", example: { ko: "의자가 셋 있어요.", ja: "椅子が三つあります。" } },
  { id: "k1a_34", word: "넷", romaja: "net", pos: "수사", topik: 1, category: "number", meaning: "四つ", example: { ko: "사람이 넷 왔어요.", ja: "人が四人来ました。" } },
  { id: "k1a_35", word: "다섯", romaja: "daseot", pos: "수사", topik: 1, category: "number", meaning: "五つ", example: { ko: "귤을 다섯 개 샀어요.", ja: "みかんを五個買いました。" } },
  { id: "k1a_36", word: "일", romaja: "il", pos: "수사", topik: 1, category: "number", meaning: "一（漢数字）", example: { ko: "일 번 버스를 타세요.", ja: "一番のバスに乗ってください。" } },
  { id: "k1a_37", word: "이", romaja: "i", pos: "수사", topik: 1, category: "number", meaning: "二（漢数字）", example: { ko: "이 층에 화장실이 있어요.", ja: "二階にトイレがあります。" } },
  { id: "k1a_38", word: "삼", romaja: "sam", pos: "수사", topik: 1, category: "number", meaning: "三（漢数字）", example: { ko: "삼 월에 학교가 시작해요.", ja: "三月に学校が始まります。" } },
  { id: "k1a_39", word: "사", romaja: "sa", pos: "수사", topik: 1, category: "number", meaning: "四（漢数字）", example: { ko: "사 시에 만나요.", ja: "四時に会いましょう。" } },
  { id: "k1a_40", word: "오", romaja: "o", pos: "수사", topik: 1, category: "number", meaning: "五（漢数字）", example: { ko: "오 분만 기다려 주세요.", ja: "五分だけ待ってください。" } },
  { id: "k1a_41", word: "십", romaja: "sip", pos: "수사", topik: 1, category: "number", meaning: "十（漢数字）", example: { ko: "십 분 후에 도착해요.", ja: "十分後に到着します。" } },
  { id: "k1a_42", word: "백", romaja: "baek", pos: "수사", topik: 1, category: "number", meaning: "百", example: { ko: "이 책은 백 페이지예요.", ja: "この本は百ページです。" } },
  { id: "k1a_43", word: "천", romaja: "cheon", pos: "수사", topik: 1, category: "number", meaning: "千", example: { ko: "이천 원이에요.", ja: "二千ウォンです。" } },
  { id: "k1a_44", word: "만", romaja: "man", pos: "수사", topik: 1, category: "number", meaning: "万", example: { ko: "이 가방은 만 원이에요.", ja: "このカバンは一万ウォンです。" } },
  { id: "k1a_45", word: "번호", romaja: "beonho", pos: "명사", topik: 1, category: "number", meaning: "番号", example: { ko: "전화번호가 뭐예요?", ja: "電話番号は何ですか？" } },

  // ===== time (시간·날짜) =====
  { id: "k1a_46", word: "오늘", romaja: "oneul", pos: "명사", topik: 1, category: "time", meaning: "今日", example: { ko: "오늘 날씨가 좋아요.", ja: "今日は天気がいいです。" } },
  { id: "k1a_47", word: "내일", romaja: "naeil", pos: "명사", topik: 1, category: "time", meaning: "明日", example: { ko: "내일 시험이 있어요.", ja: "明日試験があります。" } },
  { id: "k1a_48", word: "어제", romaja: "eoje", pos: "명사", topik: 1, category: "time", meaning: "昨日", example: { ko: "어제 친구를 만났어요.", ja: "昨日友達に会いました。" } },
  { id: "k1a_49", word: "지금", romaja: "jigeum", pos: "부사", topik: 1, category: "time", meaning: "今", example: { ko: "지금 몇 시예요?", ja: "今何時ですか？" } },
  { id: "k1a_50", word: "아침", romaja: "achim", pos: "명사", topik: 1, category: "time", meaning: "朝", example: { ko: "아침에 운동을 해요.", ja: "朝に運動をします。" } },
  { id: "k1a_51", word: "점심", romaja: "jeomsim", pos: "명사", topik: 1, category: "time", meaning: "昼・昼食", example: { ko: "점심에 김밥을 먹었어요.", ja: "昼にキンパを食べました。" } },
  { id: "k1a_52", word: "저녁", romaja: "jeonyeok", pos: "명사", topik: 1, category: "time", meaning: "夕方・夕食", example: { ko: "저녁에 집에 가요.", ja: "夕方に家に帰ります。" } },
  { id: "k1a_53", word: "밤", romaja: "bam", pos: "명사", topik: 1, category: "time", meaning: "夜", example: { ko: "밤에 별이 많아요.", ja: "夜に星がたくさんあります。" } },
  { id: "k1a_54", word: "시간", romaja: "sigan", pos: "명사", topik: 1, category: "time", meaning: "時間", example: { ko: "시간이 없어요.", ja: "時間がありません。" } },
  { id: "k1a_55", word: "시", romaja: "si", pos: "명사", topik: 1, category: "time", meaning: "時（じ）", example: { ko: "지금 세 시예요.", ja: "今三時です。" } },
  { id: "k1a_56", word: "분", romaja: "bun", pos: "명사", topik: 1, category: "time", meaning: "分", example: { ko: "십 분만 더 자고 싶어요.", ja: "あと十分だけ寝たいです。" } },
  { id: "k1a_57", word: "날", romaja: "nal", pos: "명사", topik: 1, category: "time", meaning: "日（ひ）", example: { ko: "그 날은 비가 왔어요.", ja: "その日は雨が降りました。" } },
  { id: "k1a_58", word: "주말", romaja: "jumal", pos: "명사", topik: 1, category: "time", meaning: "週末", example: { ko: "주말에 뭐 해요?", ja: "週末に何をしますか？" } },
  { id: "k1a_59", word: "요일", romaja: "yoil", pos: "명사", topik: 1, category: "time", meaning: "曜日", example: { ko: "오늘은 무슨 요일이에요?", ja: "今日は何曜日ですか？" } },
  { id: "k1a_60", word: "월요일", romaja: "woryoil", pos: "명사", topik: 1, category: "time", meaning: "月曜日", example: { ko: "월요일에 회의가 있어요.", ja: "月曜日に会議があります。" } },
  { id: "k1a_61", word: "년", romaja: "nyeon", pos: "명사", topik: 1, category: "time", meaning: "年", example: { ko: "한국에서 일 년 살았어요.", ja: "韓国で一年暮らしました。" } },
  { id: "k1a_62", word: "달", romaja: "dal", pos: "명사", topik: 1, category: "time", meaning: "月（つき・期間）", example: { ko: "한 달에 한 번 만나요.", ja: "一ヶ月に一回会います。" } },

  // ===== food (음식·飲食) =====
  { id: "k1a_63", word: "밥", romaja: "bap", pos: "명사", topik: 1, category: "food", meaning: "ご飯", example: { ko: "밥을 많이 먹었어요.", ja: "ご飯をたくさん食べました。" } },
  { id: "k1a_64", word: "물", romaja: "mul", pos: "명사", topik: 1, category: "food", meaning: "水", example: { ko: "물 좀 주세요.", ja: "水をください。" } },
  { id: "k1a_65", word: "커피", romaja: "keopi", pos: "명사", topik: 1, category: "food", meaning: "コーヒー", example: { ko: "아침에 커피를 마셔요.", ja: "朝にコーヒーを飲みます。" } },
  { id: "k1a_66", word: "차", romaja: "cha", pos: "명사", topik: 1, category: "food", meaning: "お茶", example: { ko: "따뜻한 차를 마시고 싶어요.", ja: "温かいお茶が飲みたいです。" } },
  { id: "k1a_67", word: "빵", romaja: "ppang", pos: "명사", topik: 1, category: "food", meaning: "パン", example: { ko: "빵하고 우유를 먹었어요.", ja: "パンと牛乳を食べました。" } },
  { id: "k1a_68", word: "우유", romaja: "uyu", pos: "명사", topik: 1, category: "food", meaning: "牛乳", example: { ko: "우유는 냉장고에 있어요.", ja: "牛乳は冷蔵庫にあります。" } },
  { id: "k1a_69", word: "고기", romaja: "gogi", pos: "명사", topik: 1, category: "food", meaning: "肉", example: { ko: "저는 고기를 좋아해요.", ja: "私は肉が好きです。" } },
  { id: "k1a_70", word: "과일", romaja: "gwail", pos: "명사", topik: 1, category: "food", meaning: "果物", example: { ko: "과일을 매일 먹어요.", ja: "果物を毎日食べます。" } },
  { id: "k1a_71", word: "사과", romaja: "sagwa", pos: "명사", topik: 1, category: "food", meaning: "りんご", example: { ko: "사과가 아주 달아요.", ja: "りんごがとても甘いです。" } },
  { id: "k1a_72", word: "김치", romaja: "gimchi", pos: "명사", topik: 1, category: "food", meaning: "キムチ", example: { ko: "김치가 조금 매워요.", ja: "キムチが少し辛いです。" } },
  { id: "k1a_73", word: "음식", romaja: "eumsik", pos: "명사", topik: 1, category: "food", meaning: "食べ物・料理", example: { ko: "한국 음식을 좋아해요.", ja: "韓国料理が好きです。" } },
  { id: "k1a_74", word: "라면", romaja: "ramyeon", pos: "명사", topik: 1, category: "food", meaning: "ラーメン", example: { ko: "밤에 라면을 끓였어요.", ja: "夜にラーメンを作りました。" } },
  { id: "k1a_75", word: "달걀", romaja: "dalgyal", pos: "명사", topik: 1, category: "food", meaning: "卵", example: { ko: "달걀 두 개를 삶았어요.", ja: "卵を二個ゆでました。" } },
  { id: "k1a_76", word: "야채", romaja: "yachae", pos: "명사", topik: 1, category: "food", meaning: "野菜", example: { ko: "야채를 많이 드세요.", ja: "野菜をたくさん召し上がってください。" } },
  { id: "k1a_77", word: "설탕", romaja: "seoltang", pos: "명사", topik: 1, category: "food", meaning: "砂糖", example: { ko: "커피에 설탕을 넣었어요.", ja: "コーヒーに砂糖を入れました。" } },

  // ===== place (장소) =====
  { id: "k1a_78", word: "집", romaja: "jip", pos: "명사", topik: 1, category: "place", meaning: "家", example: { ko: "집에서 쉬고 싶어요.", ja: "家で休みたいです。" } },
  { id: "k1a_79", word: "학교", romaja: "haggyo", pos: "명사", topik: 1, category: "place", meaning: "学校", example: { ko: "학교에 걸어서 가요.", ja: "学校に歩いて行きます。" } },
  { id: "k1a_80", word: "회사", romaja: "hoesa", pos: "명사", topik: 1, category: "place", meaning: "会社", example: { ko: "회사가 집에서 멀어요.", ja: "会社が家から遠いです。" } },
  { id: "k1a_81", word: "병원", romaja: "byeongwon", pos: "명사", topik: 1, category: "place", meaning: "病院", example: { ko: "아파서 병원에 갔어요.", ja: "具合が悪くて病院に行きました。" } },
  { id: "k1a_82", word: "은행", romaja: "eunhaeng", pos: "명사", topik: 1, category: "place", meaning: "銀行", example: { ko: "은행에서 돈을 찾았어요.", ja: "銀行でお金をおろしました。" } },
  { id: "k1a_83", word: "식당", romaja: "sikdang", pos: "명사", topik: 1, category: "place", meaning: "食堂・レストラン", example: { ko: "이 식당은 음식이 맛있어요.", ja: "この食堂は料理がおいしいです。" } },
  { id: "k1a_84", word: "가게", romaja: "gage", pos: "명사", topik: 1, category: "place", meaning: "店", example: { ko: "가게에서 빵을 샀어요.", ja: "店でパンを買いました。" } },
  { id: "k1a_85", word: "시장", romaja: "sijang", pos: "명사", topik: 1, category: "place", meaning: "市場", example: { ko: "시장에 과일이 많아요.", ja: "市場に果物がたくさんあります。" } },
  { id: "k1a_86", word: "공원", romaja: "gongwon", pos: "명사", topik: 1, category: "place", meaning: "公園", example: { ko: "공원에서 산책을 해요.", ja: "公園で散歩をします。" } },
  { id: "k1a_87", word: "도서관", romaja: "doseogwan", pos: "명사", topik: 1, category: "place", meaning: "図書館", example: { ko: "도서관에서 공부했어요.", ja: "図書館で勉強しました。" } },
  { id: "k1a_88", word: "역", romaja: "yeok", pos: "명사", topik: 1, category: "place", meaning: "駅", example: { ko: "역까지 십 분 걸려요.", ja: "駅まで十分かかります。" } },
  { id: "k1a_89", word: "화장실", romaja: "hwajangsil", pos: "명사", topik: 1, category: "place", meaning: "トイレ", example: { ko: "화장실이 어디예요?", ja: "トイレはどこですか？" } },
  { id: "k1a_90", word: "방", romaja: "bang", pos: "명사", topik: 1, category: "place", meaning: "部屋", example: { ko: "방이 아주 깨끗해요.", ja: "部屋がとてもきれいです。" } },
  { id: "k1a_91", word: "교실", romaja: "gyosil", pos: "명사", topik: 1, category: "place", meaning: "教室", example: { ko: "교실에 학생이 많아요.", ja: "教室に学生がたくさんいます。" } },
  { id: "k1a_92", word: "나라", romaja: "nara", pos: "명사", topik: 1, category: "place", meaning: "国", example: { ko: "어느 나라에서 왔어요?", ja: "どの国から来ましたか？" } },

  // ===== daily (생활·物) =====
  { id: "k1a_93", word: "책", romaja: "chaek", pos: "명사", topik: 1, category: "daily", meaning: "本", example: { ko: "이 책은 재미있어요.", ja: "この本は面白いです。" } },
  { id: "k1a_94", word: "가방", romaja: "gabang", pos: "명사", topik: 1, category: "daily", meaning: "カバン", example: { ko: "가방에 책이 많아요.", ja: "カバンに本がたくさんあります。" } },
  { id: "k1a_95", word: "옷", romaja: "ot", pos: "명사", topik: 1, category: "daily", meaning: "服", example: { ko: "새 옷을 샀어요.", ja: "新しい服を買いました。" } },
  { id: "k1a_96", word: "신발", romaja: "sinbal", pos: "명사", topik: 1, category: "daily", meaning: "靴", example: { ko: "신발이 좀 작아요.", ja: "靴が少し小さいです。" } },
  { id: "k1a_97", word: "돈", romaja: "don", pos: "명사", topik: 1, category: "daily", meaning: "お金", example: { ko: "돈이 조금 있어요.", ja: "お金が少しあります。" } },
  { id: "k1a_98", word: "전화", romaja: "jeonhwa", pos: "명사", topik: 1, category: "daily", meaning: "電話", example: { ko: "친구에게 전화를 했어요.", ja: "友達に電話をしました。" } },
  { id: "k1a_99", word: "컴퓨터", romaja: "keompyuteo", pos: "명사", topik: 1, category: "daily", meaning: "パソコン", example: { ko: "컴퓨터로 일을 해요.", ja: "パソコンで仕事をします。" } },
  { id: "k1a_100", word: "시계", romaja: "sigye", pos: "명사", topik: 1, category: "daily", meaning: "時計", example: { ko: "벽에 시계가 있어요.", ja: "壁に時計があります。" } },
  { id: "k1a_101", word: "우산", romaja: "usan", pos: "명사", topik: 1, category: "daily", meaning: "傘", example: { ko: "비가 와서 우산을 샀어요.", ja: "雨が降って傘を買いました。" } },
  { id: "k1a_102", word: "의자", romaja: "uija", pos: "명사", topik: 1, category: "daily", meaning: "椅子", example: { ko: "의자에 앉으세요.", ja: "椅子に座ってください。" } },
  { id: "k1a_103", word: "책상", romaja: "chaeksang", pos: "명사", topik: 1, category: "daily", meaning: "机", example: { ko: "책상 위에 노트가 있어요.", ja: "机の上にノートがあります。" } },
  { id: "k1a_104", word: "연필", romaja: "yeonpil", pos: "명사", topik: 1, category: "daily", meaning: "鉛筆", example: { ko: "연필로 이름을 썼어요.", ja: "鉛筆で名前を書きました。" } },
  { id: "k1a_105", word: "창문", romaja: "changmun", pos: "명사", topik: 1, category: "daily", meaning: "窓", example: { ko: "창문을 열어 주세요.", ja: "窓を開けてください。" } },
  { id: "k1a_106", word: "텔레비전", romaja: "tellebijeon", pos: "명사", topik: 1, category: "daily", meaning: "テレビ", example: { ko: "저녁에 텔레비전을 봐요.", ja: "夕方にテレビを見ます。" } },
  { id: "k1a_107", word: "사진", romaja: "sajin", pos: "명사", topik: 1, category: "daily", meaning: "写真", example: { ko: "여기에서 사진을 찍었어요.", ja: "ここで写真を撮りました。" } },

  // ===== body (몸) =====
  { id: "k1a_108", word: "몸", romaja: "mom", pos: "명사", topik: 1, category: "body", meaning: "体", example: { ko: "오늘은 몸이 안 좋아요.", ja: "今日は体の調子が悪いです。" } },
  { id: "k1a_109", word: "머리", romaja: "meori", pos: "명사", topik: 1, category: "body", meaning: "頭・髪", example: { ko: "머리가 조금 아파요.", ja: "頭が少し痛いです。" } },
  { id: "k1a_110", word: "눈", romaja: "nun", pos: "명사", topik: 1, category: "body", meaning: "目", example: { ko: "동생은 눈이 커요.", ja: "弟は目が大きいです。" } },
  { id: "k1a_111", word: "코", romaja: "ko", pos: "명사", topik: 1, category: "body", meaning: "鼻", example: { ko: "감기 때문에 코가 막혔어요.", ja: "風邪で鼻が詰まりました。" } },
  { id: "k1a_112", word: "입", romaja: "ip", pos: "명사", topik: 1, category: "body", meaning: "口", example: { ko: "입을 크게 벌리세요.", ja: "口を大きく開けてください。" } },
  { id: "k1a_113", word: "귀", romaja: "gwi", pos: "명사", topik: 1, category: "body", meaning: "耳", example: { ko: "귀가 잘 안 들려요.", ja: "耳がよく聞こえません。" } },
  { id: "k1a_114", word: "손", romaja: "son", pos: "명사", topik: 1, category: "body", meaning: "手", example: { ko: "밥 먹기 전에 손을 씻어요.", ja: "ご飯を食べる前に手を洗います。" } },
  { id: "k1a_115", word: "발", romaja: "bal", pos: "명사", topik: 1, category: "body", meaning: "足", example: { ko: "많이 걸어서 발이 아파요.", ja: "たくさん歩いて足が痛いです。" } },
  { id: "k1a_116", word: "다리", romaja: "dari", pos: "명사", topik: 1, category: "body", meaning: "脚", example: { ko: "다리가 길어요.", ja: "脚が長いです。" } },
  { id: "k1a_117", word: "팔", romaja: "pal", pos: "명사", topik: 1, category: "body", meaning: "腕", example: { ko: "팔을 들어 보세요.", ja: "腕を上げてみてください。" } },
  { id: "k1a_118", word: "배", romaja: "bae", pos: "명사", topik: 1, category: "body", meaning: "お腹", example: { ko: "배가 너무 고파요.", ja: "お腹がとても空きました。" } },
  { id: "k1a_119", word: "얼굴", romaja: "eolgul", pos: "명사", topik: 1, category: "body", meaning: "顔", example: { ko: "얼굴을 깨끗이 씻었어요.", ja: "顔をきれいに洗いました。" } },
  { id: "k1a_120", word: "이", romaja: "i", pos: "명사", topik: 1, category: "body", meaning: "歯", example: { ko: "자기 전에 이를 닦아요.", ja: "寝る前に歯を磨きます。" } },

  // ===== verb-basic (기본 동사) =====
  { id: "k1a_121", word: "가다", romaja: "gada", pos: "동사", topik: 1, category: "verb-basic", meaning: "行く", example: { ko: "학교에 가요.", ja: "学校に行きます。" } },
  { id: "k1a_122", word: "오다", romaja: "oda", pos: "동사", topik: 1, category: "verb-basic", meaning: "来る", example: { ko: "친구가 집에 와요.", ja: "友達が家に来ます。" } },
  { id: "k1a_123", word: "먹다", romaja: "meokda", pos: "동사", topik: 1, category: "verb-basic", meaning: "食べる", example: { ko: "점심을 먹어요.", ja: "昼ご飯を食べます。" } },
  { id: "k1a_124", word: "마시다", romaja: "masida", pos: "동사", topik: 1, category: "verb-basic", meaning: "飲む", example: { ko: "물을 마셔요.", ja: "水を飲みます。" } },
  { id: "k1a_125", word: "보다", romaja: "boda", pos: "동사", topik: 1, category: "verb-basic", meaning: "見る", example: { ko: "영화를 봐요.", ja: "映画を見ます。" } },
  { id: "k1a_126", word: "읽다", romaja: "ikda", pos: "동사", topik: 1, category: "verb-basic", meaning: "読む", example: { ko: "책을 읽어요.", ja: "本を読みます。" } },
  { id: "k1a_127", word: "쓰다", romaja: "sseuda", pos: "동사", topik: 1, category: "verb-basic", meaning: "書く・使う", example: { ko: "편지를 써요.", ja: "手紙を書きます。" } },
  { id: "k1a_128", word: "사다", romaja: "sada", pos: "동사", topik: 1, category: "verb-basic", meaning: "買う", example: { ko: "옷을 사요.", ja: "服を買います。" } },
  { id: "k1a_129", word: "하다", romaja: "hada", pos: "동사", topik: 1, category: "verb-basic", meaning: "する", example: { ko: "숙제를 해요.", ja: "宿題をします。" } },
  { id: "k1a_130", word: "자다", romaja: "jada", pos: "동사", topik: 1, category: "verb-basic", meaning: "寝る", example: { ko: "밤 열한 시에 자요.", ja: "夜十一時に寝ます。" } },
  { id: "k1a_131", word: "일어나다", romaja: "ireonada", pos: "동사", topik: 1, category: "verb-basic", meaning: "起きる", example: { ko: "아침 일곱 시에 일어나요.", ja: "朝七時に起きます。" } },
  { id: "k1a_132", word: "공부하다", romaja: "gongbuhada", pos: "동사", topik: 1, category: "verb-basic", meaning: "勉強する", example: { ko: "한국어를 공부해요.", ja: "韓国語を勉強します。" } },
  { id: "k1a_133", word: "만나다", romaja: "mannada", pos: "동사", topik: 1, category: "verb-basic", meaning: "会う", example: { ko: "주말에 친구를 만나요.", ja: "週末に友達に会います。" } },
  { id: "k1a_134", word: "주다", romaja: "juda", pos: "동사", topik: 1, category: "verb-basic", meaning: "あげる・くれる", example: { ko: "동생에게 선물을 줘요.", ja: "弟にプレゼントをあげます。" } },
  { id: "k1a_135", word: "좋아하다", romaja: "joahada", pos: "동사", topik: 1, category: "verb-basic", meaning: "好きだ・好む", example: { ko: "저는 음악을 좋아해요.", ja: "私は音楽が好きです。" } },
  { id: "k1a_136", word: "말하다", romaja: "malhada", pos: "동사", topik: 1, category: "verb-basic", meaning: "話す・言う", example: { ko: "천천히 말해 주세요.", ja: "ゆっくり話してください。" } },
  { id: "k1a_137", word: "듣다", romaja: "deutda", pos: "동사", topik: 1, category: "verb-basic", meaning: "聞く", example: { ko: "음악을 들어요.", ja: "音楽を聞きます。" } },

  // ===== adjective (형용사) =====
  { id: "k1a_138", word: "좋다", romaja: "jota", pos: "형용사", topik: 1, category: "adjective", meaning: "良い", example: { ko: "날씨가 좋아요.", ja: "天気が良いです。" } },
  { id: "k1a_139", word: "나쁘다", romaja: "nappeuda", pos: "형용사", topik: 1, category: "adjective", meaning: "悪い", example: { ko: "오늘 기분이 나빠요.", ja: "今日は気分が悪いです。" } },
  { id: "k1a_140", word: "크다", romaja: "keuda", pos: "형용사", topik: 1, category: "adjective", meaning: "大きい", example: { ko: "이 가방이 너무 커요.", ja: "このカバンが大きすぎます。" } },
  { id: "k1a_141", word: "작다", romaja: "jakda", pos: "형용사", topik: 1, category: "adjective", meaning: "小さい", example: { ko: "방이 조금 작아요.", ja: "部屋が少し小さいです。" } },
  { id: "k1a_142", word: "많다", romaja: "manta", pos: "형용사", topik: 1, category: "adjective", meaning: "多い", example: { ko: "사람이 많아요.", ja: "人が多いです。" } },
  { id: "k1a_143", word: "적다", romaja: "jeokda", pos: "형용사", topik: 1, category: "adjective", meaning: "少ない", example: { ko: "돈이 너무 적어요.", ja: "お金が少なすぎます。" } },
  { id: "k1a_144", word: "비싸다", romaja: "bissada", pos: "형용사", topik: 1, category: "adjective", meaning: "（値段が）高い", example: { ko: "이 옷은 비싸요.", ja: "この服は高いです。" } },
  { id: "k1a_145", word: "싸다", romaja: "ssada", pos: "형용사", topik: 1, category: "adjective", meaning: "安い", example: { ko: "이 가게는 과일이 싸요.", ja: "この店は果物が安いです。" } },
  { id: "k1a_146", word: "맛있다", romaja: "masitda", pos: "형용사", topik: 1, category: "adjective", meaning: "おいしい", example: { ko: "이 음식이 정말 맛있어요.", ja: "この料理は本当においしいです。" } },
  { id: "k1a_147", word: "예쁘다", romaja: "yeppeuda", pos: "형용사", topik: 1, category: "adjective", meaning: "きれいだ・かわいい", example: { ko: "꽃이 아주 예뻐요.", ja: "花がとてもきれいです。" } },
  { id: "k1a_148", word: "덥다", romaja: "deopda", pos: "형용사", topik: 1, category: "adjective", meaning: "暑い", example: { ko: "여름에는 날씨가 더워요.", ja: "夏は天気が暑いです。" } },
  { id: "k1a_149", word: "춥다", romaja: "chupda", pos: "형용사", topik: 1, category: "adjective", meaning: "寒い", example: { ko: "겨울에는 아주 추워요.", ja: "冬はとても寒いです。" } },
  { id: "k1a_150", word: "재미있다", romaja: "jaemiitda", pos: "형용사", topik: 1, category: "adjective", meaning: "面白い", example: { ko: "이 드라마가 재미있어요.", ja: "このドラマが面白いです。" } },
];
