import type { KoWord } from "./types";

export const KO_VOCAB_K2: KoWord[] = [
  { id: "k2_1", word: "약속", romaja: "yaksok", pos: "명사", topik: 2, category: "daily", meaning: "約束", example: { ko: "친구와 약속이 있어요.", ja: "友達と約束があります。" } },
  { id: "k2_2", word: "회의", romaja: "hoeui", pos: "명사", topik: 2, category: "work", meaning: "会議", example: { ko: "오후에 회의가 있어요.", ja: "午後に会議があります。" } },
  { id: "k2_3", word: "약국", romaja: "yakguk", pos: "명사", topik: 2, category: "place", meaning: "薬局", example: { ko: "약국에서 약을 샀어요.", ja: "薬局で薬を買いました。" } },
  { id: "k2_4", word: "감기", romaja: "gamgi", pos: "명사", topik: 2, category: "health", meaning: "風邪", example: { ko: "감기에 걸렸어요.", ja: "風邪をひきました。" } },
  { id: "k2_5", word: "열", romaja: "yeol", pos: "명사", topik: 2, category: "health", meaning: "熱", example: { ko: "열이 많이 나요.", ja: "熱がたくさん出ています。" } },
  { id: "k2_6", word: "두통", romaja: "dutong", pos: "명사", topik: 2, category: "health", meaning: "頭痛", example: { ko: "두통이 심해요.", ja: "頭痛がひどいです。" } },
  { id: "k2_7", word: "운동", romaja: "undong", pos: "명사", topik: 2, category: "health", meaning: "運動", example: { ko: "매일 아침 운동을 해요.", ja: "毎朝運動をします。" } },
  { id: "k2_8", word: "건강", romaja: "geongang", pos: "명사", topik: 2, category: "health", meaning: "健康", example: { ko: "건강이 제일 중요해요.", ja: "健康が一番大切です。" } },
  { id: "k2_9", word: "병원", romaja: "byeongwon", pos: "명사", topik: 2, category: "place", meaning: "病院", example: { ko: "어제 병원에 갔어요.", ja: "昨日病院に行きました。" } },
  { id: "k2_10", word: "치료", romaja: "chiryo", pos: "명사", topik: 2, category: "health", meaning: "治療", example: { ko: "치료를 받고 있어요.", ja: "治療を受けています。" } },
  { id: "k2_11", word: "주사", romaja: "jusa", pos: "명사", topik: 2, category: "health", meaning: "注射", example: { ko: "주사를 맞기 싫어요.", ja: "注射を打たれるのが嫌です。" } },
  { id: "k2_12", word: "환자", romaja: "hwanja", pos: "명사", topik: 2, category: "people", meaning: "患者", example: { ko: "환자가 많아요.", ja: "患者が多いです。" } },
  { id: "k2_13", word: "의사", romaja: "uisa", pos: "명사", topik: 2, category: "people", meaning: "医者", example: { ko: "의사 선생님이 친절해요.", ja: "お医者さんが親切です。" } },
  { id: "k2_14", word: "간호사", romaja: "ganhosa", pos: "명사", topik: 2, category: "people", meaning: "看護師", example: { ko: "간호사가 주사를 놨어요.", ja: "看護師が注射をしました。" } },
  { id: "k2_15", word: "이웃", romaja: "iut", pos: "명사", topik: 2, category: "people", meaning: "隣人", example: { ko: "이웃과 사이가 좋아요.", ja: "隣人と仲がいいです。" } },
  { id: "k2_16", word: "손님", romaja: "sonnim", pos: "명사", topik: 2, category: "people", meaning: "お客さん", example: { ko: "손님이 오셨어요.", ja: "お客さんがいらっしゃいました。" } },
  { id: "k2_17", word: "주인", romaja: "juin", pos: "명사", topik: 2, category: "people", meaning: "主人・オーナー", example: { ko: "가게 주인이 친절해요.", ja: "店のオーナーが親切です。" } },
  { id: "k2_18", word: "부부", romaja: "bubu", pos: "명사", topik: 2, category: "people", meaning: "夫婦", example: { ko: "저 부부는 사이가 좋아요.", ja: "あの夫婦は仲がいいです。" } },
  { id: "k2_19", word: "어른", romaja: "eoreun", pos: "명사", topik: 2, category: "people", meaning: "大人", example: { ko: "어른에게 인사를 했어요.", ja: "大人に挨拶をしました。" } },
  { id: "k2_20", word: "청년", romaja: "cheongnyeon", pos: "명사", topik: 2, category: "people", meaning: "青年", example: { ko: "그는 성실한 청년이에요.", ja: "彼は誠実な青年です。" } },
  { id: "k2_21", word: "이모", romaja: "imo", pos: "명사", topik: 2, category: "people", meaning: "おば（母方）", example: { ko: "이모 집에 놀러 갔어요.", ja: "おばの家に遊びに行きました。" } },
  { id: "k2_22", word: "삼촌", romaja: "samchon", pos: "명사", topik: 2, category: "people", meaning: "おじ", example: { ko: "삼촌이 선물을 주셨어요.", ja: "おじがプレゼントをくれました。" } },
  { id: "k2_23", word: "손자", romaja: "sonja", pos: "명사", topik: 2, category: "people", meaning: "孫", example: { ko: "할머니가 손자를 안았어요.", ja: "祖母が孫を抱きました。" } },
  { id: "k2_24", word: "사위", romaja: "sawi", pos: "명사", topik: 2, category: "people", meaning: "婿", example: { ko: "사위가 인사하러 왔어요.", ja: "婿が挨拶しに来ました。" } },
  { id: "k2_25", word: "동료", romaja: "dongnyo", pos: "명사", topik: 2, category: "work", meaning: "同僚", example: { ko: "동료와 같이 점심을 먹었어요.", ja: "同僚と一緒に昼食を食べました。" } },
  { id: "k2_26", word: "부장", romaja: "bujang", pos: "명사", topik: 2, category: "work", meaning: "部長", example: { ko: "부장님이 출장을 가셨어요.", ja: "部長が出張に行かれました。" } },
  { id: "k2_27", word: "회사원", romaja: "hoesawon", pos: "명사", topik: 2, category: "work", meaning: "会社員", example: { ko: "저는 회사원이에요.", ja: "私は会社員です。" } },
  { id: "k2_28", word: "직업", romaja: "jigeop", pos: "명사", topik: 2, category: "work", meaning: "職業", example: { ko: "직업이 뭐예요?", ja: "職業は何ですか？" } },
  { id: "k2_29", word: "월급", romaja: "wolgeup", pos: "명사", topik: 2, category: "work", meaning: "月給", example: { ko: "이번 달 월급을 받았어요.", ja: "今月の給料をもらいました。" } },
  { id: "k2_30", word: "출근", romaja: "chulgeun", pos: "명사", topik: 2, category: "work", meaning: "出勤", example: { ko: "아침 아홉 시에 출근해요.", ja: "朝九時に出勤します。" } },
  { id: "k2_31", word: "퇴근", romaja: "toegeun", pos: "명사", topik: 2, category: "work", meaning: "退勤", example: { ko: "보통 여섯 시에 퇴근해요.", ja: "普段六時に退勤します。" } },
  { id: "k2_32", word: "휴가", romaja: "hyuga", pos: "명사", topik: 2, category: "work", meaning: "休暇", example: { ko: "다음 주에 휴가를 갈 거예요.", ja: "来週休暇に行く予定です。" } },
  { id: "k2_33", word: "면접", romaja: "myeonjeop", pos: "명사", topik: 2, category: "work", meaning: "面接", example: { ko: "내일 면접이 있어요.", ja: "明日面接があります。" } },
  { id: "k2_34", word: "서류", romaja: "seoryu", pos: "명사", topik: 2, category: "work", meaning: "書類", example: { ko: "서류를 준비했어요.", ja: "書類を準備しました。" } },
  { id: "k2_35", word: "계획", romaja: "gyehoek", pos: "명사", topik: 2, category: "work", meaning: "計画", example: { ko: "여행 계획을 세웠어요.", ja: "旅行の計画を立てました。" } },
  { id: "k2_36", word: "결과", romaja: "gyeolgwa", pos: "명사", topik: 2, category: "work", meaning: "結果", example: { ko: "시험 결과가 나왔어요.", ja: "試験の結果が出ました。" } },
  { id: "k2_37", word: "방법", romaja: "bangbeop", pos: "명사", topik: 2, category: "work", meaning: "方法", example: { ko: "좋은 방법이 있어요.", ja: "いい方法があります。" } },
  { id: "k2_38", word: "이유", romaja: "iyu", pos: "명사", topik: 2, category: "daily", meaning: "理由", example: { ko: "늦은 이유를 말했어요.", ja: "遅れた理由を話しました。" } },
  { id: "k2_39", word: "약", romaja: "yak", pos: "명사", topik: 2, category: "health", meaning: "薬", example: { ko: "식사 후에 약을 드세요.", ja: "食事の後に薬を飲んでください。" } },
  { id: "k2_40", word: "음식점", romaja: "eumsikjeom", pos: "명사", topik: 2, category: "place", meaning: "飲食店", example: { ko: "유명한 음식점에 갔어요.", ja: "有名な飲食店に行きました。" } },
  { id: "k2_41", word: "시장", romaja: "sijang", pos: "명사", topik: 2, category: "place", meaning: "市場", example: { ko: "시장에서 과일을 샀어요.", ja: "市場で果物を買いました。" } },
  { id: "k2_42", word: "은행", romaja: "eunhaeng", pos: "명사", topik: 2, category: "place", meaning: "銀行", example: { ko: "은행에서 돈을 찾았어요.", ja: "銀行でお金をおろしました。" } },
  { id: "k2_43", word: "우체국", romaja: "ucheguk", pos: "명사", topik: 2, category: "place", meaning: "郵便局", example: { ko: "우체국에서 편지를 보냈어요.", ja: "郵便局で手紙を送りました。" } },
  { id: "k2_44", word: "미용실", romaja: "miyongsil", pos: "명사", topik: 2, category: "place", meaning: "美容室", example: { ko: "미용실에서 머리를 잘랐어요.", ja: "美容室で髪を切りました。" } },
  { id: "k2_45", word: "공항", romaja: "gonghang", pos: "명사", topik: 2, category: "place", meaning: "空港", example: { ko: "공항까지 택시를 탔어요.", ja: "空港までタクシーに乗りました。" } },
  { id: "k2_46", word: "정류장", romaja: "jeongnyujang", pos: "명사", topik: 2, category: "place", meaning: "停留所", example: { ko: "버스 정류장에서 기다렸어요.", ja: "バス停で待ちました。" } },
  { id: "k2_47", word: "주차장", romaja: "juchajang", pos: "명사", topik: 2, category: "place", meaning: "駐車場", example: { ko: "주차장이 가득 찼어요.", ja: "駐車場がいっぱいです。" } },
  { id: "k2_48", word: "사거리", romaja: "sageori", pos: "명사", topik: 2, category: "place", meaning: "交差点", example: { ko: "사거리에서 오른쪽으로 가세요.", ja: "交差点で右に行ってください。" } },
  { id: "k2_49", word: "건물", romaja: "geonmul", pos: "명사", topik: 2, category: "place", meaning: "建物", example: { ko: "저 건물이 아주 높아요.", ja: "あの建物はとても高いです。" } },
  { id: "k2_50", word: "지하철역", romaja: "jihacheollyeok", pos: "명사", topik: 2, category: "place", meaning: "地下鉄の駅", example: { ko: "지하철역이 가까워요.", ja: "地下鉄の駅が近いです。" } },
  { id: "k2_51", word: "골목", romaja: "golmok", pos: "명사", topik: 2, category: "place", meaning: "路地", example: { ko: "좁은 골목으로 들어갔어요.", ja: "狭い路地に入りました。" } },
  { id: "k2_52", word: "고향", romaja: "gohyang", pos: "명사", topik: 2, category: "place", meaning: "故郷", example: { ko: "방학에 고향에 갔어요.", ja: "休みに故郷に帰りました。" } },
  { id: "k2_53", word: "재료", romaja: "jaeryo", pos: "명사", topik: 2, category: "food", meaning: "材料", example: { ko: "요리 재료를 샀어요.", ja: "料理の材料を買いました。" } },
  { id: "k2_54", word: "양념", romaja: "yangnyeom", pos: "명사", topik: 2, category: "food", meaning: "薬味・味付け", example: { ko: "양념이 맛있어요.", ja: "味付けがおいしいです。" } },
  { id: "k2_55", word: "반찬", romaja: "banchan", pos: "명사", topik: 2, category: "food", meaning: "おかず", example: { ko: "반찬이 다양해요.", ja: "おかずが豊富です。" } },
  { id: "k2_56", word: "국", romaja: "guk", pos: "명사", topik: 2, category: "food", meaning: "スープ・汁物", example: { ko: "따뜻한 국을 먹었어요.", ja: "温かいスープを飲みました。" } },
  { id: "k2_57", word: "찌개", romaja: "jjigae", pos: "명사", topik: 2, category: "food", meaning: "チゲ・鍋料理", example: { ko: "김치찌개를 좋아해요.", ja: "キムチチゲが好きです。" } },
  { id: "k2_58", word: "간식", romaja: "gansik", pos: "명사", topik: 2, category: "food", meaning: "おやつ・間食", example: { ko: "아이가 간식을 먹어요.", ja: "子どもがおやつを食べます。" } },
  { id: "k2_59", word: "후식", romaja: "husik", pos: "명사", topik: 2, category: "food", meaning: "デザート", example: { ko: "후식으로 과일을 먹었어요.", ja: "デザートに果物を食べました。" } },
  { id: "k2_60", word: "맛집", romaja: "matjip", pos: "명사", topik: 2, category: "food", meaning: "おいしい店・名店", example: { ko: "이 동네 맛집을 찾았어요.", ja: "この町のおいしい店を見つけました。" } },
  { id: "k2_61", word: "주문", romaja: "jumun", pos: "명사", topik: 2, category: "food", meaning: "注文", example: { ko: "음식을 주문했어요.", ja: "料理を注文しました。" } },
  { id: "k2_62", word: "메뉴", romaja: "menyu", pos: "명사", topik: 2, category: "food", meaning: "メニュー", example: { ko: "메뉴를 보여 주세요.", ja: "メニューを見せてください。" } },
  { id: "k2_63", word: "맛", romaja: "mat", pos: "명사", topik: 2, category: "food", meaning: "味", example: { ko: "이 음식 맛이 좋아요.", ja: "この料理は味がいいです。" } },
  { id: "k2_64", word: "냄새", romaja: "naemsae", pos: "명사", topik: 2, category: "daily", meaning: "におい", example: { ko: "좋은 냄새가 나요.", ja: "いいにおいがします。" } },
  { id: "k2_65", word: "그릇", romaja: "geureut", pos: "명사", topik: 2, category: "food", meaning: "器・うつわ", example: { ko: "그릇을 깨끗이 씻었어요.", ja: "器をきれいに洗いました。" } },
  { id: "k2_66", word: "젓가락", romaja: "jeotgarak", pos: "명사", topik: 2, category: "food", meaning: "箸", example: { ko: "젓가락으로 먹어요.", ja: "箸で食べます。" } },
  { id: "k2_67", word: "숟가락", romaja: "sutgarak", pos: "명사", topik: 2, category: "food", meaning: "スプーン", example: { ko: "숟가락으로 국을 떠요.", ja: "スプーンでスープをすくいます。" } },
  { id: "k2_68", word: "지갑", romaja: "jigap", pos: "명사", topik: 2, category: "daily", meaning: "財布", example: { ko: "지갑을 잃어버렸어요.", ja: "財布をなくしました。" } },
  { id: "k2_69", word: "우산", romaja: "usan", pos: "명사", topik: 2, category: "daily", meaning: "傘", example: { ko: "우산을 가지고 가세요.", ja: "傘を持って行ってください。" } },
  { id: "k2_70", word: "열쇠", romaja: "yeolsoe", pos: "명사", topik: 2, category: "daily", meaning: "鍵", example: { ko: "집 열쇠를 찾고 있어요.", ja: "家の鍵を探しています。" } },
  { id: "k2_71", word: "거울", romaja: "geoul", pos: "명사", topik: 2, category: "daily", meaning: "鏡", example: { ko: "거울을 보고 머리를 빗어요.", ja: "鏡を見て髪をとかします。" } },
  { id: "k2_72", word: "수건", romaja: "sugeon", pos: "명사", topik: 2, category: "daily", meaning: "タオル", example: { ko: "수건으로 손을 닦았어요.", ja: "タオルで手を拭きました。" } },
  { id: "k2_73", word: "쓰레기", romaja: "sseuregi", pos: "명사", topik: 2, category: "daily", meaning: "ゴミ", example: { ko: "쓰레기를 버렸어요.", ja: "ゴミを捨てました。" } },
  { id: "k2_74", word: "청소", romaja: "cheongso", pos: "명사", topik: 2, category: "daily", meaning: "掃除", example: { ko: "주말에 청소를 해요.", ja: "週末に掃除をします。" } },
  { id: "k2_75", word: "빨래", romaja: "ppallae", pos: "명사", topik: 2, category: "daily", meaning: "洗濯", example: { ko: "오늘 빨래를 했어요.", ja: "今日洗濯をしました。" } },
  { id: "k2_76", word: "설거지", romaja: "seolgeoji", pos: "명사", topik: 2, category: "daily", meaning: "皿洗い", example: { ko: "밥을 먹고 설거지를 했어요.", ja: "ご飯を食べて皿洗いをしました。" } },
  { id: "k2_77", word: "준비", romaja: "junbi", pos: "명사", topik: 2, category: "daily", meaning: "準備", example: { ko: "여행 준비를 했어요.", ja: "旅行の準備をしました。" } },
  { id: "k2_78", word: "습관", romaja: "seupgwan", pos: "명사", topik: 2, category: "daily", meaning: "習慣", example: { ko: "일찍 자는 습관이 있어요.", ja: "早く寝る習慣があります。" } },
  { id: "k2_79", word: "취미", romaja: "chwimi", pos: "명사", topik: 2, category: "hobby", meaning: "趣味", example: { ko: "제 취미는 독서예요.", ja: "私の趣味は読書です。" } },
  { id: "k2_80", word: "여행", romaja: "yeohaeng", pos: "명사", topik: 2, category: "hobby", meaning: "旅行", example: { ko: "여름에 여행을 가고 싶어요.", ja: "夏に旅行に行きたいです。" } },
  { id: "k2_81", word: "사진", romaja: "sajin", pos: "명사", topik: 2, category: "hobby", meaning: "写真", example: { ko: "사진을 찍는 것을 좋아해요.", ja: "写真を撮るのが好きです。" } },
  { id: "k2_82", word: "그림", romaja: "geurim", pos: "명사", topik: 2, category: "hobby", meaning: "絵", example: { ko: "그림을 잘 그려요.", ja: "絵が上手です。" } },
  { id: "k2_83", word: "노래", romaja: "norae", pos: "명사", topik: 2, category: "hobby", meaning: "歌", example: { ko: "한국 노래를 자주 들어요.", ja: "韓国の歌をよく聞きます。" } },
  { id: "k2_84", word: "춤", romaja: "chum", pos: "명사", topik: 2, category: "hobby", meaning: "踊り・ダンス", example: { ko: "친구가 춤을 잘 춰요.", ja: "友達は踊りが上手です。" } },
  { id: "k2_85", word: "운동화", romaja: "undonghwa", pos: "명사", topik: 2, category: "hobby", meaning: "運動靴・スニーカー", example: { ko: "새 운동화를 샀어요.", ja: "新しいスニーカーを買いました。" } },
  { id: "k2_86", word: "경기", romaja: "gyeonggi", pos: "명사", topik: 2, category: "hobby", meaning: "試合", example: { ko: "축구 경기를 봤어요.", ja: "サッカーの試合を見ました。" } },
  { id: "k2_87", word: "공연", romaja: "gongyeon", pos: "명사", topik: 2, category: "hobby", meaning: "公演", example: { ko: "공연이 아주 멋있었어요.", ja: "公演がとても素晴らしかったです。" } },
  { id: "k2_88", word: "영화관", romaja: "yeonghwagwan", pos: "명사", topik: 2, category: "hobby", meaning: "映画館", example: { ko: "영화관에서 영화를 봤어요.", ja: "映画館で映画を見ました。" } },
  { id: "k2_89", word: "소설", romaja: "soseol", pos: "명사", topik: 2, category: "hobby", meaning: "小説", example: { ko: "재미있는 소설을 읽었어요.", ja: "面白い小説を読みました。" } },
  { id: "k2_90", word: "기분", romaja: "gibun", pos: "명사", topik: 2, category: "emotion", meaning: "気分", example: { ko: "오늘 기분이 좋아요.", ja: "今日は気分がいいです。" } },
  { id: "k2_91", word: "걱정", romaja: "geokjeong", pos: "명사", topik: 2, category: "emotion", meaning: "心配", example: { ko: "시험 걱정을 많이 해요.", ja: "試験のことをとても心配しています。" } },
  { id: "k2_92", word: "관심", romaja: "gwansim", pos: "명사", topik: 2, category: "emotion", meaning: "関心・興味", example: { ko: "음악에 관심이 많아요.", ja: "音楽にとても興味があります。" } },
  { id: "k2_93", word: "사랑", romaja: "sarang", pos: "명사", topik: 2, category: "emotion", meaning: "愛", example: { ko: "가족의 사랑을 느껴요.", ja: "家族の愛を感じます。" } },
  { id: "k2_94", word: "추억", romaja: "chueok", pos: "명사", topik: 2, category: "emotion", meaning: "思い出", example: { ko: "좋은 추억이 많아요.", ja: "いい思い出がたくさんあります。" } },
  { id: "k2_95", word: "꿈", romaja: "kkum", pos: "명사", topik: 2, category: "emotion", meaning: "夢", example: { ko: "제 꿈은 의사예요.", ja: "私の夢は医者です。" } },
  { id: "k2_96", word: "성격", romaja: "seonggyeok", pos: "명사", topik: 2, category: "emotion", meaning: "性格", example: { ko: "그는 성격이 밝아요.", ja: "彼は性格が明るいです。" } },
  { id: "k2_97", word: "느낌", romaja: "neukkim", pos: "명사", topik: 2, category: "emotion", meaning: "感じ", example: { ko: "이상한 느낌이 들어요.", ja: "変な感じがします。" } },
  { id: "k2_98", word: "마음", romaja: "maeum", pos: "명사", topik: 2, category: "emotion", meaning: "心", example: { ko: "따뜻한 마음을 가졌어요.", ja: "温かい心を持っています。" } },
  { id: "k2_99", word: "오전", romaja: "ojeon", pos: "명사", topik: 2, category: "time", meaning: "午前", example: { ko: "오전에 수업이 있어요.", ja: "午前に授業があります。" } },
  { id: "k2_100", word: "오후", romaja: "ohu", pos: "명사", topik: 2, category: "time", meaning: "午後", example: { ko: "오후에 친구를 만나요.", ja: "午後に友達に会います。" } },
  { id: "k2_101", word: "주말", romaja: "jumal", pos: "명사", topik: 2, category: "time", meaning: "週末", example: { ko: "주말에 쉬어요.", ja: "週末に休みます。" } },
  { id: "k2_102", word: "평일", romaja: "pyeongil", pos: "명사", topik: 2, category: "time", meaning: "平日", example: { ko: "평일에는 바빠요.", ja: "平日は忙しいです。" } },
  { id: "k2_103", word: "지난주", romaja: "jinanju", pos: "명사", topik: 2, category: "time", meaning: "先週", example: { ko: "지난주에 영화를 봤어요.", ja: "先週映画を見ました。" } },
  { id: "k2_104", word: "다음 달", romaja: "daeum dal", pos: "명사", topik: 2, category: "time", meaning: "来月", example: { ko: "다음 달에 이사를 가요.", ja: "来月引っ越します。" } },
  { id: "k2_105", word: "최근", romaja: "choegeun", pos: "명사", topik: 2, category: "time", meaning: "最近", example: { ko: "최근에 바빴어요.", ja: "最近忙しかったです。" } },
  { id: "k2_106", word: "요즘", romaja: "yojeum", pos: "명사", topik: 2, category: "time", meaning: "この頃・最近", example: { ko: "요즘 날씨가 좋아요.", ja: "この頃天気がいいです。" } },
  { id: "k2_107", word: "잠깐", romaja: "jamkkan", pos: "부사", topik: 2, category: "time", meaning: "ちょっと・しばらく", example: { ko: "잠깐 기다려 주세요.", ja: "ちょっと待ってください。" } },
  { id: "k2_108", word: "갑자기", romaja: "gapjagi", pos: "부사", topik: 2, category: "adverb", meaning: "急に", example: { ko: "갑자기 비가 왔어요.", ja: "急に雨が降りました。" } },
  { id: "k2_109", word: "벌써", romaja: "beolsseo", pos: "부사", topik: 2, category: "adverb", meaning: "もう・すでに", example: { ko: "벌써 점심시간이에요.", ja: "もうお昼の時間です。" } },
  { id: "k2_110", word: "아직", romaja: "ajik", pos: "부사", topik: 2, category: "adverb", meaning: "まだ", example: { ko: "아직 안 끝났어요.", ja: "まだ終わっていません。" } },
  { id: "k2_111", word: "거의", romaja: "geoui", pos: "부사", topik: 2, category: "adverb", meaning: "ほとんど", example: { ko: "거의 다 했어요.", ja: "ほとんど終わりました。" } },
  { id: "k2_112", word: "특히", romaja: "teukhi", pos: "부사", topik: 2, category: "adverb", meaning: "特に", example: { ko: "특히 여름을 좋아해요.", ja: "特に夏が好きです。" } },
  { id: "k2_113", word: "역시", romaja: "yeoksi", pos: "부사", topik: 2, category: "adverb", meaning: "やはり", example: { ko: "역시 이게 제일 좋아요.", ja: "やはりこれが一番いいです。" } },
  { id: "k2_114", word: "별로", romaja: "byeollo", pos: "부사", topik: 2, category: "adverb", meaning: "あまり（〜ない）", example: { ko: "이 영화는 별로 안 좋아요.", ja: "この映画はあまりよくないです。" } },
  { id: "k2_115", word: "직접", romaja: "jikjeop", pos: "부사", topik: 2, category: "adverb", meaning: "直接・自分で", example: { ko: "직접 만들었어요.", ja: "自分で作りました。" } },
  { id: "k2_116", word: "천천히", romaja: "cheoncheonhi", pos: "부사", topik: 2, category: "adverb", meaning: "ゆっくり", example: { ko: "천천히 말해 주세요.", ja: "ゆっくり話してください。" } },
  { id: "k2_117", word: "다시", romaja: "dasi", pos: "부사", topik: 2, category: "adverb", meaning: "また・再び", example: { ko: "다시 한번 설명해 주세요.", ja: "もう一度説明してください。" } },
  { id: "k2_118", word: "가끔", romaja: "gakkeum", pos: "부사", topik: 2, category: "adverb", meaning: "たまに", example: { ko: "가끔 영화를 봐요.", ja: "たまに映画を見ます。" } },
  { id: "k2_119", word: "자주", romaja: "jaju", pos: "부사", topik: 2, category: "adverb", meaning: "よく・頻繁に", example: { ko: "친구를 자주 만나요.", ja: "友達によく会います。" } },
  { id: "k2_120", word: "항상", romaja: "hangsang", pos: "부사", topik: 2, category: "adverb", meaning: "いつも", example: { ko: "항상 웃어요.", ja: "いつも笑っています。" } },
  { id: "k2_121", word: "준비하다", romaja: "junbihada", pos: "동사", topik: 2, category: "verb", meaning: "準備する", example: { ko: "시험을 준비해요.", ja: "試験の準備をします。" } },
  { id: "k2_122", word: "초대하다", romaja: "chodaehada", pos: "동사", topik: 2, category: "verb", meaning: "招待する", example: { ko: "친구를 집에 초대했어요.", ja: "友達を家に招待しました。" } },
  { id: "k2_123", word: "약속하다", romaja: "yaksokhada", pos: "동사", topik: 2, category: "verb", meaning: "約束する", example: { ko: "내일 만나기로 약속했어요.", ja: "明日会うと約束しました。" } },
  { id: "k2_124", word: "걱정하다", romaja: "geokjeonghada", pos: "동사", topik: 2, category: "verb", meaning: "心配する", example: { ko: "너무 걱정하지 마세요.", ja: "あまり心配しないでください。" } },
  { id: "k2_125", word: "결정하다", romaja: "gyeoljeonghada", pos: "동사", topik: 2, category: "verb", meaning: "決定する", example: { ko: "여행지를 결정했어요.", ja: "旅行先を決定しました。" } },
  { id: "k2_126", word: "설명하다", romaja: "seolmyeonghada", pos: "동사", topik: 2, category: "verb", meaning: "説明する", example: { ko: "선생님이 친절하게 설명해요.", ja: "先生が親切に説明します。" } },
  { id: "k2_127", word: "신청하다", romaja: "sincheonghada", pos: "동사", topik: 2, category: "verb", meaning: "申し込む", example: { ko: "수업을 신청했어요.", ja: "授業を申し込みました。" } },
  { id: "k2_128", word: "확인하다", romaja: "hwaginhada", pos: "동사", topik: 2, category: "verb", meaning: "確認する", example: { ko: "예약을 확인했어요.", ja: "予約を確認しました。" } },
  { id: "k2_129", word: "이용하다", romaja: "iyonghada", pos: "동사", topik: 2, category: "verb", meaning: "利用する", example: { ko: "지하철을 이용해요.", ja: "地下鉄を利用します。" } },
  { id: "k2_130", word: "소개하다", romaja: "sogaehada", pos: "동사", topik: 2, category: "verb", meaning: "紹介する", example: { ko: "친구를 소개해 줬어요.", ja: "友達を紹介してくれました。" } },
  { id: "k2_131", word: "찾다", romaja: "chatda", pos: "동사", topik: 2, category: "verb", meaning: "探す・見つける", example: { ko: "잃어버린 지갑을 찾았어요.", ja: "なくした財布を見つけました。" } },
  { id: "k2_132", word: "빌리다", romaja: "billida", pos: "동사", topik: 2, category: "verb", meaning: "借りる", example: { ko: "도서관에서 책을 빌렸어요.", ja: "図書館で本を借りました。" } },
  { id: "k2_133", word: "돌려주다", romaja: "dollyeojuda", pos: "동사", topik: 2, category: "verb", meaning: "返す", example: { ko: "친구에게 책을 돌려줬어요.", ja: "友達に本を返しました。" } },
  { id: "k2_134", word: "고치다", romaja: "gochida", pos: "동사", topik: 2, category: "verb", meaning: "直す・修理する", example: { ko: "고장난 시계를 고쳤어요.", ja: "壊れた時計を直しました。" } },
  { id: "k2_135", word: "바꾸다", romaja: "bakkuda", pos: "동사", topik: 2, category: "verb", meaning: "変える・交換する", example: { ko: "약속 시간을 바꿨어요.", ja: "約束の時間を変えました。" } },
  { id: "k2_136", word: "잃어버리다", romaja: "ireobeorida", pos: "동사", topik: 2, category: "verb", meaning: "なくす・失う", example: { ko: "우산을 잃어버렸어요.", ja: "傘をなくしました。" } },
  { id: "k2_137", word: "남다", romaja: "namda", pos: "동사", topik: 2, category: "verb", meaning: "残る", example: { ko: "음식이 많이 남았어요.", ja: "料理がたくさん残りました。" } },
  { id: "k2_138", word: "모으다", romaja: "moeuda", pos: "동사", topik: 2, category: "verb", meaning: "集める・貯める", example: { ko: "돈을 모으고 있어요.", ja: "お金を貯めています。" } },
  { id: "k2_139", word: "나누다", romaja: "nanuda", pos: "동사", topik: 2, category: "verb", meaning: "分ける", example: { ko: "과자를 친구와 나눠 먹었어요.", ja: "お菓子を友達と分けて食べました。" } },
  { id: "k2_140", word: "지키다", romaja: "jikida", pos: "동사", topik: 2, category: "verb", meaning: "守る", example: { ko: "약속을 꼭 지켜요.", ja: "約束を必ず守ります。" } },
  { id: "k2_141", word: "참다", romaja: "chamda", pos: "동사", topik: 2, category: "verb", meaning: "我慢する", example: { ko: "아픈 것을 참았어요.", ja: "痛いのを我慢しました。" } },
  { id: "k2_142", word: "느끼다", romaja: "neukkida", pos: "동사", topik: 2, category: "verb", meaning: "感じる", example: { ko: "행복을 느꼈어요.", ja: "幸せを感じました。" } },
  { id: "k2_143", word: "잊다", romaja: "itda", pos: "동사", topik: 2, category: "verb", meaning: "忘れる", example: { ko: "비밀번호를 잊었어요.", ja: "パスワードを忘れました。" } },
  { id: "k2_144", word: "기억하다", romaja: "gieokhada", pos: "동사", topik: 2, category: "verb", meaning: "覚える・記憶する", example: { ko: "그 일을 잘 기억해요.", ja: "そのことをよく覚えています。" } },
  { id: "k2_145", word: "걸리다", romaja: "geollida", pos: "동사", topik: 2, category: "verb", meaning: "かかる（時間・病気）", example: { ko: "감기에 걸렸어요.", ja: "風邪をひきました。" } },
  { id: "k2_146", word: "내리다", romaja: "naerida", pos: "동사", topik: 2, category: "verb", meaning: "降りる・降る", example: { ko: "다음 역에서 내려요.", ja: "次の駅で降ります。" } },
  { id: "k2_147", word: "올라가다", romaja: "ollagada", pos: "동사", topik: 2, category: "verb", meaning: "上がる・登る", example: { ko: "산에 올라갔어요.", ja: "山に登りました。" } },
  { id: "k2_148", word: "들어가다", romaja: "deureogada", pos: "동사", topik: 2, category: "verb", meaning: "入る", example: { ko: "방에 들어갔어요.", ja: "部屋に入りました。" } },
  { id: "k2_149", word: "나가다", romaja: "nagada", pos: "동사", topik: 2, category: "verb", meaning: "出る・出かける", example: { ko: "밖에 나갔어요.", ja: "外に出ました。" } },
  { id: "k2_150", word: "도착하다", romaja: "dochakhada", pos: "동사", topik: 2, category: "verb", meaning: "到着する", example: { ko: "역에 도착했어요.", ja: "駅に到着しました。" } },
  { id: "k2_151", word: "출발하다", romaja: "chulbalhada", pos: "동사", topik: 2, category: "verb", meaning: "出発する", example: { ko: "기차가 곧 출발해요.", ja: "電車がもうすぐ出発します。" } },
  { id: "k2_152", word: "예약하다", romaja: "yeyakhada", pos: "동사", topik: 2, category: "verb", meaning: "予約する", example: { ko: "식당을 예약했어요.", ja: "レストランを予約しました。" } },
  { id: "k2_153", word: "복잡하다", romaja: "bokjapada", pos: "형용사", topik: 2, category: "adjective", meaning: "複雑だ・混雑している", example: { ko: "길이 너무 복잡해요.", ja: "道がとても混んでいます。" } },
  { id: "k2_154", word: "간단하다", romaja: "gandanhada", pos: "형용사", topik: 2, category: "adjective", meaning: "簡単だ", example: { ko: "문제가 간단해요.", ja: "問題が簡単です。" } },
  { id: "k2_155", word: "편하다", romaja: "pyeonhada", pos: "형용사", topik: 2, category: "adjective", meaning: "楽だ・快適だ", example: { ko: "이 의자가 편해요.", ja: "この椅子は楽です。" } },
  { id: "k2_156", word: "불편하다", romaja: "bulpyeonhada", pos: "형용사", topik: 2, category: "adjective", meaning: "不便だ", example: { ko: "교통이 불편해요.", ja: "交通が不便です。" } },
  { id: "k2_157", word: "조용하다", romaja: "joyonghada", pos: "형용사", topik: 2, category: "adjective", meaning: "静かだ", example: { ko: "도서관이 조용해요.", ja: "図書館は静かです。" } },
  { id: "k2_158", word: "시끄럽다", romaja: "sikkeureopda", pos: "형용사", topik: 2, category: "adjective", meaning: "うるさい", example: { ko: "밖이 너무 시끄러워요.", ja: "外がとてもうるさいです。" } },
  { id: "k2_159", word: "중요하다", romaja: "jungyohada", pos: "형용사", topik: 2, category: "adjective", meaning: "重要だ・大切だ", example: { ko: "건강이 중요해요.", ja: "健康が大切です。" } },
  { id: "k2_160", word: "필요하다", romaja: "piryohada", pos: "형용사", topik: 2, category: "adjective", meaning: "必要だ", example: { ko: "돈이 필요해요.", ja: "お金が必要です。" } },
  { id: "k2_161", word: "특별하다", romaja: "teukbyeolhada", pos: "형용사", topik: 2, category: "adjective", meaning: "特別だ", example: { ko: "오늘은 특별한 날이에요.", ja: "今日は特別な日です。" } },
  { id: "k2_162", word: "비슷하다", romaja: "biseuthada", pos: "형용사", topik: 2, category: "adjective", meaning: "似ている", example: { ko: "두 사람이 비슷해요.", ja: "二人は似ています。" } },
  { id: "k2_163", word: "친절하다", romaja: "chinjeolhada", pos: "형용사", topik: 2, category: "adjective", meaning: "親切だ", example: { ko: "점원이 친절해요.", ja: "店員が親切です。" } },
  { id: "k2_164", word: "심심하다", romaja: "simsimhada", pos: "형용사", topik: 2, category: "adjective", meaning: "退屈だ", example: { ko: "주말에 심심했어요.", ja: "週末は退屈でした。" } },
  { id: "k2_165", word: "답답하다", romaja: "dapdaphada", pos: "형용사", topik: 2, category: "adjective", meaning: "もどかしい・息苦しい", example: { ko: "말이 안 통해서 답답해요.", ja: "話が通じなくてもどかしいです。" } },
  { id: "k2_166", word: "신기하다", romaja: "singihada", pos: "형용사", topik: 2, category: "adjective", meaning: "不思議だ・珍しい", example: { ko: "정말 신기한 일이에요.", ja: "本当に不思議なことです。" } },
  { id: "k2_167", word: "딱딱하다", romaja: "ttakttakhada", pos: "형용사", topik: 2, category: "adjective", meaning: "硬い", example: { ko: "빵이 딱딱해요.", ja: "パンが硬いです。" } },
  { id: "k2_168", word: "부드럽다", romaja: "budeureopda", pos: "형용사", topik: 2, category: "adjective", meaning: "柔らかい", example: { ko: "이 빵은 부드러워요.", ja: "このパンは柔らかいです。" } },
  { id: "k2_169", word: "깨끗하다", romaja: "kkaekkeuthada", pos: "형용사", topik: 2, category: "adjective", meaning: "きれいだ・清潔だ", example: { ko: "방이 깨끗해요.", ja: "部屋がきれいです。" } },
  { id: "k2_170", word: "더럽다", romaja: "deoreopda", pos: "형용사", topik: 2, category: "adjective", meaning: "汚い", example: { ko: "손이 더러워요.", ja: "手が汚いです。" } },
  { id: "k2_171", word: "위험하다", romaja: "wiheomhada", pos: "형용사", topik: 2, category: "adjective", meaning: "危険だ", example: { ko: "밤에 혼자 다니면 위험해요.", ja: "夜に一人で出歩くと危険です。" } },
  { id: "k2_172", word: "안전하다", romaja: "anjeonhada", pos: "형용사", topik: 2, category: "adjective", meaning: "安全だ", example: { ko: "이 동네는 안전해요.", ja: "この町は安全です。" } },
  { id: "k2_173", word: "똑똑하다", romaja: "ttokttokhada", pos: "형용사", topik: 2, category: "adjective", meaning: "賢い", example: { ko: "그 학생은 똑똑해요.", ja: "あの学生は賢いです。" } },
  { id: "k2_174", word: "게으르다", romaja: "geeureuda", pos: "형용사", topik: 2, category: "adjective", meaning: "怠け者だ", example: { ko: "동생은 좀 게을러요.", ja: "弟は少し怠け者です。" } },
  { id: "k2_175", word: "부지런하다", romaja: "bujireonhada", pos: "형용사", topik: 2, category: "adjective", meaning: "勤勉だ・まめだ", example: { ko: "그는 아주 부지런해요.", ja: "彼はとても勤勉です。" } },
  { id: "k2_176", word: "수술", romaja: "susul", pos: "명사", topik: 2, category: "health", meaning: "手術", example: { ko: "다음 주에 수술을 받아요.", ja: "来週手術を受けます。" } },
  { id: "k2_177", word: "스트레스", romaja: "seuteureseu", pos: "명사", topik: 2, category: "health", meaning: "ストレス", example: { ko: "요즘 스트레스가 많아요.", ja: "最近ストレスが多いです。" } },
  { id: "k2_178", word: "체중", romaja: "chejung", pos: "명사", topik: 2, category: "health", meaning: "体重", example: { ko: "체중이 조금 늘었어요.", ja: "体重が少し増えました。" } },
  { id: "k2_179", word: "잠", romaja: "jam", pos: "명사", topik: 2, category: "health", meaning: "睡眠・眠り", example: { ko: "어제 잠을 잘 못 잤어요.", ja: "昨日よく眠れませんでした。" } },
  { id: "k2_180", word: "낫다", romaja: "natda", pos: "동사", topik: 2, category: "health", meaning: "治る", example: { ko: "감기가 다 나았어요.", ja: "風邪がすっかり治りました。" } },
];
