export interface PhrasebookPhrase {
  jp: string;        // 일본어 문장 (한자 포함 가능)
  reading: string;   // 전체 히라가나/가나 읽기 (TTS·후리가나용)
  romaji: string;    // 헵번식 로마자
  ko: string;        // 한국어 뜻
  tip?: string;      // 짧은 사용 팁 (선택, 한국어)
}

export interface PhrasebookSituation {
  key: string;       // 영문 슬러그 (예: "airport")
  title: string;     // 한국어 제목 (예: "공항·입국")
  emoji: string;
  phrases: PhrasebookPhrase[];
}

export const TRAVEL_PHRASEBOOK: PhrasebookSituation[] = [
  {
    key: "airport",
    title: "공항·입국",
    emoji: "✈️",
    phrases: [
      {
        jp: "観光で来ました。",
        reading: "かんこうできました。",
        romaji: "Kankou de kimashita.",
        ko: "관광하러 왔습니다.",
        tip: "입국심사에서 방문 목적을 물으면 자주 쓰는 대답이에요.",
      },
      {
        jp: "三泊四日の予定です。",
        reading: "さんぱくよっかのよていです。",
        romaji: "Sanpaku yokka no yotei desu.",
        ko: "3박 4일 예정입니다.",
      },
      {
        jp: "ホテルに泊まります。",
        reading: "ほてるにとまります。",
        romaji: "Hoteru ni tomarimasu.",
        ko: "호텔에 묵습니다.",
      },
      {
        jp: "荷物はどこで受け取れますか。",
        reading: "にもつはどこでうけとれますか。",
        romaji: "Nimotsu wa doko de uketoremasu ka.",
        ko: "짐은 어디서 찾을 수 있나요?",
      },
      {
        jp: "スーツケースが出てきません。",
        reading: "すーつけーすがでてきません。",
        romaji: "Suutsukeesu ga dete kimasen.",
        ko: "캐리어가 안 나와요.",
        tip: "수하물이 분실됐을 때 직원에게 말하세요.",
      },
      {
        jp: "両替はどこでできますか。",
        reading: "りょうがえはどこでできますか。",
        romaji: "Ryougae wa doko de dekimasu ka.",
        ko: "환전은 어디서 할 수 있나요?",
      },
      {
        jp: "一万円札をくずしてもらえますか。",
        reading: "いちまんえんさつをくずしてもらえますか。",
        romaji: "Ichiman-en satsu o kuzushite moraemasu ka.",
        ko: "만 엔짜리를 잔돈으로 바꿔 주실 수 있나요?",
        tip: "「くずす」는 큰 돈을 잔돈으로 바꾼다는 뜻이에요.",
      },
      {
        jp: "これは申告が必要ですか。",
        reading: "これはしんこくがひつようですか。",
        romaji: "Kore wa shinkoku ga hitsuyou desu ka.",
        ko: "이건 신고가 필요한가요?",
        tip: "세관에서 물건에 대해 물어볼 때 쓰세요.",
      },
      {
        jp: "電車の乗り場はどこですか。",
        reading: "でんしゃののりばはどこですか。",
        romaji: "Densha no noriba wa doko desu ka.",
        ko: "전철 타는 곳은 어디인가요?",
      },
      {
        jp: "市内へのバスはありますか。",
        reading: "しないへのばすはありますか。",
        romaji: "Shinai e no basu wa arimasu ka.",
        ko: "시내로 가는 버스가 있나요?",
      },
      {
        jp: "無料のWi-Fiはありますか。",
        reading: "むりょうのわいふぁいはありますか。",
        romaji: "Muryou no waifai wa arimasu ka.",
        ko: "무료 와이파이가 있나요?",
      },
      {
        jp: "トイレはどこですか。",
        reading: "といれはどこですか。",
        romaji: "Toire wa doko desu ka.",
        ko: "화장실은 어디인가요?",
      },
    ],
  },
  {
    key: "hotel",
    title: "호텔·숙소",
    emoji: "🏨",
    phrases: [
      {
        jp: "チェックインをお願いします。",
        reading: "ちぇっくいんをおねがいします。",
        romaji: "Chekkuin o onegai shimasu.",
        ko: "체크인 부탁합니다.",
      },
      {
        jp: "予約してあります。",
        reading: "よやくしてあります。",
        romaji: "Yoyaku shite arimasu.",
        ko: "예약했습니다.",
      },
      {
        jp: "名前はキムです。",
        reading: "なまえはきむです。",
        romaji: "Namae wa Kimu desu.",
        ko: "이름은 김입니다.",
        tip: "본인 성을 가타카나 발음으로 말하면 알아듣기 쉬워요.",
      },
      {
        jp: "チェックアウトは何時ですか。",
        reading: "ちぇっくあうとはなんじですか。",
        romaji: "Chekkuauto wa nanji desu ka.",
        ko: "체크아웃은 몇 시인가요?",
      },
      {
        jp: "荷物を預かってもらえますか。",
        reading: "にもつをあずかってもらえますか。",
        romaji: "Nimotsu o azukatte moraemasu ka.",
        ko: "짐을 맡아 주실 수 있나요?",
        tip: "체크인 전이나 체크아웃 후에 짐을 맡길 때 유용해요.",
      },
      {
        jp: "Wi-Fiのパスワードを教えてください。",
        reading: "わいふぁいのぱすわーどをおしえてください。",
        romaji: "Waifai no pasuwaado o oshiete kudasai.",
        ko: "와이파이 비밀번호를 알려 주세요.",
      },
      {
        jp: "朝食は何時からですか。",
        reading: "ちょうしょくはなんじからですか。",
        romaji: "Choushoku wa nanji kara desu ka.",
        ko: "조식은 몇 시부터인가요?",
      },
      {
        jp: "朝食は付いていますか。",
        reading: "ちょうしょくはついていますか。",
        romaji: "Choushoku wa tsuite imasu ka.",
        ko: "조식이 포함되어 있나요?",
      },
      {
        jp: "部屋を変えてもらえますか。",
        reading: "へやをかえてもらえますか。",
        romaji: "Heya o kaete moraemasu ka.",
        ko: "방을 바꿔 주실 수 있나요?",
      },
      {
        jp: "エアコンが効きません。",
        reading: "えあこんがききません。",
        romaji: "Eakon ga kikimasen.",
        ko: "에어컨이 작동하지 않아요.",
        tip: "「効く(きく)」는 기계가 제대로 작동한다는 뜻이에요.",
      },
      {
        jp: "タオルを追加でもらえますか。",
        reading: "たおるをついかでもらえますか。",
        romaji: "Taoru o tsuika de moraemasu ka.",
        ko: "수건을 추가로 받을 수 있나요?",
      },
      {
        jp: "タクシーを呼んでもらえますか。",
        reading: "たくしーをよんでもらえますか。",
        romaji: "Takushii o yonde moraemasu ka.",
        ko: "택시를 불러 주실 수 있나요?",
      },
    ],
  },
  {
    key: "restaurant",
    title: "식당·주문",
    emoji: "🍽️",
    phrases: [
      {
        jp: "二人です。",
        reading: "ふたりです。",
        romaji: "Futari desu.",
        ko: "두 명입니다.",
        tip: "식당 입구에서 인원수를 말할 때 쓰세요.",
      },
      {
        jp: "席は空いていますか。",
        reading: "せきはあいていますか。",
        romaji: "Seki wa aite imasu ka.",
        ko: "자리 있나요?",
      },
      {
        jp: "メニューをお願いします。",
        reading: "めにゅーをおねがいします。",
        romaji: "Menyuu o onegai shimasu.",
        ko: "메뉴 주세요.",
      },
      {
        jp: "おすすめは何ですか。",
        reading: "おすすめはなんですか。",
        romaji: "Osusume wa nan desu ka.",
        ko: "추천 메뉴는 뭔가요?",
      },
      {
        jp: "これをください。",
        reading: "これをください。",
        romaji: "Kore o kudasai.",
        ko: "이거 주세요.",
        tip: "메뉴를 손가락으로 가리키며 말하면 가장 확실해요.",
      },
      {
        jp: "同じものをお願いします。",
        reading: "おなじものをおねがいします。",
        romaji: "Onaji mono o onegai shimasu.",
        ko: "같은 걸로 주세요.",
      },
      {
        jp: "辛くしないでください。",
        reading: "からくしないでください。",
        romaji: "Karaku shinaide kudasai.",
        ko: "맵지 않게 해 주세요.",
      },
      {
        jp: "卵アレルギーがあります。",
        reading: "たまごあれるぎーがあります。",
        romaji: "Tamago arerugii ga arimasu.",
        ko: "달걀 알레르기가 있어요.",
        tip: "재료 이름만 바꿔서 다른 알레르기에도 쓸 수 있어요.",
      },
      {
        jp: "お会計をお願いします。",
        reading: "おかいけいをおねがいします。",
        romaji: "Okaikei o onegai shimasu.",
        ko: "계산해 주세요.",
      },
      {
        jp: "別々で払えますか。",
        reading: "べつべつではらえますか。",
        romaji: "Betsubetsu de haraemasu ka.",
        ko: "따로 계산할 수 있나요?",
      },
      {
        jp: "持ち帰りできますか。",
        reading: "もちかえりできますか。",
        romaji: "Mochikaeri dekimasu ka.",
        ko: "포장 되나요?",
      },
      {
        jp: "お水をもらえますか。",
        reading: "おみずをもらえますか。",
        romaji: "Omizu o moraemasu ka.",
        ko: "물 좀 주실 수 있나요?",
      },
      {
        jp: "とても美味しかったです。",
        reading: "とてもおいしかったです。",
        romaji: "Totemo oishikatta desu.",
        ko: "정말 맛있었어요.",
      },
    ],
  },
  {
    key: "shopping",
    title: "쇼핑·계산",
    emoji: "🛍️",
    phrases: [
      {
        jp: "これはいくらですか。",
        reading: "これはいくらですか。",
        romaji: "Kore wa ikura desu ka.",
        ko: "이건 얼마인가요?",
      },
      {
        jp: "ちょっと見ているだけです。",
        reading: "ちょっとみているだけです。",
        romaji: "Chotto mite iru dake desu.",
        ko: "그냥 둘러보는 중이에요.",
        tip: "점원이 말을 걸 때 부드럽게 거절하는 표현이에요.",
      },
      {
        jp: "もっと大きいサイズはありますか。",
        reading: "もっとおおきいさいずはありますか。",
        romaji: "Motto ookii saizu wa arimasu ka.",
        ko: "더 큰 사이즈 있나요?",
      },
      {
        jp: "別の色はありますか。",
        reading: "べつのいろはありますか。",
        romaji: "Betsu no iro wa arimasu ka.",
        ko: "다른 색깔 있나요?",
      },
      {
        jp: "試着してもいいですか。",
        reading: "しちゃくしてもいいですか。",
        romaji: "Shichaku shite mo ii desu ka.",
        ko: "입어 봐도 되나요?",
      },
      {
        jp: "免税にできますか。",
        reading: "めんぜいにできますか。",
        romaji: "Menzei ni dekimasu ka.",
        ko: "면세 되나요?",
        tip: "여권을 보여 달라고 할 수 있으니 미리 준비하세요.",
      },
      {
        jp: "カードで払えますか。",
        reading: "かーどではらえますか。",
        romaji: "Kaado de haraemasu ka.",
        ko: "카드로 결제 되나요?",
      },
      {
        jp: "現金しか使えませんか。",
        reading: "げんきんしかつかえませんか。",
        romaji: "Genkin shika tsukaemasen ka.",
        ko: "현금만 되나요?",
      },
      {
        jp: "プレゼント用に包んでもらえますか。",
        reading: "ぷれぜんとようにつつんでもらえますか。",
        romaji: "Purezento you ni tsutsunde moraemasu ka.",
        ko: "선물용으로 포장해 주실 수 있나요?",
      },
      {
        jp: "袋をもらえますか。",
        reading: "ふくろをもらえますか。",
        romaji: "Fukuro o moraemasu ka.",
        ko: "봉투 주실 수 있나요?",
      },
      {
        jp: "少し安くなりませんか。",
        reading: "すこしやすくなりませんか。",
        romaji: "Sukoshi yasuku narimasen ka.",
        ko: "조금 깎아 주실 수 있나요?",
        tip: "일본은 정찰제가 많아 흥정은 잘 안 통해요.",
      },
      {
        jp: "これを買います。",
        reading: "これをかいます。",
        romaji: "Kore o kaimasu.",
        ko: "이거 살게요.",
      },
    ],
  },
  {
    key: "transport",
    title: "교통·이동",
    emoji: "🚃",
    phrases: [
      {
        jp: "切符はどこで買えますか。",
        reading: "きっぷはどこでかえますか。",
        romaji: "Kippu wa doko de kaemasu ka.",
        ko: "표는 어디서 살 수 있나요?",
      },
      {
        jp: "新宿まで一枚ください。",
        reading: "しんじゅくまでいちまいください。",
        romaji: "Shinjuku made ichimai kudasai.",
        ko: "신주쿠까지 한 장 주세요.",
        tip: "목적지 이름만 바꿔 어디서든 쓸 수 있어요.",
      },
      {
        jp: "この電車は東京駅に止まりますか。",
        reading: "このでんしゃはとうきょうえきにとまりますか。",
        romaji: "Kono densha wa Toukyou eki ni tomarimasu ka.",
        ko: "이 전철은 도쿄역에 서나요?",
      },
      {
        jp: "どこで乗り換えますか。",
        reading: "どこでのりかえますか。",
        romaji: "Doko de norikaemasu ka.",
        ko: "어디서 환승하나요?",
      },
      {
        jp: "何番線ですか。",
        reading: "なんばんせんですか。",
        romaji: "Nanbansen desu ka.",
        ko: "몇 번 승강장인가요?",
      },
      {
        jp: "次の駅で降ります。",
        reading: "つぎのえきでおります。",
        romaji: "Tsugi no eki de orimasu.",
        ko: "다음 역에서 내려요.",
      },
      {
        jp: "この住所までお願いします。",
        reading: "このじゅうしょまでおねがいします。",
        romaji: "Kono juusho made onegai shimasu.",
        ko: "이 주소까지 가 주세요.",
        tip: "택시에서 주소를 보여 주며 말하면 편해요.",
      },
      {
        jp: "ここで止めてください。",
        reading: "ここでとめてください。",
        romaji: "Koko de tomete kudasai.",
        ko: "여기서 세워 주세요.",
      },
      {
        jp: "どのくらい時間がかかりますか。",
        reading: "どのくらいじかんがかかりますか。",
        romaji: "Dono kurai jikan ga kakarimasu ka.",
        ko: "얼마나 걸리나요?",
      },
      {
        jp: "終電は何時ですか。",
        reading: "しゅうでんはなんじですか。",
        romaji: "Shuuden wa nanji desu ka.",
        ko: "막차는 몇 시인가요?",
        tip: "「終電(しゅうでん)」은 그날의 마지막 전철이에요.",
      },
      {
        jp: "ICカードはどこでチャージできますか。",
        reading: "あいしーかーどはどこでちゃーじできますか。",
        romaji: "IC kaado wa doko de chaaji dekimasu ka.",
        ko: "교통카드는 어디서 충전할 수 있나요?",
      },
      {
        jp: "バス停はどこですか。",
        reading: "ばすていはどこですか。",
        romaji: "Basutei wa doko desu ka.",
        ko: "버스 정류장은 어디인가요?",
      },
    ],
  },
  {
    key: "directions",
    title: "길 묻기",
    emoji: "🗺️",
    phrases: [
      {
        jp: "すみません、ちょっといいですか。",
        reading: "すみません、ちょっといいですか。",
        romaji: "Sumimasen, chotto ii desu ka.",
        ko: "실례합니다, 잠깐 괜찮을까요?",
        tip: "길을 물을 때 먼저 이렇게 말을 거는 게 자연스러워요.",
      },
      {
        jp: "駅はどこですか。",
        reading: "えきはどこですか。",
        romaji: "Eki wa doko desu ka.",
        ko: "역은 어디인가요?",
      },
      {
        jp: "ここから遠いですか。",
        reading: "ここからとおいですか。",
        romaji: "Koko kara tooi desu ka.",
        ko: "여기서 먼가요?",
      },
      {
        jp: "歩いて行けますか。",
        reading: "あるいていけますか。",
        romaji: "Aruite ikemasu ka.",
        ko: "걸어서 갈 수 있나요?",
      },
      {
        jp: "まっすぐですか、それとも曲がりますか。",
        reading: "まっすぐですか、それともまがりますか。",
        romaji: "Massugu desu ka, soretomo magarimasu ka.",
        ko: "직진인가요, 아니면 꺾어야 하나요?",
      },
      {
        jp: "この地図で教えてもらえますか。",
        reading: "このちずでおしえてもらえますか。",
        romaji: "Kono chizu de oshiete moraemasu ka.",
        ko: "이 지도에서 알려 주실 수 있나요?",
        tip: "지도를 보여 주며 물으면 훨씬 정확해요.",
      },
      {
        jp: "近くにコンビニはありますか。",
        reading: "ちかくにこんびにはありますか。",
        romaji: "Chikaku ni konbini wa arimasu ka.",
        ko: "근처에 편의점이 있나요?",
      },
      {
        jp: "一番近い駅はどこですか。",
        reading: "いちばんちかいえきはどこですか。",
        romaji: "Ichiban chikai eki wa doko desu ka.",
        ko: "가장 가까운 역은 어디인가요?",
      },
      {
        jp: "トイレはどこにありますか。",
        reading: "といれはどこにありますか。",
        romaji: "Toire wa doko ni arimasu ka.",
        ko: "화장실은 어디에 있나요?",
      },
      {
        jp: "この建物は何ですか。",
        reading: "このたてものはなんですか。",
        romaji: "Kono tatemono wa nan desu ka.",
        ko: "이 건물은 뭔가요?",
      },
      {
        jp: "道に迷いました。",
        reading: "みちにまよいました。",
        romaji: "Michi ni mayoimashita.",
        ko: "길을 잃었어요.",
      },
      {
        jp: "ありがとうございます、助かりました。",
        reading: "ありがとうございます、たすかりました。",
        romaji: "Arigatou gozaimasu, tasukarimashita.",
        ko: "감사합니다, 덕분에 살았어요.",
        tip: "도움을 받은 뒤 감사 인사로 자주 쓰는 표현이에요.",
      },
    ],
  },
  {
    key: "emergency",
    title: "긴급·병원",
    emoji: "🆘",
    phrases: [
      {
        jp: "助けてください。",
        reading: "たすけてください。",
        romaji: "Tasukete kudasai.",
        ko: "도와주세요.",
      },
      {
        jp: "救急車を呼んでください。",
        reading: "きゅうきゅうしゃをよんでください。",
        romaji: "Kyuukyuusha o yonde kudasai.",
        ko: "구급차를 불러 주세요.",
        tip: "일본 긴급 전화는 구급·소방 119, 경찰 110이에요.",
      },
      {
        jp: "気分が悪いです。",
        reading: "きぶんがわるいです。",
        romaji: "Kibun ga warui desu.",
        ko: "몸이 안 좋아요.",
      },
      {
        jp: "お腹が痛いです。",
        reading: "おなかがいたいです。",
        romaji: "Onaka ga itai desu.",
        ko: "배가 아파요.",
        tip: "「〜が痛いです」 앞에 아픈 부위만 바꾸면 돼요.",
      },
      {
        jp: "頭が痛いです。",
        reading: "あたまがいたいです。",
        romaji: "Atama ga itai desu.",
        ko: "머리가 아파요.",
      },
      {
        jp: "近くに病院はありますか。",
        reading: "ちかくにびょういんはありますか。",
        romaji: "Chikaku ni byouin wa arimasu ka.",
        ko: "근처에 병원이 있나요?",
      },
      {
        jp: "薬局はどこですか。",
        reading: "やっきょくはどこですか。",
        romaji: "Yakkyoku wa doko desu ka.",
        ko: "약국은 어디인가요?",
      },
      {
        jp: "風邪薬はありますか。",
        reading: "かぜぐすりはありますか。",
        romaji: "Kazegusuri wa arimasu ka.",
        ko: "감기약 있나요?",
      },
      {
        jp: "財布をなくしました。",
        reading: "さいふをなくしました。",
        romaji: "Saifu o nakushimashita.",
        ko: "지갑을 잃어버렸어요.",
      },
      {
        jp: "パスポートをなくしました。",
        reading: "ぱすぽーとをなくしました。",
        romaji: "Pasupooto o nakushimashita.",
        ko: "여권을 잃어버렸어요.",
        tip: "여권 분실 시 가까운 경찰서와 대사관에 바로 연락하세요.",
      },
      {
        jp: "警察を呼んでください。",
        reading: "けいさつをよんでください。",
        romaji: "Keisatsu o yonde kudasai.",
        ko: "경찰을 불러 주세요.",
      },
      {
        jp: "韓国語が話せる人はいますか。",
        reading: "かんこくごがはなせるひとはいますか。",
        romaji: "Kankokugo ga hanaseru hito wa imasu ka.",
        ko: "한국어 할 수 있는 사람 있나요?",
      },
    ],
  },
  {
    key: "basic",
    title: "기본·인사",
    emoji: "💬",
    phrases: [
      {
        jp: "おはようございます。",
        reading: "おはようございます。",
        romaji: "Ohayou gozaimasu.",
        ko: "안녕하세요. (아침 인사)",
      },
      {
        jp: "こんにちは。",
        reading: "こんにちは。",
        romaji: "Konnichiwa.",
        ko: "안녕하세요. (낮 인사)",
      },
      {
        jp: "ありがとうございます。",
        reading: "ありがとうございます。",
        romaji: "Arigatou gozaimasu.",
        ko: "감사합니다.",
      },
      {
        jp: "すみません。",
        reading: "すみません。",
        romaji: "Sumimasen.",
        ko: "죄송합니다. / 실례합니다.",
        tip: "사과와 \"저기요\" 두 가지 뜻으로 모두 쓰여요.",
      },
      {
        jp: "ごめんなさい。",
        reading: "ごめんなさい。",
        romaji: "Gomennasai.",
        ko: "미안합니다.",
      },
      {
        jp: "お願いします。",
        reading: "おねがいします。",
        romaji: "Onegai shimasu.",
        ko: "부탁합니다.",
      },
      {
        jp: "大丈夫です。",
        reading: "だいじょうぶです。",
        romaji: "Daijoubu desu.",
        ko: "괜찮습니다.",
        tip: "권유를 거절할 때 \"괜찮아요(됐어요)\"로도 쓸 수 있어요.",
      },
      {
        jp: "わかりません。",
        reading: "わかりません。",
        romaji: "Wakarimasen.",
        ko: "모르겠어요.",
      },
      {
        jp: "もう一度言ってください。",
        reading: "もういちどいってください。",
        romaji: "Mou ichido itte kudasai.",
        ko: "한 번 더 말해 주세요.",
      },
      {
        jp: "もっとゆっくり話してください。",
        reading: "もっとゆっくりはなしてください。",
        romaji: "Motto yukkuri hanashite kudasai.",
        ko: "조금 더 천천히 말해 주세요.",
      },
      {
        jp: "日本語が少しだけわかります。",
        reading: "にほんごがすこしだけわかります。",
        romaji: "Nihongo ga sukoshi dake wakarimasu.",
        ko: "일본어를 조금만 알아요.",
      },
      {
        jp: "英語は話せますか。",
        reading: "えいごははなせますか。",
        romaji: "Eigo wa hanasemasu ka.",
        ko: "영어 할 수 있나요?",
      },
      {
        jp: "ここに書いてもらえますか。",
        reading: "ここにかいてもらえますか。",
        romaji: "Koko ni kaite moraemasu ka.",
        ko: "여기에 적어 주실 수 있나요?",
        tip: "말로 이해가 어려울 때 숫자나 단어를 적어 달라고 하면 편해요.",
      },
    ],
  },
];
