import type { Word } from "./types";

// 확장 단어 (JLPT N5) — 기존 vocab.ts 와 합쳐진다.
export const EXTRA_VOCAB: Word[] = [
  // ── 숫자 보강 ────────────────────────────────
  { id: "x_n1", word: "四", reading: "よん", romaji: "yon", meaning: "넷, 4", pos: "수사", category: "number",
    example: { tokens: [{ t: "四", r: "よ" }, { t: "時", r: "じ" }, { t: "に" }, { t: "帰", r: "かえ" }, { t: "ります。" }], ko: "4시에 돌아갑니다." } },
  { id: "x_n2", word: "五", reading: "ご", romaji: "go", meaning: "다섯, 5", pos: "수사", category: "number",
    example: { tokens: [{ t: "五", r: "ご" }, { t: "つください。" }], ko: "다섯 개 주세요." } },
  { id: "x_n3", word: "六", reading: "ろく", romaji: "roku", meaning: "여섯, 6", pos: "수사", category: "number",
    example: { tokens: [{ t: "六", r: "ろく" }, { t: "時", r: "じ" }, { t: "に" }, { t: "起", r: "お" }, { t: "きます。" }], ko: "6시에 일어납니다." } },
  { id: "x_n4", word: "七", reading: "なな", romaji: "nana", meaning: "일곱, 7", pos: "수사", category: "number",
    example: { tokens: [{ t: "七", r: "なな" }, { t: "つあります。" }], ko: "일곱 개 있습니다." } },
  { id: "x_n5", word: "八", reading: "はち", romaji: "hachi", meaning: "여덟, 8", pos: "수사", category: "number",
    example: { tokens: [{ t: "八", r: "はち" }, { t: "時", r: "じ" }, { t: "です。" }], ko: "8시입니다." } },
  { id: "x_n6", word: "九", reading: "きゅう", romaji: "kyuu", meaning: "아홉, 9", pos: "수사", category: "number",
    example: { tokens: [{ t: "九", r: "きゅう" }, { t: "個", r: "こ" }, { t: "あります。" }], ko: "아홉 개 있습니다." } },
  { id: "x_n7", word: "十", reading: "じゅう", romaji: "juu", meaning: "열, 10", pos: "수사", category: "number",
    example: { tokens: [{ t: "十", r: "じゅう" }, { t: "分", r: "ぷん" }, { t: "待", r: "ま" }, { t: "ちます。" }], ko: "10분 기다립니다." } },
  { id: "x_n8", word: "万", reading: "まん", romaji: "man", meaning: "만, 10000", pos: "수사", category: "number",
    example: { tokens: [{ t: "一", r: "いち" }, { t: "万", r: "まん" }, { t: "円", r: "えん" }, { t: "です。" }], ko: "만 엔입니다." } },

  // ── 시간·요일 ────────────────────────────────
  { id: "x_t1", word: "月曜日", reading: "げつようび", romaji: "getsuyoubi", meaning: "월요일", pos: "명사", category: "time",
    example: { tokens: [{ t: "月曜日", r: "げつようび" }, { t: "に" }, { t: "会", r: "あ" }, { t: "いましょう。" }], ko: "월요일에 만납시다." } },
  { id: "x_t2", word: "金曜日", reading: "きんようび", romaji: "kinyoubi", meaning: "금요일", pos: "명사", category: "time",
    example: { tokens: [{ t: "金曜日", r: "きんようび" }, { t: "は" }, { t: "忙", r: "いそが" }, { t: "しいです。" }], ko: "금요일은 바쁩니다." } },
  { id: "x_t3", word: "土曜日", reading: "どようび", romaji: "doyoubi", meaning: "토요일", pos: "명사", category: "time",
    example: { tokens: [{ t: "土曜日", r: "どようび" }, { t: "に" }, { t: "出", r: "で" }, { t: "かけます。" }], ko: "토요일에 외출합니다." } },
  { id: "x_t4", word: "日曜日", reading: "にちようび", romaji: "nichiyoubi", meaning: "일요일", pos: "명사", category: "time",
    example: { tokens: [{ t: "日曜日", r: "にちようび" }, { t: "は" }, { t: "休", r: "やす" }, { t: "みます。" }], ko: "일요일은 쉽니다." } },
  { id: "x_t5", word: "毎日", reading: "まいにち", romaji: "mainichi", meaning: "매일", pos: "명사", category: "time",
    example: { tokens: [{ t: "毎日", r: "まいにち" }, { t: "勉強", r: "べんきょう" }, { t: "します。" }], ko: "매일 공부합니다." } },
  { id: "x_t6", word: "午後", reading: "ごご", romaji: "gogo", meaning: "오후", pos: "명사", category: "time",
    example: { tokens: [{ t: "午後", r: "ごご" }, { t: "三", r: "さん" }, { t: "時", r: "じ" }, { t: "に。" }], ko: "오후 3시에." } },
  { id: "x_t7", word: "去年", reading: "きょねん", romaji: "kyonen", meaning: "작년", pos: "명사", category: "time",
    example: { tokens: [{ t: "去年", r: "きょねん" }, { t: "日本", r: "にほん" }, { t: "へ" }, { t: "行", r: "い" }, { t: "きました。" }], ko: "작년에 일본에 갔습니다." } },

  // ── 사람·가족 보강 ───────────────────────────
  { id: "x_p1", word: "兄", reading: "あに", romaji: "ani", meaning: "형, 오빠 (내)", pos: "명사", category: "people",
    example: { tokens: [{ t: "兄", r: "あに" }, { t: "は" }, { t: "二十歳", r: "はたち" }, { t: "です。" }], ko: "형은 스무 살입니다." } },
  { id: "x_p2", word: "姉", reading: "あね", romaji: "ane", meaning: "누나, 언니 (내)", pos: "명사", category: "people",
    example: { tokens: [{ t: "姉", r: "あね" }, { t: "は" }, { t: "優", r: "やさ" }, { t: "しいです。" }], ko: "누나는 상냥합니다." } },
  { id: "x_p3", word: "彼", reading: "かれ", romaji: "kare", meaning: "그, 남자친구", pos: "대명사", category: "people",
    example: { tokens: [{ t: "彼", r: "かれ" }, { t: "は" }, { t: "先生", r: "せんせい" }, { t: "です。" }], ko: "그는 선생님입니다." } },
  { id: "x_p4", word: "皆さん", reading: "みなさん", romaji: "minasan", meaning: "여러분", pos: "명사", category: "people",
    example: { tokens: [{ t: "皆", r: "みな" }, { t: "さん、こんにちは。" }], ko: "여러분, 안녕하세요." } },

  // ── 음식 보강 ────────────────────────────────
  { id: "x_f1", word: "卵", reading: "たまご", romaji: "tamago", meaning: "달걀", pos: "명사", category: "food",
    example: { tokens: [{ t: "卵", r: "たまご" }, { t: "を" }, { t: "二", r: "ふた" }, { t: "つ" }, { t: "買", r: "か" }, { t: "います。" }], ko: "달걀을 두 개 삽니다." } },
  { id: "x_f2", word: "果物", reading: "くだもの", romaji: "kudamono", meaning: "과일", pos: "명사", category: "food",
    example: { tokens: [{ t: "果物", r: "くだもの" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "과일을 좋아합니다." } },
  { id: "x_f3", word: "牛乳", reading: "ぎゅうにゅう", romaji: "gyuunyuu", meaning: "우유", pos: "명사", category: "food",
    example: { tokens: [{ t: "毎朝", r: "まいあさ" }, { t: "牛乳", r: "ぎゅうにゅう" }, { t: "を" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "매일 아침 우유를 마십니다." } },
  { id: "x_f4", word: "甘い", reading: "あまい", romaji: "amai", meaning: "달다", pos: "い형용사", category: "food",
    example: { tokens: [{ t: "この" }, { t: "ケーキは" }, { t: "甘", r: "あま" }, { t: "いです。" }], ko: "이 케이크는 답니다." } },
  { id: "x_f5", word: "辛い", reading: "からい", romaji: "karai", meaning: "맵다", pos: "い형용사", category: "food",
    example: { tokens: [{ t: "キムチは" }, { t: "辛", r: "から" }, { t: "いです。" }], ko: "김치는 맵습니다." } },

  // ── 장소·교통 보강 ───────────────────────────
  { id: "x_pl1", word: "会社", reading: "かいしゃ", romaji: "kaisha", meaning: "회사", pos: "명사", category: "place",
    example: { tokens: [{ t: "会社", r: "かいしゃ" }, { t: "まで" }, { t: "電車", r: "でんしゃ" }, { t: "で" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "회사까지 전철로 갑니다." } },
  { id: "x_pl2", word: "銀行", reading: "ぎんこう", romaji: "ginkou", meaning: "은행", pos: "명사", category: "place",
    example: { tokens: [{ t: "銀行", r: "ぎんこう" }, { t: "は" }, { t: "何時", r: "なんじ" }, { t: "まで" }, { t: "ですか。" }], ko: "은행은 몇 시까지예요?" } },
  { id: "x_pl3", word: "空港", reading: "くうこう", romaji: "kuukou", meaning: "공항", pos: "명사", category: "place",
    example: { tokens: [{ t: "空港", r: "くうこう" }, { t: "で" }, { t: "待", r: "ま" }, { t: "ちます。" }], ko: "공항에서 기다립니다." } },
  { id: "x_pl4", word: "左", reading: "ひだり", romaji: "hidari", meaning: "왼쪽", pos: "명사", category: "place",
    example: { tokens: [{ t: "左", r: "ひだり" }, { t: "に" }, { t: "曲", r: "ま" }, { t: "がってください。" }], ko: "왼쪽으로 도세요." } },
  { id: "x_pl5", word: "近く", reading: "ちかく", romaji: "chikaku", meaning: "근처", pos: "명사", category: "place",
    example: { tokens: [{ t: "近", r: "ちか" }, { t: "くに" }, { t: "コンビニがあります。" }], ko: "근처에 편의점이 있습니다." } },

  // ── 자연·날씨 ────────────────────────────────
  { id: "x_na1", word: "空", reading: "そら", romaji: "sora", meaning: "하늘", pos: "명사", category: "nature",
    example: { tokens: [{ t: "空", r: "そら" }, { t: "が" }, { t: "青", r: "あお" }, { t: "いです。" }], ko: "하늘이 파랗습니다." } },
  { id: "x_na2", word: "海", reading: "うみ", romaji: "umi", meaning: "바다", pos: "명사", category: "nature",
    example: { tokens: [{ t: "夏", r: "なつ" }, { t: "に" }, { t: "海", r: "うみ" }, { t: "へ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "여름에 바다에 갑니다." } },
  { id: "x_na3", word: "山", reading: "やま", romaji: "yama", meaning: "산", pos: "명사", category: "nature",
    example: { tokens: [{ t: "山", r: "やま" }, { t: "に" }, { t: "登", r: "のぼ" }, { t: "ります。" }], ko: "산에 오릅니다." } },
  { id: "x_na4", word: "花", reading: "はな", romaji: "hana", meaning: "꽃", pos: "명사", category: "nature",
    example: { tokens: [{ t: "花", r: "はな" }, { t: "が" }, { t: "咲", r: "さ" }, { t: "きました。" }], ko: "꽃이 피었습니다." } },
  { id: "x_na5", word: "雪", reading: "ゆき", romaji: "yuki", meaning: "눈", pos: "명사", category: "nature",
    example: { tokens: [{ t: "冬", r: "ふゆ" }, { t: "は" }, { t: "雪", r: "ゆき" }, { t: "が" }, { t: "降", r: "ふ" }, { t: "ります。" }], ko: "겨울에는 눈이 내립니다." } },
  { id: "x_na6", word: "風", reading: "かぜ", romaji: "kaze", meaning: "바람", pos: "명사", category: "nature",
    example: { tokens: [{ t: "風", r: "かぜ" }, { t: "が" }, { t: "強", r: "つよ" }, { t: "いです。" }], ko: "바람이 셉니다." } },
  { id: "x_na7", word: "暑い", reading: "あつい", romaji: "atsui", meaning: "덥다", pos: "い형용사", category: "nature",
    example: { tokens: [{ t: "今日", r: "きょう" }, { t: "は" }, { t: "暑", r: "あつ" }, { t: "いですね。" }], ko: "오늘은 덥네요." } },
  { id: "x_na8", word: "寒い", reading: "さむい", romaji: "samui", meaning: "춥다", pos: "い형용사", category: "nature",
    example: { tokens: [{ t: "外", r: "そと" }, { t: "は" }, { t: "寒", r: "さむ" }, { t: "いです。" }], ko: "밖은 춥습니다." } },

  // ── 신체·건강 ────────────────────────────────
  { id: "x_b1", word: "頭", reading: "あたま", romaji: "atama", meaning: "머리", pos: "명사", category: "body",
    example: { tokens: [{ t: "頭", r: "あたま" }, { t: "が" }, { t: "痛", r: "いた" }, { t: "いです。" }], ko: "머리가 아픕니다." } },
  { id: "x_b2", word: "目", reading: "め", romaji: "me", meaning: "눈", pos: "명사", category: "body",
    example: { tokens: [{ t: "目", r: "め" }, { t: "が" }, { t: "きれいですね。" }], ko: "눈이 예쁘네요." } },
  { id: "x_b3", word: "手", reading: "て", romaji: "te", meaning: "손", pos: "명사", category: "body",
    example: { tokens: [{ t: "手", r: "て" }, { t: "を" }, { t: "洗", r: "あら" }, { t: "います。" }], ko: "손을 씻습니다." } },
  { id: "x_b4", word: "足", reading: "あし", romaji: "ashi", meaning: "발, 다리", pos: "명사", category: "body",
    example: { tokens: [{ t: "足", r: "あし" }, { t: "が" }, { t: "疲", r: "つか" }, { t: "れました。" }], ko: "다리가 피곤합니다." } },
  { id: "x_b5", word: "病気", reading: "びょうき", romaji: "byouki", meaning: "병", pos: "명사", category: "body",
    example: { tokens: [{ t: "病気", r: "びょうき" }, { t: "に" }, { t: "なりました。" }], ko: "병이 났습니다." } },
  { id: "x_b6", word: "元気", reading: "げんき", romaji: "genki", meaning: "기운, 건강", pos: "な형용사", category: "body",
    example: { tokens: [{ t: "今日", r: "きょう" }, { t: "も" }, { t: "元気", r: "げんき" }, { t: "です。" }], ko: "오늘도 건강합니다." } },

  // ── 취미·활동 ────────────────────────────────
  { id: "x_h1", word: "音楽", reading: "おんがく", romaji: "ongaku", meaning: "음악", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "音楽", r: "おんがく" }, { t: "を" }, { t: "聞", r: "き" }, { t: "きます。" }], ko: "음악을 듣습니다." } },
  { id: "x_h2", word: "映画", reading: "えいが", romaji: "eiga", meaning: "영화", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "映画", r: "えいが" }, { t: "を" }, { t: "見", r: "み" }, { t: "ました。" }], ko: "영화를 봤습니다." } },
  { id: "x_h3", word: "旅行", reading: "りょこう", romaji: "ryokou", meaning: "여행", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "旅行", r: "りょこう" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "여행을 좋아합니다." } },
  { id: "x_h4", word: "運動", reading: "うんどう", romaji: "undou", meaning: "운동", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "毎日", r: "まいにち" }, { t: "運動", r: "うんどう" }, { t: "します。" }], ko: "매일 운동합니다." } },
  { id: "x_h5", word: "写真", reading: "しゃしん", romaji: "shashin", meaning: "사진", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "写真", r: "しゃしん" }, { t: "を" }, { t: "撮", r: "と" }, { t: "ります。" }], ko: "사진을 찍습니다." } },
  { id: "x_h6", word: "歌", reading: "うた", romaji: "uta", meaning: "노래", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "歌", r: "うた" }, { t: "を" }, { t: "歌", r: "うた" }, { t: "います。" }], ko: "노래를 부릅니다." } },

  // ── 색·모양 ──────────────────────────────────
  { id: "x_c1", word: "赤", reading: "あか", romaji: "aka", meaning: "빨강", pos: "명사", category: "color",
    example: { tokens: [{ t: "赤", r: "あか" }, { t: "い" }, { t: "りんごです。" }], ko: "빨간 사과입니다." } },
  { id: "x_c2", word: "青", reading: "あお", romaji: "ao", meaning: "파랑", pos: "명사", category: "color",
    example: { tokens: [{ t: "青", r: "あお" }, { t: "い" }, { t: "空", r: "そら" }, { t: "ですね。" }], ko: "파란 하늘이네요." } },
  { id: "x_c3", word: "白", reading: "しろ", romaji: "shiro", meaning: "하양", pos: "명사", category: "color",
    example: { tokens: [{ t: "白", r: "しろ" }, { t: "い" }, { t: "シャツを" }, { t: "着", r: "き" }, { t: "ます。" }], ko: "흰 셔츠를 입습니다." } },
  { id: "x_c4", word: "黒", reading: "くろ", romaji: "kuro", meaning: "검정", pos: "명사", category: "color",
    example: { tokens: [{ t: "黒", r: "くろ" }, { t: "い" }, { t: "鞄", r: "かばん" }, { t: "です。" }], ko: "검은 가방입니다." } },
  { id: "x_c5", word: "丸い", reading: "まるい", romaji: "marui", meaning: "둥글다", pos: "い형용사", category: "color",
    example: { tokens: [{ t: "丸", r: "まる" }, { t: "い" }, { t: "テーブルです。" }], ko: "둥근 테이블입니다." } },

  // ── 형용사 보강 ──────────────────────────────
  { id: "x_a1", word: "長い", reading: "ながい", romaji: "nagai", meaning: "길다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "髪", r: "かみ" }, { t: "が" }, { t: "長", r: "なが" }, { t: "いです。" }], ko: "머리가 깁니다." } },
  { id: "x_a2", word: "短い", reading: "みじかい", romaji: "mijikai", meaning: "짧다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "この" }, { t: "ペンは" }, { t: "短", r: "みじか" }, { t: "いです。" }], ko: "이 펜은 짧습니다." } },
  { id: "x_a3", word: "忙しい", reading: "いそがしい", romaji: "isogashii", meaning: "바쁘다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "今週", r: "こんしゅう" }, { t: "は" }, { t: "忙", r: "いそが" }, { t: "しいです。" }], ko: "이번 주는 바쁩니다." } },
  { id: "x_a4", word: "静か", reading: "しずか", romaji: "shizuka", meaning: "조용함", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "図書館", r: "としょかん" }, { t: "は" }, { t: "静", r: "しず" }, { t: "かです。" }], ko: "도서관은 조용합니다." } },
  { id: "x_a5", word: "有名", reading: "ゆうめい", romaji: "yuumei", meaning: "유명함", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "ここは" }, { t: "有名", r: "ゆうめい" }, { t: "な" }, { t: "店", r: "みせ" }, { t: "です。" }], ko: "여기는 유명한 가게입니다." } },
  { id: "x_a6", word: "きれい", reading: "きれい", romaji: "kirei", meaning: "예쁨, 깨끗함", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "部屋", r: "へや" }, { t: "が" }, { t: "きれいです。" }], ko: "방이 깨끗합니다." } },

  // ── 생활·사물 보강 ───────────────────────────
  { id: "x_d1", word: "電話", reading: "でんわ", romaji: "denwa", meaning: "전화", pos: "명사", category: "daily",
    example: { tokens: [{ t: "後", r: "あと" }, { t: "で" }, { t: "電話", r: "でんわ" }, { t: "します。" }], ko: "나중에 전화하겠습니다." } },
  { id: "x_d2", word: "傘", reading: "かさ", romaji: "kasa", meaning: "우산", pos: "명사", category: "daily",
    example: { tokens: [{ t: "傘", r: "かさ" }, { t: "を" }, { t: "忘", r: "わす" }, { t: "れました。" }], ko: "우산을 잊어버렸습니다." } },
  { id: "x_d3", word: "服", reading: "ふく", romaji: "fuku", meaning: "옷", pos: "명사", category: "daily",
    example: { tokens: [{ t: "新", r: "あたら" }, { t: "しい" }, { t: "服", r: "ふく" }, { t: "を" }, { t: "買", r: "か" }, { t: "いました。" }], ko: "새 옷을 샀습니다." } },
  { id: "x_d4", word: "鍵", reading: "かぎ", romaji: "kagi", meaning: "열쇠", pos: "명사", category: "daily",
    example: { tokens: [{ t: "鍵", r: "かぎ" }, { t: "が" }, { t: "ありません。" }], ko: "열쇠가 없습니다." } },
  { id: "x_d5", word: "椅子", reading: "いす", romaji: "isu", meaning: "의자", pos: "명사", category: "daily",
    example: { tokens: [{ t: "椅子", r: "いす" }, { t: "に" }, { t: "座", r: "すわ" }, { t: "ってください。" }], ko: "의자에 앉으세요." } },

  // ── 부사·표현 보강 ───────────────────────────
  { id: "x_av1", word: "あまり", reading: "あまり", romaji: "amari", meaning: "별로 (~않다)", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "あまり" }, { t: "好", r: "す" }, { t: "きじゃないです。" }], ko: "별로 좋아하지 않습니다." } },
  { id: "x_av2", word: "いつも", reading: "いつも", romaji: "itsumo", meaning: "항상", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "いつも" }, { t: "元気", r: "げんき" }, { t: "ですね。" }], ko: "항상 활기차네요." } },
  { id: "x_av3", word: "本当に", reading: "ほんとうに", romaji: "hontou ni", meaning: "정말로", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "本当", r: "ほんとう" }, { t: "に" }, { t: "ありがとう。" }], ko: "정말로 고마워요." } },
  { id: "x_av4", word: "なぜ", reading: "なぜ", romaji: "naze", meaning: "왜", pos: "의문사", category: "adverb",
    example: { tokens: [{ t: "なぜ" }, { t: "来", r: "こ" }, { t: "なかったの？" }], ko: "왜 안 왔어?" } },
  { id: "x_av5", word: "どうやって", reading: "どうやって", romaji: "douyatte", meaning: "어떻게", pos: "의문사", category: "adverb",
    example: { tokens: [{ t: "どうやって" }, { t: "行", r: "い" }, { t: "きますか。" }], ko: "어떻게 가나요?" } },
];
