import type { Word } from "./types";

// JLPT N5 확장 단어 — 사람·신체·시간 (batch B3)
export const VOCAB_B3: Word[] = [
  // ===== people (사람·가족·직업·인간관계·대명사) =====
  { id: "b3_1", word: "弟", reading: "おとうと", romaji: "otouto", meaning: "남동생", pos: "명사", category: "people",
    example: { tokens: [{ t: "弟", r: "おとうと" }, { t: "は" }, { t: "学生", r: "がくせい" }, { t: "です。" }], ko: "남동생은 학생입니다." } },
  { id: "b3_2", word: "妹", reading: "いもうと", romaji: "imouto", meaning: "여동생", pos: "명사", category: "people",
    example: { tokens: [{ t: "妹", r: "いもうと" }, { t: "は" }, { t: "かわいい", }, { t: "です。" }], ko: "여동생은 귀엽습니다." } },
  { id: "b3_3", word: "祖父", reading: "そふ", romaji: "sofu", meaning: "할아버지", pos: "명사", category: "people",
    example: { tokens: [{ t: "祖父", r: "そふ" }, { t: "は" }, { t: "元気", r: "げんき" }, { t: "です。" }], ko: "할아버지는 건강합니다." } },
  { id: "b3_4", word: "祖母", reading: "そぼ", romaji: "sobo", meaning: "할머니", pos: "명사", category: "people",
    example: { tokens: [{ t: "祖母", r: "そぼ" }, { t: "は" }, { t: "やさしい" }, { t: "です。" }], ko: "할머니는 다정합니다." } },
  { id: "b3_5", word: "おじいさん", reading: "おじいさん", romaji: "ojiisan", meaning: "할아버지(높임)", pos: "명사", category: "people",
    example: { tokens: [{ t: "おじいさん" }, { t: "は" }, { t: "本", r: "ほん" }, { t: "を" }, { t: "読", r: "よ" }, { t: "みます。" }], ko: "할아버지는 책을 읽습니다." } },
  { id: "b3_6", word: "おばあさん", reading: "おばあさん", romaji: "obaasan", meaning: "할머니(높임)", pos: "명사", category: "people",
    example: { tokens: [{ t: "おばあさん" }, { t: "は" }, { t: "庭", r: "にわ" }, { t: "に" }, { t: "います。" }], ko: "할머니는 정원에 있습니다." } },
  { id: "b3_7", word: "おじ", reading: "おじ", romaji: "oji", meaning: "삼촌·외삼촌", pos: "명사", category: "people",
    example: { tokens: [{ t: "おじ" }, { t: "は" }, { t: "医者", r: "いしゃ" }, { t: "です。" }], ko: "삼촌은 의사입니다." } },
  { id: "b3_8", word: "おば", reading: "おば", romaji: "oba", meaning: "고모·이모", pos: "명사", category: "people",
    example: { tokens: [{ t: "おば" }, { t: "は" }, { t: "東京", r: "とうきょう" }, { t: "に" }, { t: "います。" }], ko: "이모는 도쿄에 있습니다." } },
  { id: "b3_9", word: "息子", reading: "むすこ", romaji: "musuko", meaning: "아들", pos: "명사", category: "people",
    example: { tokens: [{ t: "息子", r: "むすこ" }, { t: "は" }, { t: "五", r: "ご" }, { t: "さい" }, { t: "です。" }], ko: "아들은 다섯 살입니다." } },
  { id: "b3_10", word: "娘", reading: "むすめ", romaji: "musume", meaning: "딸", pos: "명사", category: "people",
    example: { tokens: [{ t: "娘", r: "むすめ" }, { t: "は" }, { t: "歌", r: "うた" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "딸은 노래를 좋아합니다." } },
  { id: "b3_11", word: "夫", reading: "おっと", romaji: "otto", meaning: "남편", pos: "명사", category: "people",
    example: { tokens: [{ t: "夫", r: "おっと" }, { t: "は" }, { t: "会社員", r: "かいしゃいん" }, { t: "です。" }], ko: "남편은 회사원입니다." } },
  { id: "b3_12", word: "妻", reading: "つま", romaji: "tsuma", meaning: "아내", pos: "명사", category: "people",
    example: { tokens: [{ t: "妻", r: "つま" }, { t: "は" }, { t: "料理", r: "りょうり" }, { t: "が" }, { t: "上手", r: "じょうず" }, { t: "です。" }], ko: "아내는 요리를 잘합니다." } },
  { id: "b3_13", word: "主人", reading: "しゅじん", romaji: "shujin", meaning: "남편(겸손)", pos: "명사", category: "people",
    example: { tokens: [{ t: "主人", r: "しゅじん" }, { t: "は" }, { t: "今", r: "いま" }, { t: "いません。" }], ko: "남편은 지금 없습니다." } },
  { id: "b3_14", word: "奥さん", reading: "おくさん", romaji: "okusan", meaning: "(남의) 부인", pos: "명사", category: "people",
    example: { tokens: [{ t: "奥", r: "おく" }, { t: "さんは" }, { t: "きれい" }, { t: "です。" }], ko: "부인은 예쁩니다." } },
  { id: "b3_15", word: "赤ちゃん", reading: "あかちゃん", romaji: "akachan", meaning: "아기", pos: "명사", category: "people",
    example: { tokens: [{ t: "赤", r: "あか" }, { t: "ちゃんが" }, { t: "寝", r: "ね" }, { t: "ています。" }], ko: "아기가 자고 있습니다." } },
  { id: "b3_16", word: "男", reading: "おとこ", romaji: "otoko", meaning: "남자", pos: "명사", category: "people",
    example: { tokens: [{ t: "あの" }, { t: "男", r: "おとこ" }, { t: "の" }, { t: "人", r: "ひと" }, { t: "は" }, { t: "誰", r: "だれ" }, { t: "ですか。" }], ko: "저 남자는 누구입니까?" } },
  { id: "b3_17", word: "女", reading: "おんな", romaji: "onna", meaning: "여자", pos: "명사", category: "people",
    example: { tokens: [{ t: "女", r: "おんな" }, { t: "の" }, { t: "人", r: "ひと" }, { t: "が" }, { t: "二人", r: "ふたり" }, { t: "います。" }], ko: "여자가 두 명 있습니다." } },
  { id: "b3_18", word: "男の子", reading: "おとこのこ", romaji: "otokonoko", meaning: "남자아이", pos: "명사", category: "people",
    example: { tokens: [{ t: "男", r: "おとこ" }, { t: "の" }, { t: "子", r: "こ" }, { t: "が" }, { t: "遊", r: "あそ" }, { t: "んでいます。" }], ko: "남자아이가 놀고 있습니다." } },
  { id: "b3_19", word: "女の子", reading: "おんなのこ", romaji: "onnanoko", meaning: "여자아이", pos: "명사", category: "people",
    example: { tokens: [{ t: "女", r: "おんな" }, { t: "の" }, { t: "子", r: "こ" }, { t: "は" }, { t: "三", r: "さん" }, { t: "さい" }, { t: "です。" }], ko: "여자아이는 세 살입니다." } },
  { id: "b3_20", word: "人", reading: "ひと", romaji: "hito", meaning: "사람", pos: "명사", category: "people",
    example: { tokens: [{ t: "あの" }, { t: "人", r: "ひと" }, { t: "は" }, { t: "先生", r: "せんせい" }, { t: "です。" }], ko: "저 사람은 선생님입니다." } },
  { id: "b3_21", word: "大人", reading: "おとな", romaji: "otona", meaning: "어른", pos: "명사", category: "people",
    example: { tokens: [{ t: "大人", r: "おとな" }, { t: "の" }, { t: "切符", r: "きっぷ" }, { t: "を" }, { t: "ください。" }], ko: "어른 표를 주세요." } },
  { id: "b3_22", word: "友人", reading: "ゆうじん", romaji: "yuujin", meaning: "친구(격식)", pos: "명사", category: "people",
    example: { tokens: [{ t: "友人", r: "ゆうじん" }, { t: "と" }, { t: "旅行", r: "りょこう" }, { t: "します。" }], ko: "친구와 여행합니다." } },
  { id: "b3_23", word: "彼女", reading: "かのじょ", romaji: "kanojo", meaning: "그녀·여자친구", pos: "대명사", category: "people",
    example: { tokens: [{ t: "彼女", r: "かのじょ" }, { t: "は" }, { t: "学生", r: "がくせい" }, { t: "です。" }], ko: "그녀는 학생입니다." } },
  { id: "b3_24", word: "医者", reading: "いしゃ", romaji: "isha", meaning: "의사", pos: "명사", category: "people",
    example: { tokens: [{ t: "兄", r: "あに" }, { t: "は" }, { t: "医者", r: "いしゃ" }, { t: "に" }, { t: "なりました。" }], ko: "형은 의사가 되었습니다." } },
  { id: "b3_25", word: "看護師", reading: "かんごし", romaji: "kangoshi", meaning: "간호사", pos: "명사", category: "people",
    example: { tokens: [{ t: "看護師", r: "かんごし" }, { t: "が" }, { t: "薬", r: "くすり" }, { t: "を" }, { t: "くれました。" }], ko: "간호사가 약을 주었습니다." } },
  { id: "b3_26", word: "警察官", reading: "けいさつかん", romaji: "keisatsukan", meaning: "경찰관", pos: "명사", category: "people",
    example: { tokens: [{ t: "警察官", r: "けいさつかん" }, { t: "に" }, { t: "道", r: "みち" }, { t: "を" }, { t: "聞", r: "き" }, { t: "きます。" }], ko: "경찰관에게 길을 묻습니다." } },
  { id: "b3_27", word: "駅員", reading: "えきいん", romaji: "ekiin", meaning: "역무원", pos: "명사", category: "people",
    example: { tokens: [{ t: "駅員", r: "えきいん" }, { t: "に" }, { t: "切符", r: "きっぷ" }, { t: "を" }, { t: "見", r: "み" }, { t: "せます。" }], ko: "역무원에게 표를 보여줍니다." } },
  { id: "b3_28", word: "店員", reading: "てんいん", romaji: "ten'in", meaning: "점원", pos: "명사", category: "people",
    example: { tokens: [{ t: "店員", r: "てんいん" }, { t: "が" }, { t: "親切", r: "しんせつ" }, { t: "です。" }], ko: "점원이 친절합니다." } },
  { id: "b3_29", word: "大学生", reading: "だいがくせい", romaji: "daigakusei", meaning: "대학생", pos: "명사", category: "people",
    example: { tokens: [{ t: "姉", r: "あね" }, { t: "は" }, { t: "大学生", r: "だいがくせい" }, { t: "です。" }], ko: "누나는 대학생입니다." } },
  { id: "b3_30", word: "留学生", reading: "りゅうがくせい", romaji: "ryuugakusei", meaning: "유학생", pos: "명사", category: "people",
    example: { tokens: [{ t: "私", r: "わたし" }, { t: "は" }, { t: "留学生", r: "りゅうがくせい" }, { t: "です。" }], ko: "저는 유학생입니다." } },
  { id: "b3_31", word: "方", reading: "かた", romaji: "kata", meaning: "분(사람 높임)", pos: "명사", category: "people",
    example: { tokens: [{ t: "あの" }, { t: "方", r: "かた" }, { t: "は" }, { t: "どなた" }, { t: "ですか。" }], ko: "저분은 누구십니까?" } },
  { id: "b3_32", word: "君", reading: "きみ", romaji: "kimi", meaning: "너·자네", pos: "대명사", category: "people",
    example: { tokens: [{ t: "君", r: "きみ" }, { t: "の" }, { t: "名前", r: "なまえ" }, { t: "は" }, { t: "何", r: "なん" }, { t: "ですか。" }], ko: "너의 이름은 무엇입니까?" } },
  { id: "b3_33", word: "あなた", reading: "あなた", romaji: "anata", meaning: "당신", pos: "대명사", category: "people",
    example: { tokens: [{ t: "あなた" }, { t: "は" }, { t: "韓国人", r: "かんこくじん" }, { t: "ですか。" }], ko: "당신은 한국인입니까?" } },
  { id: "b3_34", word: "僕", reading: "ぼく", romaji: "boku", meaning: "나(남성)", pos: "대명사", category: "people",
    example: { tokens: [{ t: "僕", r: "ぼく" }, { t: "は" }, { t: "学生", r: "がくせい" }, { t: "です。" }], ko: "나는 학생입니다." } },
  { id: "b3_35", word: "自分", reading: "じぶん", romaji: "jibun", meaning: "자신·스스로", pos: "명사", category: "people",
    example: { tokens: [{ t: "自分", r: "じぶん" }, { t: "で" }, { t: "作", r: "つく" }, { t: "ります。" }], ko: "스스로 만듭니다." } },
  { id: "b3_36", word: "みんな", reading: "みんな", romaji: "minna", meaning: "모두·다같이", pos: "명사", category: "people",
    example: { tokens: [{ t: "みんな" }, { t: "で" }, { t: "食", r: "た" }, { t: "べましょう。" }], ko: "다같이 먹읍시다." } },
  { id: "b3_37", word: "大勢", reading: "おおぜい", romaji: "oozei", meaning: "여럿·많은 사람", pos: "명사", category: "people",
    example: { tokens: [{ t: "人", r: "ひと" }, { t: "が" }, { t: "大勢", r: "おおぜい" }, { t: "います。" }], ko: "사람이 많이 있습니다." } },
  { id: "b3_38", word: "これ", reading: "これ", romaji: "kore", meaning: "이것", pos: "대명사", category: "people",
    example: { tokens: [{ t: "これ" }, { t: "は" }, { t: "誰", r: "だれ" }, { t: "の" }, { t: "本", r: "ほん" }, { t: "ですか。" }], ko: "이것은 누구의 책입니까?" } },
  { id: "b3_39", word: "それ", reading: "それ", romaji: "sore", meaning: "그것", pos: "대명사", category: "people",
    example: { tokens: [{ t: "それ" }, { t: "は" }, { t: "妹", r: "いもうと" }, { t: "の" }, { t: "かばん" }, { t: "です。" }], ko: "그것은 여동생의 가방입니다." } },
  { id: "b3_40", word: "あれ", reading: "あれ", romaji: "are", meaning: "저것", pos: "대명사", category: "people",
    example: { tokens: [{ t: "あれ" }, { t: "は" }, { t: "祖父", r: "そふ" }, { t: "の" }, { t: "車", r: "くるま" }, { t: "です。" }], ko: "저것은 할아버지의 차입니다." } },
  { id: "b3_41", word: "どれ", reading: "どれ", romaji: "dore", meaning: "어느 것", pos: "의문사", category: "people",
    example: { tokens: [{ t: "あなた" }, { t: "の" }, { t: "傘", r: "かさ" }, { t: "は" }, { t: "どれ" }, { t: "ですか。" }], ko: "당신의 우산은 어느 것입니까?" } },
  { id: "b3_42", word: "誰", reading: "だれ", romaji: "dare", meaning: "누구", pos: "의문사", category: "people",
    example: { tokens: [{ t: "あの" }, { t: "人", r: "ひと" }, { t: "は" }, { t: "誰", r: "だれ" }, { t: "ですか。" }], ko: "저 사람은 누구입니까?" } },
  { id: "b3_43", word: "どなた", reading: "どなた", romaji: "donata", meaning: "어느 분(높임)", pos: "의문사", category: "people",
    example: { tokens: [{ t: "失礼", r: "しつれい" }, { t: "ですが、" }, { t: "どなた" }, { t: "ですか。" }], ko: "실례지만 어느 분이십니까?" } },
  { id: "b3_44", word: "家内", reading: "かない", romaji: "kanai", meaning: "(자기) 아내", pos: "명사", category: "people",
    example: { tokens: [{ t: "家内", r: "かない" }, { t: "と" }, { t: "買", r: "か" }, { t: "い" }, { t: "物", r: "もの" }, { t: "に" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "아내와 쇼핑하러 갑니다." } },
  { id: "b3_45", word: "両親", reading: "りょうしん", romaji: "ryoushin", meaning: "부모님", pos: "명사", category: "people",
    example: { tokens: [{ t: "両親", r: "りょうしん" }, { t: "は" }, { t: "韓国", r: "かんこく" }, { t: "に" }, { t: "います。" }], ko: "부모님은 한국에 있습니다." } },
  { id: "b3_46", word: "子供たち", reading: "こどもたち", romaji: "kodomotachi", meaning: "아이들", pos: "명사", category: "people",
    example: { tokens: [{ t: "子供", r: "こども" }, { t: "たちが" }, { t: "歌", r: "うた" }, { t: "います。" }], ko: "아이들이 노래합니다." } },

  // ===== body (신체·건강·감정·상태) =====
  { id: "b3_47", word: "体", reading: "からだ", romaji: "karada", meaning: "몸", pos: "명사", category: "body",
    example: { tokens: [{ t: "体", r: "からだ" }, { t: "が" }, { t: "丈夫", r: "じょうぶ" }, { t: "です。" }], ko: "몸이 튼튼합니다." } },
  { id: "b3_48", word: "顔", reading: "かお", romaji: "kao", meaning: "얼굴", pos: "명사", category: "body",
    example: { tokens: [{ t: "顔", r: "かお" }, { t: "を" }, { t: "洗", r: "あら" }, { t: "います。" }], ko: "얼굴을 씻습니다." } },
  { id: "b3_49", word: "髪", reading: "かみ", romaji: "kami", meaning: "머리카락", pos: "명사", category: "body",
    example: { tokens: [{ t: "姉", r: "あね" }, { t: "の" }, { t: "髪", r: "かみ" }, { t: "は" }, { t: "長", r: "なが" }, { t: "いです。" }], ko: "누나의 머리카락은 깁니다." } },
  { id: "b3_50", word: "耳", reading: "みみ", romaji: "mimi", meaning: "귀", pos: "명사", category: "body",
    example: { tokens: [{ t: "耳", r: "みみ" }, { t: "が" }, { t: "痛", r: "いた" }, { t: "いです。" }], ko: "귀가 아픕니다." } },
  { id: "b3_51", word: "鼻", reading: "はな", romaji: "hana", meaning: "코", pos: "명사", category: "body",
    example: { tokens: [{ t: "犬", r: "いぬ" }, { t: "の" }, { t: "鼻", r: "はな" }, { t: "は" }, { t: "黒", r: "くろ" }, { t: "いです。" }], ko: "개의 코는 검습니다." } },
  { id: "b3_52", word: "口", reading: "くち", romaji: "kuchi", meaning: "입", pos: "명사", category: "body",
    example: { tokens: [{ t: "口", r: "くち" }, { t: "を" }, { t: "大", r: "おお" }, { t: "きく" }, { t: "開", r: "あ" }, { t: "けます。" }], ko: "입을 크게 벌립니다." } },
  { id: "b3_53", word: "歯", reading: "は", romaji: "ha", meaning: "이·치아", pos: "명사", category: "body",
    example: { tokens: [{ t: "毎日", r: "まいにち" }, { t: "歯", r: "は" }, { t: "を" }, { t: "みがきます。" }], ko: "매일 이를 닦습니다." } },
  { id: "b3_54", word: "首", reading: "くび", romaji: "kubi", meaning: "목", pos: "명사", category: "body",
    example: { tokens: [{ t: "首", r: "くび" }, { t: "が" }, { t: "痛", r: "いた" }, { t: "いです。" }], ko: "목이 아픕니다." } },
  { id: "b3_55", word: "肩", reading: "かた", romaji: "kata", meaning: "어깨", pos: "명사", category: "body",
    example: { tokens: [{ t: "肩", r: "かた" }, { t: "が" }, { t: "疲", r: "つか" }, { t: "れました。" }], ko: "어깨가 뻐근합니다." } },
  { id: "b3_56", word: "背中", reading: "せなか", romaji: "senaka", meaning: "등", pos: "명사", category: "body",
    example: { tokens: [{ t: "背中", r: "せなか" }, { t: "が" }, { t: "かゆい" }, { t: "です。" }], ko: "등이 가렵습니다." } },
  { id: "b3_57", word: "腕", reading: "うで", romaji: "ude", meaning: "팔", pos: "명사", category: "body",
    example: { tokens: [{ t: "腕", r: "うで" }, { t: "が" }, { t: "長", r: "なが" }, { t: "いです。" }], ko: "팔이 깁니다." } },
  { id: "b3_58", word: "指", reading: "ゆび", romaji: "yubi", meaning: "손가락", pos: "명사", category: "body",
    example: { tokens: [{ t: "指", r: "ゆび" }, { t: "で" }, { t: "指", r: "さ" }, { t: "します。" }], ko: "손가락으로 가리킵니다." } },
  { id: "b3_59", word: "お腹", reading: "おなか", romaji: "onaka", meaning: "배", pos: "명사", category: "body",
    example: { tokens: [{ t: "お" }, { t: "腹", r: "なか" }, { t: "が" }, { t: "痛", r: "いた" }, { t: "いです。" }], ko: "배가 아픕니다." } },
  { id: "b3_60", word: "胸", reading: "むね", romaji: "mune", meaning: "가슴", pos: "명사", category: "body",
    example: { tokens: [{ t: "胸", r: "むね" }, { t: "が" }, { t: "苦", r: "くる" }, { t: "しいです。" }], ko: "가슴이 답답합니다." } },
  { id: "b3_61", word: "心", reading: "こころ", romaji: "kokoro", meaning: "마음", pos: "명사", category: "body",
    example: { tokens: [{ t: "やさしい" }, { t: "心", r: "こころ" }, { t: "の" }, { t: "人", r: "ひと" }, { t: "です。" }], ko: "마음이 따뜻한 사람입니다." } },
  { id: "b3_62", word: "気持ち", reading: "きもち", romaji: "kimochi", meaning: "기분·마음", pos: "명사", category: "body",
    example: { tokens: [{ t: "気持", r: "きも" }, { t: "ちが" }, { t: "いい" }, { t: "です。" }], ko: "기분이 좋습니다." } },
  { id: "b3_63", word: "気分", reading: "きぶん", romaji: "kibun", meaning: "기분·컨디션", pos: "명사", category: "body",
    example: { tokens: [{ t: "今日", r: "きょう" }, { t: "は" }, { t: "気分", r: "きぶん" }, { t: "が" }, { t: "悪", r: "わる" }, { t: "いです。" }], ko: "오늘은 컨디션이 나쁩니다." } },
  { id: "b3_64", word: "風邪", reading: "かぜ", romaji: "kaze", meaning: "감기", pos: "명사", category: "body",
    example: { tokens: [{ t: "風邪", r: "かぜ" }, { t: "を" }, { t: "ひきました。" }], ko: "감기에 걸렸습니다." } },
  { id: "b3_65", word: "熱", reading: "ねつ", romaji: "netsu", meaning: "열", pos: "명사", category: "body",
    example: { tokens: [{ t: "熱", r: "ねつ" }, { t: "が" }, { t: "あります。" }], ko: "열이 있습니다." } },
  { id: "b3_66", word: "薬", reading: "くすり", romaji: "kusuri", meaning: "약", pos: "명사", category: "body",
    example: { tokens: [{ t: "薬", r: "くすり" }, { t: "を" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "약을 먹습니다." } },
  { id: "b3_67", word: "けが", reading: "けが", romaji: "kega", meaning: "부상·상처", pos: "명사", category: "body",
    example: { tokens: [{ t: "足", r: "あし" }, { t: "に" }, { t: "けが" }, { t: "を" }, { t: "しました。" }], ko: "다리를 다쳤습니다." } },
  { id: "b3_68", word: "痛い", reading: "いたい", romaji: "itai", meaning: "아프다", pos: "い형용사", category: "body",
    example: { tokens: [{ t: "頭", r: "あたま" }, { t: "が" }, { t: "痛", r: "いた" }, { t: "いです。" }], ko: "머리가 아픕니다." } },
  { id: "b3_69", word: "かゆい", reading: "かゆい", romaji: "kayui", meaning: "가렵다", pos: "い형용사", category: "body",
    example: { tokens: [{ t: "目", r: "め" }, { t: "が" }, { t: "かゆい" }, { t: "です。" }], ko: "눈이 가렵습니다." } },
  { id: "b3_70", word: "眠い", reading: "ねむい", romaji: "nemui", meaning: "졸리다", pos: "い형용사", category: "body",
    example: { tokens: [{ t: "とても" }, { t: "眠", r: "ねむ" }, { t: "いです。" }], ko: "매우 졸립니다." } },
  { id: "b3_71", word: "嬉しい", reading: "うれしい", romaji: "ureshii", meaning: "기쁘다", pos: "い형용사", category: "body",
    example: { tokens: [{ t: "会", r: "あ" }, { t: "えて" }, { t: "嬉", r: "うれ" }, { t: "しいです。" }], ko: "만나서 기쁩니다." } },
  { id: "b3_72", word: "悲しい", reading: "かなしい", romaji: "kanashii", meaning: "슬프다", pos: "い형용사", category: "body",
    example: { tokens: [{ t: "別", r: "わか" }, { t: "れは" }, { t: "悲", r: "かな" }, { t: "しいです。" }], ko: "이별은 슬픕니다." } },
  { id: "b3_73", word: "怖い", reading: "こわい", romaji: "kowai", meaning: "무섭다", pos: "い형용사", category: "body",
    example: { tokens: [{ t: "あの" }, { t: "犬", r: "いぬ" }, { t: "は" }, { t: "怖", r: "こわ" }, { t: "いです。" }], ko: "저 개는 무섭습니다." } },
  { id: "b3_74", word: "寂しい", reading: "さびしい", romaji: "sabishii", meaning: "외롭다·쓸쓸하다", pos: "い형용사", category: "body",
    example: { tokens: [{ t: "一人", r: "ひとり" }, { t: "は" }, { t: "寂", r: "さび" }, { t: "しいです。" }], ko: "혼자는 외롭습니다." } },
  { id: "b3_75", word: "痛み", reading: "いたみ", romaji: "itami", meaning: "통증", pos: "명사", category: "body",
    example: { tokens: [{ t: "痛", r: "いた" }, { t: "みが" }, { t: "あります。" }], ko: "통증이 있습니다." } },
  { id: "b3_76", word: "健康", reading: "けんこう", romaji: "kenkou", meaning: "건강", pos: "명사", category: "body",
    example: { tokens: [{ t: "祖父", r: "そふ" }, { t: "は" }, { t: "健康", r: "けんこう" }, { t: "です。" }], ko: "할아버지는 건강합니다." } },
  { id: "b3_77", word: "丈夫", reading: "じょうぶ", romaji: "joubu", meaning: "튼튼함·건강함", pos: "な형용사", category: "body",
    example: { tokens: [{ t: "この" }, { t: "机", r: "つくえ" }, { t: "は" }, { t: "丈夫", r: "じょうぶ" }, { t: "です。" }], ko: "이 책상은 튼튼합니다." } },
  { id: "b3_78", word: "血", reading: "ち", romaji: "chi", meaning: "피", pos: "명사", category: "body",
    example: { tokens: [{ t: "指", r: "ゆび" }, { t: "から" }, { t: "血", r: "ち" }, { t: "が" }, { t: "出", r: "で" }, { t: "ました。" }], ko: "손가락에서 피가 났습니다." } },
  { id: "b3_79", word: "声", reading: "こえ", romaji: "koe", meaning: "목소리", pos: "명사", category: "body",
    example: { tokens: [{ t: "母", r: "はは" }, { t: "の" }, { t: "声", r: "こえ" }, { t: "は" }, { t: "やさしい" }, { t: "です。" }], ko: "엄마의 목소리는 다정합니다." } },
  { id: "b3_80", word: "顔色", reading: "かおいろ", romaji: "kaoiro", meaning: "안색", pos: "명사", category: "body",
    example: { tokens: [{ t: "顔色", r: "かおいろ" }, { t: "が" }, { t: "悪", r: "わる" }, { t: "いです。" }], ko: "안색이 나쁩니다." } },
  { id: "b3_81", word: "おいしそう", reading: "おいしそう", romaji: "oishisou", meaning: "맛있어 보임", pos: "な형용사", category: "body",
    example: { tokens: [{ t: "ケーキ" }, { t: "が" }, { t: "おいしそう" }, { t: "です。" }], ko: "케이크가 맛있어 보입니다." } },
  { id: "b3_82", word: "元気がない", reading: "げんきがない", romaji: "genki ga nai", meaning: "기운이 없다", pos: "な형용사", category: "body",
    example: { tokens: [{ t: "弟", r: "おとうと" }, { t: "は" }, { t: "元気", r: "げんき" }, { t: "が" }, { t: "ない" }, { t: "です。" }], ko: "남동생은 기운이 없습니다." } },
  { id: "b3_83", word: "汗", reading: "あせ", romaji: "ase", meaning: "땀", pos: "명사", category: "body",
    example: { tokens: [{ t: "汗", r: "あせ" }, { t: "を" }, { t: "かきます。" }], ko: "땀을 흘립니다." } },
  { id: "b3_84", word: "涙", reading: "なみだ", romaji: "namida", meaning: "눈물", pos: "명사", category: "body",
    example: { tokens: [{ t: "涙", r: "なみだ" }, { t: "が" }, { t: "出", r: "で" }, { t: "ました。" }], ko: "눈물이 났습니다." } },
  { id: "b3_85", word: "怒る", reading: "おこりっぽい", romaji: "okorippoi", meaning: "화를 잘 냄", pos: "い형용사", category: "body",
    example: { tokens: [{ t: "父", r: "ちち" }, { t: "は" }, { t: "怒", r: "おこ" }, { t: "りっぽい" }, { t: "です。" }], ko: "아버지는 화를 잘 냅니다." } },

  // ===== time (시간·날짜·요일·달력 표현) =====
  { id: "b3_86", word: "時", reading: "じ", romaji: "ji", meaning: "시(시각)", pos: "명사", category: "time",
    example: { tokens: [{ t: "今", r: "いま" }, { t: "三", r: "さん" }, { t: "時", r: "じ" }, { t: "です。" }], ko: "지금 세 시입니다." } },
  { id: "b3_87", word: "分", reading: "ふん", romaji: "fun", meaning: "분", pos: "명사", category: "time",
    example: { tokens: [{ t: "十", r: "じゅっ" }, { t: "分", r: "ぷん" }, { t: "待", r: "ま" }, { t: "ちます。" }], ko: "십 분 기다립니다." } },
  { id: "b3_88", word: "秒", reading: "びょう", romaji: "byou", meaning: "초", pos: "명사", category: "time",
    example: { tokens: [{ t: "三十", r: "さんじゅう" }, { t: "秒", r: "びょう" }, { t: "かかります。" }], ko: "삼십 초 걸립니다." } },
  { id: "b3_89", word: "年", reading: "とし", romaji: "toshi", meaning: "해·년", pos: "명사", category: "time",
    example: { tokens: [{ t: "今年", r: "ことし" }, { t: "は" }, { t: "いい" }, { t: "年", r: "とし" }, { t: "です。" }], ko: "올해는 좋은 해입니다." } },
  { id: "b3_90", word: "月", reading: "つき", romaji: "tsuki", meaning: "달·월", pos: "명사", category: "time",
    example: { tokens: [{ t: "来", r: "らい" }, { t: "月", r: "げつ" }, { t: "に" }, { t: "会", r: "あ" }, { t: "いましょう。" }], ko: "다음 달에 만납시다." } },
  { id: "b3_91", word: "週", reading: "しゅう", romaji: "shuu", meaning: "주", pos: "명사", category: "time",
    example: { tokens: [{ t: "一", r: "いっ" }, { t: "週間", r: "しゅうかん" }, { t: "休", r: "やす" }, { t: "みます。" }], ko: "일주일 쉽니다." } },
  { id: "b3_92", word: "火曜日", reading: "かようび", romaji: "kayoubi", meaning: "화요일", pos: "명사", category: "time",
    example: { tokens: [{ t: "火曜日", r: "かようび" }, { t: "に" }, { t: "病院", r: "びょういん" }, { t: "へ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "화요일에 병원에 갑니다." } },
  { id: "b3_93", word: "水曜日", reading: "すいようび", romaji: "suiyoubi", meaning: "수요일", pos: "명사", category: "time",
    example: { tokens: [{ t: "水曜日", r: "すいようび" }, { t: "は" }, { t: "忙", r: "いそが" }, { t: "しいです。" }], ko: "수요일은 바쁩니다." } },
  { id: "b3_94", word: "木曜日", reading: "もくようび", romaji: "mokuyoubi", meaning: "목요일", pos: "명사", category: "time",
    example: { tokens: [{ t: "木曜日", r: "もくようび" }, { t: "に" }, { t: "テスト" }, { t: "が" }, { t: "あります。" }], ko: "목요일에 시험이 있습니다." } },
  { id: "b3_95", word: "一昨日", reading: "おととい", romaji: "ototoi", meaning: "그저께", pos: "명사", category: "time",
    example: { tokens: [{ t: "一昨日", r: "おととい" }, { t: "雨", r: "あめ" }, { t: "が" }, { t: "降", r: "ふ" }, { t: "りました。" }], ko: "그저께 비가 내렸습니다." } },
  { id: "b3_96", word: "明後日", reading: "あさって", romaji: "asatte", meaning: "모레", pos: "명사", category: "time",
    example: { tokens: [{ t: "明後日", r: "あさって" }, { t: "は" }, { t: "休", r: "やす" }, { t: "みです。" }], ko: "모레는 휴일입니다." } },
  { id: "b3_97", word: "今朝", reading: "けさ", romaji: "kesa", meaning: "오늘 아침", pos: "명사", category: "time",
    example: { tokens: [{ t: "今朝", r: "けさ" }, { t: "は" }, { t: "寒", r: "さむ" }, { t: "かったです。" }], ko: "오늘 아침은 추웠습니다." } },
  { id: "b3_98", word: "今晩", reading: "こんばん", romaji: "konban", meaning: "오늘 밤", pos: "명사", category: "time",
    example: { tokens: [{ t: "今晩", r: "こんばん" }, { t: "映画", r: "えいが" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "오늘 밤 영화를 봅니다." } },
  { id: "b3_99", word: "夕方", reading: "ゆうがた", romaji: "yuugata", meaning: "저녁(무렵)", pos: "명사", category: "time",
    example: { tokens: [{ t: "夕方", r: "ゆうがた" }, { t: "に" }, { t: "帰", r: "かえ" }, { t: "ります。" }], ko: "저녁에 돌아갑니다." } },
  { id: "b3_100", word: "昼", reading: "ひる", romaji: "hiru", meaning: "낮·점심", pos: "명사", category: "time",
    example: { tokens: [{ t: "昼", r: "ひる" }, { t: "に" }, { t: "ご" }, { t: "飯", r: "はん" }, { t: "を" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "점심에 밥을 먹습니다." } },
  { id: "b3_101", word: "正午", reading: "しょうご", romaji: "shougo", meaning: "정오", pos: "명사", category: "time",
    example: { tokens: [{ t: "正午", r: "しょうご" }, { t: "に" }, { t: "会", r: "あ" }, { t: "いましょう。" }], ko: "정오에 만납시다." } },
  { id: "b3_102", word: "午前", reading: "ごぜん", romaji: "gozen", meaning: "오전", pos: "명사", category: "time",
    example: { tokens: [{ t: "午前", r: "ごぜん" }, { t: "九", r: "く" }, { t: "時", r: "じ" }, { t: "に" }, { t: "始", r: "はじ" }, { t: "まります。" }], ko: "오전 아홉 시에 시작합니다." } },
  { id: "b3_103", word: "来週", reading: "らいしゅう", romaji: "raishuu", meaning: "다음 주", pos: "명사", category: "time",
    example: { tokens: [{ t: "来週", r: "らいしゅう" }, { t: "旅行", r: "りょこう" }, { t: "します。" }], ko: "다음 주 여행합니다." } },
  { id: "b3_104", word: "先週", reading: "せんしゅう", romaji: "senshuu", meaning: "지난주", pos: "명사", category: "time",
    example: { tokens: [{ t: "先週", r: "せんしゅう" }, { t: "は" }, { t: "忙", r: "いそが" }, { t: "しかったです。" }], ko: "지난주는 바빴습니다." } },
  { id: "b3_105", word: "来月", reading: "らいげつ", romaji: "raigetsu", meaning: "다음 달", pos: "명사", category: "time",
    example: { tokens: [{ t: "来月", r: "らいげつ" }, { t: "韓国", r: "かんこく" }, { t: "へ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "다음 달 한국에 갑니다." } },
  { id: "b3_106", word: "先月", reading: "せんげつ", romaji: "sengetsu", meaning: "지난달", pos: "명사", category: "time",
    example: { tokens: [{ t: "先月", r: "せんげつ" }, { t: "引", r: "ひ" }, { t: "っ" }, { t: "越", r: "こ" }, { t: "しました。" }], ko: "지난달 이사했습니다." } },
  { id: "b3_107", word: "来年", reading: "らいねん", romaji: "rainen", meaning: "내년", pos: "명사", category: "time",
    example: { tokens: [{ t: "来年", r: "らいねん" }, { t: "大学生", r: "だいがくせい" }, { t: "に" }, { t: "なります。" }], ko: "내년 대학생이 됩니다." } },
  { id: "b3_108", word: "今年", reading: "ことし", romaji: "kotoshi", meaning: "올해", pos: "명사", category: "time",
    example: { tokens: [{ t: "今年", r: "ことし" }, { t: "は" }, { t: "雪", r: "ゆき" }, { t: "が" }, { t: "多", r: "おお" }, { t: "いです。" }], ko: "올해는 눈이 많습니다." } },
  { id: "b3_109", word: "最近", reading: "さいきん", romaji: "saikin", meaning: "최근·요즘", pos: "명사", category: "time",
    example: { tokens: [{ t: "最近", r: "さいきん" }, { t: "忙", r: "いそが" }, { t: "しいです。" }], ko: "요즘 바쁩니다." } },
  { id: "b3_110", word: "さっき", reading: "さっき", romaji: "sakki", meaning: "아까·조금 전", pos: "부사", category: "time",
    example: { tokens: [{ t: "さっき" }, { t: "電話", r: "でんわ" }, { t: "が" }, { t: "ありました。" }], ko: "아까 전화가 왔습니다." } },
  { id: "b3_111", word: "あとで", reading: "あとで", romaji: "atode", meaning: "나중에", pos: "부사", category: "time",
    example: { tokens: [{ t: "あとで" }, { t: "電話", r: "でんわ" }, { t: "します。" }], ko: "나중에 전화하겠습니다." } },
  { id: "b3_112", word: "これから", reading: "これから", romaji: "korekara", meaning: "이제부터·앞으로", pos: "부사", category: "time",
    example: { tokens: [{ t: "これから" }, { t: "勉強", r: "べんきょう" }, { t: "します。" }], ko: "이제부터 공부합니다." } },
  { id: "b3_113", word: "将来", reading: "しょうらい", romaji: "shourai", meaning: "장래·미래", pos: "명사", category: "time",
    example: { tokens: [{ t: "将来", r: "しょうらい" }, { t: "医者", r: "いしゃ" }, { t: "に" }, { t: "なりたいです。" }], ko: "장래에 의사가 되고 싶습니다." } },
  { id: "b3_114", word: "昔", reading: "むかし", romaji: "mukashi", meaning: "옛날", pos: "명사", category: "time",
    example: { tokens: [{ t: "昔", r: "むかし" }, { t: "ここ" }, { t: "に" }, { t: "店", r: "みせ" }, { t: "が" }, { t: "ありました。" }], ko: "옛날에 여기에 가게가 있었습니다." } },
  { id: "b3_115", word: "いつ", reading: "いつ", romaji: "itsu", meaning: "언제", pos: "의문사", category: "time",
    example: { tokens: [{ t: "誕生日", r: "たんじょうび" }, { t: "は" }, { t: "いつ" }, { t: "ですか。" }], ko: "생일은 언제입니까?" } },
  { id: "b3_116", word: "何時", reading: "なんじ", romaji: "nanji", meaning: "몇 시", pos: "의문사", category: "time",
    example: { tokens: [{ t: "今", r: "いま" }, { t: "何時", r: "なんじ" }, { t: "ですか。" }], ko: "지금 몇 시입니까?" } },
  { id: "b3_117", word: "何曜日", reading: "なんようび", romaji: "nan'youbi", meaning: "무슨 요일", pos: "의문사", category: "time",
    example: { tokens: [{ t: "今日", r: "きょう" }, { t: "は" }, { t: "何曜日", r: "なんようび" }, { t: "ですか。" }], ko: "오늘은 무슨 요일입니까?" } },
  { id: "b3_118", word: "誕生日", reading: "たんじょうび", romaji: "tanjoubi", meaning: "생일", pos: "명사", category: "time",
    example: { tokens: [{ t: "妹", r: "いもうと" }, { t: "の" }, { t: "誕生日", r: "たんじょうび" }, { t: "です。" }], ko: "여동생의 생일입니다." } },
  { id: "b3_119", word: "休み", reading: "やすみ", romaji: "yasumi", meaning: "휴일·쉬는 날", pos: "명사", category: "time",
    example: { tokens: [{ t: "明日", r: "あした" }, { t: "は" }, { t: "休", r: "やす" }, { t: "みです。" }], ko: "내일은 휴일입니다." } },
  { id: "b3_120", word: "春休み", reading: "はるやすみ", romaji: "haruyasumi", meaning: "봄방학", pos: "명사", category: "time",
    example: { tokens: [{ t: "春休", r: "はるやす" }, { t: "みに" }, { t: "旅行", r: "りょこう" }, { t: "します。" }], ko: "봄방학에 여행합니다." } },
  { id: "b3_121", word: "夏休み", reading: "なつやすみ", romaji: "natsuyasumi", meaning: "여름방학", pos: "명사", category: "time",
    example: { tokens: [{ t: "夏休", r: "なつやす" }, { t: "みは" }, { t: "長", r: "なが" }, { t: "いです。" }], ko: "여름방학은 깁니다." } },
  { id: "b3_122", word: "毎週", reading: "まいしゅう", romaji: "maishuu", meaning: "매주", pos: "명사", category: "time",
    example: { tokens: [{ t: "毎週", r: "まいしゅう" }, { t: "運動", r: "うんどう" }, { t: "します。" }], ko: "매주 운동합니다." } },
  { id: "b3_123", word: "毎月", reading: "まいつき", romaji: "maitsuki", meaning: "매달", pos: "명사", category: "time",
    example: { tokens: [{ t: "毎月", r: "まいつき" }, { t: "本", r: "ほん" }, { t: "を" }, { t: "買", r: "か" }, { t: "います。" }], ko: "매달 책을 삽니다." } },
  { id: "b3_124", word: "毎年", reading: "まいとし", romaji: "maitoshi", meaning: "매년", pos: "명사", category: "time",
    example: { tokens: [{ t: "毎年", r: "まいとし" }, { t: "海", r: "うみ" }, { t: "へ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "매년 바다에 갑니다." } },
  { id: "b3_125", word: "毎朝", reading: "まいあさ", romaji: "maiasa", meaning: "매일 아침", pos: "명사", category: "time",
    example: { tokens: [{ t: "毎朝", r: "まいあさ" }, { t: "コーヒー" }, { t: "を" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "매일 아침 커피를 마십니다." } },
  { id: "b3_126", word: "毎晩", reading: "まいばん", romaji: "maiban", meaning: "매일 밤", pos: "명사", category: "time",
    example: { tokens: [{ t: "毎晩", r: "まいばん" }, { t: "本", r: "ほん" }, { t: "を" }, { t: "読", r: "よ" }, { t: "みます。" }], ko: "매일 밤 책을 읽습니다." } },
  { id: "b3_127", word: "午前中", reading: "ごぜんちゅう", romaji: "gozenchuu", meaning: "오전 중", pos: "명사", category: "time",
    example: { tokens: [{ t: "午前中", r: "ごぜんちゅう" }, { t: "に" }, { t: "来", r: "き" }, { t: "てください。" }], ko: "오전 중에 와 주세요." } },
  { id: "b3_128", word: "週末", reading: "しゅうまつ", romaji: "shuumatsu", meaning: "주말", pos: "명사", category: "time",
    example: { tokens: [{ t: "週末", r: "しゅうまつ" }, { t: "は" }, { t: "暇", r: "ひま" }, { t: "です。" }], ko: "주말은 한가합니다." } },
  { id: "b3_129", word: "時々", reading: "ときどき", romaji: "tokidoki", meaning: "때때로·가끔", pos: "부사", category: "time",
    example: { tokens: [{ t: "時々", r: "ときどき" }, { t: "映画", r: "えいが" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "가끔 영화를 봅니다." } },
  { id: "b3_130", word: "そろそろ", reading: "そろそろ", romaji: "sorosoro", meaning: "슬슬·이제", pos: "부사", category: "time",
    example: { tokens: [{ t: "そろそろ" }, { t: "帰", r: "かえ" }, { t: "りましょう。" }], ko: "슬슬 돌아갑시다." } },
  { id: "b3_131", word: "すぐ", reading: "すぐ", romaji: "sugu", meaning: "곧·바로", pos: "부사", category: "time",
    example: { tokens: [{ t: "すぐ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "바로 가겠습니다." } },
  { id: "b3_132", word: "夜中", reading: "よなか", romaji: "yonaka", meaning: "한밤중", pos: "명사", category: "time",
    example: { tokens: [{ t: "夜中", r: "よなか" }, { t: "に" }, { t: "目", r: "め" }, { t: "が" }, { t: "さめました。" }], ko: "한밤중에 잠이 깼습니다." } },
];
