import type { Word } from "./types";

// JLPT N5 확장 단어 — 숫자·형용사·색 (batch B4)
export const VOCAB_B4: Word[] = [
  // ── 숫자·조수사 (number) ──────────────────────────
  { id: "b4_1", word: "零", reading: "れい", romaji: "rei", meaning: "영, 0", pos: "수사", category: "number",
    example: { tokens: [{ t: "零", r: "れい" }, { t: "から" }, { t: "始", r: "はじ" }, { t: "めます。" }], ko: "0부터 시작합니다." } },
  { id: "b4_2", word: "ゼロ", reading: "ぜろ", romaji: "zero", meaning: "제로, 0", pos: "수사", category: "number",
    example: { tokens: [{ t: "ゼロです。" }], ko: "제로입니다." } },
  { id: "b4_3", word: "億", reading: "おく", romaji: "oku", meaning: "억", pos: "수사", category: "number",
    example: { tokens: [{ t: "一", r: "いち" }, { t: "億", r: "おく" }, { t: "円", r: "えん" }, { t: "です。" }], ko: "1억 엔입니다." } },
  { id: "b4_4", word: "一つ", reading: "ひとつ", romaji: "hitotsu", meaning: "한 개", pos: "수사", category: "number",
    example: { tokens: [{ t: "りんごを" }, { t: "一", r: "ひと" }, { t: "つください。" }], ko: "사과를 한 개 주세요." } },
  { id: "b4_5", word: "二つ", reading: "ふたつ", romaji: "futatsu", meaning: "두 개", pos: "수사", category: "number",
    example: { tokens: [{ t: "卵", r: "たまご" }, { t: "が" }, { t: "二", r: "ふた" }, { t: "つあります。" }], ko: "달걀이 두 개 있습니다." } },
  { id: "b4_6", word: "三つ", reading: "みっつ", romaji: "mittsu", meaning: "세 개", pos: "수사", category: "number",
    example: { tokens: [{ t: "三", r: "みっ" }, { t: "つで" }, { t: "十分", r: "じゅうぶん" }, { t: "です。" }], ko: "세 개로 충분합니다." } },
  { id: "b4_7", word: "四つ", reading: "よっつ", romaji: "yottsu", meaning: "네 개", pos: "수사", category: "number",
    example: { tokens: [{ t: "椅子", r: "いす" }, { t: "が" }, { t: "四", r: "よっ" }, { t: "つあります。" }], ko: "의자가 네 개 있습니다." } },
  { id: "b4_8", word: "五つ", reading: "いつつ", romaji: "itsutsu", meaning: "다섯 개", pos: "수사", category: "number",
    example: { tokens: [{ t: "五", r: "いつ" }, { t: "つください。" }], ko: "다섯 개 주세요." } },
  { id: "b4_9", word: "六つ", reading: "むっつ", romaji: "muttsu", meaning: "여섯 개", pos: "수사", category: "number",
    example: { tokens: [{ t: "六", r: "むっ" }, { t: "つ" }, { t: "買", r: "か" }, { t: "いました。" }], ko: "여섯 개 샀습니다." } },
  { id: "b4_10", word: "七つ", reading: "ななつ", romaji: "nanatsu", meaning: "일곱 개", pos: "수사", category: "number",
    example: { tokens: [{ t: "七", r: "なな" }, { t: "つに" }, { t: "分", r: "わ" }, { t: "けます。" }], ko: "일곱 개로 나눕니다." } },
  { id: "b4_11", word: "八つ", reading: "やっつ", romaji: "yattsu", meaning: "여덟 개", pos: "수사", category: "number",
    example: { tokens: [{ t: "八", r: "やっ" }, { t: "つも" }, { t: "あります。" }], ko: "여덟 개나 있습니다." } },
  { id: "b4_12", word: "九つ", reading: "ここのつ", romaji: "kokonotsu", meaning: "아홉 개", pos: "수사", category: "number",
    example: { tokens: [{ t: "九", r: "ここの" }, { t: "つ" }, { t: "数", r: "かぞ" }, { t: "えました。" }], ko: "아홉 개 세었습니다." } },
  { id: "b4_13", word: "一人", reading: "ひとり", romaji: "hitori", meaning: "한 명, 혼자", pos: "수사", category: "number",
    example: { tokens: [{ t: "一人", r: "ひとり" }, { t: "で" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "혼자서 갑니다." } },
  { id: "b4_14", word: "二人", reading: "ふたり", romaji: "futari", meaning: "두 명", pos: "수사", category: "number",
    example: { tokens: [{ t: "二人", r: "ふたり" }, { t: "で" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "둘이서 먹습니다." } },
  { id: "b4_15", word: "三人", reading: "さんにん", romaji: "sannin", meaning: "세 명", pos: "수사", category: "number",
    example: { tokens: [{ t: "三人", r: "さんにん" }, { t: "が" }, { t: "来", r: "き" }, { t: "ました。" }], ko: "세 명이 왔습니다." } },
  { id: "b4_16", word: "一個", reading: "いっこ", romaji: "ikko", meaning: "한 개(個)", pos: "수사", category: "number",
    example: { tokens: [{ t: "卵", r: "たまご" }, { t: "を" }, { t: "一個", r: "いっこ" }, { t: "ください。" }], ko: "달걀을 한 개 주세요." } },
  { id: "b4_17", word: "一本", reading: "いっぽん", romaji: "ippon", meaning: "한 자루, 한 병(本)", pos: "수사", category: "number",
    example: { tokens: [{ t: "ペンを" }, { t: "一本", r: "いっぽん" }, { t: "貸", r: "か" }, { t: "してください。" }], ko: "펜을 한 자루 빌려주세요." } },
  { id: "b4_18", word: "一枚", reading: "いちまい", romaji: "ichimai", meaning: "한 장(枚)", pos: "수사", category: "number",
    example: { tokens: [{ t: "紙", r: "かみ" }, { t: "を" }, { t: "一枚", r: "いちまい" }, { t: "ください。" }], ko: "종이를 한 장 주세요." } },
  { id: "b4_19", word: "一冊", reading: "いっさつ", romaji: "issatsu", meaning: "한 권(冊)", pos: "수사", category: "number",
    example: { tokens: [{ t: "本", r: "ほん" }, { t: "を" }, { t: "一冊", r: "いっさつ" }, { t: "買", r: "か" }, { t: "いました。" }], ko: "책을 한 권 샀습니다." } },
  { id: "b4_20", word: "一台", reading: "いちだい", romaji: "ichidai", meaning: "한 대(台)", pos: "수사", category: "number",
    example: { tokens: [{ t: "車", r: "くるま" }, { t: "が" }, { t: "一台", r: "いちだい" }, { t: "あります。" }], ko: "차가 한 대 있습니다." } },
  { id: "b4_21", word: "一匹", reading: "いっぴき", romaji: "ippiki", meaning: "한 마리(匹)", pos: "수사", category: "number",
    example: { tokens: [{ t: "猫", r: "ねこ" }, { t: "が" }, { t: "一匹", r: "いっぴき" }, { t: "います。" }], ko: "고양이가 한 마리 있습니다." } },
  { id: "b4_22", word: "一杯", reading: "いっぱい", romaji: "ippai", meaning: "한 잔(杯)", pos: "수사", category: "number",
    example: { tokens: [{ t: "お" }, { t: "茶", r: "ちゃ" }, { t: "を" }, { t: "一杯", r: "いっぱい" }, { t: "どうぞ。" }], ko: "차를 한 잔 드세요." } },
  { id: "b4_23", word: "一回", reading: "いっかい", romaji: "ikkai", meaning: "한 번(回)", pos: "수사", category: "number",
    example: { tokens: [{ t: "一回", r: "いっかい" }, { t: "だけ" }, { t: "会", r: "あ" }, { t: "いました。" }], ko: "한 번만 만났습니다." } },
  { id: "b4_24", word: "一度", reading: "いちど", romaji: "ichido", meaning: "한 번(度)", pos: "수사", category: "number",
    example: { tokens: [{ t: "もう" }, { t: "一度", r: "いちど" }, { t: "言", r: "い" }, { t: "ってください。" }], ko: "한 번 더 말해 주세요." } },
  { id: "b4_25", word: "一番", reading: "いちばん", romaji: "ichiban", meaning: "가장, 제일", pos: "수사", category: "number",
    example: { tokens: [{ t: "これが" }, { t: "一番", r: "いちばん" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "이것이 제일 좋습니다." } },
  { id: "b4_26", word: "半", reading: "はん", romaji: "han", meaning: "반, 30분", pos: "수사", category: "number",
    example: { tokens: [{ t: "三", r: "さん" }, { t: "時", r: "じ" }, { t: "半", r: "はん" }, { t: "です。" }], ko: "3시 반입니다." } },
  { id: "b4_27", word: "多い", reading: "おおい", romaji: "ooi", meaning: "많다", pos: "い형용사", category: "number",
    example: { tokens: [{ t: "人", r: "ひと" }, { t: "が" }, { t: "多", r: "おお" }, { t: "いです。" }], ko: "사람이 많습니다." } },
  { id: "b4_28", word: "少ない", reading: "すくない", romaji: "sukunai", meaning: "적다", pos: "い형용사", category: "number",
    example: { tokens: [{ t: "お" }, { t: "金", r: "かね" }, { t: "が" }, { t: "少", r: "すく" }, { t: "ないです。" }], ko: "돈이 적습니다." } },
  { id: "b4_29", word: "全部", reading: "ぜんぶ", romaji: "zenbu", meaning: "전부, 모두", pos: "명사", category: "number",
    example: { tokens: [{ t: "全部", r: "ぜんぶ" }, { t: "食", r: "た" }, { t: "べました。" }], ko: "전부 먹었습니다." } },
  { id: "b4_30", word: "みんな", reading: "みんな", romaji: "minna", meaning: "모두, 다 같이", pos: "명사", category: "number",
    example: { tokens: [{ t: "みんなで" }, { t: "遊", r: "あそ" }, { t: "びます。" }], ko: "다 같이 놉니다." } },
  { id: "b4_31", word: "数", reading: "かず", romaji: "kazu", meaning: "수, 숫자", pos: "명사", category: "number",
    example: { tokens: [{ t: "数", r: "かず" }, { t: "を" }, { t: "数", r: "かぞ" }, { t: "えます。" }], ko: "수를 셉니다." } },
  { id: "b4_32", word: "番号", reading: "ばんごう", romaji: "bangou", meaning: "번호", pos: "명사", category: "number",
    example: { tokens: [{ t: "電話", r: "でんわ" }, { t: "番号", r: "ばんごう" }, { t: "を" }, { t: "教", r: "おし" }, { t: "えてください。" }], ko: "전화번호를 알려 주세요." } },
  { id: "b4_33", word: "一歳", reading: "いっさい", romaji: "issai", meaning: "한 살(歳)", pos: "수사", category: "number",
    example: { tokens: [{ t: "妹", r: "いもうと" }, { t: "は" }, { t: "一歳", r: "いっさい" }, { t: "です。" }], ko: "여동생은 한 살입니다." } },
  { id: "b4_34", word: "二十歳", reading: "はたち", romaji: "hatachi", meaning: "스무 살", pos: "수사", category: "number",
    example: { tokens: [{ t: "今年", r: "ことし" }, { t: "二十歳", r: "はたち" }, { t: "になりました。" }], ko: "올해 스무 살이 되었습니다." } },
  { id: "b4_35", word: "何", reading: "なん", romaji: "nan", meaning: "몇, 무엇", pos: "수사", category: "number",
    example: { tokens: [{ t: "何", r: "なん" }, { t: "個", r: "こ" }, { t: "ありますか。" }], ko: "몇 개 있습니까?" } },
  { id: "b4_36", word: "何人", reading: "なんにん", romaji: "nannin", meaning: "몇 명", pos: "수사", category: "number",
    example: { tokens: [{ t: "何人", r: "なんにん" }, { t: "来", r: "き" }, { t: "ますか。" }], ko: "몇 명 옵니까?" } },
  { id: "b4_37", word: "何時", reading: "なんじ", romaji: "nanji", meaning: "몇 시", pos: "수사", category: "number",
    example: { tokens: [{ t: "今", r: "いま" }, { t: "何時", r: "なんじ" }, { t: "ですか。" }], ko: "지금 몇 시입니까?" } },
  { id: "b4_38", word: "番", reading: "ばん", romaji: "ban", meaning: "번, 차례", pos: "수사", category: "number",
    example: { tokens: [{ t: "二", r: "に" }, { t: "番", r: "ばん" }, { t: "の" }, { t: "電車", r: "でんしゃ" }, { t: "に" }, { t: "乗", r: "の" }, { t: "ります。" }], ko: "2번 전철을 탑니다." } },
  { id: "b4_39", word: "両方", reading: "りょうほう", romaji: "ryouhou", meaning: "양쪽, 둘 다", pos: "명사", category: "number",
    example: { tokens: [{ t: "両方", r: "りょうほう" }, { t: "ください。" }], ko: "둘 다 주세요." } },
  { id: "b4_40", word: "半分", reading: "はんぶん", romaji: "hanbun", meaning: "절반", pos: "명사", category: "number",
    example: { tokens: [{ t: "ケーキを" }, { t: "半分", r: "はんぶん" }, { t: "に" }, { t: "切", r: "き" }, { t: "ります。" }], ko: "케이크를 반으로 자릅니다." } },

  // ── 형용사 (adjective) ────────────────────────────
  { id: "b4_41", word: "重い", reading: "おもい", romaji: "omoi", meaning: "무겁다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "荷物", r: "にもつ" }, { t: "が" }, { t: "重", r: "おも" }, { t: "いです。" }], ko: "짐이 무겁습니다." } },
  { id: "b4_42", word: "軽い", reading: "かるい", romaji: "karui", meaning: "가볍다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "この" }, { t: "鞄", r: "かばん" }, { t: "は" }, { t: "軽", r: "かる" }, { t: "いです。" }], ko: "이 가방은 가볍습니다." } },
  { id: "b4_43", word: "太い", reading: "ふとい", romaji: "futoi", meaning: "굵다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "太", r: "ふと" }, { t: "い" }, { t: "木", r: "き" }, { t: "があります。" }], ko: "굵은 나무가 있습니다." } },
  { id: "b4_44", word: "細い", reading: "ほそい", romaji: "hosoi", meaning: "가늘다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "細", r: "ほそ" }, { t: "い" }, { t: "道", r: "みち" }, { t: "です。" }], ko: "좁은 길입니다." } },
  { id: "b4_45", word: "広い", reading: "ひろい", romaji: "hiroi", meaning: "넓다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "部屋", r: "へや" }, { t: "が" }, { t: "広", r: "ひろ" }, { t: "いです。" }], ko: "방이 넓습니다." } },
  { id: "b4_46", word: "狭い", reading: "せまい", romaji: "semai", meaning: "좁다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "この" }, { t: "部屋", r: "へや" }, { t: "は" }, { t: "狭", r: "せま" }, { t: "いです。" }], ko: "이 방은 좁습니다." } },
  { id: "b4_47", word: "強い", reading: "つよい", romaji: "tsuyoi", meaning: "강하다, 세다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "彼", r: "かれ" }, { t: "は" }, { t: "強", r: "つよ" }, { t: "いです。" }], ko: "그는 강합니다." } },
  { id: "b4_48", word: "弱い", reading: "よわい", romaji: "yowai", meaning: "약하다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "体", r: "からだ" }, { t: "が" }, { t: "弱", r: "よわ" }, { t: "いです。" }], ko: "몸이 약합니다." } },
  { id: "b4_49", word: "速い", reading: "はやい", romaji: "hayai", meaning: "빠르다(속도)", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "この" }, { t: "車", r: "くるま" }, { t: "は" }, { t: "速", r: "はや" }, { t: "いです。" }], ko: "이 차는 빠릅니다." } },
  { id: "b4_50", word: "遅い", reading: "おそい", romaji: "osoi", meaning: "느리다, 늦다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "バスが" }, { t: "遅", r: "おそ" }, { t: "いです。" }], ko: "버스가 느립니다." } },
  { id: "b4_51", word: "早い", reading: "はやい", romaji: "hayai", meaning: "이르다(시각)", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "朝", r: "あさ" }, { t: "が" }, { t: "早", r: "はや" }, { t: "いです。" }], ko: "아침이 이릅니다." } },
  { id: "b4_52", word: "古い", reading: "ふるい", romaji: "furui", meaning: "오래되다, 낡다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "この" }, { t: "家", r: "いえ" }, { t: "は" }, { t: "古", r: "ふる" }, { t: "いです。" }], ko: "이 집은 오래되었습니다." } },
  { id: "b4_53", word: "若い", reading: "わかい", romaji: "wakai", meaning: "젊다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "先生", r: "せんせい" }, { t: "は" }, { t: "若", r: "わか" }, { t: "いです。" }], ko: "선생님은 젊습니다." } },
  { id: "b4_54", word: "明るい", reading: "あかるい", romaji: "akarui", meaning: "밝다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "部屋", r: "へや" }, { t: "が" }, { t: "明", r: "あか" }, { t: "るいです。" }], ko: "방이 밝습니다." } },
  { id: "b4_55", word: "暗い", reading: "くらい", romaji: "kurai", meaning: "어둡다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "外", r: "そと" }, { t: "が" }, { t: "暗", r: "くら" }, { t: "いです。" }], ko: "밖이 어둡습니다." } },
  { id: "b4_56", word: "近い", reading: "ちかい", romaji: "chikai", meaning: "가깝다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "駅", r: "えき" }, { t: "が" }, { t: "近", r: "ちか" }, { t: "いです。" }], ko: "역이 가깝습니다." } },
  { id: "b4_57", word: "遠い", reading: "とおい", romaji: "tooi", meaning: "멀다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "学校", r: "がっこう" }, { t: "は" }, { t: "遠", r: "とお" }, { t: "いです。" }], ko: "학교는 멉니다." } },
  { id: "b4_58", word: "良い", reading: "よい", romaji: "yoi", meaning: "좋다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "天気", r: "てんき" }, { t: "が" }, { t: "良", r: "よ" }, { t: "いです。" }], ko: "날씨가 좋습니다." } },
  { id: "b4_59", word: "悪い", reading: "わるい", romaji: "warui", meaning: "나쁘다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "頭", r: "あたま" }, { t: "が" }, { t: "悪", r: "わる" }, { t: "いです。" }], ko: "머리가 나쁩니다." } },
  { id: "b4_60", word: "怖い", reading: "こわい", romaji: "kowai", meaning: "무섭다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "あの" }, { t: "犬", r: "いぬ" }, { t: "は" }, { t: "怖", r: "こわ" }, { t: "いです。" }], ko: "저 개는 무섭습니다." } },
  { id: "b4_61", word: "痛い", reading: "いたい", romaji: "itai", meaning: "아프다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "お" }, { t: "腹", r: "なか" }, { t: "が" }, { t: "痛", r: "いた" }, { t: "いです。" }], ko: "배가 아픕니다." } },
  { id: "b4_62", word: "易しい", reading: "やさしい", romaji: "yasashii", meaning: "쉽다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "この" }, { t: "問題", r: "もんだい" }, { t: "は" }, { t: "易", r: "やさ" }, { t: "しいです。" }], ko: "이 문제는 쉽습니다." } },
  { id: "b4_63", word: "優しい", reading: "やさしい", romaji: "yasashii", meaning: "상냥하다, 다정하다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "母", r: "はは" }, { t: "は" }, { t: "優", r: "やさ" }, { t: "しいです。" }], ko: "어머니는 상냥합니다." } },
  { id: "b4_64", word: "うるさい", reading: "うるさい", romaji: "urusai", meaning: "시끄럽다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "外", r: "そと" }, { t: "が" }, { t: "うるさいです。" }], ko: "밖이 시끄럽습니다." } },
  { id: "b4_65", word: "汚い", reading: "きたない", romaji: "kitanai", meaning: "더럽다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "手", r: "て" }, { t: "が" }, { t: "汚", r: "きたな" }, { t: "いです。" }], ko: "손이 더럽습니다." } },
  { id: "b4_66", word: "かわいい", reading: "かわいい", romaji: "kawaii", meaning: "귀엽다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "この" }, { t: "猫", r: "ねこ" }, { t: "はかわいいです。" }], ko: "이 고양이는 귀엽습니다." } },
  { id: "b4_67", word: "面白い", reading: "おもしろい", romaji: "omoshiroi", meaning: "재미있다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "この" }, { t: "本", r: "ほん" }, { t: "は" }, { t: "面白", r: "おもしろ" }, { t: "いです。" }], ko: "이 책은 재미있습니다." } },
  { id: "b4_68", word: "つまらない", reading: "つまらない", romaji: "tsumaranai", meaning: "지루하다, 시시하다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "映画", r: "えいが" }, { t: "がつまらないです。" }], ko: "영화가 지루합니다." } },
  { id: "b4_69", word: "重要", reading: "じゅうよう", romaji: "juuyou", meaning: "중요하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "重要", r: "じゅうよう" }, { t: "な" }, { t: "話", r: "はなし" }, { t: "です。" }], ko: "중요한 이야기입니다." } },
  { id: "b4_70", word: "大切", reading: "たいせつ", romaji: "taisetsu", meaning: "소중하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "大切", r: "たいせつ" }, { t: "な" }, { t: "友達", r: "ともだち" }, { t: "です。" }], ko: "소중한 친구입니다." } },
  { id: "b4_71", word: "大丈夫", reading: "だいじょうぶ", romaji: "daijoubu", meaning: "괜찮다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "もう" }, { t: "大丈夫", r: "だいじょうぶ" }, { t: "です。" }], ko: "이제 괜찮습니다." } },
  { id: "b4_72", word: "大変", reading: "たいへん", romaji: "taihen", meaning: "힘들다, 큰일이다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "仕事", r: "しごと" }, { t: "が" }, { t: "大変", r: "たいへん" }, { t: "です。" }], ko: "일이 힘듭니다." } },
  { id: "b4_73", word: "暇", reading: "ひま", romaji: "hima", meaning: "한가하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "今日", r: "きょう" }, { t: "は" }, { t: "暇", r: "ひま" }, { t: "です。" }], ko: "오늘은 한가합니다." } },
  { id: "b4_74", word: "簡単", reading: "かんたん", romaji: "kantan", meaning: "간단하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "簡単", r: "かんたん" }, { t: "な" }, { t: "料理", r: "りょうり" }, { t: "です。" }], ko: "간단한 요리입니다." } },
  { id: "b4_75", word: "親切", reading: "しんせつ", romaji: "shinsetsu", meaning: "친절하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "店員", r: "てんいん" }, { t: "が" }, { t: "親切", r: "しんせつ" }, { t: "です。" }], ko: "점원이 친절합니다." } },
  { id: "b4_76", word: "にぎやか", reading: "にぎやか", romaji: "nigiyaka", meaning: "번화하다, 활기차다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "この" }, { t: "町", r: "まち" }, { t: "はにぎやかです。" }], ko: "이 동네는 번화합니다." } },
  { id: "b4_77", word: "上手", reading: "じょうず", romaji: "jouzu", meaning: "잘하다, 능숙하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "歌", r: "うた" }, { t: "が" }, { t: "上手", r: "じょうず" }, { t: "です。" }], ko: "노래를 잘합니다." } },
  { id: "b4_78", word: "下手", reading: "へた", romaji: "heta", meaning: "서투르다, 못하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "絵", r: "え" }, { t: "が" }, { t: "下手", r: "へた" }, { t: "です。" }], ko: "그림을 못 그립니다." } },
  { id: "b4_79", word: "嫌い", reading: "きらい", romaji: "kirai", meaning: "싫어하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "虫", r: "むし" }, { t: "が" }, { t: "嫌", r: "きら" }, { t: "いです。" }], ko: "벌레를 싫어합니다." } },
  { id: "b4_80", word: "同じ", reading: "おなじ", romaji: "onaji", meaning: "같다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "私", r: "わたし" }, { t: "と" }, { t: "同", r: "おな" }, { t: "じです。" }], ko: "저와 같습니다." } },
  { id: "b4_81", word: "いろいろ", reading: "いろいろ", romaji: "iroiro", meaning: "여러 가지다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "いろいろな" }, { t: "国", r: "くに" }, { t: "に" }, { t: "行", r: "い" }, { t: "きました。" }], ko: "여러 나라에 갔습니다." } },
  { id: "b4_82", word: "特別", reading: "とくべつ", romaji: "tokubetsu", meaning: "특별하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "特別", r: "とくべつ" }, { t: "な" }, { t: "日", r: "ひ" }, { t: "です。" }], ko: "특별한 날입니다." } },
  { id: "b4_83", word: "必要", reading: "ひつよう", romaji: "hitsuyou", meaning: "필요하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "お" }, { t: "金", r: "かね" }, { t: "が" }, { t: "必要", r: "ひつよう" }, { t: "です。" }], ko: "돈이 필요합니다." } },
  { id: "b4_84", word: "安全", reading: "あんぜん", romaji: "anzen", meaning: "안전하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "ここは" }, { t: "安全", r: "あんぜん" }, { t: "です。" }], ko: "여기는 안전합니다." } },
  { id: "b4_85", word: "自由", reading: "じゆう", romaji: "jiyuu", meaning: "자유롭다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "自由", r: "じゆう" }, { t: "に" }, { t: "使", r: "つか" }, { t: "ってください。" }], ko: "자유롭게 쓰세요." } },
  { id: "b4_86", word: "丁寧", reading: "ていねい", romaji: "teinei", meaning: "정중하다, 꼼꼼하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "丁寧", r: "ていねい" }, { t: "に" }, { t: "書", r: "か" }, { t: "きます。" }], ko: "정성껏 씁니다." } },
  { id: "b4_87", word: "立派", reading: "りっぱ", romaji: "rippa", meaning: "훌륭하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "立派", r: "りっぱ" }, { t: "な" }, { t: "建物", r: "たてもの" }, { t: "です。" }], ko: "훌륭한 건물입니다." } },
  { id: "b4_88", word: "大事", reading: "だいじ", romaji: "daiji", meaning: "중요하다, 소중하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "大事", r: "だいじ" }, { t: "な" }, { t: "本", r: "ほん" }, { t: "です。" }], ko: "소중한 책입니다." } },
  { id: "b4_89", word: "結構", reading: "けっこう", romaji: "kekkou", meaning: "괜찮다, 충분하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "もう" }, { t: "結構", r: "けっこう" }, { t: "です。" }], ko: "이제 됐습니다." } },
  { id: "b4_90", word: "丈夫", reading: "じょうぶ", romaji: "joubu", meaning: "튼튼하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "丈夫", r: "じょうぶ" }, { t: "な" }, { t: "靴", r: "くつ" }, { t: "です。" }], ko: "튼튼한 신발입니다." } },
  { id: "b4_91", word: "暖かい", reading: "あたたかい", romaji: "atatakai", meaning: "따뜻하다(분위기·물건)", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "暖", r: "あたた" }, { t: "かい" }, { t: "部屋", r: "へや" }, { t: "です。" }], ko: "따뜻한 방입니다." } },
  { id: "b4_92", word: "厚い", reading: "あつい", romaji: "atsui", meaning: "두껍다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "厚", r: "あつ" }, { t: "い" }, { t: "本", r: "ほん" }, { t: "です。" }], ko: "두꺼운 책입니다." } },
  { id: "b4_93", word: "薄い", reading: "うすい", romaji: "usui", meaning: "얇다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "薄", r: "うす" }, { t: "い" }, { t: "紙", r: "かみ" }, { t: "です。" }], ko: "얇은 종이입니다." } },
  { id: "b4_94", word: "深い", reading: "ふかい", romaji: "fukai", meaning: "깊다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "この" }, { t: "川", r: "かわ" }, { t: "は" }, { t: "深", r: "ふか" }, { t: "いです。" }], ko: "이 강은 깊습니다." } },
  { id: "b4_95", word: "浅い", reading: "あさい", romaji: "asai", meaning: "얕다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "ここは" }, { t: "浅", r: "あさ" }, { t: "いです。" }], ko: "여기는 얕습니다." } },
  { id: "b4_96", word: "低い", reading: "ひくい", romaji: "hikui", meaning: "낮다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "天井", r: "てんじょう" }, { t: "が" }, { t: "低", r: "ひく" }, { t: "いです。" }], ko: "천장이 낮습니다." } },
  { id: "b4_97", word: "うれしい", reading: "うれしい", romaji: "ureshii", meaning: "기쁘다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "とてもうれしいです。" }], ko: "매우 기쁩니다." } },
  { id: "b4_98", word: "悲しい", reading: "かなしい", romaji: "kanashii", meaning: "슬프다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "話", r: "はなし" }, { t: "を" }, { t: "聞", r: "き" }, { t: "いて" }, { t: "悲", r: "かな" }, { t: "しいです。" }], ko: "이야기를 듣고 슬픕니다." } },
  { id: "b4_99", word: "寂しい", reading: "さびしい", romaji: "sabishii", meaning: "외롭다, 쓸쓸하다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "一人", r: "ひとり" }, { t: "で" }, { t: "寂", r: "さび" }, { t: "しいです。" }], ko: "혼자라서 외롭습니다." } },
  { id: "b4_100", word: "欲しい", reading: "ほしい", romaji: "hoshii", meaning: "갖고 싶다, 원하다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "新", r: "あたら" }, { t: "しい" }, { t: "車", r: "くるま" }, { t: "が" }, { t: "欲", r: "ほ" }, { t: "しいです。" }], ko: "새 차를 갖고 싶습니다." } },
  { id: "b4_101", word: "眠い", reading: "ねむい", romaji: "nemui", meaning: "졸리다", pos: "い형용사", category: "adjective",
    example: { tokens: [{ t: "とても" }, { t: "眠", r: "ねむ" }, { t: "いです。" }], ko: "매우 졸립니다." } },
  { id: "b4_102", word: "便利", reading: "べんり", romaji: "benri", meaning: "편리하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "この" }, { t: "店", r: "みせ" }, { t: "は" }, { t: "便利", r: "べんり" }, { t: "です。" }], ko: "이 가게는 편리합니다." } },
  { id: "b4_103", word: "不便", reading: "ふべん", romaji: "fuben", meaning: "불편하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "ここは" }, { t: "不便", r: "ふべん" }, { t: "です。" }], ko: "여기는 불편합니다." } },
  { id: "b4_104", word: "綺麗", reading: "きれい", romaji: "kirei", meaning: "예쁘다, 깨끗하다", pos: "な형용사", category: "adjective",
    example: { tokens: [{ t: "部屋", r: "へや" }, { t: "が" }, { t: "綺麗", r: "きれい" }, { t: "です。" }], ko: "방이 깨끗합니다." } },

  // ── 색·모양 (color) ───────────────────────────────
  { id: "b4_105", word: "黄色", reading: "きいろ", romaji: "kiiro", meaning: "노란색", pos: "명사", category: "color",
    example: { tokens: [{ t: "黄色", r: "きいろ" }, { t: "い" }, { t: "花", r: "はな" }, { t: "です。" }], ko: "노란 꽃입니다." } },
  { id: "b4_106", word: "茶色", reading: "ちゃいろ", romaji: "chairo", meaning: "갈색", pos: "명사", category: "color",
    example: { tokens: [{ t: "茶色", r: "ちゃいろ" }, { t: "の" }, { t: "鞄", r: "かばん" }, { t: "です。" }], ko: "갈색 가방입니다." } },
  { id: "b4_107", word: "緑", reading: "みどり", romaji: "midori", meaning: "초록색", pos: "명사", category: "color",
    example: { tokens: [{ t: "緑", r: "みどり" }, { t: "の" }, { t: "木", r: "き" }, { t: "がきれいです。" }], ko: "초록 나무가 예쁩니다." } },
  { id: "b4_108", word: "紫", reading: "むらさき", romaji: "murasaki", meaning: "보라색", pos: "명사", category: "color",
    example: { tokens: [{ t: "紫", r: "むらさき" }, { t: "の" }, { t: "服", r: "ふく" }, { t: "です。" }], ko: "보라색 옷입니다." } },
  { id: "b4_109", word: "ピンク", reading: "ぴんく", romaji: "pinku", meaning: "분홍색", pos: "명사", category: "color",
    example: { tokens: [{ t: "ピンクの" }, { t: "傘", r: "かさ" }, { t: "です。" }], ko: "분홍색 우산입니다." } },
  { id: "b4_110", word: "灰色", reading: "はいいろ", romaji: "haiiro", meaning: "회색", pos: "명사", category: "color",
    example: { tokens: [{ t: "灰色", r: "はいいろ" }, { t: "の" }, { t: "猫", r: "ねこ" }, { t: "です。" }], ko: "회색 고양이입니다." } },
  { id: "b4_111", word: "オレンジ", reading: "おれんじ", romaji: "orenji", meaning: "주황색", pos: "명사", category: "color",
    example: { tokens: [{ t: "オレンジの" }, { t: "服", r: "ふく" }, { t: "を" }, { t: "着", r: "き" }, { t: "ます。" }], ko: "주황색 옷을 입습니다." } },
  { id: "b4_112", word: "金色", reading: "きんいろ", romaji: "kiniro", meaning: "금색", pos: "명사", category: "color",
    example: { tokens: [{ t: "金色", r: "きんいろ" }, { t: "の" }, { t: "時計", r: "とけい" }, { t: "です。" }], ko: "금색 시계입니다." } },
  { id: "b4_113", word: "銀色", reading: "ぎんいろ", romaji: "giniro", meaning: "은색", pos: "명사", category: "color",
    example: { tokens: [{ t: "銀色", r: "ぎんいろ" }, { t: "の" }, { t: "車", r: "くるま" }, { t: "です。" }], ko: "은색 차입니다." } },
  { id: "b4_114", word: "色", reading: "いろ", romaji: "iro", meaning: "색, 색깔", pos: "명사", category: "color",
    example: { tokens: [{ t: "好", r: "す" }, { t: "きな" }, { t: "色", r: "いろ" }, { t: "は" }, { t: "何", r: "なに" }, { t: "ですか。" }], ko: "좋아하는 색은 무엇입니까?" } },
  { id: "b4_115", word: "形", reading: "かたち", romaji: "katachi", meaning: "모양, 형태", pos: "명사", category: "color",
    example: { tokens: [{ t: "面白", r: "おもしろ" }, { t: "い" }, { t: "形", r: "かたち" }, { t: "です。" }], ko: "재미있는 모양입니다." } },
  { id: "b4_116", word: "四角", reading: "しかく", romaji: "shikaku", meaning: "사각형, 네모", pos: "명사", category: "color",
    example: { tokens: [{ t: "四角", r: "しかく" }, { t: "い" }, { t: "箱", r: "はこ" }, { t: "です。" }], ko: "네모난 상자입니다." } },
  { id: "b4_117", word: "三角", reading: "さんかく", romaji: "sankaku", meaning: "삼각형", pos: "명사", category: "color",
    example: { tokens: [{ t: "三角", r: "さんかく" }, { t: "の" }, { t: "形", r: "かたち" }, { t: "です。" }], ko: "삼각형 모양입니다." } },
  { id: "b4_118", word: "星", reading: "ほし", romaji: "hoshi", meaning: "별, 별 모양", pos: "명사", category: "color",
    example: { tokens: [{ t: "星", r: "ほし" }, { t: "の" }, { t: "形", r: "かたち" }, { t: "です。" }], ko: "별 모양입니다." } },
  { id: "b4_119", word: "点", reading: "てん", romaji: "ten", meaning: "점", pos: "명사", category: "color",
    example: { tokens: [{ t: "白", r: "しろ" }, { t: "い" }, { t: "点", r: "てん" }, { t: "があります。" }], ko: "하얀 점이 있습니다." } },
  { id: "b4_120", word: "線", reading: "せん", romaji: "sen", meaning: "선, 줄", pos: "명사", category: "color",
    example: { tokens: [{ t: "赤", r: "あか" }, { t: "い" }, { t: "線", r: "せん" }, { t: "を" }, { t: "引", r: "ひ" }, { t: "きます。" }], ko: "빨간 선을 긋습니다." } },
  { id: "b4_121", word: "明るい色", reading: "あかるいいろ", romaji: "akarui iro", meaning: "밝은 색", pos: "명사", category: "color",
    example: { tokens: [{ t: "明", r: "あか" }, { t: "るい" }, { t: "色", r: "いろ" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "밝은 색을 좋아합니다." } },
  { id: "b4_122", word: "濃い", reading: "こい", romaji: "koi", meaning: "(색이) 진하다", pos: "い형용사", category: "color",
    example: { tokens: [{ t: "濃", r: "こ" }, { t: "い" }, { t: "青", r: "あお" }, { t: "です。" }], ko: "진한 파랑입니다." } },
  { id: "b4_123", word: "丸", reading: "まる", romaji: "maru", meaning: "동그라미, 원", pos: "명사", category: "color",
    example: { tokens: [{ t: "丸", r: "まる" }, { t: "を" }, { t: "書", r: "か" }, { t: "きます。" }], ko: "동그라미를 그립니다." } },
  { id: "b4_124", word: "光", reading: "ひかり", romaji: "hikari", meaning: "빛", pos: "명사", category: "color",
    example: { tokens: [{ t: "星", r: "ほし" }, { t: "の" }, { t: "光", r: "ひかり" }, { t: "がきれいです。" }], ko: "별빛이 예쁩니다." } },
];
