import type { Word } from "./types";

// JLPT N5 확장 단어 — 음식·자연 (batch B1)
export const VOCAB_B1: Word[] = [
  // ===== FOOD (음식·식사) =====
  { id: "b1_1", word: "りんご", reading: "りんご", romaji: "ringo", meaning: "사과", pos: "명사", category: "food",
    example: { tokens: [{ t: "赤", r: "あか" }, { t: "い" }, { t: "りんごを" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "빨간 사과를 먹습니다." } },
  { id: "b1_2", word: "みかん", reading: "みかん", romaji: "mikan", meaning: "귤", pos: "명사", category: "food",
    example: { tokens: [{ t: "冬", r: "ふゆ" }, { t: "は" }, { t: "みかんが" }, { t: "おいしいです。" }], ko: "겨울에는 귤이 맛있습니다." } },
  { id: "b1_3", word: "バナナ", reading: "バナナ", romaji: "banana", meaning: "바나나", pos: "명사", category: "food",
    example: { tokens: [{ t: "毎朝", r: "まいあさ" }, { t: "バナナを" }, { t: "一", r: "ひと" }, { t: "つ" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "매일 아침 바나나를 하나 먹습니다." } },
  { id: "b1_4", word: "いちご", reading: "いちご", romaji: "ichigo", meaning: "딸기", pos: "명사", category: "food",
    example: { tokens: [{ t: "いちごの" }, { t: "ケーキが" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "딸기 케이크를 좋아합니다." } },
  { id: "b1_5", word: "すいか", reading: "すいか", romaji: "suika", meaning: "수박", pos: "명사", category: "food",
    example: { tokens: [{ t: "夏", r: "なつ" }, { t: "に" }, { t: "すいかを" }, { t: "食", r: "た" }, { t: "べました。" }], ko: "여름에 수박을 먹었습니다." } },
  { id: "b1_6", word: "ぶどう", reading: "ぶどう", romaji: "budou", meaning: "포도", pos: "명사", category: "food",
    example: { tokens: [{ t: "ぶどうは" }, { t: "甘", r: "あま" }, { t: "いです。" }], ko: "포도는 답니다." } },
  { id: "b1_7", word: "米", reading: "こめ", romaji: "kome", meaning: "쌀", pos: "명사", category: "food",
    example: { tokens: [{ t: "日本", r: "にほん" }, { t: "の" }, { t: "米", r: "こめ" }, { t: "は" }, { t: "おいしいです。" }], ko: "일본의 쌀은 맛있습니다." } },
  { id: "b1_8", word: "お菓子", reading: "おかし", romaji: "okashi", meaning: "과자", pos: "명사", category: "food",
    example: { tokens: [{ t: "子供", r: "こども" }, { t: "は" }, { t: "お菓子", r: "おかし" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "아이는 과자를 좋아합니다." } },
  { id: "b1_9", word: "飴", reading: "あめ", romaji: "ame", meaning: "사탕", pos: "명사", category: "food",
    example: { tokens: [{ t: "飴", r: "あめ" }, { t: "を" }, { t: "一", r: "ひと" }, { t: "つ" }, { t: "ください。" }], ko: "사탕을 하나 주세요." } },
  { id: "b1_10", word: "チョコレート", reading: "チョコレート", romaji: "chokoreeto", meaning: "초콜릿", pos: "명사", category: "food",
    example: { tokens: [{ t: "甘", r: "あま" }, { t: "い" }, { t: "チョコレートが" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "단 초콜릿을 좋아합니다." } },
  { id: "b1_11", word: "アイス", reading: "アイス", romaji: "aisu", meaning: "아이스크림", pos: "명사", category: "food",
    example: { tokens: [{ t: "暑", r: "あつ" }, { t: "いので" }, { t: "アイスを" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "더워서 아이스크림을 먹습니다." } },
  { id: "b1_12", word: "ケーキ", reading: "ケーキ", romaji: "keeki", meaning: "케이크", pos: "명사", category: "food",
    example: { tokens: [{ t: "誕生日", r: "たんじょうび" }, { t: "に" }, { t: "ケーキを" }, { t: "食", r: "た" }, { t: "べました。" }], ko: "생일에 케이크를 먹었습니다." } },
  { id: "b1_13", word: "砂糖", reading: "さとう", romaji: "satou", meaning: "설탕", pos: "명사", category: "food",
    example: { tokens: [{ t: "コーヒーに" }, { t: "砂糖", r: "さとう" }, { t: "を" }, { t: "入", r: "い" }, { t: "れます。" }], ko: "커피에 설탕을 넣습니다." } },
  { id: "b1_14", word: "塩", reading: "しお", romaji: "shio", meaning: "소금", pos: "명사", category: "food",
    example: { tokens: [{ t: "スープに" }, { t: "塩", r: "しお" }, { t: "を" }, { t: "入", r: "い" }, { t: "れます。" }], ko: "수프에 소금을 넣습니다." } },
  { id: "b1_15", word: "醤油", reading: "しょうゆ", romaji: "shouyu", meaning: "간장", pos: "명사", category: "food",
    example: { tokens: [{ t: "寿司", r: "すし" }, { t: "に" }, { t: "醤油", r: "しょうゆ" }, { t: "を" }, { t: "つけます。" }], ko: "초밥에 간장을 찍습니다." } },
  { id: "b1_16", word: "味噌", reading: "みそ", romaji: "miso", meaning: "된장", pos: "명사", category: "food",
    example: { tokens: [{ t: "朝", r: "あさ" }, { t: "は" }, { t: "味噌", r: "みそ" }, { t: "の" }, { t: "スープを" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "아침에는 된장국을 마십니다." } },
  { id: "b1_17", word: "油", reading: "あぶら", romaji: "abura", meaning: "기름", pos: "명사", category: "food",
    example: { tokens: [{ t: "フライパンに" }, { t: "油", r: "あぶら" }, { t: "を" }, { t: "入", r: "い" }, { t: "れます。" }], ko: "프라이팬에 기름을 넣습니다." } },
  { id: "b1_18", word: "お酒", reading: "おさけ", romaji: "osake", meaning: "술", pos: "명사", category: "food",
    example: { tokens: [{ t: "父", r: "ちち" }, { t: "は" }, { t: "お酒", r: "おさけ" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "아버지는 술을 좋아합니다." } },
  { id: "b1_19", word: "ビール", reading: "ビール", romaji: "biiru", meaning: "맥주", pos: "명사", category: "food",
    example: { tokens: [{ t: "冷", r: "つめ" }, { t: "たい" }, { t: "ビールを" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "차가운 맥주를 마십니다." } },
  { id: "b1_20", word: "ジュース", reading: "ジュース", romaji: "juusu", meaning: "주스", pos: "명사", category: "food",
    example: { tokens: [{ t: "オレンジジュースを" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "오렌지 주스를 마십니다." } },
  { id: "b1_21", word: "コーヒー", reading: "コーヒー", romaji: "koohii", meaning: "커피", pos: "명사", category: "food",
    example: { tokens: [{ t: "朝", r: "あさ" }, { t: "に" }, { t: "コーヒーを" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "아침에 커피를 마십니다." } },
  { id: "b1_22", word: "紅茶", reading: "こうちゃ", romaji: "koucha", meaning: "홍차", pos: "명사", category: "food",
    example: { tokens: [{ t: "母", r: "はは" }, { t: "は" }, { t: "紅茶", r: "こうちゃ" }, { t: "を" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "어머니는 홍차를 마십니다." } },
  { id: "b1_23", word: "食べ物", reading: "たべもの", romaji: "tabemono", meaning: "음식, 먹을 것", pos: "명사", category: "food",
    example: { tokens: [{ t: "好", r: "す" }, { t: "きな" }, { t: "食", r: "た" }, { t: "べ" }, { t: "物", r: "もの" }, { t: "は" }, { t: "何", r: "なに" }, { t: "ですか。" }], ko: "좋아하는 음식은 무엇입니까?" } },
  { id: "b1_24", word: "飲み物", reading: "のみもの", romaji: "nomimono", meaning: "음료, 마실 것", pos: "명사", category: "food",
    example: { tokens: [{ t: "飲", r: "の" }, { t: "み" }, { t: "物", r: "もの" }, { t: "は" }, { t: "何", r: "なに" }, { t: "が" }, { t: "いいですか。" }], ko: "음료는 무엇이 좋습니까?" } },
  { id: "b1_25", word: "朝ご飯", reading: "あさごはん", romaji: "asagohan", meaning: "아침밥", pos: "명사", category: "food",
    example: { tokens: [{ t: "朝", r: "あさ" }, { t: "ご" }, { t: "飯", r: "はん" }, { t: "を" }, { t: "食", r: "た" }, { t: "べました。" }], ko: "아침밥을 먹었습니다." } },
  { id: "b1_26", word: "昼ご飯", reading: "ひるごはん", romaji: "hirugohan", meaning: "점심밥", pos: "명사", category: "food",
    example: { tokens: [{ t: "昼", r: "ひる" }, { t: "ご" }, { t: "飯", r: "はん" }, { t: "は" }, { t: "うどんです。" }], ko: "점심밥은 우동입니다." } },
  { id: "b1_27", word: "晩ご飯", reading: "ばんごはん", romaji: "bangohan", meaning: "저녁밥", pos: "명사", category: "food",
    example: { tokens: [{ t: "晩", r: "ばん" }, { t: "ご" }, { t: "飯", r: "はん" }, { t: "は" }, { t: "家", r: "いえ" }, { t: "で" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "저녁밥은 집에서 먹습니다." } },
  { id: "b1_28", word: "弁当", reading: "べんとう", romaji: "bentou", meaning: "도시락", pos: "명사", category: "food",
    example: { tokens: [{ t: "弁当", r: "べんとう" }, { t: "を" }, { t: "買", r: "か" }, { t: "いました。" }], ko: "도시락을 샀습니다." } },
  { id: "b1_29", word: "料理", reading: "りょうり", romaji: "ryouri", meaning: "요리", pos: "명사", category: "food",
    example: { tokens: [{ t: "母", r: "はは" }, { t: "の" }, { t: "料理", r: "りょうり" }, { t: "は" }, { t: "おいしいです。" }], ko: "어머니의 요리는 맛있습니다." } },
  { id: "b1_30", word: "味", reading: "あじ", romaji: "aji", meaning: "맛", pos: "명사", category: "food",
    example: { tokens: [{ t: "この" }, { t: "スープは" }, { t: "味", r: "あじ" }, { t: "が" }, { t: "いいです。" }], ko: "이 수프는 맛이 좋습니다." } },
  { id: "b1_31", word: "おかず", reading: "おかず", romaji: "okazu", meaning: "반찬", pos: "명사", category: "food",
    example: { tokens: [{ t: "今日", r: "きょう" }, { t: "の" }, { t: "おかずは" }, { t: "魚", r: "さかな" }, { t: "です。" }], ko: "오늘의 반찬은 생선입니다." } },
  { id: "b1_32", word: "スープ", reading: "スープ", romaji: "suupu", meaning: "수프, 국", pos: "명사", category: "food",
    example: { tokens: [{ t: "温", r: "あたた" }, { t: "かい" }, { t: "スープを" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "따뜻한 수프를 마십니다." } },
  { id: "b1_33", word: "サラダ", reading: "サラダ", romaji: "sarada", meaning: "샐러드", pos: "명사", category: "food",
    example: { tokens: [{ t: "野菜", r: "やさい" }, { t: "の" }, { t: "サラダを" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "채소 샐러드를 먹습니다." } },
  { id: "b1_34", word: "豆腐", reading: "とうふ", romaji: "toufu", meaning: "두부", pos: "명사", category: "food",
    example: { tokens: [{ t: "味噌", r: "みそ" }, { t: "の" }, { t: "スープに" }, { t: "豆腐", r: "とうふ" }, { t: "を" }, { t: "入", r: "い" }, { t: "れます。" }], ko: "된장국에 두부를 넣습니다." } },
  { id: "b1_35", word: "豚肉", reading: "ぶたにく", romaji: "butaniku", meaning: "돼지고기", pos: "명사", category: "food",
    example: { tokens: [{ t: "豚肉", r: "ぶたにく" }, { t: "を" }, { t: "買", r: "か" }, { t: "いました。" }], ko: "돼지고기를 샀습니다." } },
  { id: "b1_36", word: "牛肉", reading: "ぎゅうにく", romaji: "gyuuniku", meaning: "소고기", pos: "명사", category: "food",
    example: { tokens: [{ t: "牛肉", r: "ぎゅうにく" }, { t: "は" }, { t: "高", r: "たか" }, { t: "いです。" }], ko: "소고기는 비쌉니다." } },
  { id: "b1_37", word: "鶏肉", reading: "とりにく", romaji: "toriniku", meaning: "닭고기", pos: "명사", category: "food",
    example: { tokens: [{ t: "鶏肉", r: "とりにく" }, { t: "の" }, { t: "料理", r: "りょうり" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "닭고기 요리를 좋아합니다." } },
  { id: "b1_38", word: "海老", reading: "えび", romaji: "ebi", meaning: "새우", pos: "명사", category: "food",
    example: { tokens: [{ t: "海老", r: "えび" }, { t: "の" }, { t: "天", r: "てん" }, { t: "ぷらを" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "새우 튀김을 먹습니다." } },
  { id: "b1_39", word: "寿司", reading: "すし", romaji: "sushi", meaning: "초밥", pos: "명사", category: "food",
    example: { tokens: [{ t: "週末", r: "しゅうまつ" }, { t: "に" }, { t: "寿司", r: "すし" }, { t: "を" }, { t: "食", r: "た" }, { t: "べました。" }], ko: "주말에 초밥을 먹었습니다." } },
  { id: "b1_40", word: "天ぷら", reading: "てんぷら", romaji: "tenpura", meaning: "튀김", pos: "명사", category: "food",
    example: { tokens: [{ t: "天", r: "てん" }, { t: "ぷらは" }, { t: "おいしいです。" }], ko: "튀김은 맛있습니다." } },
  { id: "b1_41", word: "そば", reading: "そば", romaji: "soba", meaning: "소바, 메밀국수", pos: "명사", category: "food",
    example: { tokens: [{ t: "昼", r: "ひる" }, { t: "に" }, { t: "そばを" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "점심에 소바를 먹습니다." } },
  { id: "b1_42", word: "うどん", reading: "うどん", romaji: "udon", meaning: "우동", pos: "명사", category: "food",
    example: { tokens: [{ t: "温", r: "あたた" }, { t: "かい" }, { t: "うどんが" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "따뜻한 우동을 좋아합니다." } },
  { id: "b1_43", word: "カレー", reading: "カレー", romaji: "karee", meaning: "카레", pos: "명사", category: "food",
    example: { tokens: [{ t: "今夜", r: "こんや" }, { t: "は" }, { t: "カレーを" }, { t: "作", r: "つく" }, { t: "ります。" }], ko: "오늘 밤은 카레를 만듭니다." } },
  { id: "b1_44", word: "ラーメン", reading: "ラーメン", romaji: "raamen", meaning: "라멘", pos: "명사", category: "food",
    example: { tokens: [{ t: "この" }, { t: "店", r: "みせ" }, { t: "の" }, { t: "ラーメンは" }, { t: "有名", r: "ゆうめい" }, { t: "です。" }], ko: "이 가게의 라멘은 유명합니다." } },
  { id: "b1_45", word: "餅", reading: "もち", romaji: "mochi", meaning: "떡", pos: "명사", category: "food",
    example: { tokens: [{ t: "お" }, { t: "正月", r: "しょうがつ" }, { t: "に" }, { t: "餅", r: "もち" }, { t: "を" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "설날에 떡을 먹습니다." } },
  { id: "b1_46", word: "パスタ", reading: "パスタ", romaji: "pasuta", meaning: "파스타", pos: "명사", category: "food",
    example: { tokens: [{ t: "昼", r: "ひる" }, { t: "に" }, { t: "パスタを" }, { t: "食", r: "た" }, { t: "べました。" }], ko: "점심에 파스타를 먹었습니다." } },
  { id: "b1_47", word: "サンドイッチ", reading: "サンドイッチ", romaji: "sandoicchi", meaning: "샌드위치", pos: "명사", category: "food",
    example: { tokens: [{ t: "公園", r: "こうえん" }, { t: "で" }, { t: "サンドイッチを" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "공원에서 샌드위치를 먹습니다." } },
  { id: "b1_48", word: "ハンバーガー", reading: "ハンバーガー", romaji: "hanbaagaa", meaning: "햄버거", pos: "명사", category: "food",
    example: { tokens: [{ t: "ハンバーガーと" }, { t: "ジュースを" }, { t: "ください。" }], ko: "햄버거와 주스를 주세요." } },
  { id: "b1_49", word: "ピザ", reading: "ピザ", romaji: "piza", meaning: "피자", pos: "명사", category: "food",
    example: { tokens: [{ t: "友達", r: "ともだち" }, { t: "と" }, { t: "ピザを" }, { t: "食", r: "た" }, { t: "べました。" }], ko: "친구와 피자를 먹었습니다." } },
  { id: "b1_50", word: "卵焼き", reading: "たまごやき", romaji: "tamagoyaki", meaning: "계란말이", pos: "명사", category: "food",
    example: { tokens: [{ t: "朝", r: "あさ" }, { t: "に" }, { t: "卵焼", r: "たまごや" }, { t: "きを" }, { t: "作", r: "つく" }, { t: "ります。" }], ko: "아침에 계란말이를 만듭니다." } },
  { id: "b1_51", word: "苦い", reading: "にがい", romaji: "nigai", meaning: "쓰다", pos: "い형용사", category: "food",
    example: { tokens: [{ t: "この" }, { t: "コーヒーは" }, { t: "苦", r: "にが" }, { t: "いです。" }], ko: "이 커피는 씁니다." } },
  { id: "b1_52", word: "酸っぱい", reading: "すっぱい", romaji: "suppai", meaning: "시다", pos: "い형용사", category: "food",
    example: { tokens: [{ t: "この" }, { t: "みかんは" }, { t: "酸", r: "す" }, { t: "っぱいです。" }], ko: "이 귤은 십니다." } },
  { id: "b1_53", word: "熱い", reading: "あつい", romaji: "atsui", meaning: "뜨겁다", pos: "い형용사", category: "food",
    example: { tokens: [{ t: "熱", r: "あつ" }, { t: "い" }, { t: "お" }, { t: "茶", r: "ちゃ" }, { t: "を" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "뜨거운 차를 마십니다." } },
  { id: "b1_54", word: "冷たい", reading: "つめたい", romaji: "tsumetai", meaning: "차갑다", pos: "い형용사", category: "food",
    example: { tokens: [{ t: "冷", r: "つめ" }, { t: "たい" }, { t: "水", r: "みず" }, { t: "を" }, { t: "ください。" }], ko: "차가운 물을 주세요." } },
  { id: "b1_55", word: "お皿", reading: "おさら", romaji: "osara", meaning: "접시", pos: "명사", category: "food",
    example: { tokens: [{ t: "お" }, { t: "皿", r: "さら" }, { t: "を" }, { t: "洗", r: "あら" }, { t: "います。" }], ko: "접시를 씻습니다." } },
  { id: "b1_56", word: "箸", reading: "はし", romaji: "hashi", meaning: "젓가락", pos: "명사", category: "food",
    example: { tokens: [{ t: "箸", r: "はし" }, { t: "で" }, { t: "ご" }, { t: "飯", r: "はん" }, { t: "を" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "젓가락으로 밥을 먹습니다." } },
  { id: "b1_57", word: "茶碗", reading: "ちゃわん", romaji: "chawan", meaning: "밥공기", pos: "명사", category: "food",
    example: { tokens: [{ t: "茶碗", r: "ちゃわん" }, { t: "に" }, { t: "ご" }, { t: "飯", r: "はん" }, { t: "を" }, { t: "入", r: "い" }, { t: "れます。" }], ko: "밥공기에 밥을 담습니다." } },
  { id: "b1_58", word: "コップ", reading: "コップ", romaji: "koppu", meaning: "컵", pos: "명사", category: "food",
    example: { tokens: [{ t: "コップで" }, { t: "水", r: "みず" }, { t: "を" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "컵으로 물을 마십니다." } },
  { id: "b1_59", word: "フォーク", reading: "フォーク", romaji: "fooku", meaning: "포크", pos: "명사", category: "food",
    example: { tokens: [{ t: "フォークで" }, { t: "ケーキを" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "포크로 케이크를 먹습니다." } },
  { id: "b1_60", word: "スプーン", reading: "スプーン", romaji: "supuun", meaning: "숟가락", pos: "명사", category: "food",
    example: { tokens: [{ t: "スプーンで" }, { t: "スープを" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "숟가락으로 수프를 먹습니다." } },
  { id: "b1_61", word: "ナイフ", reading: "ナイフ", romaji: "naifu", meaning: "나이프, 칼", pos: "명사", category: "food",
    example: { tokens: [{ t: "ナイフで" }, { t: "肉", r: "にく" }, { t: "を" }, { t: "切", r: "き" }, { t: "ります。" }], ko: "나이프로 고기를 자릅니다." } },
  { id: "b1_62", word: "レストラン", reading: "レストラン", romaji: "resutoran", meaning: "레스토랑", pos: "명사", category: "food",
    example: { tokens: [{ t: "駅", r: "えき" }, { t: "の" }, { t: "近", r: "ちか" }, { t: "くに" }, { t: "レストランが" }, { t: "あります。" }], ko: "역 근처에 레스토랑이 있습니다." } },
  { id: "b1_63", word: "喫茶店", reading: "きっさてん", romaji: "kissaten", meaning: "찻집, 카페", pos: "명사", category: "food",
    example: { tokens: [{ t: "喫茶店", r: "きっさてん" }, { t: "で" }, { t: "コーヒーを" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "찻집에서 커피를 마십니다." } },
  { id: "b1_64", word: "メニュー", reading: "メニュー", romaji: "menyuu", meaning: "메뉴", pos: "명사", category: "food",
    example: { tokens: [{ t: "メニューを" }, { t: "見", r: "み" }, { t: "せてください。" }], ko: "메뉴를 보여 주세요." } },
  { id: "b1_65", word: "ピーマン", reading: "ピーマン", romaji: "piiman", meaning: "피망", pos: "명사", category: "food",
    example: { tokens: [{ t: "子供", r: "こども" }, { t: "は" }, { t: "ピーマンが" }, { t: "嫌", r: "きら" }, { t: "いです。" }], ko: "아이는 피망을 싫어합니다." } },
  { id: "b1_66", word: "玉ねぎ", reading: "たまねぎ", romaji: "tamanegi", meaning: "양파", pos: "명사", category: "food",
    example: { tokens: [{ t: "玉", r: "たま" }, { t: "ねぎを" }, { t: "切", r: "き" }, { t: "ります。" }], ko: "양파를 자릅니다." } },
  { id: "b1_67", word: "じゃがいも", reading: "じゃがいも", romaji: "jagaimo", meaning: "감자", pos: "명사", category: "food",
    example: { tokens: [{ t: "カレーに" }, { t: "じゃがいもを" }, { t: "入", r: "い" }, { t: "れます。" }], ko: "카레에 감자를 넣습니다." } },
  { id: "b1_68", word: "にんじん", reading: "にんじん", romaji: "ninjin", meaning: "당근", pos: "명사", category: "food",
    example: { tokens: [{ t: "にんじんは" }, { t: "赤", r: "あか" }, { t: "いです。" }], ko: "당근은 빨갛습니다." } },
  { id: "b1_69", word: "トマト", reading: "トマト", romaji: "tomato", meaning: "토마토", pos: "명사", category: "food",
    example: { tokens: [{ t: "サラダに" }, { t: "トマトを" }, { t: "入", r: "い" }, { t: "れます。" }], ko: "샐러드에 토마토를 넣습니다." } },

  // ===== NATURE (자연·날씨·동식물) =====
  { id: "b1_70", word: "木", reading: "き", romaji: "ki", meaning: "나무", pos: "명사", category: "nature",
    example: { tokens: [{ t: "公園", r: "こうえん" }, { t: "に" }, { t: "大", r: "おお" }, { t: "きな" }, { t: "木", r: "き" }, { t: "が" }, { t: "あります。" }], ko: "공원에 큰 나무가 있습니다." } },
  { id: "b1_71", word: "川", reading: "かわ", romaji: "kawa", meaning: "강", pos: "명사", category: "nature",
    example: { tokens: [{ t: "川", r: "かわ" }, { t: "で" }, { t: "魚", r: "さかな" }, { t: "を" }, { t: "見", r: "み" }, { t: "ました。" }], ko: "강에서 물고기를 봤습니다." } },
  { id: "b1_72", word: "池", reading: "いけ", romaji: "ike", meaning: "연못", pos: "명사", category: "nature",
    example: { tokens: [{ t: "池", r: "いけ" }, { t: "に" }, { t: "鳥", r: "とり" }, { t: "が" }, { t: "います。" }], ko: "연못에 새가 있습니다." } },
  { id: "b1_73", word: "森", reading: "もり", romaji: "mori", meaning: "숲", pos: "명사", category: "nature",
    example: { tokens: [{ t: "森", r: "もり" }, { t: "の" }, { t: "中", r: "なか" }, { t: "は" }, { t: "静", r: "しず" }, { t: "かです。" }], ko: "숲 속은 조용합니다." } },
  { id: "b1_74", word: "林", reading: "はやし", romaji: "hayashi", meaning: "수풀, 작은 숲", pos: "명사", category: "nature",
    example: { tokens: [{ t: "山", r: "やま" }, { t: "に" }, { t: "林", r: "はやし" }, { t: "が" }, { t: "あります。" }], ko: "산에 작은 숲이 있습니다." } },
  { id: "b1_75", word: "石", reading: "いし", romaji: "ishi", meaning: "돌", pos: "명사", category: "nature",
    example: { tokens: [{ t: "川", r: "かわ" }, { t: "に" }, { t: "大", r: "おお" }, { t: "きな" }, { t: "石", r: "いし" }, { t: "が" }, { t: "あります。" }], ko: "강에 큰 돌이 있습니다." } },
  { id: "b1_76", word: "土", reading: "つち", romaji: "tsuchi", meaning: "흙", pos: "명사", category: "nature",
    example: { tokens: [{ t: "土", r: "つち" }, { t: "に" }, { t: "花", r: "はな" }, { t: "を" }, { t: "植", r: "う" }, { t: "えます。" }], ko: "흙에 꽃을 심습니다." } },
  { id: "b1_77", word: "草", reading: "くさ", romaji: "kusa", meaning: "풀", pos: "명사", category: "nature",
    example: { tokens: [{ t: "庭", r: "にわ" }, { t: "に" }, { t: "草", r: "くさ" }, { t: "が" }, { t: "あります。" }], ko: "정원에 풀이 있습니다." } },
  { id: "b1_78", word: "葉", reading: "は", romaji: "ha", meaning: "잎", pos: "명사", category: "nature",
    example: { tokens: [{ t: "秋", r: "あき" }, { t: "に" }, { t: "葉", r: "は" }, { t: "が" }, { t: "赤", r: "あか" }, { t: "くなります。" }], ko: "가을에 잎이 빨개집니다." } },
  { id: "b1_79", word: "太陽", reading: "たいよう", romaji: "taiyou", meaning: "태양", pos: "명사", category: "nature",
    example: { tokens: [{ t: "太陽", r: "たいよう" }, { t: "が" }, { t: "明", r: "あか" }, { t: "るいです。" }], ko: "태양이 밝습니다." } },
  { id: "b1_80", word: "月", reading: "つき", romaji: "tsuki", meaning: "달", pos: "명사", category: "nature",
    example: { tokens: [{ t: "今夜", r: "こんや" }, { t: "の" }, { t: "月", r: "つき" }, { t: "は" }, { t: "きれいです。" }], ko: "오늘 밤의 달은 아름답습니다." } },
  { id: "b1_81", word: "星", reading: "ほし", romaji: "hoshi", meaning: "별", pos: "명사", category: "nature",
    example: { tokens: [{ t: "夜", r: "よる" }, { t: "に" }, { t: "星", r: "ほし" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "밤에 별을 봅니다." } },
  { id: "b1_82", word: "雲", reading: "くも", romaji: "kumo", meaning: "구름", pos: "명사", category: "nature",
    example: { tokens: [{ t: "空", r: "そら" }, { t: "に" }, { t: "白", r: "しろ" }, { t: "い" }, { t: "雲", r: "くも" }, { t: "が" }, { t: "あります。" }], ko: "하늘에 흰 구름이 있습니다." } },
  { id: "b1_83", word: "雨", reading: "あめ", romaji: "ame", meaning: "비", pos: "명사", category: "nature",
    example: { tokens: [{ t: "今日", r: "きょう" }, { t: "は" }, { t: "雨", r: "あめ" }, { t: "です。" }], ko: "오늘은 비가 옵니다." } },
  { id: "b1_84", word: "晴れ", reading: "はれ", romaji: "hare", meaning: "맑음", pos: "명사", category: "nature",
    example: { tokens: [{ t: "明日", r: "あした" }, { t: "は" }, { t: "晴", r: "は" }, { t: "れです。" }], ko: "내일은 맑습니다." } },
  { id: "b1_85", word: "曇り", reading: "くもり", romaji: "kumori", meaning: "흐림", pos: "명사", category: "nature",
    example: { tokens: [{ t: "今日", r: "きょう" }, { t: "は" }, { t: "曇", r: "くも" }, { t: "りです。" }], ko: "오늘은 흐립니다." } },
  { id: "b1_86", word: "季節", reading: "きせつ", romaji: "kisetsu", meaning: "계절", pos: "명사", category: "nature",
    example: { tokens: [{ t: "好", r: "す" }, { t: "きな" }, { t: "季節", r: "きせつ" }, { t: "は" }, { t: "春", r: "はる" }, { t: "です。" }], ko: "좋아하는 계절은 봄입니다." } },
  { id: "b1_87", word: "春", reading: "はる", romaji: "haru", meaning: "봄", pos: "명사", category: "nature",
    example: { tokens: [{ t: "春", r: "はる" }, { t: "に" }, { t: "花", r: "はな" }, { t: "が" }, { t: "咲", r: "さ" }, { t: "きます。" }], ko: "봄에 꽃이 핍니다." } },
  { id: "b1_88", word: "夏", reading: "なつ", romaji: "natsu", meaning: "여름", pos: "명사", category: "nature",
    example: { tokens: [{ t: "夏", r: "なつ" }, { t: "は" }, { t: "暑", r: "あつ" }, { t: "いです。" }], ko: "여름은 덥습니다." } },
  { id: "b1_89", word: "秋", reading: "あき", romaji: "aki", meaning: "가을", pos: "명사", category: "nature",
    example: { tokens: [{ t: "秋", r: "あき" }, { t: "は" }, { t: "涼", r: "すず" }, { t: "しいです。" }], ko: "가을은 시원합니다." } },
  { id: "b1_90", word: "冬", reading: "ふゆ", romaji: "fuyu", meaning: "겨울", pos: "명사", category: "nature",
    example: { tokens: [{ t: "冬", r: "ふゆ" }, { t: "は" }, { t: "寒", r: "さむ" }, { t: "いです。" }], ko: "겨울은 춥습니다." } },
  { id: "b1_91", word: "自然", reading: "しぜん", romaji: "shizen", meaning: "자연", pos: "명사", category: "nature",
    example: { tokens: [{ t: "この" }, { t: "町", r: "まち" }, { t: "は" }, { t: "自然", r: "しぜん" }, { t: "が" }, { t: "多", r: "おお" }, { t: "いです。" }], ko: "이 마을은 자연이 많습니다." } },
  { id: "b1_92", word: "鳥", reading: "とり", romaji: "tori", meaning: "새", pos: "명사", category: "nature",
    example: { tokens: [{ t: "木", r: "き" }, { t: "に" }, { t: "鳥", r: "とり" }, { t: "が" }, { t: "います。" }], ko: "나무에 새가 있습니다." } },
  { id: "b1_93", word: "猫", reading: "ねこ", romaji: "neko", meaning: "고양이", pos: "명사", category: "nature",
    example: { tokens: [{ t: "白", r: "しろ" }, { t: "い" }, { t: "猫", r: "ねこ" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "흰 고양이를 좋아합니다." } },
  { id: "b1_94", word: "虫", reading: "むし", romaji: "mushi", meaning: "벌레", pos: "명사", category: "nature",
    example: { tokens: [{ t: "夏", r: "なつ" }, { t: "は" }, { t: "虫", r: "むし" }, { t: "が" }, { t: "多", r: "おお" }, { t: "いです。" }], ko: "여름은 벌레가 많습니다." } },
  { id: "b1_95", word: "馬", reading: "うま", romaji: "uma", meaning: "말", pos: "명사", category: "nature",
    example: { tokens: [{ t: "馬", r: "うま" }, { t: "は" }, { t: "速", r: "はや" }, { t: "いです。" }], ko: "말은 빠릅니다." } },
  { id: "b1_96", word: "牛", reading: "うし", romaji: "ushi", meaning: "소", pos: "명사", category: "nature",
    example: { tokens: [{ t: "牧場", r: "ぼくじょう" }, { t: "に" }, { t: "牛", r: "うし" }, { t: "が" }, { t: "います。" }], ko: "목장에 소가 있습니다." } },
  { id: "b1_97", word: "豚", reading: "ぶた", romaji: "buta", meaning: "돼지", pos: "명사", category: "nature",
    example: { tokens: [{ t: "豚", r: "ぶた" }, { t: "は" }, { t: "かわいいです。" }], ko: "돼지는 귀엽습니다." } },
  { id: "b1_98", word: "象", reading: "ぞう", romaji: "zou", meaning: "코끼리", pos: "명사", category: "nature",
    example: { tokens: [{ t: "象", r: "ぞう" }, { t: "は" }, { t: "大", r: "おお" }, { t: "きいです。" }], ko: "코끼리는 큽니다." } },
  { id: "b1_99", word: "動物", reading: "どうぶつ", romaji: "doubutsu", meaning: "동물", pos: "명사", category: "nature",
    example: { tokens: [{ t: "動物", r: "どうぶつ" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "동물을 좋아합니다." } },
  { id: "b1_100", word: "植物", reading: "しょくぶつ", romaji: "shokubutsu", meaning: "식물", pos: "명사", category: "nature",
    example: { tokens: [{ t: "部屋", r: "へや" }, { t: "に" }, { t: "植物", r: "しょくぶつ" }, { t: "が" }, { t: "あります。" }], ko: "방에 식물이 있습니다." } },
  { id: "b1_101", word: "湖", reading: "みずうみ", romaji: "mizuumi", meaning: "호수", pos: "명사", category: "nature",
    example: { tokens: [{ t: "湖", r: "みずうみ" }, { t: "は" }, { t: "きれいです。" }], ko: "호수는 아름답습니다." } },
  { id: "b1_102", word: "島", reading: "しま", romaji: "shima", meaning: "섬", pos: "명사", category: "nature",
    example: { tokens: [{ t: "小", r: "ちい" }, { t: "さい" }, { t: "島", r: "しま" }, { t: "に" }, { t: "行", r: "い" }, { t: "きました。" }], ko: "작은 섬에 갔습니다." } },
  { id: "b1_103", word: "砂", reading: "すな", romaji: "suna", meaning: "모래", pos: "명사", category: "nature",
    example: { tokens: [{ t: "海", r: "うみ" }, { t: "の" }, { t: "砂", r: "すな" }, { t: "は" }, { t: "白", r: "しろ" }, { t: "いです。" }], ko: "바다의 모래는 하얗습니다." } },
  { id: "b1_104", word: "氷", reading: "こおり", romaji: "koori", meaning: "얼음", pos: "명사", category: "nature",
    example: { tokens: [{ t: "冬", r: "ふゆ" }, { t: "に" }, { t: "池", r: "いけ" }, { t: "が" }, { t: "氷", r: "こおり" }, { t: "になります。" }], ko: "겨울에 연못이 얼음이 됩니다." } },
  { id: "b1_105", word: "暖かい", reading: "あたたかい", romaji: "atatakai", meaning: "따뜻하다", pos: "い형용사", category: "nature",
    example: { tokens: [{ t: "春", r: "はる" }, { t: "は" }, { t: "暖", r: "あたた" }, { t: "かいです。" }], ko: "봄은 따뜻합니다." } },
  { id: "b1_106", word: "涼しい", reading: "すずしい", romaji: "suzushii", meaning: "시원하다", pos: "い형용사", category: "nature",
    example: { tokens: [{ t: "秋", r: "あき" }, { t: "の" }, { t: "風", r: "かぜ" }, { t: "は" }, { t: "涼", r: "すず" }, { t: "しいです。" }], ko: "가을의 바람은 시원합니다." } },
  { id: "b1_107", word: "森林", reading: "しんりん", romaji: "shinrin", meaning: "삼림", pos: "명사", category: "nature",
    example: { tokens: [{ t: "ここは" }, { t: "森林", r: "しんりん" }, { t: "が" }, { t: "多", r: "おお" }, { t: "いです。" }], ko: "이곳은 삼림이 많습니다." } },
  { id: "b1_108", word: "波", reading: "なみ", romaji: "nami", meaning: "파도", pos: "명사", category: "nature",
    example: { tokens: [{ t: "海", r: "うみ" }, { t: "の" }, { t: "波", r: "なみ" }, { t: "が" }, { t: "高", r: "たか" }, { t: "いです。" }], ko: "바다의 파도가 높습니다." } },
  { id: "b1_109", word: "光", reading: "ひかり", romaji: "hikari", meaning: "빛", pos: "명사", category: "nature",
    example: { tokens: [{ t: "太陽", r: "たいよう" }, { t: "の" }, { t: "光", r: "ひかり" }, { t: "が" }, { t: "明", r: "あか" }, { t: "るいです。" }], ko: "태양의 빛이 밝습니다." } },
  { id: "b1_110", word: "空気", reading: "くうき", romaji: "kuuki", meaning: "공기", pos: "명사", category: "nature",
    example: { tokens: [{ t: "山", r: "やま" }, { t: "の" }, { t: "空気", r: "くうき" }, { t: "は" }, { t: "きれいです。" }], ko: "산의 공기는 깨끗합니다." } },
  { id: "b1_111", word: "森の中", reading: "もりのなか", romaji: "mori no naka", meaning: "숲 속", pos: "명사", category: "nature",
    example: { tokens: [{ t: "森", r: "もり" }, { t: "の" }, { t: "中", r: "なか" }, { t: "で" }, { t: "鳥", r: "とり" }, { t: "が" }, { t: "鳴", r: "な" }, { t: "きます。" }], ko: "숲 속에서 새가 웁니다." } },
  { id: "b1_112", word: "桜", reading: "さくら", romaji: "sakura", meaning: "벚꽃", pos: "명사", category: "nature",
    example: { tokens: [{ t: "春", r: "はる" }, { t: "に" }, { t: "桜", r: "さくら" }, { t: "が" }, { t: "咲", r: "さ" }, { t: "きます。" }], ko: "봄에 벚꽃이 핍니다." } },
  { id: "b1_113", word: "葉っぱ", reading: "はっぱ", romaji: "happa", meaning: "잎사귀", pos: "명사", category: "nature",
    example: { tokens: [{ t: "緑", r: "みどり" }, { t: "の" }, { t: "葉", r: "は" }, { t: "っぱが" }, { t: "きれいです。" }], ko: "초록 잎사귀가 예쁩니다." } },
  { id: "b1_114", word: "虹", reading: "にじ", romaji: "niji", meaning: "무지개", pos: "명사", category: "nature",
    example: { tokens: [{ t: "雨", r: "あめ" }, { t: "の" }, { t: "あとに" }, { t: "虹", r: "にじ" }, { t: "が" }, { t: "出", r: "で" }, { t: "ました。" }], ko: "비 온 뒤에 무지개가 떴습니다." } },
  { id: "b1_115", word: "天気予報", reading: "てんきよほう", romaji: "tenki yohou", meaning: "일기예보", pos: "명사", category: "nature",
    example: { tokens: [{ t: "天気", r: "てんき" }, { t: "予報", r: "よほう" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "일기예보를 봅니다." } },
  { id: "b1_116", word: "うさぎ", reading: "うさぎ", romaji: "usagi", meaning: "토끼", pos: "명사", category: "nature",
    example: { tokens: [{ t: "うさぎは" }, { t: "かわいいです。" }], ko: "토끼는 귀엽습니다." } },
  { id: "b1_117", word: "くま", reading: "くま", romaji: "kuma", meaning: "곰", pos: "명사", category: "nature",
    example: { tokens: [{ t: "山", r: "やま" }, { t: "に" }, { t: "くまが" }, { t: "います。" }], ko: "산에 곰이 있습니다." } },
  { id: "b1_118", word: "魚屋", reading: "さかなや", romaji: "sakanaya", meaning: "생선가게", pos: "명사", category: "nature",
    example: { tokens: [{ t: "魚屋", r: "さかなや" }, { t: "で" }, { t: "魚", r: "さかな" }, { t: "を" }, { t: "買", r: "か" }, { t: "います。" }], ko: "생선가게에서 생선을 삽니다." } },
  { id: "b1_119", word: "枝", reading: "えだ", romaji: "eda", meaning: "가지", pos: "명사", category: "nature",
    example: { tokens: [{ t: "木", r: "き" }, { t: "の" }, { t: "枝", r: "えだ" }, { t: "に" }, { t: "鳥", r: "とり" }, { t: "が" }, { t: "います。" }], ko: "나무 가지에 새가 있습니다." } },
  { id: "b1_120", word: "根", reading: "ね", romaji: "ne", meaning: "뿌리", pos: "명사", category: "nature",
    example: { tokens: [{ t: "木", r: "き" }, { t: "の" }, { t: "根", r: "ね" }, { t: "は" }, { t: "太", r: "ふと" }, { t: "いです。" }], ko: "나무의 뿌리는 굵습니다." } },
  { id: "b1_121", word: "暑い日", reading: "あついひ", romaji: "atsui hi", meaning: "더운 날", pos: "명사", category: "nature",
    example: { tokens: [{ t: "暑", r: "あつ" }, { t: "い" }, { t: "日", r: "ひ" }, { t: "は" }, { t: "海", r: "うみ" }, { t: "に" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "더운 날은 바다에 갑니다." } },
  { id: "b1_122", word: "魚の池", reading: "さかなのいけ", romaji: "sakana no ike", meaning: "물고기 연못", pos: "명사", category: "nature",
    example: { tokens: [{ t: "公園", r: "こうえん" }, { t: "の" }, { t: "池", r: "いけ" }, { t: "に" }, { t: "魚", r: "さかな" }, { t: "が" }, { t: "います。" }], ko: "공원 연못에 물고기가 있습니다." } },
  { id: "b1_123", word: "花畑", reading: "はなばたけ", romaji: "hanabatake", meaning: "꽃밭", pos: "명사", category: "nature",
    example: { tokens: [{ t: "春", r: "はる" }, { t: "に" }, { t: "花畑", r: "はなばたけ" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "봄에 꽃밭을 봅니다." } },
  { id: "b1_124", word: "夕日", reading: "ゆうひ", romaji: "yuuhi", meaning: "석양", pos: "명사", category: "nature",
    example: { tokens: [{ t: "海", r: "うみ" }, { t: "で" }, { t: "夕日", r: "ゆうひ" }, { t: "を" }, { t: "見", r: "み" }, { t: "ました。" }], ko: "바다에서 석양을 봤습니다." } },
  { id: "b1_125", word: "朝日", reading: "あさひ", romaji: "asahi", meaning: "아침해", pos: "명사", category: "nature",
    example: { tokens: [{ t: "山", r: "やま" }, { t: "で" }, { t: "朝日", r: "あさひ" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "산에서 아침해를 봅니다." } },
  { id: "b1_126", word: "緑", reading: "みどり", romaji: "midori", meaning: "초록, 녹색", pos: "명사", category: "nature",
    example: { tokens: [{ t: "山", r: "やま" }, { t: "は" }, { t: "緑", r: "みどり" }, { t: "が" }, { t: "多", r: "おお" }, { t: "いです。" }], ko: "산은 초록이 많습니다." } },
  { id: "b1_127", word: "魚つり", reading: "さかなつり", romaji: "sakanatsuri", meaning: "낚시", pos: "명사", category: "nature",
    example: { tokens: [{ t: "川", r: "かわ" }, { t: "で" }, { t: "魚", r: "さかな" }, { t: "つりを" }, { t: "します。" }], ko: "강에서 낚시를 합니다." } },
  { id: "b1_128", word: "庭", reading: "にわ", romaji: "niwa", meaning: "정원, 마당", pos: "명사", category: "nature",
    example: { tokens: [{ t: "庭", r: "にわ" }, { t: "に" }, { t: "花", r: "はな" }, { t: "が" }, { t: "あります。" }], ko: "마당에 꽃이 있습니다." } },
  { id: "b1_129", word: "畑", reading: "はたけ", romaji: "hatake", meaning: "밭", pos: "명사", category: "nature",
    example: { tokens: [{ t: "畑", r: "はたけ" }, { t: "で" }, { t: "野菜", r: "やさい" }, { t: "を" }, { t: "作", r: "つく" }, { t: "ります。" }], ko: "밭에서 채소를 기릅니다." } },
  { id: "b1_130", word: "田んぼ", reading: "たんぼ", romaji: "tanbo", meaning: "논", pos: "명사", category: "nature",
    example: { tokens: [{ t: "田", r: "た" }, { t: "んぼで" }, { t: "米", r: "こめ" }, { t: "を" }, { t: "作", r: "つく" }, { t: "ります。" }], ko: "논에서 쌀을 짓습니다." } },
];
