import type { Word } from "./types";

// JLPT N5 확장 단어 — 취미·부사·인사 (batch B5)
export const VOCAB_B5: Word[] = [
  // ===== hobby (취미·스포츠·공부·일·여가) =====
  { id: "b5_1", word: "新聞", reading: "しんぶん", romaji: "shinbun", meaning: "신문", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "毎朝", r: "まいあさ" }, { t: "新聞", r: "しんぶん" }, { t: "を" }, { t: "読", r: "よ" }, { t: "みます。" }], ko: "매일 아침 신문을 읽습니다." } },
  { id: "b5_2", word: "雑誌", reading: "ざっし", romaji: "zasshi", meaning: "잡지", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "この" }, { t: "雑誌", r: "ざっし" }, { t: "は" }, { t: "面白", r: "おもしろ" }, { t: "いです。" }], ko: "이 잡지는 재미있습니다." } },
  { id: "b5_3", word: "漫画", reading: "まんが", romaji: "manga", meaning: "만화", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "日本", r: "にほん" }, { t: "の" }, { t: "漫画", r: "まんが" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "일본 만화를 좋아합니다." } },
  { id: "b5_4", word: "小説", reading: "しょうせつ", romaji: "shōsetsu", meaning: "소설", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "夜", r: "よる" }, { t: "に" }, { t: "小説", r: "しょうせつ" }, { t: "を" }, { t: "読", r: "よ" }, { t: "みます。" }], ko: "밤에 소설을 읽습니다." } },
  { id: "b5_5", word: "絵", reading: "え", romaji: "e", meaning: "그림", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "妹", r: "いもうと" }, { t: "は" }, { t: "絵", r: "え" }, { t: "が" }, { t: "上手", r: "じょうず" }, { t: "です。" }], ko: "여동생은 그림을 잘 그립니다." } },
  { id: "b5_6", word: "ピアノ", reading: "ぴあの", romaji: "piano", meaning: "피아노", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "毎日", r: "まいにち" }, { t: "ピアノ" }, { t: "を" }, { t: "練習", r: "れんしゅう" }, { t: "します。" }], ko: "매일 피아노를 연습합니다." } },
  { id: "b5_7", word: "ギター", reading: "ぎたー", romaji: "gitā", meaning: "기타", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "兄", r: "あに" }, { t: "は" }, { t: "ギター" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "형은 기타를 좋아합니다." } },
  { id: "b5_8", word: "スポーツ", reading: "すぽーつ", romaji: "supōtsu", meaning: "스포츠", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "どんな" }, { t: "スポーツ" }, { t: "が" }, { t: "好", r: "す" }, { t: "きですか。" }], ko: "어떤 스포츠를 좋아합니까?" } },
  { id: "b5_9", word: "野球", reading: "やきゅう", romaji: "yakyū", meaning: "야구", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "父", r: "ちち" }, { t: "と" }, { t: "野球", r: "やきゅう" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "아버지와 야구를 봅니다." } },
  { id: "b5_10", word: "サッカー", reading: "さっかー", romaji: "sakkā", meaning: "축구", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "公園", r: "こうえん" }, { t: "で" }, { t: "サッカー" }, { t: "を" }, { t: "します。" }], ko: "공원에서 축구를 합니다." } },
  { id: "b5_11", word: "テニス", reading: "てにす", romaji: "tenisu", meaning: "테니스", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "友達", r: "ともだち" }, { t: "と" }, { t: "テニス" }, { t: "を" }, { t: "します。" }], ko: "친구와 테니스를 합니다." } },
  { id: "b5_12", word: "水泳", reading: "すいえい", romaji: "suiei", meaning: "수영", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "夏", r: "なつ" }, { t: "は" }, { t: "水泳", r: "すいえい" }, { t: "が" }, { t: "楽", r: "たの" }, { t: "しいです。" }], ko: "여름에는 수영이 즐겁습니다." } },
  { id: "b5_13", word: "散歩", reading: "さんぽ", romaji: "sanpo", meaning: "산책", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "朝", r: "あさ" }, { t: "の" }, { t: "散歩", r: "さんぽ" }, { t: "は" }, { t: "気持", r: "きも" }, { t: "ちいいです。" }], ko: "아침 산책은 기분이 좋습니다." } },
  { id: "b5_14", word: "釣り", reading: "つり", romaji: "tsuri", meaning: "낚시", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "海", r: "うみ" }, { t: "で" }, { t: "釣", r: "つ" }, { t: "り" }, { t: "を" }, { t: "します。" }], ko: "바다에서 낚시를 합니다." } },
  { id: "b5_15", word: "ゲーム", reading: "げーむ", romaji: "gēmu", meaning: "게임", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "弟", r: "おとうと" }, { t: "は" }, { t: "ゲーム" }, { t: "が" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "남동생은 게임을 좋아합니다." } },
  { id: "b5_16", word: "趣味", reading: "しゅみ", romaji: "shumi", meaning: "취미", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "私", r: "わたし" }, { t: "の" }, { t: "趣味", r: "しゅみ" }, { t: "は" }, { t: "読書", r: "どくしょ" }, { t: "です。" }], ko: "제 취미는 독서입니다." } },
  { id: "b5_17", word: "練習", reading: "れんしゅう", romaji: "renshū", meaning: "연습", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "毎日", r: "まいにち" }, { t: "練習", r: "れんしゅう" }, { t: "を" }, { t: "します。" }], ko: "매일 연습을 합니다." } },
  { id: "b5_18", word: "試合", reading: "しあい", romaji: "shiai", meaning: "시합·경기", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "明日", r: "あした" }, { t: "は" }, { t: "試合", r: "しあい" }, { t: "が" }, { t: "あります。" }], ko: "내일은 시합이 있습니다." } },
  { id: "b5_19", word: "ダンス", reading: "だんす", romaji: "dansu", meaning: "댄스·춤", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "姉", r: "あね" }, { t: "は" }, { t: "ダンス" }, { t: "が" }, { t: "上手", r: "じょうず" }, { t: "です。" }], ko: "언니는 춤을 잘 춥니다." } },
  { id: "b5_20", word: "カラオケ", reading: "からおけ", romaji: "karaoke", meaning: "노래방", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "週末", r: "しゅうまつ" }, { t: "に" }, { t: "カラオケ" }, { t: "へ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "주말에 노래방에 갑니다." } },
  { id: "b5_21", word: "買い物", reading: "かいもの", romaji: "kaimono", meaning: "쇼핑·장보기", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "母", r: "はは" }, { t: "と" }, { t: "買", r: "か" }, { t: "い" }, { t: "物", r: "もの" }, { t: "に" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "어머니와 쇼핑하러 갑니다." } },
  { id: "b5_22", word: "勉強", reading: "べんきょう", romaji: "benkyō", meaning: "공부", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "図書館", r: "としょかん" }, { t: "で" }, { t: "勉強", r: "べんきょう" }, { t: "を" }, { t: "します。" }], ko: "도서관에서 공부를 합니다." } },
  { id: "b5_23", word: "宿題", reading: "しゅくだい", romaji: "shukudai", meaning: "숙제", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "今", r: "いま" }, { t: "宿題", r: "しゅくだい" }, { t: "を" }, { t: "して" }, { t: "います。" }], ko: "지금 숙제를 하고 있습니다." } },
  { id: "b5_24", word: "試験", reading: "しけん", romaji: "shiken", meaning: "시험", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "来週", r: "らいしゅう" }, { t: "試験", r: "しけん" }, { t: "が" }, { t: "あります。" }], ko: "다음 주에 시험이 있습니다." } },
  { id: "b5_25", word: "問題", reading: "もんだい", romaji: "mondai", meaning: "문제", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "この" }, { t: "問題", r: "もんだい" }, { t: "は" }, { t: "難", r: "むずか" }, { t: "しいです。" }], ko: "이 문제는 어렵습니다." } },
  { id: "b5_26", word: "答え", reading: "こたえ", romaji: "kotae", meaning: "답·정답", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "答", r: "こた" }, { t: "え" }, { t: "は" }, { t: "これ" }, { t: "です。" }], ko: "답은 이것입니다." } },
  { id: "b5_27", word: "質問", reading: "しつもん", romaji: "shitsumon", meaning: "질문", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "質問", r: "しつもん" }, { t: "が" }, { t: "あります。" }], ko: "질문이 있습니다." } },
  { id: "b5_28", word: "言葉", reading: "ことば", romaji: "kotoba", meaning: "말·단어", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "この" }, { t: "言葉", r: "ことば" }, { t: "の" }, { t: "意味", r: "いみ" }, { t: "は" }, { t: "何", r: "なん" }, { t: "ですか。" }], ko: "이 단어의 뜻은 무엇입니까?" } },
  { id: "b5_29", word: "英語", reading: "えいご", romaji: "eigo", meaning: "영어", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "英語", r: "えいご" }, { t: "で" }, { t: "話", r: "はな" }, { t: "します。" }], ko: "영어로 이야기합니다." } },
  { id: "b5_30", word: "日本語", reading: "にほんご", romaji: "nihongo", meaning: "일본어", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "日本語", r: "にほんご" }, { t: "を" }, { t: "勉強", r: "べんきょう" }, { t: "します。" }], ko: "일본어를 공부합니다." } },
  { id: "b5_31", word: "漢字", reading: "かんじ", romaji: "kanji", meaning: "한자", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "漢字", r: "かんじ" }, { t: "は" }, { t: "少", r: "すこ" }, { t: "し" }, { t: "難", r: "むずか" }, { t: "しいです。" }], ko: "한자는 조금 어렵습니다." } },
  { id: "b5_32", word: "文字", reading: "もじ", romaji: "moji", meaning: "글자·문자", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "この" }, { t: "文字", r: "もじ" }, { t: "は" }, { t: "小", r: "ちい" }, { t: "さいです。" }], ko: "이 글자는 작습니다." } },
  { id: "b5_33", word: "番組", reading: "ばんぐみ", romaji: "bangumi", meaning: "(방송) 프로그램", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "この" }, { t: "番組", r: "ばんぐみ" }, { t: "は" }, { t: "人気", r: "にんき" }, { t: "です。" }], ko: "이 프로그램은 인기가 있습니다." } },
  { id: "b5_34", word: "パーティー", reading: "ぱーてぃー", romaji: "pātī", meaning: "파티", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "今夜", r: "こんや" }, { t: "パーティー" }, { t: "が" }, { t: "あります。" }], ko: "오늘 밤에 파티가 있습니다." } },
  { id: "b5_35", word: "歌手", reading: "かしゅ", romaji: "kashu", meaning: "가수", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "好", r: "す" }, { t: "きな" }, { t: "歌手", r: "かしゅ" }, { t: "は" }, { t: "誰", r: "だれ" }, { t: "ですか。" }], ko: "좋아하는 가수는 누구입니까?" } },
  { id: "b5_36", word: "切手", reading: "きって", romaji: "kitte", meaning: "우표", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "切手", r: "きって" }, { t: "を" }, { t: "集", r: "あつ" }, { t: "めます。" }], ko: "우표를 모읍니다." } },
  { id: "b5_37", word: "図書館", reading: "としょかん", romaji: "toshokan", meaning: "도서관", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "図書館", r: "としょかん" }, { t: "で" }, { t: "本", r: "ほん" }, { t: "を" }, { t: "借", r: "か" }, { t: "ります。" }], ko: "도서관에서 책을 빌립니다." } },
  { id: "b5_38", word: "公園", reading: "こうえん", romaji: "kōen", meaning: "공원", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "公園", r: "こうえん" }, { t: "で" }, { t: "遊", r: "あそ" }, { t: "びます。" }], ko: "공원에서 놉니다." } },
  { id: "b5_39", word: "読書", reading: "どくしょ", romaji: "dokusho", meaning: "독서", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "週末", r: "しゅうまつ" }, { t: "は" }, { t: "読書", r: "どくしょ" }, { t: "を" }, { t: "します。" }], ko: "주말에는 독서를 합니다." } },
  { id: "b5_40", word: "授業", reading: "じゅぎょう", romaji: "jugyō", meaning: "수업", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "授業", r: "じゅぎょう" }, { t: "は" }, { t: "九時", r: "くじ" }, { t: "から" }, { t: "です。" }], ko: "수업은 9시부터입니다." } },
  { id: "b5_41", word: "辞書", reading: "じしょ", romaji: "jisho", meaning: "사전", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "辞書", r: "じしょ" }, { t: "で" }, { t: "言葉", r: "ことば" }, { t: "を" }, { t: "調", r: "しら" }, { t: "べます。" }], ko: "사전으로 단어를 찾습니다." } },
  { id: "b5_42", word: "鉛筆", reading: "えんぴつ", romaji: "enpitsu", meaning: "연필", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "鉛筆", r: "えんぴつ" }, { t: "で" }, { t: "書", r: "か" }, { t: "きます。" }], ko: "연필로 씁니다." } },
  { id: "b5_43", word: "紙", reading: "かみ", romaji: "kami", meaning: "종이", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "白", r: "しろ" }, { t: "い" }, { t: "紙", r: "かみ" }, { t: "に" }, { t: "絵", r: "え" }, { t: "を" }, { t: "描", r: "か" }, { t: "きます。" }], ko: "하얀 종이에 그림을 그립니다." } },
  { id: "b5_44", word: "趣向", reading: "しゅこう", romaji: "shukō", meaning: "취향·기호", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "人", r: "ひと" }, { t: "それぞれ" }, { t: "趣向", r: "しゅこう" }, { t: "が" }, { t: "あります。" }], ko: "사람마다 취향이 있습니다." } },
  { id: "b5_45", word: "週末", reading: "しゅうまつ", romaji: "shūmatsu", meaning: "주말 여가", pos: "명사", category: "hobby",
    example: { tokens: [{ t: "次", r: "つぎ" }, { t: "の" }, { t: "週末", r: "しゅうまつ" }, { t: "は" }, { t: "暇", r: "ひま" }, { t: "です。" }], ko: "다음 주말은 한가합니다." } },

  // ===== adverb (부사·접속사·의문사·지시어) =====
  { id: "b5_46", word: "よく", reading: "よく", romaji: "yoku", meaning: "자주·잘", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "私", r: "わたし" }, { t: "は" }, { t: "よく" }, { t: "映画", r: "えいが" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "저는 자주 영화를 봅니다." } },
  { id: "b5_47", word: "たぶん", reading: "たぶん", romaji: "tabun", meaning: "아마", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "明日", r: "あした" }, { t: "は" }, { t: "たぶん" }, { t: "雨", r: "あめ" }, { t: "です。" }], ko: "내일은 아마 비가 옵니다." } },
  { id: "b5_48", word: "少し", reading: "すこし", romaji: "sukoshi", meaning: "조금", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "少", r: "すこ" }, { t: "し" }, { t: "疲", r: "つか" }, { t: "れました。" }], ko: "조금 피곤합니다." } },
  { id: "b5_49", word: "すぐ", reading: "すぐ", romaji: "sugu", meaning: "곧·바로", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "すぐ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "바로 가겠습니다." } },
  { id: "b5_50", word: "もっと", reading: "もっと", romaji: "motto", meaning: "더·더욱", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "もっと" }, { t: "勉強", r: "べんきょう" }, { t: "が" }, { t: "したいです。" }], ko: "더 공부가 하고 싶습니다." } },
  { id: "b5_51", word: "だんだん", reading: "だんだん", romaji: "dandan", meaning: "점점", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "だんだん" }, { t: "暑", r: "あつ" }, { t: "く" }, { t: "なります。" }], ko: "점점 더워집니다." } },
  { id: "b5_52", word: "ゆっくり", reading: "ゆっくり", romaji: "yukkuri", meaning: "천천히", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "ゆっくり" }, { t: "話", r: "はな" }, { t: "して" }, { t: "ください。" }], ko: "천천히 말해 주세요." } },
  { id: "b5_53", word: "きっと", reading: "きっと", romaji: "kitto", meaning: "분명히·꼭", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "彼", r: "かれ" }, { t: "は" }, { t: "きっと" }, { t: "来", r: "き" }, { t: "ます。" }], ko: "그는 분명히 옵니다." } },
  { id: "b5_54", word: "ぜひ", reading: "ぜひ", romaji: "zehi", meaning: "꼭·부디", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "ぜひ" }, { t: "来", r: "き" }, { t: "て" }, { t: "ください。" }], ko: "꼭 와 주세요." } },
  { id: "b5_55", word: "また", reading: "また", romaji: "mata", meaning: "또·다시", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "また" }, { t: "明日", r: "あした" }, { t: "会", r: "あ" }, { t: "いましょう。" }], ko: "또 내일 만납시다." } },
  { id: "b5_56", word: "一番", reading: "いちばん", romaji: "ichiban", meaning: "가장·제일", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "これ" }, { t: "が" }, { t: "一番", r: "いちばん" }, { t: "好", r: "す" }, { t: "きです。" }], ko: "이것이 가장 좋습니다." } },
  { id: "b5_57", word: "全部", reading: "ぜんぶ", romaji: "zenbu", meaning: "전부·모두", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "全部", r: "ぜんぶ" }, { t: "食", r: "た" }, { t: "べました。" }], ko: "전부 먹었습니다." } },
  { id: "b5_58", word: "みんな", reading: "みんな", romaji: "minna", meaning: "모두·다", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "みんな" }, { t: "で" }, { t: "歌", r: "うた" }, { t: "います。" }], ko: "다 함께 노래합니다." } },
  { id: "b5_59", word: "早く", reading: "はやく", romaji: "hayaku", meaning: "빨리·일찍", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "朝", r: "あさ" }, { t: "早", r: "はや" }, { t: "く" }, { t: "起", r: "お" }, { t: "きます。" }], ko: "아침 일찍 일어납니다." } },
  { id: "b5_60", word: "まっすぐ", reading: "まっすぐ", romaji: "massugu", meaning: "곧장·똑바로", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "まっすぐ" }, { t: "行", r: "い" }, { t: "って" }, { t: "ください。" }], ko: "곧장 가 주세요." } },
  { id: "b5_61", word: "そして", reading: "そして", romaji: "soshite", meaning: "그리고", pos: "접속사", category: "adverb",
    example: { tokens: [{ t: "本", r: "ほん" }, { t: "を" }, { t: "読", r: "よ" }, { t: "みます。" }, { t: "そして" }, { t: "寝", r: "ね" }, { t: "ます。" }], ko: "책을 읽습니다. 그리고 잡니다." } },
  { id: "b5_62", word: "でも", reading: "でも", romaji: "demo", meaning: "그렇지만·하지만", pos: "접속사", category: "adverb",
    example: { tokens: [{ t: "高", r: "たか" }, { t: "いです。" }, { t: "でも" }, { t: "買", r: "か" }, { t: "います。" }], ko: "비쌉니다. 하지만 삽니다." } },
  { id: "b5_63", word: "しかし", reading: "しかし", romaji: "shikashi", meaning: "그러나", pos: "접속사", category: "adverb",
    example: { tokens: [{ t: "雨", r: "あめ" }, { t: "です。" }, { t: "しかし" }, { t: "出", r: "で" }, { t: "かけます。" }], ko: "비가 옵니다. 그러나 외출합니다." } },
  { id: "b5_64", word: "それから", reading: "それから", romaji: "sorekara", meaning: "그러고 나서·그다음", pos: "접속사", category: "adverb",
    example: { tokens: [{ t: "ご飯", r: "ごはん" }, { t: "を" }, { t: "食", r: "た" }, { t: "べます。" }, { t: "それから" }, { t: "勉強", r: "べんきょう" }, { t: "します。" }], ko: "밥을 먹습니다. 그러고 나서 공부합니다." } },
  { id: "b5_65", word: "だから", reading: "だから", romaji: "dakara", meaning: "그래서·그러니까", pos: "접속사", category: "adverb",
    example: { tokens: [{ t: "寒", r: "さむ" }, { t: "いです。" }, { t: "だから" }, { t: "上着", r: "うわぎ" }, { t: "を" }, { t: "着", r: "き" }, { t: "ます。" }], ko: "춥습니다. 그래서 겉옷을 입습니다." } },
  { id: "b5_66", word: "では", reading: "では", romaji: "dewa", meaning: "그러면·그럼", pos: "접속사", category: "adverb",
    example: { tokens: [{ t: "では" }, { t: "始", r: "はじ" }, { t: "めましょう。" }], ko: "그럼 시작합시다." } },
  { id: "b5_67", word: "じゃあ", reading: "じゃあ", romaji: "jā", meaning: "그럼 (구어)", pos: "접속사", category: "adverb",
    example: { tokens: [{ t: "じゃあ" }, { t: "また" }, { t: "明日", r: "あした" }, { t: "。" }], ko: "그럼 또 내일." } },
  { id: "b5_68", word: "それで", reading: "それで", romaji: "sorede", meaning: "그래서", pos: "접속사", category: "adverb",
    example: { tokens: [{ t: "それで" }, { t: "どう" }, { t: "しましたか。" }], ko: "그래서 어떻게 했습니까?" } },
  { id: "b5_69", word: "けれども", reading: "けれども", romaji: "keredomo", meaning: "그렇지만·하지만", pos: "접속사", category: "adverb",
    example: { tokens: [{ t: "高", r: "たか" }, { t: "いです。" }, { t: "けれども" }, { t: "おいしいです。" }], ko: "비쌉니다. 하지만 맛있습니다." } },
  { id: "b5_70", word: "どう", reading: "どう", romaji: "dō", meaning: "어떻게·어때", pos: "의문사", category: "adverb",
    example: { tokens: [{ t: "味", r: "あじ" }, { t: "は" }, { t: "どう" }, { t: "ですか。" }], ko: "맛은 어떻습니까?" } },
  { id: "b5_71", word: "どこ", reading: "どこ", romaji: "doko", meaning: "어디", pos: "의문사", category: "adverb",
    example: { tokens: [{ t: "駅", r: "えき" }, { t: "は" }, { t: "どこ" }, { t: "ですか。" }], ko: "역은 어디입니까?" } },
  { id: "b5_72", word: "どちら", reading: "どちら", romaji: "dochira", meaning: "어느 쪽·어디 (정중)", pos: "의문사", category: "adverb",
    example: { tokens: [{ t: "お国", r: "おくに" }, { t: "は" }, { t: "どちら" }, { t: "ですか。" }], ko: "고향은 어디십니까?" } },
  { id: "b5_73", word: "どれ", reading: "どれ", romaji: "dore", meaning: "어느 것", pos: "의문사", category: "adverb",
    example: { tokens: [{ t: "あなた" }, { t: "の" }, { t: "傘", r: "かさ" }, { t: "は" }, { t: "どれ" }, { t: "ですか。" }], ko: "당신의 우산은 어느 것입니까?" } },
  { id: "b5_74", word: "どんな", reading: "どんな", romaji: "donna", meaning: "어떤", pos: "의문사", category: "adverb",
    example: { tokens: [{ t: "どんな" }, { t: "音楽", r: "おんがく" }, { t: "が" }, { t: "好", r: "す" }, { t: "きですか。" }], ko: "어떤 음악을 좋아합니까?" } },
  { id: "b5_75", word: "いつ", reading: "いつ", romaji: "itsu", meaning: "언제", pos: "의문사", category: "adverb",
    example: { tokens: [{ t: "誕生日", r: "たんじょうび" }, { t: "は" }, { t: "いつ" }, { t: "ですか。" }], ko: "생일은 언제입니까?" } },
  { id: "b5_76", word: "なに", reading: "なに", romaji: "nani", meaning: "무엇", pos: "의문사", category: "adverb",
    example: { tokens: [{ t: "なに" }, { t: "を" }, { t: "食", r: "た" }, { t: "べますか。" }], ko: "무엇을 먹습니까?" } },
  { id: "b5_77", word: "なん", reading: "なん", romaji: "nan", meaning: "무엇·몇 (음 변화)", pos: "의문사", category: "adverb",
    example: { tokens: [{ t: "これ" }, { t: "は" }, { t: "なん" }, { t: "ですか。" }], ko: "이것은 무엇입니까?" } },
  { id: "b5_78", word: "だれ", reading: "だれ", romaji: "dare", meaning: "누구", pos: "의문사", category: "adverb",
    example: { tokens: [{ t: "あの" }, { t: "人", r: "ひと" }, { t: "は" }, { t: "だれ" }, { t: "ですか。" }], ko: "저 사람은 누구입니까?" } },
  { id: "b5_79", word: "これ", reading: "これ", romaji: "kore", meaning: "이것", pos: "대명사", category: "adverb",
    example: { tokens: [{ t: "これ" }, { t: "は" }, { t: "私", r: "わたし" }, { t: "の" }, { t: "本", r: "ほん" }, { t: "です。" }], ko: "이것은 제 책입니다." } },
  { id: "b5_80", word: "それ", reading: "それ", romaji: "sore", meaning: "그것", pos: "대명사", category: "adverb",
    example: { tokens: [{ t: "それ" }, { t: "を" }, { t: "ください。" }], ko: "그것을 주세요." } },
  { id: "b5_81", word: "あれ", reading: "あれ", romaji: "are", meaning: "저것", pos: "대명사", category: "adverb",
    example: { tokens: [{ t: "あれ" }, { t: "は" }, { t: "何", r: "なん" }, { t: "ですか。" }], ko: "저것은 무엇입니까?" } },
  { id: "b5_82", word: "ここ", reading: "ここ", romaji: "koko", meaning: "여기", pos: "대명사", category: "adverb",
    example: { tokens: [{ t: "ここ" }, { t: "で" }, { t: "待", r: "ま" }, { t: "ちます。" }], ko: "여기에서 기다립니다." } },
  { id: "b5_83", word: "そこ", reading: "そこ", romaji: "soko", meaning: "거기", pos: "대명사", category: "adverb",
    example: { tokens: [{ t: "そこ" }, { t: "に" }, { t: "置", r: "お" }, { t: "いて" }, { t: "ください。" }], ko: "거기에 놓아 주세요." } },
  { id: "b5_84", word: "あそこ", reading: "あそこ", romaji: "asoko", meaning: "저기", pos: "대명사", category: "adverb",
    example: { tokens: [{ t: "あそこ" }, { t: "に" }, { t: "店", r: "みせ" }, { t: "が" }, { t: "あります。" }], ko: "저기에 가게가 있습니다." } },
  { id: "b5_85", word: "この", reading: "この", romaji: "kono", meaning: "이 (지시)", pos: "대명사", category: "adverb",
    example: { tokens: [{ t: "この" }, { t: "本", r: "ほん" }, { t: "は" }, { t: "面白", r: "おもしろ" }, { t: "いです。" }], ko: "이 책은 재미있습니다." } },
  { id: "b5_86", word: "その", reading: "その", romaji: "sono", meaning: "그 (지시)", pos: "대명사", category: "adverb",
    example: { tokens: [{ t: "その" }, { t: "人", r: "ひと" }, { t: "は" }, { t: "先生", r: "せんせい" }, { t: "です。" }], ko: "그 사람은 선생님입니다." } },
  { id: "b5_87", word: "あの", reading: "あの", romaji: "ano", meaning: "저 (지시)", pos: "대명사", category: "adverb",
    example: { tokens: [{ t: "あの" }, { t: "山", r: "やま" }, { t: "は" }, { t: "高", r: "たか" }, { t: "いです。" }], ko: "저 산은 높습니다." } },
  { id: "b5_88", word: "ときどき", reading: "ときどき", romaji: "tokidoki", meaning: "때때로·가끔", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "ときどき" }, { t: "散歩", r: "さんぽ" }, { t: "を" }, { t: "します。" }], ko: "가끔 산책을 합니다." } },
  { id: "b5_89", word: "ぜんぜん", reading: "ぜんぜん", romaji: "zenzen", meaning: "전혀", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "ぜんぜん" }, { t: "分", r: "わ" }, { t: "かりません。" }], ko: "전혀 모르겠습니다." } },
  { id: "b5_90", word: "なかなか", reading: "なかなか", romaji: "nakanaka", meaning: "좀처럼·꽤", pos: "부사", category: "adverb",
    example: { tokens: [{ t: "電車", r: "でんしゃ" }, { t: "が" }, { t: "なかなか" }, { t: "来", r: "こ" }, { t: "ません。" }], ko: "전철이 좀처럼 오지 않습니다." } },

  // ===== greeting (인사·정형 표현·인사말) =====
  { id: "b5_91", word: "いらっしゃいませ", reading: "いらっしゃいませ", romaji: "irasshaimase", meaning: "어서 오세요", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "店員", r: "てんいん" }, { t: "「" }, { t: "いらっしゃいませ" }, { t: "。」" }], ko: "점원: \"어서 오세요.\"" } },
  { id: "b5_92", word: "おはよう", reading: "おはよう", romaji: "ohayō", meaning: "안녕 (아침, 반말)", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "おはよう" }, { t: "、" }, { t: "今日", r: "きょう" }, { t: "も" }, { t: "いい" }, { t: "天気", r: "てんき" }, { t: "だね。" }], ko: "안녕, 오늘도 날씨가 좋네." } },
  { id: "b5_93", word: "ただいま", reading: "ただいま", romaji: "tadaima", meaning: "다녀왔습니다", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "ただいま" }, { t: "、" }, { t: "今", r: "いま" }, { t: "帰", r: "かえ" }, { t: "りました。" }], ko: "다녀왔습니다, 지금 돌아왔어요." } },
  { id: "b5_94", word: "おかえり", reading: "おかえり", romaji: "okaeri", meaning: "잘 다녀왔어 (어서 와)", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "おかえり" }, { t: "、" }, { t: "疲", r: "つか" }, { t: "れたでしょう。" }], ko: "어서 와, 피곤하지." } },
  { id: "b5_95", word: "いってきます", reading: "いってきます", romaji: "ittekimasu", meaning: "다녀오겠습니다", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "いってきます" }, { t: "、" }, { t: "学校", r: "がっこう" }, { t: "へ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "다녀오겠습니다, 학교에 가요." } },
  { id: "b5_96", word: "いってらっしゃい", reading: "いってらっしゃい", romaji: "itterasshai", meaning: "다녀오세요", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "いってらっしゃい" }, { t: "、" }, { t: "気", r: "き" }, { t: "を" }, { t: "つけてね。" }], ko: "다녀오세요, 조심해요." } },
  { id: "b5_97", word: "おめでとう", reading: "おめでとう", romaji: "omedetō", meaning: "축하해", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "誕生日", r: "たんじょうび" }, { t: "おめでとう" }, { t: "。" }], ko: "생일 축하해." } },
  { id: "b5_98", word: "お願いします", reading: "おねがいします", romaji: "onegaishimasu", meaning: "부탁합니다", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "これ" }, { t: "を" }, { t: "お" }, { t: "願", r: "ねが" }, { t: "いします。" }], ko: "이것을 부탁합니다." } },
  { id: "b5_99", word: "よろしく", reading: "よろしく", romaji: "yoroshiku", meaning: "잘 부탁해", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "どうぞ" }, { t: "よろしく" }, { t: "。" }], ko: "아무쪼록 잘 부탁해." } },
  { id: "b5_100", word: "ようこそ", reading: "ようこそ", romaji: "yōkoso", meaning: "환영합니다", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "日本", r: "にほん" }, { t: "へ" }, { t: "ようこそ" }, { t: "。" }], ko: "일본에 오신 것을 환영합니다." } },
  { id: "b5_101", word: "お疲れさま", reading: "おつかれさま", romaji: "otsukaresama", meaning: "수고하셨습니다", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "今日", r: "きょう" }, { t: "も" }, { t: "お" }, { t: "疲", r: "つか" }, { t: "れさま" }, { t: "でした。" }], ko: "오늘도 수고하셨습니다." } },
  { id: "b5_102", word: "失礼します", reading: "しつれいします", romaji: "shitsureishimasu", meaning: "실례합니다", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "失礼", r: "しつれい" }, { t: "します" }, { t: "、" }, { t: "入", r: "はい" }, { t: "っても" }, { t: "いいですか。" }], ko: "실례합니다, 들어가도 될까요?" } },
  { id: "b5_103", word: "ごちそうさま", reading: "ごちそうさま", romaji: "gochisōsama", meaning: "잘 먹었습니다", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "ごちそうさま" }, { t: "、" }, { t: "とても" }, { t: "おいしかったです。" }], ko: "잘 먹었습니다, 아주 맛있었어요." } },
  { id: "b5_104", word: "どういたしまして", reading: "どういたしまして", romaji: "dōitashimashite", meaning: "천만에요", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "いいえ" }, { t: "、" }, { t: "どういたしまして" }, { t: "。" }], ko: "아니요, 천만에요." } },
  { id: "b5_105", word: "はい", reading: "はい", romaji: "hai", meaning: "네·예", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "はい" }, { t: "、" }, { t: "そう" }, { t: "です。" }], ko: "네, 그렇습니다." } },
  { id: "b5_106", word: "いいえ", reading: "いいえ", romaji: "iie", meaning: "아니요", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "いいえ" }, { t: "、" }, { t: "違", r: "ちが" }, { t: "います。" }], ko: "아니요, 다릅니다." } },
  { id: "b5_107", word: "もしもし", reading: "もしもし", romaji: "moshimoshi", meaning: "여보세요", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "もしもし" }, { t: "、" }, { t: "田中", r: "たなか" }, { t: "です。" }], ko: "여보세요, 다나카입니다." } },
  { id: "b5_108", word: "おはようございます", reading: "おはようございます", romaji: "ohayō gozaimasu", meaning: "안녕하세요 (아침)", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "先生", r: "せんせい" }, { t: "、" }, { t: "おはようございます" }, { t: "。" }], ko: "선생님, 안녕하세요." } },
  { id: "b5_109", word: "おやすみ", reading: "おやすみ", romaji: "oyasumi", meaning: "잘 자 (반말)", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "おやすみ" }, { t: "、" }, { t: "また" }, { t: "明日", r: "あした" }, { t: "。" }], ko: "잘 자, 또 내일." } },
  { id: "b5_110", word: "ありがとうございます", reading: "ありがとうございます", romaji: "arigatō gozaimasu", meaning: "감사합니다", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "本当", r: "ほんとう" }, { t: "に" }, { t: "ありがとうございます" }, { t: "。" }], ko: "정말 감사합니다." } },
  { id: "b5_111", word: "おかげさまで", reading: "おかげさまで", romaji: "okagesamade", meaning: "덕분에요", pos: "감탄사", category: "greeting",
    example: { tokens: [{ t: "おかげさまで" }, { t: "元気", r: "げんき" }, { t: "です。" }], ko: "덕분에 잘 지냅니다." } },
];
