import type { Word } from "./types";

// JLPT N5 확장 단어 — 장소·생활사물 (batch B2)
export const VOCAB_B2: Word[] = [
  // ===== place (장소·교통·건물·방향·위치) =====
  { id: "b2_1", word: "公園", reading: "こうえん", romaji: "kouen", meaning: "공원", pos: "명사", category: "place",
    example: { tokens: [{ t: "公園", r: "こうえん" }, { t: "で" }, { t: "遊", r: "あそ" }, { t: "びます。" }], ko: "공원에서 놉니다." } },
  { id: "b2_2", word: "部屋", reading: "へや", romaji: "heya", meaning: "방", pos: "명사", category: "place",
    example: { tokens: [{ t: "部屋", r: "へや" }, { t: "が" }, { t: "広", r: "ひろ" }, { t: "いです。" }], ko: "방이 넓습니다." } },
  { id: "b2_3", word: "庭", reading: "にわ", romaji: "niwa", meaning: "정원·마당", pos: "명사", category: "place",
    example: { tokens: [{ t: "庭", r: "にわ" }, { t: "に" }, { t: "花", r: "はな" }, { t: "が" }, { t: "あります。" }], ko: "마당에 꽃이 있습니다." } },
  { id: "b2_4", word: "道", reading: "みち", romaji: "michi", meaning: "길", pos: "명사", category: "place",
    example: { tokens: [{ t: "道", r: "みち" }, { t: "を" }, { t: "渡", r: "わた" }, { t: "ります。" }], ko: "길을 건넙니다." } },
  { id: "b2_5", word: "橋", reading: "はし", romaji: "hashi", meaning: "다리", pos: "명사", category: "place",
    example: { tokens: [{ t: "橋", r: "はし" }, { t: "を" }, { t: "渡", r: "わた" }, { t: "ります。" }], ko: "다리를 건넙니다." } },
  { id: "b2_6", word: "港", reading: "みなと", romaji: "minato", meaning: "항구", pos: "명사", category: "place",
    example: { tokens: [{ t: "港", r: "みなと" }, { t: "に" }, { t: "船", r: "ふね" }, { t: "が" }, { t: "あります。" }], ko: "항구에 배가 있습니다." } },
  { id: "b2_7", word: "図書館", reading: "としょかん", romaji: "toshokan", meaning: "도서관", pos: "명사", category: "place",
    example: { tokens: [{ t: "図書館", r: "としょかん" }, { t: "で" }, { t: "勉強", r: "べんきょう" }, { t: "します。" }], ko: "도서관에서 공부합니다." } },
  { id: "b2_8", word: "郵便局", reading: "ゆうびんきょく", romaji: "yuubinkyoku", meaning: "우체국", pos: "명사", category: "place",
    example: { tokens: [{ t: "郵便局", r: "ゆうびんきょく" }, { t: "は" }, { t: "どこ" }, { t: "ですか。" }], ko: "우체국은 어디예요?" } },
  { id: "b2_9", word: "交番", reading: "こうばん", romaji: "kouban", meaning: "파출소", pos: "명사", category: "place",
    example: { tokens: [{ t: "交番", r: "こうばん" }, { t: "で" }, { t: "道", r: "みち" }, { t: "を" }, { t: "聞", r: "き" }, { t: "きます。" }], ko: "파출소에서 길을 묻습니다." } },
  { id: "b2_10", word: "デパート", reading: "でぱーと", romaji: "depaato", meaning: "백화점", pos: "명사", category: "place",
    example: { tokens: [{ t: "デパート" }, { t: "で" }, { t: "買", r: "か" }, { t: "い" }, { t: "物", r: "もの" }, { t: "します。" }], ko: "백화점에서 쇼핑합니다." } },
  { id: "b2_11", word: "スーパー", reading: "すーぱー", romaji: "suupaa", meaning: "슈퍼마켓", pos: "명사", category: "place",
    example: { tokens: [{ t: "スーパー" }, { t: "で" }, { t: "野菜", r: "やさい" }, { t: "を" }, { t: "買", r: "か" }, { t: "います。" }], ko: "슈퍼에서 채소를 삽니다." } },
  { id: "b2_12", word: "コンビニ", reading: "こんびに", romaji: "konbini", meaning: "편의점", pos: "명사", category: "place",
    example: { tokens: [{ t: "コンビニ" }, { t: "は" }, { t: "近", r: "ちか" }, { t: "いです。" }], ko: "편의점은 가깝습니다." } },
  { id: "b2_13", word: "市場", reading: "いちば", romaji: "ichiba", meaning: "시장", pos: "명사", category: "place",
    example: { tokens: [{ t: "市場", r: "いちば" }, { t: "で" }, { t: "魚", r: "さかな" }, { t: "を" }, { t: "買", r: "か" }, { t: "います。" }], ko: "시장에서 생선을 삽니다." } },
  { id: "b2_14", word: "教室", reading: "きょうしつ", romaji: "kyoushitsu", meaning: "교실", pos: "명사", category: "place",
    example: { tokens: [{ t: "教室", r: "きょうしつ" }, { t: "に" }, { t: "入", r: "はい" }, { t: "ります。" }], ko: "교실에 들어갑니다." } },
  { id: "b2_15", word: "入口", reading: "いりぐち", romaji: "iriguchi", meaning: "입구", pos: "명사", category: "place",
    example: { tokens: [{ t: "入口", r: "いりぐち" }, { t: "は" }, { t: "あちら" }, { t: "です。" }], ko: "입구는 저쪽입니다." } },
  { id: "b2_16", word: "出口", reading: "でぐち", romaji: "deguchi", meaning: "출구", pos: "명사", category: "place",
    example: { tokens: [{ t: "出口", r: "でぐち" }, { t: "は" }, { t: "どこ" }, { t: "ですか。" }], ko: "출구는 어디예요?" } },
  { id: "b2_17", word: "角", reading: "かど", romaji: "kado", meaning: "모퉁이", pos: "명사", category: "place",
    example: { tokens: [{ t: "角", r: "かど" }, { t: "を" }, { t: "曲", r: "ま" }, { t: "がります。" }], ko: "모퉁이를 돕니다." } },
  { id: "b2_18", word: "隣", reading: "となり", romaji: "tonari", meaning: "옆·이웃", pos: "명사", category: "place",
    example: { tokens: [{ t: "隣", r: "となり" }, { t: "の" }, { t: "部屋", r: "へや" }, { t: "です。" }], ko: "옆방입니다." } },
  { id: "b2_19", word: "前", reading: "まえ", romaji: "mae", meaning: "앞", pos: "명사", category: "place",
    example: { tokens: [{ t: "駅", r: "えき" }, { t: "の" }, { t: "前", r: "まえ" }, { t: "で" }, { t: "会", r: "あ" }, { t: "います。" }], ko: "역 앞에서 만납니다." } },
  { id: "b2_20", word: "後ろ", reading: "うしろ", romaji: "ushiro", meaning: "뒤", pos: "명사", category: "place",
    example: { tokens: [{ t: "後", r: "うし" }, { t: "ろ" }, { t: "に" }, { t: "立", r: "た" }, { t: "ちます。" }], ko: "뒤에 섭니다." } },
  { id: "b2_21", word: "上", reading: "うえ", romaji: "ue", meaning: "위", pos: "명사", category: "place",
    example: { tokens: [{ t: "机", r: "つくえ" }, { t: "の" }, { t: "上", r: "うえ" }, { t: "に" }, { t: "あります。" }], ko: "책상 위에 있습니다." } },
  { id: "b2_22", word: "下", reading: "した", romaji: "shita", meaning: "아래", pos: "명사", category: "place",
    example: { tokens: [{ t: "椅子", r: "いす" }, { t: "の" }, { t: "下", r: "した" }, { t: "に" }, { t: "あります。" }], ko: "의자 아래에 있습니다." } },
  { id: "b2_23", word: "中", reading: "なか", romaji: "naka", meaning: "안·속", pos: "명사", category: "place",
    example: { tokens: [{ t: "鞄", r: "かばん" }, { t: "の" }, { t: "中", r: "なか" }, { t: "に" }, { t: "あります。" }], ko: "가방 안에 있습니다." } },
  { id: "b2_24", word: "外", reading: "そと", romaji: "soto", meaning: "밖", pos: "명사", category: "place",
    example: { tokens: [{ t: "外", r: "そと" }, { t: "は" }, { t: "寒", r: "さむ" }, { t: "いです。" }], ko: "밖은 춥습니다." } },
  { id: "b2_25", word: "横", reading: "よこ", romaji: "yoko", meaning: "옆·가로", pos: "명사", category: "place",
    example: { tokens: [{ t: "店", r: "みせ" }, { t: "の" }, { t: "横", r: "よこ" }, { t: "に" }, { t: "あります。" }], ko: "가게 옆에 있습니다." } },
  { id: "b2_26", word: "そば", reading: "そば", romaji: "soba", meaning: "곁·근처", pos: "명사", category: "place",
    example: { tokens: [{ t: "駅", r: "えき" }, { t: "の" }, { t: "そば" }, { t: "に" }, { t: "あります。" }], ko: "역 근처에 있습니다." } },
  { id: "b2_27", word: "間", reading: "あいだ", romaji: "aida", meaning: "사이", pos: "명사", category: "place",
    example: { tokens: [{ t: "店", r: "みせ" }, { t: "と" }, { t: "店", r: "みせ" }, { t: "の" }, { t: "間", r: "あいだ" }, { t: "です。" }], ko: "가게와 가게 사이입니다." } },
  { id: "b2_28", word: "向こう", reading: "むこう", romaji: "mukou", meaning: "맞은편·저쪽", pos: "명사", category: "place",
    example: { tokens: [{ t: "向", r: "む" }, { t: "こう" }, { t: "に" }, { t: "見", r: "み" }, { t: "えます。" }], ko: "저쪽에 보입니다." } },
  { id: "b2_29", word: "駐車場", reading: "ちゅうしゃじょう", romaji: "chuushajou", meaning: "주차장", pos: "명사", category: "place",
    example: { tokens: [{ t: "駐車場", r: "ちゅうしゃじょう" }, { t: "は" }, { t: "広", r: "ひろ" }, { t: "いです。" }], ko: "주차장은 넓습니다." } },
  { id: "b2_30", word: "ホテル", reading: "ほてる", romaji: "hoteru", meaning: "호텔", pos: "명사", category: "place",
    example: { tokens: [{ t: "ホテル" }, { t: "に" }, { t: "泊", r: "と" }, { t: "まります。" }], ko: "호텔에 묵습니다." } },
  { id: "b2_31", word: "旅館", reading: "りょかん", romaji: "ryokan", meaning: "여관", pos: "명사", category: "place",
    example: { tokens: [{ t: "旅館", r: "りょかん" }, { t: "は" }, { t: "静", r: "しず" }, { t: "かです。" }], ko: "여관은 조용합니다." } },
  { id: "b2_32", word: "飛行機", reading: "ひこうき", romaji: "hikouki", meaning: "비행기", pos: "명사", category: "place",
    example: { tokens: [{ t: "飛行機", r: "ひこうき" }, { t: "に" }, { t: "乗", r: "の" }, { t: "ります。" }], ko: "비행기를 탑니다." } },
  { id: "b2_33", word: "船", reading: "ふね", romaji: "fune", meaning: "배", pos: "명사", category: "place",
    example: { tokens: [{ t: "船", r: "ふね" }, { t: "で" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "배로 갑니다." } },
  { id: "b2_34", word: "自転車", reading: "じてんしゃ", romaji: "jitensha", meaning: "자전거", pos: "명사", category: "place",
    example: { tokens: [{ t: "自転車", r: "じてんしゃ" }, { t: "で" }, { t: "来", r: "き" }, { t: "ました。" }], ko: "자전거로 왔습니다." } },
  { id: "b2_35", word: "バス", reading: "ばす", romaji: "basu", meaning: "버스", pos: "명사", category: "place",
    example: { tokens: [{ t: "バス" }, { t: "で" }, { t: "学校", r: "がっこう" }, { t: "へ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "버스로 학교에 갑니다." } },
  { id: "b2_36", word: "タクシー", reading: "たくしー", romaji: "takushii", meaning: "택시", pos: "명사", category: "place",
    example: { tokens: [{ t: "タクシー" }, { t: "を" }, { t: "呼", r: "よ" }, { t: "びます。" }], ko: "택시를 부릅니다." } },
  { id: "b2_37", word: "地下鉄", reading: "ちかてつ", romaji: "chikatetsu", meaning: "지하철", pos: "명사", category: "place",
    example: { tokens: [{ t: "地下鉄", r: "ちかてつ" }, { t: "に" }, { t: "乗", r: "の" }, { t: "ります。" }], ko: "지하철을 탑니다." } },
  { id: "b2_38", word: "切符", reading: "きっぷ", romaji: "kippu", meaning: "표·티켓", pos: "명사", category: "place",
    example: { tokens: [{ t: "切符", r: "きっぷ" }, { t: "を" }, { t: "買", r: "か" }, { t: "います。" }], ko: "표를 삽니다." } },
  { id: "b2_39", word: "道路", reading: "どうろ", romaji: "douro", meaning: "도로", pos: "명사", category: "place",
    example: { tokens: [{ t: "道路", r: "どうろ" }, { t: "が" }, { t: "広", r: "ひろ" }, { t: "いです。" }], ko: "도로가 넓습니다." } },
  { id: "b2_40", word: "信号", reading: "しんごう", romaji: "shingou", meaning: "신호등", pos: "명사", category: "place",
    example: { tokens: [{ t: "信号", r: "しんごう" }, { t: "が" }, { t: "赤", r: "あか" }, { t: "です。" }], ko: "신호등이 빨강입니다." } },
  { id: "b2_41", word: "交差点", reading: "こうさてん", romaji: "kousaten", meaning: "교차로", pos: "명사", category: "place",
    example: { tokens: [{ t: "交差点", r: "こうさてん" }, { t: "を" }, { t: "渡", r: "わた" }, { t: "ります。" }], ko: "교차로를 건넙니다." } },
  { id: "b2_42", word: "階段", reading: "かいだん", romaji: "kaidan", meaning: "계단", pos: "명사", category: "place",
    example: { tokens: [{ t: "階段", r: "かいだん" }, { t: "を" }, { t: "上", r: "のぼ" }, { t: "ります。" }], ko: "계단을 올라갑니다." } },
  { id: "b2_43", word: "エレベーター", reading: "えれべーたー", romaji: "erebeetaa", meaning: "엘리베이터", pos: "명사", category: "place",
    example: { tokens: [{ t: "エレベーター" }, { t: "に" }, { t: "乗", r: "の" }, { t: "ります。" }], ko: "엘리베이터를 탑니다." } },
  { id: "b2_44", word: "場所", reading: "ばしょ", romaji: "basho", meaning: "장소", pos: "명사", category: "place",
    example: { tokens: [{ t: "場所", r: "ばしょ" }, { t: "を" }, { t: "教", r: "おし" }, { t: "えてください。" }], ko: "장소를 알려 주세요." } },
  { id: "b2_45", word: "国", reading: "くに", romaji: "kuni", meaning: "나라", pos: "명사", category: "place",
    example: { tokens: [{ t: "どの" }, { t: "国", r: "くに" }, { t: "から" }, { t: "来", r: "き" }, { t: "ましたか。" }], ko: "어느 나라에서 왔어요?" } },
  { id: "b2_46", word: "町", reading: "まち", romaji: "machi", meaning: "마을·동네", pos: "명사", category: "place",
    example: { tokens: [{ t: "この" }, { t: "町", r: "まち" }, { t: "は" }, { t: "静", r: "しず" }, { t: "かです。" }], ko: "이 동네는 조용합니다." } },
  { id: "b2_47", word: "村", reading: "むら", romaji: "mura", meaning: "마을·촌", pos: "명사", category: "place",
    example: { tokens: [{ t: "小", r: "ちい" }, { t: "さい" }, { t: "村", r: "むら" }, { t: "です。" }], ko: "작은 마을입니다." } },
  { id: "b2_48", word: "都市", reading: "とし", romaji: "toshi", meaning: "도시", pos: "명사", category: "place",
    example: { tokens: [{ t: "大", r: "おお" }, { t: "きい" }, { t: "都市", r: "とし" }, { t: "です。" }], ko: "큰 도시입니다." } },
  { id: "b2_49", word: "東京", reading: "とうきょう", romaji: "toukyou", meaning: "도쿄", pos: "명사", category: "place",
    example: { tokens: [{ t: "東京", r: "とうきょう" }, { t: "へ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "도쿄에 갑니다." } },
  { id: "b2_50", word: "北", reading: "きた", romaji: "kita", meaning: "북쪽", pos: "명사", category: "place",
    example: { tokens: [{ t: "北", r: "きた" }, { t: "へ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "북쪽으로 갑니다." } },
  { id: "b2_51", word: "南", reading: "みなみ", romaji: "minami", meaning: "남쪽", pos: "명사", category: "place",
    example: { tokens: [{ t: "南", r: "みなみ" }, { t: "は" }, { t: "暖", r: "あたた" }, { t: "かいです。" }], ko: "남쪽은 따뜻합니다." } },
  { id: "b2_52", word: "東", reading: "ひがし", romaji: "higashi", meaning: "동쪽", pos: "명사", category: "place",
    example: { tokens: [{ t: "東", r: "ひがし" }, { t: "の" }, { t: "空", r: "そら" }, { t: "が" }, { t: "明", r: "あか" }, { t: "るいです。" }], ko: "동쪽 하늘이 밝습니다." } },
  { id: "b2_53", word: "西", reading: "にし", romaji: "nishi", meaning: "서쪽", pos: "명사", category: "place",
    example: { tokens: [{ t: "西", r: "にし" }, { t: "の" }, { t: "出口", r: "でぐち" }, { t: "です。" }], ko: "서쪽 출구입니다." } },
  { id: "b2_54", word: "所", reading: "ところ", romaji: "tokoro", meaning: "곳·장소", pos: "명사", category: "place",
    example: { tokens: [{ t: "静", r: "しず" }, { t: "かな" }, { t: "所", r: "ところ" }, { t: "です。" }], ko: "조용한 곳입니다." } },
  { id: "b2_55", word: "建物", reading: "たてもの", romaji: "tatemono", meaning: "건물", pos: "명사", category: "place",
    example: { tokens: [{ t: "高", r: "たか" }, { t: "い" }, { t: "建物", r: "たてもの" }, { t: "です。" }], ko: "높은 건물입니다." } },
  { id: "b2_56", word: "公司", reading: "こうし", romaji: "koushi", meaning: "관청·공공기관", pos: "명사", category: "place",
    example: { tokens: [{ t: "公司", r: "こうし" }, { t: "の" }, { t: "前", r: "まえ" }, { t: "です。" }], ko: "관공서 앞입니다." } },
  { id: "b2_57", word: "店内", reading: "てんない", romaji: "tennai", meaning: "가게 안", pos: "명사", category: "place",
    example: { tokens: [{ t: "店内", r: "てんない" }, { t: "は" }, { t: "静", r: "しず" }, { t: "かです。" }], ko: "가게 안은 조용합니다." } },
  { id: "b2_58", word: "屋上", reading: "おくじょう", romaji: "okujou", meaning: "옥상", pos: "명사", category: "place",
    example: { tokens: [{ t: "屋上", r: "おくじょう" }, { t: "へ" }, { t: "行", r: "い" }, { t: "きます。" }], ko: "옥상에 갑니다." } },
  { id: "b2_59", word: "地図", reading: "ちず", romaji: "chizu", meaning: "지도", pos: "명사", category: "place",
    example: { tokens: [{ t: "地図", r: "ちず" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "지도를 봅니다." } },
  { id: "b2_60", word: "番号", reading: "ばんごう", romaji: "bangou", meaning: "번호", pos: "명사", category: "place",
    example: { tokens: [{ t: "部屋", r: "へや" }, { t: "の" }, { t: "番号", r: "ばんごう" }, { t: "です。" }], ko: "방 번호입니다." } },
  { id: "b2_61", word: "遠い", reading: "とおい", romaji: "tooi", meaning: "멀다", pos: "い형용사", category: "place",
    example: { tokens: [{ t: "駅", r: "えき" }, { t: "は" }, { t: "遠", r: "とお" }, { t: "いです。" }], ko: "역은 멉니다." } },

  // ===== daily (생활·사물·집·가구·문구·전자제품·의류·일용품) =====
  { id: "b2_62", word: "机", reading: "つくえ", romaji: "tsukue", meaning: "책상", pos: "명사", category: "daily",
    example: { tokens: [{ t: "机", r: "つくえ" }, { t: "の" }, { t: "上", r: "うえ" }, { t: "を" }, { t: "片付", r: "かたづ" }, { t: "けます。" }], ko: "책상 위를 정리합니다." } },
  { id: "b2_63", word: "ベッド", reading: "べっど", romaji: "beddo", meaning: "침대", pos: "명사", category: "daily",
    example: { tokens: [{ t: "ベッド" }, { t: "で" }, { t: "寝", r: "ね" }, { t: "ます。" }], ko: "침대에서 잡니다." } },
  { id: "b2_64", word: "窓", reading: "まど", romaji: "mado", meaning: "창문", pos: "명사", category: "daily",
    example: { tokens: [{ t: "窓", r: "まど" }, { t: "を" }, { t: "開", r: "あ" }, { t: "けます。" }], ko: "창문을 엽니다." } },
  { id: "b2_65", word: "ドア", reading: "どあ", romaji: "doa", meaning: "문", pos: "명사", category: "daily",
    example: { tokens: [{ t: "ドア" }, { t: "を" }, { t: "閉", r: "し" }, { t: "めます。" }], ko: "문을 닫습니다." } },
  { id: "b2_66", word: "壁", reading: "かべ", romaji: "kabe", meaning: "벽", pos: "명사", category: "daily",
    example: { tokens: [{ t: "壁", r: "かべ" }, { t: "に" }, { t: "写真", r: "しゃしん" }, { t: "を" }, { t: "貼", r: "は" }, { t: "ります。" }], ko: "벽에 사진을 붙입니다." } },
  { id: "b2_67", word: "台所", reading: "だいどころ", romaji: "daidokoro", meaning: "부엌", pos: "명사", category: "daily",
    example: { tokens: [{ t: "台所", r: "だいどころ" }, { t: "で" }, { t: "料理", r: "りょうり" }, { t: "します。" }], ko: "부엌에서 요리합니다." } },
  { id: "b2_68", word: "お風呂", reading: "おふろ", romaji: "ofuro", meaning: "욕조·목욕", pos: "명사", category: "daily",
    example: { tokens: [{ t: "お" }, { t: "風呂", r: "ふろ" }, { t: "に" }, { t: "入", r: "はい" }, { t: "ります。" }], ko: "목욕을 합니다." } },
  { id: "b2_69", word: "玄関", reading: "げんかん", romaji: "genkan", meaning: "현관", pos: "명사", category: "daily",
    example: { tokens: [{ t: "玄関", r: "げんかん" }, { t: "で" }, { t: "靴", r: "くつ" }, { t: "を" }, { t: "脱", r: "ぬ" }, { t: "ぎます。" }], ko: "현관에서 신발을 벗습니다." } },
  { id: "b2_70", word: "棚", reading: "たな", romaji: "tana", meaning: "선반", pos: "명사", category: "daily",
    example: { tokens: [{ t: "棚", r: "たな" }, { t: "に" }, { t: "本", r: "ほん" }, { t: "を" }, { t: "置", r: "お" }, { t: "きます。" }], ko: "선반에 책을 둡니다." } },
  { id: "b2_71", word: "冷蔵庫", reading: "れいぞうこ", romaji: "reizouko", meaning: "냉장고", pos: "명사", category: "daily",
    example: { tokens: [{ t: "冷蔵庫", r: "れいぞうこ" }, { t: "に" }, { t: "牛乳", r: "ぎゅうにゅう" }, { t: "が" }, { t: "あります。" }], ko: "냉장고에 우유가 있습니다." } },
  { id: "b2_72", word: "テレビ", reading: "てれび", romaji: "terebi", meaning: "텔레비전", pos: "명사", category: "daily",
    example: { tokens: [{ t: "テレビ" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "텔레비전을 봅니다." } },
  { id: "b2_73", word: "ラジオ", reading: "らじお", romaji: "rajio", meaning: "라디오", pos: "명사", category: "daily",
    example: { tokens: [{ t: "ラジオ" }, { t: "を" }, { t: "聞", r: "き" }, { t: "きます。" }], ko: "라디오를 듣습니다." } },
  { id: "b2_74", word: "パソコン", reading: "ぱそこん", romaji: "pasokon", meaning: "컴퓨터", pos: "명사", category: "daily",
    example: { tokens: [{ t: "パソコン" }, { t: "で" }, { t: "仕事", r: "しごと" }, { t: "します。" }], ko: "컴퓨터로 일합니다." } },
  { id: "b2_75", word: "時計", reading: "とけい", romaji: "tokei", meaning: "시계", pos: "명사", category: "daily",
    example: { tokens: [{ t: "時計", r: "とけい" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "시계를 봅니다." } },
  { id: "b2_76", word: "カメラ", reading: "かめら", romaji: "kamera", meaning: "카메라", pos: "명사", category: "daily",
    example: { tokens: [{ t: "カメラ" }, { t: "で" }, { t: "撮", r: "と" }, { t: "ります。" }], ko: "카메라로 찍습니다." } },
  { id: "b2_77", word: "鏡", reading: "かがみ", romaji: "kagami", meaning: "거울", pos: "명사", category: "daily",
    example: { tokens: [{ t: "鏡", r: "かがみ" }, { t: "を" }, { t: "見", r: "み" }, { t: "ます。" }], ko: "거울을 봅니다." } },
  { id: "b2_78", word: "タオル", reading: "たおる", romaji: "taoru", meaning: "수건", pos: "명사", category: "daily",
    example: { tokens: [{ t: "タオル" }, { t: "で" }, { t: "手", r: "て" }, { t: "を" }, { t: "拭", r: "ふ" }, { t: "きます。" }], ko: "수건으로 손을 닦습니다." } },
  { id: "b2_79", word: "石鹸", reading: "せっけん", romaji: "sekken", meaning: "비누", pos: "명사", category: "daily",
    example: { tokens: [{ t: "石鹸", r: "せっけん" }, { t: "で" }, { t: "手", r: "て" }, { t: "を" }, { t: "洗", r: "あら" }, { t: "います。" }], ko: "비누로 손을 씻습니다." } },
  { id: "b2_80", word: "歯ブラシ", reading: "はぶらし", romaji: "haburashi", meaning: "칫솔", pos: "명사", category: "daily",
    example: { tokens: [{ t: "歯", r: "は" }, { t: "ブラシ" }, { t: "を" }, { t: "使", r: "つか" }, { t: "います。" }], ko: "칫솔을 씁니다." } },
  { id: "b2_81", word: "紙", reading: "かみ", romaji: "kami", meaning: "종이", pos: "명사", category: "daily",
    example: { tokens: [{ t: "紙", r: "かみ" }, { t: "に" }, { t: "書", r: "か" }, { t: "きます。" }], ko: "종이에 씁니다." } },
  { id: "b2_82", word: "ノート", reading: "のーと", romaji: "nooto", meaning: "공책", pos: "명사", category: "daily",
    example: { tokens: [{ t: "ノート" }, { t: "に" }, { t: "書", r: "か" }, { t: "きます。" }], ko: "공책에 씁니다." } },
  { id: "b2_83", word: "鉛筆", reading: "えんぴつ", romaji: "enpitsu", meaning: "연필", pos: "명사", category: "daily",
    example: { tokens: [{ t: "鉛筆", r: "えんぴつ" }, { t: "で" }, { t: "書", r: "か" }, { t: "きます。" }], ko: "연필로 씁니다." } },
  { id: "b2_84", word: "ペン", reading: "ぺん", romaji: "pen", meaning: "펜", pos: "명사", category: "daily",
    example: { tokens: [{ t: "ペン" }, { t: "を" }, { t: "貸", r: "か" }, { t: "してください。" }], ko: "펜을 빌려 주세요." } },
  { id: "b2_85", word: "消しゴム", reading: "けしゴム", romaji: "keshigomu", meaning: "지우개", pos: "명사", category: "daily",
    example: { tokens: [{ t: "消", r: "け" }, { t: "しゴム" }, { t: "で" }, { t: "消", r: "け" }, { t: "します。" }], ko: "지우개로 지웁니다." } },
  { id: "b2_86", word: "辞書", reading: "じしょ", romaji: "jisho", meaning: "사전", pos: "명사", category: "daily",
    example: { tokens: [{ t: "辞書", r: "じしょ" }, { t: "を" }, { t: "引", r: "ひ" }, { t: "きます。" }], ko: "사전을 찾습니다." } },
  { id: "b2_87", word: "雑誌", reading: "ざっし", romaji: "zasshi", meaning: "잡지", pos: "명사", category: "daily",
    example: { tokens: [{ t: "雑誌", r: "ざっし" }, { t: "を" }, { t: "読", r: "よ" }, { t: "みます。" }], ko: "잡지를 읽습니다." } },
  { id: "b2_88", word: "新聞", reading: "しんぶん", romaji: "shinbun", meaning: "신문", pos: "명사", category: "daily",
    example: { tokens: [{ t: "新聞", r: "しんぶん" }, { t: "を" }, { t: "読", r: "よ" }, { t: "みます。" }], ko: "신문을 읽습니다." } },
  { id: "b2_89", word: "手紙", reading: "てがみ", romaji: "tegami", meaning: "편지", pos: "명사", category: "daily",
    example: { tokens: [{ t: "手紙", r: "てがみ" }, { t: "を" }, { t: "書", r: "か" }, { t: "きます。" }], ko: "편지를 씁니다." } },
  { id: "b2_90", word: "切手", reading: "きって", romaji: "kitte", meaning: "우표", pos: "명사", category: "daily",
    example: { tokens: [{ t: "切手", r: "きって" }, { t: "を" }, { t: "貼", r: "は" }, { t: "ります。" }], ko: "우표를 붙입니다." } },
  { id: "b2_91", word: "葉書", reading: "はがき", romaji: "hagaki", meaning: "엽서", pos: "명사", category: "daily",
    example: { tokens: [{ t: "葉書", r: "はがき" }, { t: "を" }, { t: "送", r: "おく" }, { t: "ります。" }], ko: "엽서를 보냅니다." } },
  { id: "b2_92", word: "鞄", reading: "かばん", romaji: "kaban", meaning: "가방", pos: "명사", category: "daily",
    example: { tokens: [{ t: "鞄", r: "かばん" }, { t: "を" }, { t: "持", r: "も" }, { t: "ちます。" }], ko: "가방을 듭니다." } },
  { id: "b2_93", word: "財布", reading: "さいふ", romaji: "saifu", meaning: "지갑", pos: "명사", category: "daily",
    example: { tokens: [{ t: "財布", r: "さいふ" }, { t: "を" }, { t: "忘", r: "わす" }, { t: "れました。" }], ko: "지갑을 잊었습니다." } },
  { id: "b2_94", word: "眼鏡", reading: "めがね", romaji: "megane", meaning: "안경", pos: "명사", category: "daily",
    example: { tokens: [{ t: "眼鏡", r: "めがね" }, { t: "を" }, { t: "かけます。" }], ko: "안경을 씁니다." } },
  { id: "b2_95", word: "帽子", reading: "ぼうし", romaji: "boushi", meaning: "모자", pos: "명사", category: "daily",
    example: { tokens: [{ t: "帽子", r: "ぼうし" }, { t: "を" }, { t: "かぶります。" }], ko: "모자를 씁니다." } },
  { id: "b2_96", word: "靴", reading: "くつ", romaji: "kutsu", meaning: "신발", pos: "명사", category: "daily",
    example: { tokens: [{ t: "靴", r: "くつ" }, { t: "を" }, { t: "履", r: "は" }, { t: "きます。" }], ko: "신발을 신습니다." } },
  { id: "b2_97", word: "靴下", reading: "くつした", romaji: "kutsushita", meaning: "양말", pos: "명사", category: "daily",
    example: { tokens: [{ t: "靴下", r: "くつした" }, { t: "を" }, { t: "履", r: "は" }, { t: "きます。" }], ko: "양말을 신습니다." } },
  { id: "b2_98", word: "シャツ", reading: "しゃつ", romaji: "shatsu", meaning: "셔츠", pos: "명사", category: "daily",
    example: { tokens: [{ t: "白", r: "しろ" }, { t: "い" }, { t: "シャツ" }, { t: "を" }, { t: "着", r: "き" }, { t: "ます。" }], ko: "흰 셔츠를 입습니다." } },
  { id: "b2_99", word: "ズボン", reading: "ずぼん", romaji: "zubon", meaning: "바지", pos: "명사", category: "daily",
    example: { tokens: [{ t: "ズボン" }, { t: "を" }, { t: "履", r: "は" }, { t: "きます。" }], ko: "바지를 입습니다." } },
  { id: "b2_100", word: "スカート", reading: "すかーと", romaji: "sukaato", meaning: "치마", pos: "명사", category: "daily",
    example: { tokens: [{ t: "スカート" }, { t: "が" }, { t: "短", r: "みじか" }, { t: "いです。" }], ko: "치마가 짧습니다." } },
  { id: "b2_101", word: "上着", reading: "うわぎ", romaji: "uwagi", meaning: "겉옷·상의", pos: "명사", category: "daily",
    example: { tokens: [{ t: "上着", r: "うわぎ" }, { t: "を" }, { t: "脱", r: "ぬ" }, { t: "ぎます。" }], ko: "겉옷을 벗습니다." } },
  { id: "b2_102", word: "コート", reading: "こーと", romaji: "kooto", meaning: "코트", pos: "명사", category: "daily",
    example: { tokens: [{ t: "コート" }, { t: "を" }, { t: "着", r: "き" }, { t: "ます。" }], ko: "코트를 입습니다." } },
  { id: "b2_103", word: "ボタン", reading: "ぼたん", romaji: "botan", meaning: "단추·버튼", pos: "명사", category: "daily",
    example: { tokens: [{ t: "ボタン" }, { t: "を" }, { t: "押", r: "お" }, { t: "します。" }], ko: "버튼을 누릅니다." } },
  { id: "b2_104", word: "お皿", reading: "おさら", romaji: "osara", meaning: "접시", pos: "명사", category: "daily",
    example: { tokens: [{ t: "お" }, { t: "皿", r: "さら" }, { t: "を" }, { t: "洗", r: "あら" }, { t: "います。" }], ko: "접시를 씻습니다." } },
  { id: "b2_105", word: "コップ", reading: "こっぷ", romaji: "koppu", meaning: "컵", pos: "명사", category: "daily",
    example: { tokens: [{ t: "コップ" }, { t: "に" }, { t: "水", r: "みず" }, { t: "を" }, { t: "入", r: "い" }, { t: "れます。" }], ko: "컵에 물을 넣습니다." } },
  { id: "b2_106", word: "箱", reading: "はこ", romaji: "hako", meaning: "상자", pos: "명사", category: "daily",
    example: { tokens: [{ t: "箱", r: "はこ" }, { t: "を" }, { t: "開", r: "あ" }, { t: "けます。" }], ko: "상자를 엽니다." } },
  { id: "b2_107", word: "袋", reading: "ふくろ", romaji: "fukuro", meaning: "봉지·자루", pos: "명사", category: "daily",
    example: { tokens: [{ t: "袋", r: "ふくろ" }, { t: "に" }, { t: "入", r: "い" }, { t: "れます。" }], ko: "봉지에 넣습니다." } },
  { id: "b2_108", word: "荷物", reading: "にもつ", romaji: "nimotsu", meaning: "짐", pos: "명사", category: "daily",
    example: { tokens: [{ t: "荷物", r: "にもつ" }, { t: "が" }, { t: "重", r: "おも" }, { t: "いです。" }], ko: "짐이 무겁습니다." } },
  { id: "b2_109", word: "物", reading: "もの", romaji: "mono", meaning: "물건·것", pos: "명사", category: "daily",
    example: { tokens: [{ t: "高", r: "たか" }, { t: "い" }, { t: "物", r: "もの" }, { t: "です。" }], ko: "비싼 물건입니다." } },
  { id: "b2_110", word: "道具", reading: "どうぐ", romaji: "dougu", meaning: "도구", pos: "명사", category: "daily",
    example: { tokens: [{ t: "道具", r: "どうぐ" }, { t: "を" }, { t: "使", r: "つか" }, { t: "います。" }], ko: "도구를 씁니다." } },
  { id: "b2_111", word: "電気", reading: "でんき", romaji: "denki", meaning: "전기·전등", pos: "명사", category: "daily",
    example: { tokens: [{ t: "電気", r: "でんき" }, { t: "を" }, { t: "消", r: "け" }, { t: "します。" }], ko: "전등을 끕니다." } },
  { id: "b2_112", word: "冷房", reading: "れいぼう", romaji: "reibou", meaning: "냉방·에어컨", pos: "명사", category: "daily",
    example: { tokens: [{ t: "冷房", r: "れいぼう" }, { t: "を" }, { t: "つけます。" }], ko: "냉방을 켭니다." } },
  { id: "b2_113", word: "暖房", reading: "だんぼう", romaji: "danbou", meaning: "난방", pos: "명사", category: "daily",
    example: { tokens: [{ t: "暖房", r: "だんぼう" }, { t: "を" }, { t: "つけます。" }], ko: "난방을 켭니다." } },
  { id: "b2_114", word: "電池", reading: "でんち", romaji: "denchi", meaning: "건전지", pos: "명사", category: "daily",
    example: { tokens: [{ t: "電池", r: "でんち" }, { t: "を" }, { t: "買", r: "か" }, { t: "います。" }], ko: "건전지를 삽니다." } },
  { id: "b2_115", word: "皿洗い", reading: "さらあらい", romaji: "saraarai", meaning: "설거지", pos: "명사", category: "daily",
    example: { tokens: [{ t: "皿洗", r: "さらあら" }, { t: "い" }, { t: "を" }, { t: "します。" }], ko: "설거지를 합니다." } },
  { id: "b2_116", word: "布団", reading: "ふとん", romaji: "futon", meaning: "이불", pos: "명사", category: "daily",
    example: { tokens: [{ t: "布団", r: "ふとん" }, { t: "を" }, { t: "干", r: "ほ" }, { t: "します。" }], ko: "이불을 말립니다." } },
  { id: "b2_117", word: "枕", reading: "まくら", romaji: "makura", meaning: "베개", pos: "명사", category: "daily",
    example: { tokens: [{ t: "枕", r: "まくら" }, { t: "が" }, { t: "柔", r: "やわ" }, { t: "らかいです。" }], ko: "베개가 부드럽습니다." } },
  { id: "b2_118", word: "毛布", reading: "もうふ", romaji: "moufu", meaning: "담요", pos: "명사", category: "daily",
    example: { tokens: [{ t: "毛布", r: "もうふ" }, { t: "を" }, { t: "かけます。" }], ko: "담요를 덮습니다." } },
  { id: "b2_119", word: "歯磨き粉", reading: "はみがきこ", romaji: "hamigakiko", meaning: "치약", pos: "명사", category: "daily",
    example: { tokens: [{ t: "歯磨", r: "はみが" }, { t: "き" }, { t: "粉", r: "こ" }, { t: "を" }, { t: "使", r: "つか" }, { t: "います。" }], ko: "치약을 씁니다." } },
  { id: "b2_120", word: "ハンカチ", reading: "はんかち", romaji: "hankachi", meaning: "손수건", pos: "명사", category: "daily",
    example: { tokens: [{ t: "ハンカチ" }, { t: "を" }, { t: "持", r: "も" }, { t: "ちます。" }], ko: "손수건을 가집니다." } },
  { id: "b2_121", word: "ティッシュ", reading: "てぃっしゅ", romaji: "tisshu", meaning: "휴지·티슈", pos: "명사", category: "daily",
    example: { tokens: [{ t: "ティッシュ" }, { t: "を" }, { t: "ください。" }], ko: "티슈를 주세요." } },
  { id: "b2_122", word: "ナイフ", reading: "ないふ", romaji: "naifu", meaning: "칼·나이프", pos: "명사", category: "daily",
    example: { tokens: [{ t: "ナイフ" }, { t: "で" }, { t: "切", r: "き" }, { t: "ります。" }], ko: "나이프로 자릅니다." } },
  { id: "b2_123", word: "箸", reading: "はし", romaji: "hashi", meaning: "젓가락", pos: "명사", category: "daily",
    example: { tokens: [{ t: "箸", r: "はし" }, { t: "で" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "젓가락으로 먹습니다." } },
  { id: "b2_124", word: "スプーン", reading: "すぷーん", romaji: "supuun", meaning: "숟가락", pos: "명사", category: "daily",
    example: { tokens: [{ t: "スプーン" }, { t: "で" }, { t: "食", r: "た" }, { t: "べます。" }], ko: "숟가락으로 먹습니다." } },
  { id: "b2_125", word: "フォーク", reading: "ふぉーく", romaji: "fooku", meaning: "포크", pos: "명사", category: "daily",
    example: { tokens: [{ t: "フォーク" }, { t: "を" }, { t: "使", r: "つか" }, { t: "います。" }], ko: "포크를 씁니다." } },
  { id: "b2_126", word: "茶碗", reading: "ちゃわん", romaji: "chawan", meaning: "밥공기", pos: "명사", category: "daily",
    example: { tokens: [{ t: "茶碗", r: "ちゃわん" }, { t: "に" }, { t: "ご" }, { t: "飯", r: "はん" }, { t: "を" }, { t: "入", r: "い" }, { t: "れます。" }], ko: "공기에 밥을 담습니다." } },
  { id: "b2_127", word: "鍋", reading: "なべ", romaji: "nabe", meaning: "냄비", pos: "명사", category: "daily",
    example: { tokens: [{ t: "鍋", r: "なべ" }, { t: "で" }, { t: "作", r: "つく" }, { t: "ります。" }], ko: "냄비로 만듭니다." } },
  { id: "b2_128", word: "薬", reading: "くすり", romaji: "kusuri", meaning: "약", pos: "명사", category: "daily",
    example: { tokens: [{ t: "薬", r: "くすり" }, { t: "を" }, { t: "飲", r: "の" }, { t: "みます。" }], ko: "약을 먹습니다." } },
  { id: "b2_129", word: "鉛筆削り", reading: "えんぴつけずり", romaji: "enpitsukezuri", meaning: "연필깎이", pos: "명사", category: "daily",
    example: { tokens: [{ t: "鉛筆削", r: "えんぴつけず" }, { t: "り" }, { t: "を" }, { t: "使", r: "つか" }, { t: "います。" }], ko: "연필깎이를 씁니다." } },
  { id: "b2_130", word: "はさみ", reading: "はさみ", romaji: "hasami", meaning: "가위", pos: "명사", category: "daily",
    example: { tokens: [{ t: "はさみ" }, { t: "で" }, { t: "切", r: "き" }, { t: "ります。" }], ko: "가위로 자릅니다." } },
  { id: "b2_131", word: "封筒", reading: "ふうとう", romaji: "fuutou", meaning: "봉투", pos: "명사", category: "daily",
    example: { tokens: [{ t: "封筒", r: "ふうとう" }, { t: "に" }, { t: "入", r: "い" }, { t: "れます。" }], ko: "봉투에 넣습니다." } },
  { id: "b2_132", word: "新しい靴", reading: "あたらしいくつ", romaji: "atarashii kutsu", meaning: "새 신발", pos: "명사", category: "daily",
    example: { tokens: [{ t: "新", r: "あたら" }, { t: "しい" }, { t: "靴", r: "くつ" }, { t: "が" }, { t: "ほしいです。" }], ko: "새 신발을 갖고 싶습니다." } },
  { id: "b2_133", word: "汚い", reading: "きたない", romaji: "kitanai", meaning: "더럽다", pos: "い형용사", category: "daily",
    example: { tokens: [{ t: "部屋", r: "へや" }, { t: "が" }, { t: "汚", r: "きたな" }, { t: "いです。" }], ko: "방이 더럽습니다." } },
  { id: "b2_134", word: "明るい", reading: "あかるい", romaji: "akarui", meaning: "밝다", pos: "い형용사", category: "daily",
    example: { tokens: [{ t: "部屋", r: "へや" }, { t: "が" }, { t: "明", r: "あか" }, { t: "るいです。" }], ko: "방이 밝습니다." } },
  { id: "b2_135", word: "暗い", reading: "くらい", romaji: "kurai", meaning: "어둡다", pos: "い형용사", category: "daily",
    example: { tokens: [{ t: "外", r: "そと" }, { t: "が" }, { t: "暗", r: "くら" }, { t: "いです。" }], ko: "밖이 어둡습니다." } },
  { id: "b2_136", word: "重い", reading: "おもい", romaji: "omoi", meaning: "무겁다", pos: "い형용사", category: "daily",
    example: { tokens: [{ t: "鞄", r: "かばん" }, { t: "が" }, { t: "重", r: "おも" }, { t: "いです。" }], ko: "가방이 무겁습니다." } },
  { id: "b2_137", word: "軽い", reading: "かるい", romaji: "karui", meaning: "가볍다", pos: "い형용사", category: "daily",
    example: { tokens: [{ t: "荷物", r: "にもつ" }, { t: "が" }, { t: "軽", r: "かる" }, { t: "いです。" }], ko: "짐이 가볍습니다." } },
];
