// 포인트 투 토크 / 긴급 의사소통 카드 — 화면에 크게 띄워 즉석에서 가리키며 소통.
// (은성의료재단 ↔ 가마치그룹 직원 교류용. 오프라인에서도 동작)

import type { MedCardGroup } from "./types";

export const MED_CARDS: MedCardGroup[] = [
  {
    key: "emergency",
    titleKo: "긴급",
    titleJa: "緊急",
    emoji: "🚨",
    cards: [
      {
        ko: "응급실이 어디예요?",
        koRomaja: "eunggeupsiri eodiyeyo?",
        ja: "救急室はどこですか？",
        jaReading: "きゅうきゅうしつはどこですか？",
        icon: "🚑",
        urgent: true,
      },
      {
        ko: "도와주세요!",
        koRomaja: "dowajuseyo!",
        ja: "助けてください！",
        jaReading: "たすけてください！",
        icon: "🆘",
        urgent: true,
      },
      {
        ko: "사람을 불러 주세요",
        koRomaja: "sarameul bulleo juseyo",
        ja: "人を呼んでください",
        jaReading: "ひとをよんでください",
        icon: "🏃",
        urgent: true,
      },
      {
        ko: "통역이 필요해요",
        koRomaja: "tongyeogi piryohaeyo",
        ja: "通訳が必要です",
        jaReading: "つうやくがひつようです",
        icon: "🗣️",
        urgent: true,
      },
      {
        ko: "의사를 불러 주세요",
        koRomaja: "uisareul bulleo juseyo",
        ja: "医師を呼んでください",
        jaReading: "いしをよんでください",
        icon: "👨‍⚕️",
        urgent: true,
      },
      {
        ko: "위급해요",
        koRomaja: "wigeuphaeyo",
        ja: "緊急です",
        jaReading: "きんきゅうです",
        icon: "⚠️",
        urgent: true,
      },
      {
        ko: "알레르기가 있어요",
        koRomaja: "allereugiga isseoyo",
        ja: "アレルギーがあります",
        jaReading: "あれるぎーがあります",
        icon: "🤧",
        urgent: true,
      },
    ],
  },
  {
    key: "basic",
    titleKo: "기본 의사소통",
    titleJa: "基本コミュニケーション",
    emoji: "💬",
    cards: [
      {
        ko: "네",
        koRomaja: "ne",
        ja: "はい",
        jaReading: "はい",
        icon: "⭕",
      },
      {
        ko: "아니요",
        koRomaja: "aniyo",
        ja: "いいえ",
        jaReading: "いいえ",
        icon: "❌",
      },
      {
        ko: "감사합니다",
        koRomaja: "gamsahamnida",
        ja: "ありがとうございます",
        jaReading: "ありがとうございます",
        icon: "🙏",
      },
      {
        ko: "천천히 말해 주세요",
        koRomaja: "cheoncheonhi malhae juseyo",
        ja: "ゆっくり話してください",
        jaReading: "ゆっくりはなしてください",
        icon: "🐢",
      },
      {
        ko: "다시 한 번",
        koRomaja: "dasi han beon",
        ja: "もう一度",
        jaReading: "もういちど",
        icon: "🔁",
      },
      {
        ko: "잘 모르겠어요",
        koRomaja: "jal moreugesseoyo",
        ja: "よくわかりません",
        jaReading: "よくわかりません",
        icon: "🤷",
      },
      {
        ko: "화장실",
        koRomaja: "hwajangsil",
        ja: "トイレ",
        jaReading: "といれ",
        icon: "🚻",
      },
      {
        ko: "잠깐만요",
        koRomaja: "jamkkanmanyo",
        ja: "少々お待ちください",
        jaReading: "しょうしょうおまちください",
        icon: "✋",
      },
    ],
  },
  {
    key: "symptom",
    titleKo: "통증·증상 표현",
    titleJa: "痛み・症状の表現",
    emoji: "🤕",
    cards: [
      {
        ko: "여기가 아파요",
        koRomaja: "yeogiga apayo",
        ja: "ここが痛いです",
        jaReading: "ここがいたいです",
        icon: "👉",
      },
      {
        ko: "머리가 아파요",
        koRomaja: "meoriga apayo",
        ja: "頭が痛いです",
        jaReading: "あたまがいたいです",
        icon: "🤯",
      },
      {
        ko: "숨이 차요",
        koRomaja: "sumi chayo",
        ja: "息が苦しいです",
        jaReading: "いきがくるしいです",
        icon: "😮‍💨",
      },
      {
        ko: "어지러워요",
        koRomaja: "eojireowoyo",
        ja: "めまいがします",
        jaReading: "めまいがします",
        icon: "💫",
      },
      {
        ko: "메스꺼워요",
        koRomaja: "meseukkeowoyo",
        ja: "吐き気がします",
        jaReading: "はきけがします",
        icon: "🤢",
      },
      {
        ko: "열이 나요",
        koRomaja: "yeori nayo",
        ja: "熱があります",
        jaReading: "ねつがあります",
        icon: "🌡️",
      },
      {
        ko: "가슴이 아파요",
        koRomaja: "gaseumi apayo",
        ja: "胸が痛いです",
        jaReading: "むねがいたいです",
        icon: "💔",
      },
    ],
  },
  {
    key: "request",
    titleKo: "안내·요청",
    titleJa: "案内・要請",
    emoji: "🙋",
    cards: [
      {
        ko: "안내해 주세요",
        koRomaja: "annaehae juseyo",
        ja: "案内してください",
        jaReading: "あんないしてください",
        icon: "🧭",
      },
      {
        ko: "여기서 기다리세요",
        koRomaja: "yeogiseo gidariseyo",
        ja: "ここでお待ちください",
        jaReading: "ここでおまちください",
        icon: "⏳",
      },
      {
        ko: "휠체어가 필요해요",
        koRomaja: "hwilcheeoga piryohaeyo",
        ja: "車椅子が必要です",
        jaReading: "くるまいすがひつようです",
        icon: "♿",
      },
      {
        ko: "천천히 오세요",
        koRomaja: "cheoncheonhi oseyo",
        ja: "ゆっくり来てください",
        jaReading: "ゆっくりきてください",
        icon: "🚶",
      },
      {
        ko: "보호자를 불러 주세요",
        koRomaja: "bohojareul bulleo juseyo",
        ja: "付き添いの方を呼んでください",
        jaReading: "つきそいのかたをよんでください",
        icon: "👪",
      },
      {
        ko: "이쪽으로 오세요",
        koRomaja: "ijjogeuro oseyo",
        ja: "こちらへどうぞ",
        jaReading: "こちらへどうぞ",
        icon: "➡️",
      },
    ],
  },
];
