// 포인트-투-토크 양국어 카드 — 화면에 크게 띄워 손가락으로 가리키며 즉시 소통.
// (은성의료재단 ↔ 가마치그룹 직원 상호방문용. 오프라인에서도 동작)
import type { MedCardGroup } from "./types";

export const MED_CARDS: MedCardGroup[] = [
  {
    key: "emergency",
    titleKo: "긴급",
    titleJa: "緊急",
    emoji: "🚨",
    cards: [
      {
        ko: "도와주세요",
        koRomaja: "dowajuseyo",
        ja: "助けてください",
        jaReading: "たすけてください",
        koPron: "トワジュセヨ",
        jaPron: "타스케테 쿠다사이",
        icon: "🆘",
        urgent: true,
      },
      {
        ko: "응급실이 어디예요?",
        koRomaja: "eunggeupsiri eodieyo",
        ja: "救急室はどこですか？",
        jaReading: "きゅうきゅうしつはどこですか",
        koPron: "ウングプシリ オディエヨ",
        jaPron: "큐큐시츠와 도코데스카",
        icon: "🏥",
        urgent: true,
      },
      {
        ko: "의사를 불러 주세요",
        koRomaja: "uisareul bulleo juseyo",
        ja: "医者を呼んでください",
        jaReading: "いしゃをよんでください",
        koPron: "ウィサルル プルロ ジュセヨ",
        jaPron: "이샤오 욘데 쿠다사이",
        icon: "👨‍⚕️",
        urgent: true,
      },
      {
        ko: "통역이 필요해요",
        koRomaja: "tongyeogi piryohaeyo",
        ja: "通訳が必要です",
        jaReading: "つうやくがひつようです",
        koPron: "トンヨギ ピリョヘヨ",
        jaPron: "츠우야쿠가 히츠요우데스",
        icon: "🗣️",
        urgent: true,
      },
      {
        ko: "위급해요",
        koRomaja: "wigeuphaeyo",
        ja: "緊急です",
        jaReading: "きんきゅうです",
        koPron: "ウィグペヨ",
        jaPron: "킨큐우데스",
        icon: "⚠️",
        urgent: true,
      },
      {
        ko: "알레르기가 있어요",
        koRomaja: "allereugiga isseoyo",
        ja: "アレルギーがあります",
        jaReading: "あれるぎーがあります",
        koPron: "アルレルギガ イッソヨ",
        jaPron: "아레루기가 아리마스",
        icon: "🤧",
        urgent: true,
      },
      {
        ko: "구급차를 불러 주세요",
        koRomaja: "gugeupchareul bulleo juseyo",
        ja: "救急車を呼んでください",
        jaReading: "きゅうきゅうしゃをよんでください",
        koPron: "クグプチャルル プルロ ジュセヨ",
        jaPron: "큐큐샤오 욘데 쿠다사이",
        icon: "🚑",
        urgent: true,
      },
      {
        ko: "사람을 불러 주세요",
        koRomaja: "sarameul bulleo juseyo",
        ja: "人を呼んでください",
        jaReading: "ひとをよんでください",
        koPron: "サラムル プルロ ジュセヨ",
        jaPron: "히토오 욘데 쿠다사이",
        icon: "📢",
        urgent: true,
      },
      {
        ko: "길을 잃었어요",
        koRomaja: "gireul ireosseoyo",
        ja: "道に迷いました",
        jaReading: "みちにまよいました",
        koPron: "キルル イロッソヨ",
        jaPron: "미치니 마요이마시타",
        icon: "🧭",
        urgent: true,
      },
      {
        ko: "몸이 안 좋아요",
        koRomaja: "momi an joayo",
        ja: "体調が悪いです",
        jaReading: "たいちょうがわるいです",
        koPron: "モミ アン ジョアヨ",
        jaPron: "타이쵸우가 와루이데스",
        icon: "🤒",
        urgent: true,
      },
    ],
  },
  {
    key: "basic",
    titleKo: "기본 의사소통",
    titleJa: "基本コミュニケーション",
    emoji: "💬",
    cards: [
      {
        ko: "네 / 아니요",
        koRomaja: "ne / aniyo",
        ja: "はい / いいえ",
        jaReading: "はい / いいえ",
        koPron: "ネ / アニヨ",
        jaPron: "하이 / 이이에",
        icon: "✅",
      },
      {
        ko: "감사합니다",
        koRomaja: "gamsahamnida",
        ja: "ありがとうございます",
        jaReading: "ありがとうございます",
        koPron: "カムサハムニダ",
        jaPron: "아리가토우 고자이마스",
        icon: "🙏",
      },
      {
        ko: "죄송합니다",
        koRomaja: "joesonghamnida",
        ja: "すみません",
        jaReading: "すみません",
        koPron: "チェソンハムニダ",
        jaPron: "스미마센",
        icon: "🙇",
      },
      {
        ko: "천천히 말해 주세요",
        koRomaja: "cheoncheonhi malhae juseyo",
        ja: "ゆっくり話してください",
        jaReading: "ゆっくりはなしてください",
        koPron: "チョンチョニ マレ ジュセヨ",
        jaPron: "윳쿠리 하나시테 쿠다사이",
        icon: "🐢",
      },
      {
        ko: "다시 한 번 말해 주세요",
        koRomaja: "dasi han beon malhae juseyo",
        ja: "もう一度言ってください",
        jaReading: "もういちどいってください",
        koPron: "タシ ハン ボン マレ ジュセヨ",
        jaPron: "모우 이치도 잇테 쿠다사이",
        icon: "🔁",
      },
      {
        ko: "잘 모르겠어요",
        koRomaja: "jal moreugesseoyo",
        ja: "よく分かりません",
        jaReading: "よくわかりません",
        koPron: "チャル モルゲッソヨ",
        jaPron: "요쿠 와카리마센",
        icon: "🤔",
      },
      {
        ko: "알겠습니다",
        koRomaja: "algetseumnida",
        ja: "分かりました",
        jaReading: "わかりました",
        koPron: "アルゲッスムニダ",
        jaPron: "와카리마시타",
        icon: "👍",
      },
      {
        ko: "잠깐만요",
        koRomaja: "jamkkanmanyo",
        ja: "ちょっと待ってください",
        jaReading: "ちょっとまってください",
        koPron: "チャムッカンマンニョ",
        jaPron: "춋토 맛테 쿠다사이",
        icon: "✋",
      },
      {
        ko: "괜찮아요",
        koRomaja: "gwaenchanayo",
        ja: "大丈夫です",
        jaReading: "だいじょうぶです",
        koPron: "クェンチャナヨ",
        jaPron: "다이죠우부데스",
        icon: "🆗",
      },
      {
        ko: "부탁합니다",
        koRomaja: "butakhamnida",
        ja: "お願いします",
        jaReading: "おねがいします",
        koPron: "プタカムニダ",
        jaPron: "오네가이시마스",
        icon: "🤲",
      },
      {
        ko: "이름이 뭐예요?",
        koRomaja: "ireumi mwoyeyo",
        ja: "お名前は何ですか？",
        jaReading: "おなまえはなんですか",
        koPron: "イルミ ムォエヨ",
        jaPron: "오나마에와 난데스카",
        icon: "📛",
      },
      {
        ko: "적어 주세요",
        koRomaja: "jeogeo juseyo",
        ja: "書いてください",
        jaReading: "かいてください",
        koPron: "チョゴ ジュセヨ",
        jaPron: "카이테 쿠다사이",
        icon: "✏️",
      },
    ],
  },
  {
    key: "exchange",
    titleKo: "견학·교류",
    titleJa: "見学・交流",
    emoji: "🔬",
    cards: [
      {
        ko: "견학하러 왔습니다",
        koRomaja: "gyeonhakhareo watseumnida",
        ja: "見学に来ました",
        jaReading: "けんがくにきました",
        koPron: "キョンハカロ ワッスムニダ",
        jaPron: "켄가쿠니 키마시타",
        icon: "🔬",
      },
      {
        ko: "참관해도 될까요?",
        koRomaja: "chamgwanhaedo doelkkayo",
        ja: "見学してもいいですか？",
        jaReading: "けんがくしてもいいですか",
        koPron: "チャムグァンヘド トェルッカヨ",
        jaPron: "켄가쿠시테모 이이데스카",
        icon: "👀",
      },
      {
        ko: "사진 찍어도 될까요?",
        koRomaja: "sajin jjigeodo doelkkayo",
        ja: "写真を撮ってもいいですか？",
        jaReading: "しゃしんをとってもいいですか",
        koPron: "サジン ッチゴド トェルッカヨ",
        jaPron: "샤신오 톳테모 이이데스카",
        icon: "📷",
      },
      {
        ko: "안내해 주세요",
        koRomaja: "annaehae juseyo",
        ja: "案内してください",
        jaReading: "あんないしてください",
        koPron: "アンネヘ ジュセヨ",
        jaPron: "안나이시테 쿠다사이",
        icon: "🧭",
      },
      {
        ko: "여기서 기다릴게요",
        koRomaja: "yeogiseo gidarilgeyo",
        ja: "ここで待ちます",
        jaReading: "ここでまちます",
        koPron: "ヨギソ キダリルケヨ",
        jaPron: "코코데 마치마스",
        icon: "⏳",
      },
      {
        ko: "설명해 주시겠어요?",
        koRomaja: "seolmyeonghae jusigesseoyo",
        ja: "説明していただけますか？",
        jaReading: "せつめいしていただけますか",
        koPron: "ソルミョンヘ ジュシゲッソヨ",
        jaPron: "세츠메이시테 이타다케마스카",
        icon: "💡",
      },
      {
        ko: "질문이 있어요",
        koRomaja: "jilmuni isseoyo",
        ja: "質問があります",
        jaReading: "しつもんがあります",
        koPron: "チルムニ イッソヨ",
        jaPron: "시츠몬가 아리마스",
        icon: "🙋",
      },
      {
        ko: "이쪽으로 갈까요?",
        koRomaja: "ijjogeuro galkkayo",
        ja: "こちらへ行きましょうか？",
        jaReading: "こちらへいきましょうか",
        koPron: "イッチョグロ カルッカヨ",
        jaPron: "코치라에 이키마쇼우카",
        icon: "➡️",
      },
      {
        ko: "명함입니다",
        koRomaja: "myeonghamimnida",
        ja: "名刺です",
        jaReading: "めいしです",
        koPron: "ミョンハミムニダ",
        jaPron: "메이시데스",
        icon: "💳",
      },
      {
        ko: "잘 부탁드립니다",
        koRomaja: "jal butakdeurimnida",
        ja: "よろしくお願いします",
        jaReading: "よろしくおねがいします",
        koPron: "チャル プタクトゥリムニダ",
        jaPron: "요로시쿠 오네가이시마스",
        icon: "🤝",
      },
      {
        ko: "많이 배웠습니다",
        koRomaja: "mani baewotseumnida",
        ja: "たくさん学びました",
        jaReading: "たくさんまなびました",
        koPron: "マニ ペウォッスムニダ",
        jaPron: "타쿠상 마나비마시타",
        icon: "📚",
      },
      {
        ko: "함께 가도 될까요?",
        koRomaja: "hamkke gado doelkkayo",
        ja: "一緒に行ってもいいですか？",
        jaReading: "いっしょにいってもいいですか",
        koPron: "ハムッケ カド トェルッカヨ",
        jaPron: "잇쇼니 잇테모 이이데스카",
        icon: "👥",
      },
    ],
  },
  {
    key: "direction",
    titleKo: "안내·요청",
    titleJa: "案内・要請",
    emoji: "🙋",
    cards: [
      {
        ko: "화장실이 어디예요?",
        koRomaja: "hwajangsiri eodieyo",
        ja: "トイレはどこですか？",
        jaReading: "といれはどこですか",
        koPron: "ファジャンシリ オディエヨ",
        jaPron: "토이레와 도코데스카",
        icon: "🚻",
      },
      {
        ko: "이쪽으로 오세요",
        koRomaja: "ijjogeuro oseyo",
        ja: "こちらへどうぞ",
        jaReading: "こちらへどうぞ",
        koPron: "イッチョグロ オセヨ",
        jaPron: "코치라에 도우조",
        icon: "👉",
      },
      {
        ko: "여기 앉으세요",
        koRomaja: "yeogi anjeuseyo",
        ja: "ここに座ってください",
        jaReading: "ここにすわってください",
        koPron: "ヨギ アンジュセヨ",
        jaPron: "코코니 스왓테 쿠다사이",
        icon: "🪑",
      },
      {
        ko: "따라오세요",
        koRomaja: "ttaraoseyo",
        ja: "ついて来てください",
        jaReading: "ついてきてください",
        koPron: "ッタラオセヨ",
        jaPron: "츠이테 키테 쿠다사이",
        icon: "🚶",
      },
      {
        ko: "잠시 기다려 주세요",
        koRomaja: "jamsi gidaryeo juseyo",
        ja: "少々お待ちください",
        jaReading: "しょうしょうおまちください",
        koPron: "チャムシ キダリョ ジュセヨ",
        jaPron: "쇼우쇼우 오마치 쿠다사이",
        icon: "⏱️",
      },
      {
        ko: "이것 좀 도와주세요",
        koRomaja: "igeot jom dowajuseyo",
        ja: "これを手伝ってください",
        jaReading: "これをてつだってください",
        koPron: "イゴッ チョム トワジュセヨ",
        jaPron: "코레오 테츠닷테 쿠다사이",
        icon: "🤝",
      },
      {
        ko: "여기가 어디예요?",
        koRomaja: "yeogiga eodieyo",
        ja: "ここはどこですか？",
        jaReading: "ここはどこですか",
        koPron: "ヨギガ オディエヨ",
        jaPron: "코코와 도코데스카",
        icon: "📍",
      },
      {
        ko: "출구가 어디예요?",
        koRomaja: "chulguga eodieyo",
        ja: "出口はどこですか？",
        jaReading: "でぐちはどこですか",
        koPron: "チュルグガ オディエヨ",
        jaPron: "데구치와 도코데스카",
        icon: "🚪",
      },
      {
        ko: "엘리베이터가 어디예요?",
        koRomaja: "ellibeiteoga eodieyo",
        ja: "エレベーターはどこですか？",
        jaReading: "えれべーたーはどこですか",
        koPron: "エルリベイトガ オディエヨ",
        jaPron: "에레베타와 도코데스카",
        icon: "🛗",
      },
      {
        ko: "천천히 오세요",
        koRomaja: "cheoncheonhi oseyo",
        ja: "ゆっくり来てください",
        jaReading: "ゆっくりきてください",
        koPron: "チョンチョニ オセヨ",
        jaPron: "윳쿠리 키테 쿠다사이",
        icon: "🐢",
      },
    ],
  },
  {
    key: "time",
    titleKo: "숫자·시간",
    titleJa: "数字・時間",
    emoji: "🕐",
    cards: [
      {
        ko: "몇 시예요?",
        koRomaja: "myeot siyeyo",
        ja: "何時ですか？",
        jaReading: "なんじですか",
        koPron: "ミョッ シエヨ",
        jaPron: "난지데스카",
        icon: "🕐",
      },
      {
        ko: "언제예요?",
        koRomaja: "eonjeyeyo",
        ja: "いつですか？",
        jaReading: "いつですか",
        koPron: "オンジェエヨ",
        jaPron: "이츠데스카",
        icon: "📅",
      },
      {
        ko: "오전 / 오후",
        koRomaja: "ojeon / ohu",
        ja: "午前 / 午後",
        jaReading: "ごぜん / ごご",
        koPron: "オジョン / オフ",
        jaPron: "고젠 / 고고",
        icon: "🌅",
      },
      {
        ko: "내일",
        koRomaja: "naeil",
        ja: "明日",
        jaReading: "あした",
        koPron: "ネイル",
        jaPron: "아시타",
        icon: "📆",
      },
      {
        ko: "오늘",
        koRomaja: "oneul",
        ja: "今日",
        jaReading: "きょう",
        koPron: "オヌル",
        jaPron: "쿄우",
        icon: "📍",
      },
      {
        ko: "몇 분 걸려요?",
        koRomaja: "myeot bun geollyeoyo",
        ja: "何分かかりますか？",
        jaReading: "なんぷんかかりますか",
        koPron: "ミョッ プン コルリョヨ",
        jaPron: "난푼 카카리마스카",
        icon: "⏲️",
      },
      {
        ko: "지금",
        koRomaja: "jigeum",
        ja: "今",
        jaReading: "いま",
        koPron: "チグム",
        jaPron: "이마",
        icon: "⌛",
      },
      {
        ko: "나중에",
        koRomaja: "najunge",
        ja: "後で",
        jaReading: "あとで",
        koPron: "ナジュンゲ",
        jaPron: "아토데",
        icon: "⏭️",
      },
    ],
  },
  {
    key: "daily",
    titleKo: "식사·생활",
    titleJa: "食事・生活",
    emoji: "🍱",
    cards: [
      {
        ko: "배고파요",
        koRomaja: "baegopayo",
        ja: "お腹が空きました",
        jaReading: "おなかがすきました",
        koPron: "ペゴパヨ",
        jaPron: "오나카가 스키마시타",
        icon: "🍚",
      },
      {
        ko: "물 좀 주세요",
        koRomaja: "mul jom juseyo",
        ja: "水をください",
        jaReading: "みずをください",
        koPron: "ムル チョム ジュセヨ",
        jaPron: "미즈오 쿠다사이",
        icon: "💧",
      },
      {
        ko: "식사는 어디서 해요?",
        koRomaja: "siksaneun eodiseo haeyo",
        ja: "食事はどこでしますか？",
        jaReading: "しょくじはどこでしますか",
        koPron: "シクサヌン オディソ ヘヨ",
        jaPron: "쇼쿠지와 도코데 시마스카",
        icon: "🍽️",
      },
      {
        ko: "잘 먹겠습니다",
        koRomaja: "jal meokgetseumnida",
        ja: "いただきます",
        jaReading: "いただきます",
        koPron: "チャル モッケッスムニダ",
        jaPron: "이타다키마스",
        icon: "🥢",
      },
      {
        ko: "맛있어요",
        koRomaja: "masisseoyo",
        ja: "おいしいです",
        jaReading: "おいしいです",
        koPron: "マシッソヨ",
        jaPron: "오이시이데스",
        icon: "😋",
      },
      {
        ko: "화장실 다녀올게요",
        koRomaja: "hwajangsil danyeoolgeyo",
        ja: "トイレに行ってきます",
        jaReading: "といれにいってきます",
        koPron: "ファジャンシル タニョオルケヨ",
        jaPron: "토이레니 잇테 키마스",
        icon: "🚻",
      },
      {
        ko: "피곤해요",
        koRomaja: "pigonhaeyo",
        ja: "疲れました",
        jaReading: "つかれました",
        koPron: "ピゴネヨ",
        jaPron: "츠카레마시타",
        icon: "😩",
      },
      {
        ko: "쉬고 싶어요",
        koRomaja: "swigo sipeoyo",
        ja: "休みたいです",
        jaReading: "やすみたいです",
        koPron: "スィゴ シポヨ",
        jaPron: "야스미타이데스",
        icon: "😴",
      },
    ],
  },
];
