// 포인트-투-토크 양국어 카드 — 화면에 크게 띄워 손가락으로 가리키며 즉시 소통.
// (은성의료재단 ↔ 가마치그룹 직원 상호방문용. 오프라인에서도 동작)
import type { MedCardGroup } from "./types";

export const MED_CARDS: MedCardGroup[] = [
  {
    key: "emergency",
    titleKo: "긴급",
    titleJa: "緊急",
    emoji: "🚨",
    cards: [
      {
        ko: "도와주세요",
        koRomaja: "dowajuseyo",
        ja: "助けてください",
        jaReading: "たすけてください",
        icon: "🆘",
        urgent: true,
      },
      {
        ko: "응급실이 어디예요?",
        koRomaja: "eunggeupsiri eodieyo",
        ja: "救急室はどこですか？",
        jaReading: "きゅうきゅうしつはどこですか",
        icon: "🏥",
        urgent: true,
      },
      {
        ko: "의사를 불러 주세요",
        koRomaja: "uisareul bulleo juseyo",
        ja: "医者を呼んでください",
        jaReading: "いしゃをよんでください",
        icon: "👨‍⚕️",
        urgent: true,
      },
      {
        ko: "통역이 필요해요",
        koRomaja: "tongyeogi piryohaeyo",
        ja: "通訳が必要です",
        jaReading: "つうやくがひつようです",
        icon: "🗣️",
        urgent: true,
      },
      {
        ko: "위급해요",
        koRomaja: "wigeuphaeyo",
        ja: "緊急です",
        jaReading: "きんきゅうです",
        icon: "⚠️",
        urgent: true,
      },
      {
        ko: "알레르기가 있어요",
        koRomaja: "allereugiga isseoyo",
        ja: "アレルギーがあります",
        jaReading: "あれるぎーがあります",
        icon: "🤧",
        urgent: true,
      },
      {
        ko: "구급차를 불러 주세요",
        koRomaja: "gugeupchareul bulleo juseyo",
        ja: "救急車を呼んでください",
        jaReading: "きゅうきゅうしゃをよんでください",
        icon: "🚑",
        urgent: true,
      },
      {
        ko: "사람을 불러 주세요",
        koRomaja: "sarameul bulleo juseyo",
        ja: "人を呼んでください",
        jaReading: "ひとをよんでください",
        icon: "📢",
        urgent: true,
      },
      {
        ko: "길을 잃었어요",
        koRomaja: "gireul ireosseoyo",
        ja: "道に迷いました",
        jaReading: "みちにまよいました",
        icon: "🧭",
        urgent: true,
      },
      {
        ko: "몸이 안 좋아요",
        koRomaja: "momi an joayo",
        ja: "体調が悪いです",
        jaReading: "たいちょうがわるいです",
        icon: "🤒",
        urgent: true,
      },
    ],
  },
  {
    key: "basic",
    titleKo: "기본 의사소통",
    titleJa: "基本コミュニケーション",
    emoji: "💬",
    cards: [
      {
        ko: "네 / 아니요",
        koRomaja: "ne / aniyo",
        ja: "はい / いいえ",
        jaReading: "はい / いいえ",
        icon: "✅",
      },
      {
        ko: "감사합니다",
        koRomaja: "gamsahamnida",
        ja: "ありがとうございます",
        jaReading: "ありがとうございます",
        icon: "🙏",
      },
      {
        ko: "죄송합니다",
        koRomaja: "joesonghamnida",
        ja: "すみません",
        jaReading: "すみません",
        icon: "🙇",
      },
      {
        ko: "천천히 말해 주세요",
        koRomaja: "cheoncheonhi malhae juseyo",
        ja: "ゆっくり話してください",
        jaReading: "ゆっくりはなしてください",
        icon: "🐢",
      },
      {
        ko: "다시 한 번 말해 주세요",
        koRomaja: "dasi han beon malhae juseyo",
        ja: "もう一度言ってください",
        jaReading: "もういちどいってください",
        icon: "🔁",
      },
      {
        ko: "잘 모르겠어요",
        koRomaja: "jal moreugesseoyo",
        ja: "よく分かりません",
        jaReading: "よくわかりません",
        icon: "🤔",
      },
      {
        ko: "알겠습니다",
        koRomaja: "algetseumnida",
        ja: "分かりました",
        jaReading: "わかりました",
        icon: "👍",
      },
      {
        ko: "잠깐만요",
        koRomaja: "jamkkanmanyo",
        ja: "ちょっと待ってください",
        jaReading: "ちょっとまってください",
        icon: "✋",
      },
      {
        ko: "괜찮아요",
        koRomaja: "gwaenchanayo",
        ja: "大丈夫です",
        jaReading: "だいじょうぶです",
        icon: "🆗",
      },
      {
        ko: "부탁합니다",
        koRomaja: "butakhamnida",
        ja: "お願いします",
        jaReading: "おねがいします",
        icon: "🤲",
      },
      {
        ko: "이름이 뭐예요?",
        koRomaja: "ireumi mwoyeyo",
        ja: "お名前は何ですか？",
        jaReading: "おなまえはなんですか",
        icon: "📛",
      },
      {
        ko: "적어 주세요",
        koRomaja: "jeogeo juseyo",
        ja: "書いてください",
        jaReading: "かいてください",
        icon: "✏️",
      },
    ],
  },
  {
    key: "exchange",
    titleKo: "견학·교류",
    titleJa: "見学・交流",
    emoji: "🔬",
    cards: [
      {
        ko: "견학하러 왔습니다",
        koRomaja: "gyeonhakhareo watseumnida",
        ja: "見学に来ました",
        jaReading: "けんがくにきました",
        icon: "🔬",
      },
      {
        ko: "참관해도 될까요?",
        koRomaja: "chamgwanhaedo doelkkayo",
        ja: "見学してもいいですか？",
        jaReading: "けんがくしてもいいですか",
        icon: "👀",
      },
      {
        ko: "사진 찍어도 될까요?",
        koRomaja: "sajin jjigeodo doelkkayo",
        ja: "写真を撮ってもいいですか？",
        jaReading: "しゃしんをとってもいいですか",
        icon: "📷",
      },
      {
        ko: "안내해 주세요",
        koRomaja: "annaehae juseyo",
        ja: "案内してください",
        jaReading: "あんないしてください",
        icon: "🧭",
      },
      {
        ko: "여기서 기다릴게요",
        koRomaja: "yeogiseo gidarilgeyo",
        ja: "ここで待ちます",
        jaReading: "ここでまちます",
        icon: "⏳",
      },
      {
        ko: "설명해 주시겠어요?",
        koRomaja: "seolmyeonghae jusigesseoyo",
        ja: "説明していただけますか？",
        jaReading: "せつめいしていただけますか",
        icon: "💡",
      },
      {
        ko: "질문이 있어요",
        koRomaja: "jilmuni isseoyo",
        ja: "質問があります",
        jaReading: "しつもんがあります",
        icon: "🙋",
      },
      {
        ko: "이쪽으로 갈까요?",
        koRomaja: "ijjogeuro galkkayo",
        ja: "こちらへ行きましょうか？",
        jaReading: "こちらへいきましょうか",
        icon: "➡️",
      },
      {
        ko: "명함입니다",
        koRomaja: "myeonghamimnida",
        ja: "名刺です",
        jaReading: "めいしです",
        icon: "💳",
      },
      {
        ko: "잘 부탁드립니다",
        koRomaja: "jal butakdeurimnida",
        ja: "よろしくお願いします",
        jaReading: "よろしくおねがいします",
        icon: "🤝",
      },
      {
        ko: "많이 배웠습니다",
        koRomaja: "mani baewotseumnida",
        ja: "たくさん学びました",
        jaReading: "たくさんまなびました",
        icon: "📚",
      },
      {
        ko: "함께 가도 될까요?",
        koRomaja: "hamkke gado doelkkayo",
        ja: "一緒に行ってもいいですか？",
        jaReading: "いっしょにいってもいいですか",
        icon: "👥",
      },
    ],
  },
  {
    key: "direction",
    titleKo: "안내·요청",
    titleJa: "案内・要請",
    emoji: "🙋",
    cards: [
      {
        ko: "화장실이 어디예요?",
        koRomaja: "hwajangsiri eodieyo",
        ja: "トイレはどこですか？",
        jaReading: "といれはどこですか",
        icon: "🚻",
      },
      {
        ko: "이쪽으로 오세요",
        koRomaja: "ijjogeuro oseyo",
        ja: "こちらへどうぞ",
        jaReading: "こちらへどうぞ",
        icon: "👉",
      },
      {
        ko: "여기 앉으세요",
        koRomaja: "yeogi anjeuseyo",
        ja: "ここに座ってください",
        jaReading: "ここにすわってください",
        icon: "🪑",
      },
      {
        ko: "따라오세요",
        koRomaja: "ttaraoseyo",
        ja: "ついて来てください",
        jaReading: "ついてきてください",
        icon: "🚶",
      },
      {
        ko: "잠시 기다려 주세요",
        koRomaja: "jamsi gidaryeo juseyo",
        ja: "少々お待ちください",
        jaReading: "しょうしょうおまちください",
        icon: "⏱️",
      },
      {
        ko: "이것 좀 도와주세요",
        koRomaja: "igeot jom dowajuseyo",
        ja: "これを手伝ってください",
        jaReading: "これをてつだってください",
        icon: "🤝",
      },
      {
        ko: "여기가 어디예요?",
        koRomaja: "yeogiga eodieyo",
        ja: "ここはどこですか？",
        jaReading: "ここはどこですか",
        icon: "📍",
      },
      {
        ko: "출구가 어디예요?",
        koRomaja: "chulguga eodieyo",
        ja: "出口はどこですか？",
        jaReading: "でぐちはどこですか",
        icon: "🚪",
      },
      {
        ko: "엘리베이터가 어디예요?",
        koRomaja: "ellibeiteoga eodieyo",
        ja: "エレベーターはどこですか？",
        jaReading: "えれべーたーはどこですか",
        icon: "🛗",
      },
      {
        ko: "천천히 오세요",
        koRomaja: "cheoncheonhi oseyo",
        ja: "ゆっくり来てください",
        jaReading: "ゆっくりきてください",
        icon: "🐢",
      },
    ],
  },
  {
    key: "time",
    titleKo: "숫자·시간",
    titleJa: "数字・時間",
    emoji: "🕐",
    cards: [
      {
        ko: "몇 시예요?",
        koRomaja: "myeot siyeyo",
        ja: "何時ですか？",
        jaReading: "なんじですか",
        icon: "🕐",
      },
      {
        ko: "언제예요?",
        koRomaja: "eonjeyeyo",
        ja: "いつですか？",
        jaReading: "いつですか",
        icon: "📅",
      },
      {
        ko: "오전 / 오후",
        koRomaja: "ojeon / ohu",
        ja: "午前 / 午後",
        jaReading: "ごぜん / ごご",
        icon: "🌅",
      },
      {
        ko: "내일",
        koRomaja: "naeil",
        ja: "明日",
        jaReading: "あした",
        icon: "📆",
      },
      {
        ko: "오늘",
        koRomaja: "oneul",
        ja: "今日",
        jaReading: "きょう",
        icon: "📍",
      },
      {
        ko: "몇 분 걸려요?",
        koRomaja: "myeot bun geollyeoyo",
        ja: "何分かかりますか？",
        jaReading: "なんぷんかかりますか",
        icon: "⏲️",
      },
      {
        ko: "지금",
        koRomaja: "jigeum",
        ja: "今",
        jaReading: "いま",
        icon: "⌛",
      },
      {
        ko: "나중에",
        koRomaja: "najunge",
        ja: "後で",
        jaReading: "あとで",
        icon: "⏭️",
      },
    ],
  },
  {
    key: "daily",
    titleKo: "식사·생활",
    titleJa: "食事・生活",
    emoji: "🍱",
    cards: [
      {
        ko: "배고파요",
        koRomaja: "baegopayo",
        ja: "お腹が空きました",
        jaReading: "おなかがすきました",
        icon: "🍚",
      },
      {
        ko: "물 좀 주세요",
        koRomaja: "mul jom juseyo",
        ja: "水をください",
        jaReading: "みずをください",
        icon: "💧",
      },
      {
        ko: "식사는 어디서 해요?",
        koRomaja: "siksaneun eodiseo haeyo",
        ja: "食事はどこでしますか？",
        jaReading: "しょくじはどこでしますか",
        icon: "🍽️",
      },
      {
        ko: "잘 먹겠습니다",
        koRomaja: "jal meokgetseumnida",
        ja: "いただきます",
        jaReading: "いただきます",
        icon: "🥢",
      },
      {
        ko: "맛있어요",
        koRomaja: "masisseoyo",
        ja: "おいしいです",
        jaReading: "おいしいです",
        icon: "😋",
      },
      {
        ko: "화장실 다녀올게요",
        koRomaja: "hwajangsil danyeoolgeyo",
        ja: "トイレに行ってきます",
        jaReading: "といれにいってきます",
        icon: "🚻",
      },
      {
        ko: "피곤해요",
        koRomaja: "pigonhaeyo",
        ja: "疲れました",
        jaReading: "つかれました",
        icon: "😩",
      },
      {
        ko: "쉬고 싶어요",
        koRomaja: "swigo sipeoyo",
        ja: "休みたいです",
        jaReading: "やすみたいです",
        icon: "😴",
      },
    ],
  },
];
