// 한일 의료용어 사전 — 은성의료재단 ↔ 가마치그룹 직원 교류 플랫폼용.
// 양국어 용어를 짝지어 제공하며, koRomaja(개정 로마자)·jaReading(가나 읽기)은 TTS·후리가나용.
// ⚠️ 임상 정확성은 병원 실무진의 검수가 필요함 (Clinical accuracy to be reviewed by hospital staff).

import type { MedTermCategory } from "./types";

export const MED_GLOSSARY: MedTermCategory[] = [
  {
    key: "anatomy",
    titleKo: "인체·해부",
    titleJa: "人体・解剖",
    emoji: "🫀",
    terms: [
      {
        ko: "심장",
        koRomaja: "simjang",
        ja: "心臓",
        jaReading: "しんぞう",
        exampleKo: "심장 박동이 규칙적입니다.",
        exampleJa: "心臓の拍動が規則的です。",
      },
      {
        ko: "폐",
        koRomaja: "pye",
        ja: "肺",
        jaReading: "はい",
        exampleKo: "폐에 물이 찼습니다.",
        exampleJa: "肺に水がたまっています。",
      },
      { ko: "간", koRomaja: "gan", ja: "肝臓", jaReading: "かんぞう" },
      { ko: "위", koRomaja: "wi", ja: "胃", jaReading: "い" },
      {
        ko: "신장",
        koRomaja: "sinjang",
        ja: "腎臓",
        jaReading: "じんぞう",
        exampleKo: "신장 기능이 저하되었습니다.",
        exampleJa: "腎臓の機能が低下しています。",
      },
      { ko: "혈관", koRomaja: "hyeolgwan", ja: "血管", jaReading: "けっかん" },
      { ko: "뼈", koRomaja: "ppyeo", ja: "骨", jaReading: "ほね" },
      { ko: "근육", koRomaja: "geunyuk", ja: "筋肉", jaReading: "きんにく" },
      { ko: "척추", koRomaja: "cheokchu", ja: "脊椎", jaReading: "せきつい" },
      {
        ko: "뇌",
        koRomaja: "noe",
        ja: "脳",
        jaReading: "のう",
        exampleKo: "뇌 손상이 의심됩니다.",
        exampleJa: "脳の損傷が疑われます。",
      },
      { ko: "대장", koRomaja: "daejang", ja: "大腸", jaReading: "だいちょう" },
      { ko: "소장", koRomaja: "sojang", ja: "小腸", jaReading: "しょうちょう" },
      { ko: "췌장", koRomaja: "chwejang", ja: "膵臓", jaReading: "すいぞう" },
      { ko: "방광", koRomaja: "banggwang", ja: "膀胱", jaReading: "ぼうこう" },
      { ko: "기관지", koRomaja: "gigwanji", ja: "気管支", jaReading: "きかんし" },
    ],
  },
  {
    key: "symptoms",
    titleKo: "증상·질환",
    titleJa: "症状・疾患",
    emoji: "🤒",
    terms: [
      {
        ko: "발열",
        koRomaja: "baryeol",
        ja: "発熱",
        jaReading: "はつねつ",
        exampleKo: "어젯밤부터 발열이 있습니다.",
        exampleJa: "昨夜から発熱があります。",
      },
      {
        ko: "통증",
        koRomaja: "tongjeung",
        ja: "痛み",
        jaReading: "いたみ",
        exampleKo: "어디가 가장 통증이 심하세요?",
        exampleJa: "どこが一番痛みますか。",
      },
      {
        ko: "고혈압",
        koRomaja: "gohyeorap",
        ja: "高血圧",
        jaReading: "こうけつあつ",
        exampleKo: "고혈압 약을 복용 중이십니까?",
        exampleJa: "高血圧の薬を服用していますか。",
      },
      { ko: "당뇨병", koRomaja: "dangnyobyeong", ja: "糖尿病", jaReading: "とうにょうびょう" },
      {
        ko: "골절",
        koRomaja: "goljeol",
        ja: "骨折",
        jaReading: "こっせつ",
        exampleKo: "오른쪽 발목에 골절이 있습니다.",
        exampleJa: "右の足首に骨折があります。",
      },
      { ko: "감염", koRomaja: "gamyeom", ja: "感染", jaReading: "かんせん" },
      { ko: "염증", koRomaja: "yeomjeung", ja: "炎症", jaReading: "えんしょう" },
      { ko: "부종", koRomaja: "bujong", ja: "浮腫", jaReading: "ふしゅ" },
      {
        ko: "호흡곤란",
        koRomaja: "hoheupgollan",
        ja: "呼吸困難",
        jaReading: "こきゅうこんなん",
        exampleKo: "호흡곤란을 호소하고 있습니다.",
        exampleJa: "呼吸困難を訴えています。",
      },
      { ko: "어지럼증", koRomaja: "eojireomjeung", ja: "めまい", jaReading: "めまい" },
      { ko: "구토", koRomaja: "guto", ja: "嘔吐", jaReading: "おうと" },
      { ko: "설사", koRomaja: "seolsa", ja: "下痢", jaReading: "げり" },
      { ko: "출혈", koRomaja: "chulhyeol", ja: "出血", jaReading: "しゅっけつ" },
      { ko: "마비", koRomaja: "mabi", ja: "麻痺", jaReading: "まひ" },
    ],
  },
  {
    key: "exam",
    titleKo: "검사·진단",
    titleJa: "検査・診断",
    emoji: "🔬",
    terms: [
      {
        ko: "혈액검사",
        koRomaja: "hyeoraekgeomsa",
        ja: "血液検査",
        jaReading: "けつえきけんさ",
        exampleKo: "오늘 혈액검사를 받으시겠습니다.",
        exampleJa: "本日、血液検査を行います。",
      },
      { ko: "엑스레이", koRomaja: "ekseurei", ja: "レントゲン", jaReading: "レントゲン" },
      {
        ko: "시티",
        koRomaja: "siti",
        ja: "CT",
        jaReading: "シーティー",
        exampleKo: "복부 시티 촬영이 예약되어 있습니다.",
        exampleJa: "腹部のCT撮影が予約されています。",
      },
      { ko: "엠아르아이", koRomaja: "emareuai", ja: "MRI", jaReading: "エムアールアイ" },
      { ko: "초음파", koRomaja: "choeumpa", ja: "超音波", jaReading: "ちょうおんぱ" },
      {
        ko: "심전도",
        koRomaja: "simjeondo",
        ja: "心電図",
        jaReading: "しんでんず",
        exampleKo: "심전도 검사를 먼저 하겠습니다.",
        exampleJa: "先に心電図検査をします。",
      },
      {
        ko: "채혈",
        koRomaja: "chaehyeol",
        ja: "採血",
        jaReading: "さいけつ",
        exampleKo: "왼팔에서 채혈하겠습니다.",
        exampleJa: "左腕から採血します。",
      },
      { ko: "소변검사", koRomaja: "sobyeongeomsa", ja: "尿検査", jaReading: "にょうけんさ" },
      { ko: "생검", koRomaja: "saenggeom", ja: "生検", jaReading: "せいけん" },
      { ko: "내시경", koRomaja: "naesigyeong", ja: "内視鏡", jaReading: "ないしきょう" },
      { ko: "검체", koRomaja: "geomche", ja: "検体", jaReading: "けんたい" },
      { ko: "진단", koRomaja: "jindan", ja: "診断", jaReading: "しんだん" },
      { ko: "혈당", koRomaja: "hyeoldang", ja: "血糖", jaReading: "けっとう" },
      { ko: "체온측정", koRomaja: "cheonchukjeong", ja: "体温測定", jaReading: "たいおんそくてい" },
    ],
  },
  {
    key: "medication",
    titleKo: "약품·투약",
    titleJa: "薬品・投薬",
    emoji: "💊",
    terms: [
      {
        ko: "처방전",
        koRomaja: "cheobangjeon",
        ja: "処方箋",
        jaReading: "しょほうせん",
        exampleKo: "처방전을 약국에 제출하세요.",
        exampleJa: "処方箋を薬局に出してください。",
      },
      { ko: "항생제", koRomaja: "hangsaengje", ja: "抗生物質", jaReading: "こうせいぶっしつ" },
      {
        ko: "진통제",
        koRomaja: "jintongje",
        ja: "鎮痛剤",
        jaReading: "ちんつうざい",
        exampleKo: "통증이 심하면 진통제를 드릴게요.",
        exampleJa: "痛みが強ければ鎮痛剤をお出しします。",
      },
      {
        ko: "수액",
        koRomaja: "suaek",
        ja: "点滴",
        jaReading: "てんてき",
        exampleKo: "지금 수액을 연결하겠습니다.",
        exampleJa: "これから点滴をつなぎます。",
      },
      {
        ko: "주사",
        koRomaja: "jusa",
        ja: "注射",
        jaReading: "ちゅうしゃ",
        exampleKo: "엉덩이에 주사를 놓겠습니다.",
        exampleJa: "お尻に注射をします。",
      },
      { ko: "내복약", koRomaja: "naebogyak", ja: "内服薬", jaReading: "ないふくやく" },
      { ko: "부작용", koRomaja: "bujagyong", ja: "副作用", jaReading: "ふくさよう" },
      { ko: "용량", koRomaja: "yongnyang", ja: "用量", jaReading: "ようりょう" },
      { ko: "투여", koRomaja: "tuyeo", ja: "投与", jaReading: "とうよ" },
      { ko: "복용", koRomaja: "bogyong", ja: "服用", jaReading: "ふくよう" },
      { ko: "연고", koRomaja: "yeongo", ja: "軟膏", jaReading: "なんこう" },
      { ko: "해열제", koRomaja: "haeyeolje", ja: "解熱剤", jaReading: "げねつざい" },
      { ko: "수면제", koRomaja: "sumyeonje", ja: "睡眠薬", jaReading: "すいみんやく" },
      { ko: "알약", koRomaja: "aryak", ja: "錠剤", jaReading: "じょうざい" },
    ],
  },
  {
    key: "equipment",
    titleKo: "장비·물품",
    titleJa: "機器・物品",
    emoji: "🩺",
    terms: [
      {
        ko: "청진기",
        koRomaja: "cheongjingi",
        ja: "聴診器",
        jaReading: "ちょうしんき",
        exampleKo: "청진기로 가슴 소리를 듣겠습니다.",
        exampleJa: "聴診器で胸の音を聞きます。",
      },
      {
        ko: "혈압계",
        koRomaja: "hyeorapgye",
        ja: "血圧計",
        jaReading: "けつあつけい",
        exampleKo: "혈압계로 혈압을 재겠습니다.",
        exampleJa: "血圧計で血圧を測ります。",
      },
      {
        ko: "휠체어",
        koRomaja: "hwilcheeo",
        ja: "車椅子",
        jaReading: "くるまいす",
        exampleKo: "휠체어로 검사실까지 이동합니다.",
        exampleJa: "車椅子で検査室まで移動します。",
      },
      { ko: "산소마스크", koRomaja: "sansomaseukeu", ja: "酸素マスク", jaReading: "さんそマスク" },
      { ko: "거즈", koRomaja: "geojeu", ja: "ガーゼ", jaReading: "ガーゼ" },
      { ko: "카테터", koRomaja: "kateteo", ja: "カテーテル", jaReading: "カテーテル" },
      {
        ko: "인공호흡기",
        koRomaja: "ingonghoheupgi",
        ja: "人工呼吸器",
        jaReading: "じんこうこきゅうき",
      },
      { ko: "모니터", koRomaja: "moniteo", ja: "モニター", jaReading: "モニター" },
      { ko: "주사기", koRomaja: "jusagi", ja: "注射器", jaReading: "ちゅうしゃき" },
      { ko: "체온계", koRomaja: "cheongye", ja: "体温計", jaReading: "たいおんけい" },
      { ko: "붕대", koRomaja: "bungdae", ja: "包帯", jaReading: "ほうたい" },
      { ko: "장갑", koRomaja: "janggap", ja: "手袋", jaReading: "てぶくろ" },
      { ko: "마스크", koRomaja: "maseukeu", ja: "マスク", jaReading: "マスク" },
      { ko: "들것", koRomaja: "deulgeot", ja: "担架", jaReading: "たんか" },
    ],
  },
  {
    key: "department",
    titleKo: "부서·직책",
    titleJa: "部署・職責",
    emoji: "🏥",
    terms: [
      {
        ko: "내과",
        koRomaja: "naegwa",
        ja: "内科",
        jaReading: "ないか",
        exampleKo: "내과 진료를 예약했습니다.",
        exampleJa: "内科の診察を予約しました。",
      },
      { ko: "외과", koRomaja: "oegwa", ja: "外科", jaReading: "げか" },
      {
        ko: "응급실",
        koRomaja: "eunggeupsil",
        ja: "救急室",
        jaReading: "きゅうきゅうしつ",
        exampleKo: "환자를 응급실로 옮기겠습니다.",
        exampleJa: "患者を救急室へ運びます。",
      },
      {
        ko: "중환자실",
        koRomaja: "junghwanjasil",
        ja: "集中治療室",
        jaReading: "しゅうちゅうちりょうしつ",
        exampleKo: "중환자실(ICU)에 입실했습니다.",
        exampleJa: "集中治療室(ICU)に入りました。",
      },
      {
        ko: "간호사",
        koRomaja: "ganhosa",
        ja: "看護師",
        jaReading: "かんごし",
        exampleKo: "담당 간호사를 불러 드리겠습니다.",
        exampleJa: "担当の看護師を呼びます。",
      },
      { ko: "의사", koRomaja: "uisa", ja: "医師", jaReading: "いし" },
      { ko: "약사", koRomaja: "yaksa", ja: "薬剤師", jaReading: "やくざいし" },
      { ko: "방사선사", koRomaja: "bangsaseonsa", ja: "放射線技師", jaReading: "ほうしゃせんぎし" },
      { ko: "병동", koRomaja: "byeongdong", ja: "病棟", jaReading: "びょうとう" },
      { ko: "외래", koRomaja: "oerae", ja: "外来", jaReading: "がいらい" },
      { ko: "소아과", koRomaja: "soagwa", ja: "小児科", jaReading: "しょうにか" },
      { ko: "정형외과", koRomaja: "jeonghyeongoegwa", ja: "整形外科", jaReading: "せいけいげか" },
      { ko: "원무과", koRomaja: "wonmugwa", ja: "医事課", jaReading: "いじか" },
      { ko: "수술실", koRomaja: "susulsil", ja: "手術室", jaReading: "しゅじゅつしつ" },
    ],
  },
];
