// 의료교류 회화집 — 은성의료재단 ↔ 가마치그룹 직원 상호방문용.
// 방문한 직원(연수자)과 호스트 병원 동료 사이의 직원 대 직원 대화로 구성.
// 모든 문장은 한국어·일본어를 함께 노출하며, jaReading 은 TTS·후리가나용 전체 가나 읽기.
// ⚠️ 시스템·용어 표현은 실제 운용 전 양국 병원 직원의 검수가 필요합니다.

import type { MedPhraseGroup } from "./types";

export const MED_PHRASEBOOK: MedPhraseGroup[] = [
  // ────────────────────────────── COMMON ──────────────────────────────
  {
    key: "greeting",
    role: "common",
    titleKo: "인사·자기소개",
    titleJa: "あいさつ・自己紹介",
    emoji: "👋",
    phrases: [
      {
        ko: "처음 뵙겠습니다. 은성의료재단에서 온 박서연입니다.",
        koRomaja: "cheoeum boepgesseumnida. eunseonguiryojaedaneseo on bak seoyeon-imnida.",
        ja: "初めまして。ウンソン医療財団から参りましたパク・ソヨンです。",
        jaReading: "はじめまして。うんそんいりょうざいだんからまいりましたパク・ソヨンです。",
        noteKo: "첫 만남에서는 가볍게 목례를 함께 하면 양국 모두 자연스럽습니다.",
        noteJa: "初対面では軽くお辞儀を添えると、両国とも自然です。",
      },
      {
        ko: "이번 연수에서 많이 배우고 싶습니다. 잘 부탁드립니다.",
        koRomaja: "ibeon yeonsueseo mani baeugo sipseumnida. jal butakdeurimnida.",
        ja: "今回の研修で多くを学ばせていただきたいです。どうぞよろしくお願いいたします。",
        jaReading: "こんかいのけんしゅうでおおくをまなばせていただきたいです。どうぞよろしくおねがいいたします。",
      },
      {
        ko: "제 일본어가 서툴러 천천히 말씀해 주시면 감사하겠습니다.",
        koRomaja: "je ilboneoga seotulleo cheoncheonhi malsseumhae jusimyeon gamsahagesseumnida.",
        ja: "私は日本語が不慣れですので、ゆっくり話していただけると助かります。",
        jaReading: "わたしはにほんごがふなれですので、ゆっくりはなしていただけるとたすかります。",
      },
      {
        ko: "오늘부터 일주일간 함께 일하게 되어 영광입니다.",
        koRomaja: "oneulbuteo iljuilgan hamkke ilhage doeeo yeonggwang-imnida.",
        ja: "本日から一週間ご一緒できて光栄です。",
        jaReading: "ほんじつからいっしゅうかんごいっしょできてこうえいです。",
      },
      {
        ko: "저는 내과 병동에서 근무하는 간호사입니다.",
        koRomaja: "jeoneun naegwa byeongdongeseo geunmuhaneun ganhosa-imnida.",
        ja: "私は内科病棟で勤務している看護師です。",
        jaReading: "わたしはないかびょうとうできんむしているかんごしです。",
      },
      {
        ko: "모르는 점이 있으면 여쭤봐도 괜찮을까요?",
        koRomaja: "moreuneun jeomi isseumyeon yeojjwobwado gwaenchaneulkkayo?",
        ja: "分からないことがあれば、お伺いしてもよろしいでしょうか？",
        jaReading: "わからないことがあれば、おうかがいしてもよろしいでしょうか？",
      },
    ],
  },
  {
    key: "schedule",
    role: "common",
    titleKo: "견학 요청·일정 조율",
    titleJa: "見学のお願い・日程調整",
    emoji: "📅",
    phrases: [
      {
        ko: "오늘 견학 일정을 알려 주시겠어요?",
        koRomaja: "oneul gyeonhak iljeongeul allyeo jusigesseoyo?",
        ja: "本日の見学の予定を教えていただけますか？",
        jaReading: "ほんじつのけんがくのよていをおしえていただけますか？",
      },
      {
        ko: "회진을 참관해도 될까요?",
        koRomaja: "hoejineul chamgwanhaedo doelkkayo?",
        ja: "回診を見学させていただいてもよろしいでしょうか？",
        jaReading: "かいしんをけんがくさせていただいてもよろしいでしょうか？",
      },
      {
        ko: "이 부서를 둘러봐도 될까요?",
        koRomaja: "i buseoreul dulleobwado doelkkayo?",
        ja: "この部署を見学させていただいてもよろしいですか？",
        jaReading: "このぶしょをけんがくさせていただいてもよろしいですか？",
      },
      {
        ko: "사진을 촬영해도 괜찮을까요?",
        koRomaja: "sajineul chwallyeonghaedo gwaenchaneulkkayo?",
        ja: "写真を撮影してもよろしいでしょうか？",
        jaReading: "しゃしんをさつえいしてもよろしいでしょうか？",
        noteKo: "환자나 의무기록이 보이지 않도록 촬영 전 반드시 허가를 받으세요.",
        noteJa: "患者さんやカルテが写らないよう、撮影前に必ず許可を取りましょう。",
      },
      {
        ko: "오후 일정은 몇 시에 시작하나요?",
        koRomaja: "ohu iljeongeun myeot sie sijakanayo?",
        ja: "午後の予定は何時から始まりますか？",
        jaReading: "ごごのよていはなんじからはじまりますか？",
      },
      {
        ko: "괜찮으시면 내일은 검사실도 견학하고 싶습니다.",
        koRomaja: "gwaenchaneusimyeon naeireun geomsasildo gyeonhakago sipseumnida.",
        ja: "差し支えなければ、明日は検査室も見学したいです。",
        jaReading: "さしつかえなければ、あすはけんさしつもけんがくしたいです。",
      },
    ],
  },
  {
    key: "closing",
    role: "common",
    titleKo: "감사·소감·작별",
    titleJa: "お礼・感想・別れ",
    emoji: "🙏",
    phrases: [
      {
        ko: "오늘 정말 많이 배웠습니다.",
        koRomaja: "oneul jeongmal mani baewotseumnida.",
        ja: "本日は本当にたくさん学ばせていただきました。",
        jaReading: "ほんじつはほんとうにたくさんまなばせていただきました。",
      },
      {
        ko: "친절하게 안내해 주셔서 감사합니다.",
        koRomaja: "chinjeolhage annaehae jusyeoseo gamsahamnida.",
        ja: "ご親切にご案内いただき、ありがとうございました。",
        jaReading: "ごしんせつにごあんないいただき、ありがとうございました。",
      },
      {
        ko: "귀 병원의 시스템에서 큰 자극을 받았습니다.",
        koRomaja: "gwi byeongwonui siseutemeseo keun jageugeul badatseumnida.",
        ja: "貴院のシステムから大きな刺激を受けました。",
        jaReading: "きいんのシステムからおおきなしげきをうけました。",
      },
      {
        ko: "다음에는 저희 병원에도 꼭 와 주세요.",
        koRomaja: "daeumeneun jeohui byeongwonedo kkok wa juseyo.",
        ja: "次回はぜひ私どもの病院にもお越しください。",
        jaReading: "じかいはぜひわたしどものびょういんにもおこしください。",
      },
      {
        ko: "연락처를 교환할 수 있을까요?",
        koRomaja: "yeollakcheoreul gyohwanhal su isseulkkayo?",
        ja: "連絡先を交換させていただけますか？",
        jaReading: "れんらくさきをこうかんさせていただけますか？",
        noteKo: "일본에서는 명함 교환이 일반적이므로 명함을 준비해 가면 좋습니다.",
        noteJa: "日本では名刺交換が一般的なので、名刺を用意しておくとよいです。",
      },
      {
        ko: "배운 내용을 저희 팀과 꼭 공유하겠습니다.",
        koRomaja: "baeun naeyongeul jeohui timgwa kkok gongyuhagesseumnida.",
        ja: "学んだ内容を必ず私たちのチームと共有いたします。",
        jaReading: "まなんだないようをかならずわたしたちのチームときょうゆういたします。",
      },
      {
        ko: "건강하시고, 또 뵙기를 기대하겠습니다.",
        koRomaja: "geonganghasigo, tto boepgireul gidaehagesseumnida.",
        ja: "お元気で、またお会いできるのを楽しみにしております。",
        jaReading: "おげんきで、またおあいできるのをたのしみにしております。",
      },
    ],
  },
  // ────────────────────────────── DOCTOR ──────────────────────────────
  {
    key: "rounds",
    role: "doctor",
    titleKo: "회진 동행·증례 토의",
    titleJa: "回診同行・症例検討",
    emoji: "🩺",
    phrases: [
      {
        ko: "이 증례는 어떤 기준으로 치료 방침을 정하시나요?",
        koRomaja: "i jeungnyeneun eotteon gijuneuro chiryo bangchimeul jeonghasinayo?",
        ja: "この症例は、どのような基準で治療方針を決めていらっしゃいますか？",
        jaReading: "このしょうれいは、どのようなきじゅんでちりょうほうしんをきめていらっしゃいますか？",
      },
      {
        ko: "한국에서는 이런 경우 보존적 치료를 우선합니다.",
        koRomaja: "hangugeseoneun ireon gyeongu bojonjeok chiryoreul useonhamnida.",
        ja: "韓国では、このような場合は保存的治療を優先します。",
        jaReading: "かんこくでは、このようなばあいはほぞんてきちりょうをゆうせんします。",
      },
      {
        ko: "회진은 보통 몇 명이 함께 도나요?",
        koRomaja: "hoejineun botong myeot myeongi hamkke donayo?",
        ja: "回診は普段、何名で回られますか？",
        jaReading: "かいしんはふだん、なんめいでまわられますか？",
      },
      {
        ko: "이 환자분의 영상 소견을 함께 봐도 될까요?",
        koRomaja: "i hwanjabunui yeongsang sogyeoneul hamkke bwado doelkkayo?",
        ja: "この患者さんの画像所見を一緒に拝見してもよろしいですか？",
        jaReading: "このかんじゃさんのがぞうしょけんをいっしょにはいけんしてもよろしいですか？",
        noteKo: "환자 정보를 다룰 때는 개인정보 보호에 특히 주의해야 합니다.",
        noteJa: "患者情報を扱う際は、個人情報保護に特に注意が必要です。",
      },
      {
        ko: "이 진단에 이르신 근거가 궁금합니다.",
        koRomaja: "i jindane ireusin geungeoga gunggeumhamnida.",
        ja: "この診断に至られた根拠を伺いたいです。",
        jaReading: "このしんだんにいたられたこんきょをうかがいたいです。",
      },
      {
        ko: "회진 중에 질문을 드려도 괜찮은 타이밍이 있을까요?",
        koRomaja: "hoejin junge jimuneul deuryeodo gwaenchaneun taimingi isseulkkayo?",
        ja: "回診中に質問してもよいタイミングはありますか？",
        jaReading: "かいしんちゅうにしつもんしてもよいタイミングはありますか？",
      },
    ],
  },
  {
    key: "protocol",
    role: "doctor",
    titleKo: "진료 시스템·프로토콜 질문",
    titleJa: "診療システム・プロトコル質問",
    emoji: "📋",
    phrases: [
      {
        ko: "이 질환의 표준 진료 지침이 있나요?",
        koRomaja: "i jirhwanui pyojun jillyo jichimi innayo?",
        ja: "この疾患の標準的な診療ガイドラインはありますか？",
        jaReading: "このしっかんのひょうじゅんてきなしんりょうガイドラインはありますか？",
      },
      {
        ko: "전자의무기록은 어떤 시스템을 쓰시나요?",
        koRomaja: "jeonjauimugirogeun eotteon siseutemeul sseusinayo?",
        ja: "電子カルテはどのシステムをお使いですか？",
        jaReading: "でんしカルテはどのシステムをおつかいですか？",
        noteKo: "일본에서는 전자의무기록을 보통 '電子カルテ(덴시 카르테)'라고 부릅니다.",
        noteJa: "韓国では電子カルテを「전자의무기록(EMR)」と呼びます。",
      },
      {
        ko: "타과 협진은 어떻게 의뢰하나요?",
        koRomaja: "tagwa hyeopjineun eotteoke uiroehanayo?",
        ja: "他科へのコンサルトはどのように依頼しますか？",
        jaReading: "たかへのコンサルトはどのようにいらいしますか？",
      },
      {
        ko: "임상 경로(클리니컬 패스)는 어떻게 운영하시나요?",
        koRomaja: "imsang gyeongno(keullinikeol paeseu)neun eotteoke unyeonghasinayo?",
        ja: "クリニカルパスはどのように運用されていますか？",
        jaReading: "クリニカルパスはどのようにうんようされていますか？",
      },
      {
        ko: "응급 환자가 왔을 때 의료진 호출 체계가 궁금합니다.",
        koRomaja: "eunggeup hwanjaga wasseul ttae uiryojin hochul chegyega gunggeumhamnida.",
        ja: "救急の患者が来た際の医療者の招集体制を知りたいです。",
        jaReading: "きゅうきゅうのかんじゃがきたさいのいりょうしゃのしょうしゅうたいせいをしりたいです。",
      },
      {
        ko: "처방 후 결과는 어떤 경로로 확인하시나요?",
        koRomaja: "cheobang hu gyeolgwaneun eotteon gyeongnoro hwaginhasinayo?",
        ja: "オーダー後の結果はどの経路で確認されますか？",
        jaReading: "オーダーごのけっかはどのけいろでかくにんされますか？",
      },
    ],
  },
  // ────────────────────────────── NURSE ──────────────────────────────
  {
    key: "ward-tour",
    role: "nurse",
    titleKo: "병동 업무 흐름 견학",
    titleJa: "病棟業務の見学",
    emoji: "🏥",
    phrases: [
      {
        ko: "한 병동에 간호사가 몇 명 근무하나요?",
        koRomaja: "han byeongdonge ganhosaga myeot myeong geunmuhanayo?",
        ja: "一つの病棟に看護師は何名勤務されていますか？",
        jaReading: "ひとつのびょうとうにかんごしはなんめいきんむされていますか？",
      },
      {
        ko: "교대 근무는 어떻게 편성되나요?",
        koRomaja: "gyodae geunmuneun eotteoke pyeonseongdoenayo?",
        ja: "交代勤務はどのように組まれていますか？",
        jaReading: "こうたいきんむはどのようにくまれていますか？",
      },
      {
        ko: "환자 한 명당 담당 간호사가 정해져 있나요?",
        koRomaja: "hwanja han myeongdang damdang ganhosaga jeonghaejyeo innayo?",
        ja: "患者一人ごとに受け持ちの看護師は決まっていますか？",
        jaReading: "かんじゃひとりごとにうけもちのかんごしはきまっていますか？",
        noteKo: "일본의 '受け持ち(우케모치)'는 담당 간호사 배정 방식을 가리킵니다.",
        noteJa: "韓国では受け持ち制を「담당 간호사」と表現します。",
      },
      {
        ko: "병동의 하루 업무 흐름을 설명해 주실 수 있나요?",
        koRomaja: "byeongdongui haru eommu heureumeul seolmyeonghae jusil su innayo?",
        ja: "病棟の一日の業務の流れを説明していただけますか？",
        jaReading: "びょうとうのいちにちのぎょうむのながれをせつめいしていただけますか？",
      },
      {
        ko: "간호 인력 배치 기준은 어떻게 되나요?",
        koRomaja: "ganho illyeok baechi gijuneun eotteoke doenayo?",
        ja: "看護師の人員配置の基準はどうなっていますか？",
        jaReading: "かんごしのじんいんはいちのきじゅんはどうなっていますか？",
      },
      {
        ko: "나이트 근무는 보통 몇 명이 담당하나요?",
        koRomaja: "naiteu geunmuneun botong myeot myeongi damdanghanayo?",
        ja: "夜勤は通常何名で担当されますか？",
        jaReading: "やきんはつうじょうなんめいでたんとうされますか？",
      },
    ],
  },
  {
    key: "handover",
    role: "nurse",
    titleKo: "인계 참관·간호기록 질문",
    titleJa: "申し送り見学・看護記録質問",
    emoji: "🔄",
    phrases: [
      {
        ko: "申し送り(인계)를 참관해도 될까요?",
        koRomaja: "ingyereul chamgwanhaedo doelkkayo?",
        ja: "申し送りを見学させていただいてもよろしいですか？",
        jaReading: "もうしおくりをけんがくさせていただいてもよろしいですか？",
        noteKo: "일본어 '申し送り(모시오쿠리)'는 한국의 '인계'에 해당합니다.",
        noteJa: "韓国語の「인계(インゲ)」は日本の「申し送り」に当たります。",
      },
      {
        ko: "인계는 보통 몇 분 정도 걸리나요?",
        koRomaja: "ingyeneun botong myeot bun jeongdo geollinayo?",
        ja: "申し送りは普段どのくらいの時間がかかりますか？",
        jaReading: "もうしおくりはふだんどのくらいのじかんがかかりますか？",
      },
      {
        ko: "간호 기록은 어떤 항목을 남기나요?",
        koRomaja: "ganho girogeun eotteon hangmogeul namginayo?",
        ja: "看護記録はどのような項目を残されますか？",
        jaReading: "かんごきろくはどのようなこうもくをのこされますか？",
      },
      {
        ko: "인계 시 가장 중요하게 전달하는 정보는 무엇인가요?",
        koRomaja: "ingye si gajang jungyohage jeondalhaneun jeongboneun mueosingayo?",
        ja: "申し送りの際、最も重視して伝える情報は何ですか？",
        jaReading: "もうしおくりのさい、もっともじゅうししてつたえるじょうほうはなんですか？",
      },
      {
        ko: "간호 기록은 전자 차트로 작성하시나요?",
        koRomaja: "ganho girogeun jeonja chateuro jakseonghasinayo?",
        ja: "看護記録は電子カルテで作成されますか？",
        jaReading: "かんごきろくはでんしカルテでさくせいされますか？",
      },
      {
        ko: "인계 양식(SBAR 등)을 사용하시나요?",
        koRomaja: "ingye yangsik(SBAR deung)eul sayonghasinayo?",
        ja: "申し送りの様式（SBARなど）を使っていらっしゃいますか？",
        jaReading: "もうしおくりのようしき（SBARなど）をつかっていらっしゃいますか？",
      },
    ],
  },
  // ────────────────────────────── EXAM ──────────────────────────────
  {
    key: "lab-tour",
    role: "exam",
    titleKo: "검사실·장비 운용 견학",
    titleJa: "検査室・機器運用の見学",
    emoji: "🔬",
    phrases: [
      {
        ko: "이 장비는 하루에 몇 건 정도 검사하나요?",
        koRomaja: "i jangbineun harue myeot geon jeongdo geomsahanayo?",
        ja: "この機器は一日に何件ほど検査されますか？",
        jaReading: "このききはいちにちになんけんほどけんさされますか？",
      },
      {
        ko: "장비 점검은 어떤 주기로 하나요?",
        koRomaja: "jangbi jeomgeomeun eotteon jugiro hanayo?",
        ja: "機器の点検はどのくらいの周期で行われますか？",
        jaReading: "ききのてんけんはどのくらいのしゅうきでおこなわれますか？",
      },
      {
        ko: "검사 결과는 얼마 만에 나오나요?",
        koRomaja: "geomsa gyeolgwaneun eolma mane naonayo?",
        ja: "検査結果はどのくらいで出ますか？",
        jaReading: "けんさけっかはどのくらいででますか？",
      },
      {
        ko: "이 장비의 제조사와 모델명을 여쭤봐도 될까요?",
        koRomaja: "i jangbiui jejosawa modelmyeongeul yeojjwobwado doelkkayo?",
        ja: "この機器のメーカーと型番を伺ってもよろしいですか？",
        jaReading: "このききのメーカーとかたばんをうかがってもよろしいですか？",
      },
      {
        ko: "검체 운반은 자동 시스템으로 이루어지나요?",
        koRomaja: "geomche unbaneun jadong siseutemeuro irueojinayo?",
        ja: "検体の搬送は自動システムで行われますか？",
        jaReading: "けんたいのはんそうはじどうシステムでおこなわれますか？",
        noteKo: "일본의 대형 병원은 검체 운반에 기송관(에어슈터)을 쓰는 곳이 많습니다.",
        noteJa: "韓国でも大規模病院では検体搬送に気送管を用いる施設があります。",
      },
      {
        ko: "긴급 검사는 어떻게 우선 처리하나요?",
        koRomaja: "gingeup geomsaneun eotteoke useon cheorihanayo?",
        ja: "緊急検査はどのように優先して処理されますか？",
        jaReading: "きんきゅうけんさはどのようにゆうせんしてしょりされますか？",
      },
    ],
  },
  {
    key: "workflow",
    role: "exam",
    titleKo: "검사 워크플로 비교",
    titleJa: "検査ワークフローの比較",
    emoji: "🔁",
    phrases: [
      {
        ko: "검사 의뢰부터 결과까지 흐름을 알려 주시겠어요?",
        koRomaja: "geomsa uiroebuteo gyeolgwakkaji heureumeul allyeo jusigesseoyo?",
        ja: "検査依頼から結果報告までの流れを教えていただけますか？",
        jaReading: "けんさいらいからけっかほうこくまでのながれをおしえていただけますか？",
      },
      {
        ko: "한국에서는 검사 의뢰를 전산 오더 방식으로 합니다.",
        koRomaja: "hangugeseoneun geomsa uiroereul jeonsan odeo bangsigeuro hamnida.",
        ja: "韓国では検査依頼を電子オーダー方式で行います。",
        jaReading: "かんこくではけんさいらいをでんしオーダーほうしきでおこないます。",
      },
      {
        ko: "정도관리(QC)는 어떻게 하시나요?",
        koRomaja: "jeongdogwalli(QC)neun eotteoke hasinayo?",
        ja: "精度管理（QC）はどのように行われていますか？",
        jaReading: "せいどかんり（QC）はどのようにおこなわれていますか？",
        noteKo: "'정도관리'는 일본어로 '精度管理(세이도칸리)'이며 의미가 동일합니다.",
        noteJa: "「精度管理」は韓国語で「정도관리」、意味は同じです。",
      },
      {
        ko: "검사 결과의 위험치(패닉치) 보고 절차가 궁금합니다.",
        koRomaja: "geomsa gyeolgwaui wiheomchi(paenikchi) bogo jeolchaga gunggeumhamnida.",
        ja: "検査結果のパニック値の報告手順を知りたいです。",
        jaReading: "けんさけっかのパニックちのほうこくてじゅんをしりたいです。",
      },
      {
        ko: "외부 위탁 검사는 어떤 기준으로 보내나요?",
        koRomaja: "oebu witak geomsaneun eotteon gijuneuro bonaenayo?",
        ja: "外部委託検査はどのような基準で出されますか？",
        jaReading: "がいぶいたくけんさはどのようなきじゅんでだされますか？",
      },
      {
        ko: "결과 보고는 의무기록에 자동으로 연동되나요?",
        koRomaja: "gyeolgwa bogoneun uimugiroge jadongeuro yeondongdoenayo?",
        ja: "結果報告はカルテに自動で連携されますか？",
        jaReading: "けっかほうこくはカルテにじどうでれんけいされますか？",
      },
    ],
  },
  // ────────────────────────────── PHARMACY ──────────────────────────────
  {
    key: "dispensing",
    role: "pharmacy",
    titleKo: "조제·약품관리 시스템 견학",
    titleJa: "調剤・薬品管理システムの見学",
    emoji: "💊",
    phrases: [
      {
        ko: "조제는 자동화 시스템을 쓰시나요?",
        koRomaja: "jojeneun jadonghwa siseutemeul sseusinayo?",
        ja: "調剤は自動化システムを使っていらっしゃいますか？",
        jaReading: "ちょうざいはじどうかシステムをつかっていらっしゃいますか？",
      },
      {
        ko: "마약류 관리는 어떻게 하시나요?",
        koRomaja: "mayangnyu gwallineun eotteoke hasinayo?",
        ja: "麻薬類の管理はどのようにされていますか？",
        jaReading: "まやくるいのかんりはどのようにされていますか？",
        noteKo: "마약류는 양국 모두 별도 금고 보관과 사용 기록 관리가 엄격합니다.",
        noteJa: "麻薬類は両国とも金庫保管と使用記録の管理が厳格です。",
      },
      {
        ko: "약품 재고는 어떻게 관리하나요?",
        koRomaja: "yakpum jaegoneun eotteoke gwallihanayo?",
        ja: "薬品の在庫はどのように管理されていますか？",
        jaReading: "やくひんのざいこはどのようにかんりされていますか？",
      },
      {
        ko: "조제실 동선과 작업 구역을 둘러봐도 될까요?",
        koRomaja: "jojesil dongseongwa jageop guyeogeul dulleobwado doelkkayo?",
        ja: "調剤室の動線と作業区域を見学させていただけますか？",
        jaReading: "ちょうざいしつのどうせんとさぎょうくいきをけんがくさせていただけますか？",
      },
      {
        ko: "유효기간 관리는 어떤 방식으로 하시나요?",
        koRomaja: "yuhyogigan gwallineun eotteon bangsigeuro hasinayo?",
        ja: "使用期限の管理はどのような方法でされていますか？",
        jaReading: "しようきげんのかんりはどのようなほうほうでされていますか？",
      },
      {
        ko: "주사제 무균 조제는 별도 구역에서 하시나요?",
        koRomaja: "jusaje mugyun jojeneun byeoldo guyeogeseo hasinayo?",
        ja: "注射剤の無菌調製は専用区域で行われますか？",
        jaReading: "ちゅうしゃざいのむきんちょうせいはせんようくいきでおこなわれますか？",
      },
    ],
  },
  {
    key: "prescribing",
    role: "pharmacy",
    titleKo: "처방전달체계 질문",
    titleJa: "処方伝達システムの質問",
    emoji: "📡",
    phrases: [
      {
        ko: "처방은 전산으로 약국에 전달되나요?",
        koRomaja: "cheobangeun jeonsaneuro yakguge jeondaldoenayo?",
        ja: "処方は電子的に薬局へ伝達されますか？",
        jaReading: "しょほうはでんしてきにやっきょくへでんたつされますか？",
      },
      {
        ko: "약물 상호작용은 자동으로 점검되나요?",
        koRomaja: "yangmul sanghojagyongeun jadongeuro jeomgeomdoenayo?",
        ja: "薬物相互作用は自動でチェックされますか？",
        jaReading: "やくぶつそうごさようはじどうでチェックされますか？",
      },
      {
        ko: "조제 오류를 어떻게 예방하시나요?",
        koRomaja: "joje oryureul eotteoke yebanghasinayo?",
        ja: "調剤過誤はどのように防いでいらっしゃいますか？",
        jaReading: "ちょうざいかごはどのようにふせいでいらっしゃいますか？",
      },
      {
        ko: "처방 감사(검토)는 누가 담당하나요?",
        koRomaja: "cheobang gamsa(geomto)neun nuga damdanghanayo?",
        ja: "処方監査は誰が担当されますか？",
        jaReading: "しょほうかんさはだれがたんとうされますか？",
        noteKo: "일본의 '処方監査(쇼호칸사)'는 처방 적절성을 약사가 검토하는 과정입니다.",
        noteJa: "韓国語の「처방 감사」は処方監査に当たります。",
      },
      {
        ko: "용량 오류 경고는 시스템에서 어떻게 표시되나요?",
        koRomaja: "yongnyang oryu gyeonggoneun siseutemeseo eotteoke pyosidoenayo?",
        ja: "用量エラーの警告はシステム上でどのように表示されますか？",
        jaReading: "ようりょうエラーのけいこくはシステムじょうでどのようにひょうじされますか？",
      },
      {
        ko: "처방 변경 시 병동에 어떻게 알려지나요?",
        koRomaja: "cheobang byeongyeong si byeongdonge eotteoke allyeojinayo?",
        ja: "処方変更時には病棟へどのように伝わりますか？",
        jaReading: "しょほうへんこうじにはびょうとうへどのようにつたわりますか？",
      },
    ],
  },
  // ────────────────────────────── ADMIN ──────────────────────────────
  {
    key: "coordination",
    role: "admin",
    titleKo: "교류 협약·일정 협의 / 시설 안내·네트워킹",
    titleJa: "交流協定・日程協議 / 施設案内・ネットワーキング",
    emoji: "🤝",
    phrases: [
      {
        ko: "교류 협약 내용을 함께 검토하고 싶습니다.",
        koRomaja: "gyoryu hyeobyak naeyongeul hamkke geomtohago sipseumnida.",
        ja: "交流協定の内容を一緒に確認したいです。",
        jaReading: "こうりゅうきょうていのないようをいっしょにかくにんしたいです。",
        noteKo: "양국 병원 간 협약은 보통 MOU(양해각서) 형태로 체결합니다.",
        noteJa: "両院間の協定は通常MOU（覚書）の形で締結されます。",
      },
      {
        ko: "다음 교류 일정을 협의할 수 있을까요?",
        koRomaja: "daeum gyoryu iljeongeul hyeobuihal su isseulkkayo?",
        ja: "次回の交流日程を協議させていただけますか？",
        jaReading: "じかいのこうりゅうにっていをきょうぎさせていただけますか？",
      },
      {
        ko: "시설 전체를 안내해 주시겠어요?",
        koRomaja: "siseol jeoncheneul annaehae jusigesseoyo?",
        ja: "施設全体をご案内いただけますか？",
        jaReading: "しせつぜんたいをごあんないいただけますか？",
      },
      {
        ko: "다음 방문에는 몇 명의 직원이 참여할 수 있을까요?",
        koRomaja: "daeum bangmuneneun myeot myeongui jigwoni chamyeohal su isseulkkayo?",
        ja: "次回の訪問には何名の職員が参加できますでしょうか？",
        jaReading: "じかいのほうもんにはなんめいのしょくいんがさんかできますでしょうか？",
      },
      {
        ko: "양국 직원 간 정기 교류회를 만들면 좋겠습니다.",
        koRomaja: "yangguk jigwon gan jeonggi gyoryuhoereul mandeulmyeon jokesseumnida.",
        ja: "両国の職員による定期的な交流会を設けられたらと思います。",
        jaReading: "りょうこくのしょくいんによるていきてきなこうりゅうかいをもうけられたらとおもいます。",
      },
      {
        ko: "저녁 식사 자리에 초대해 주셔서 감사합니다.",
        koRomaja: "jeonyeok siksa jarie chodaehae jusyeoseo gamsahamnida.",
        ja: "夕食の席にお招きいただき、ありがとうございます。",
        jaReading: "ゆうしょくのせきにおまねきいただき、ありがとうございます。",
      },
      {
        ko: "통역이 필요하면 미리 준비를 도와드리겠습니다.",
        koRomaja: "tongyeogi piryohamyeon miri junbireul dowadeurigesseumnida.",
        ja: "通訳が必要でしたら、事前に準備をお手伝いいたします。",
        jaReading: "つうやくがひつようでしたら、じぜんにじゅんびをおてつだいいたします。",
      },
    ],
  },
];
