// 의료교류 회화집 — 은성의료재단 ↔ 가마치그룹 직원 상호방문용.
// 모든 문장은 한국어·일본어를 함께 노출하며, jaReading 은 TTS·후리가나용 전체 가나 읽기.
// ⚠️ 임상 표현은 실제 운용 전 양국 병원 직원의 검수가 필요합니다.

import type { MedPhraseGroup } from "./types";

export const MED_PHRASEBOOK: MedPhraseGroup[] = [
  // ────────────────────────────── COMMON ──────────────────────────────
  {
    key: "common-greeting",
    role: "common",
    titleKo: "인사·자기소개",
    titleJa: "挨拶・自己紹介",
    emoji: "👋",
    phrases: [
      {
        ko: "처음 뵙겠습니다. 잘 부탁드립니다.",
        koRomaja: "cheoeum boepgesseumnida. jal butakdeurimnida.",
        ja: "初めまして。どうぞよろしくお願いいたします。",
        jaReading: "はじめまして。どうぞよろしくおねがいいたします。",
        noteKo: "첫 만남에서는 가볍게 목례를 함께 하면 양국 모두 자연스럽습니다.",
        noteJa: "初対面では軽くお辞儀を添えると、両国とも自然です。",
      },
      {
        ko: "은성의료재단에서 온 간호사 김민지입니다.",
        koRomaja: "eunseonguiryojaedaneseo on ganhosa gim minji-imnida.",
        ja: "ウンソン医療財団から参りました看護師のキム・ミンジです。",
        jaReading: "うんそんいりょうざいだんからまいりましたかんごしのキム・ミンジです。",
      },
      {
        ko: "오늘부터 일주일간 견학하게 되었습니다.",
        koRomaja: "oneulbuteo iljuilgan gyeonhakage doeeotseumnida.",
        ja: "本日から一週間、見学させていただきます。",
        jaReading: "ほんじつからいっしゅうかん、けんがくさせていただきます。",
      },
      {
        ko: "만나서 반갑습니다. 많이 배우겠습니다.",
        koRomaja: "mannaseo bangapseumnida. mani baeugesseumnida.",
        ja: "お会いできて光栄です。たくさん学ばせていただきます。",
        jaReading: "おあいできてこうえいです。たくさんまなばせていただきます。",
      },
      {
        ko: "제 일본어가 서툴러서 천천히 말씀해 주시면 감사하겠습니다.",
        koRomaja: "je ilboneoga seotulleoseo cheoncheonhi malsseumhae jusimyeon gamsahagesseumnida.",
        ja: "日本語が不慣れですので、ゆっくり話していただけると助かります。",
        jaReading: "にほんごがふなれですので、ゆっくりはなしていただけるとたすかります。",
      },
      {
        ko: "도와주셔서 정말 감사합니다.",
        koRomaja: "dowajusyeoseo jeongmal gamsahamnida.",
        ja: "お力添えいただき、本当にありがとうございます。",
        jaReading: "おちからぞえいただき、ほんとうにありがとうございます。",
      },
    ],
  },
  {
    key: "common-directions",
    role: "common",
    titleKo: "병원 안내·길찾기",
    titleJa: "院内案内・道案内",
    emoji: "🧭",
    phrases: [
      {
        ko: "외래 접수처는 어디에 있습니까?",
        koRomaja: "oerae jeopsucheoneun eodie itseumnikka?",
        ja: "外来の受付はどこにありますか。",
        jaReading: "がいらいのうけつけはどこにありますか。",
      },
      {
        ko: "병동은 3층으로 올라가시면 됩니다.",
        koRomaja: "byeongdongeun samcheungeuro ollagasimyeon doemnida.",
        ja: "病棟は3階に上がっていただければと思います。",
        jaReading: "びょうとうはさんがいにあがっていただければとおもいます。",
      },
      {
        ko: "엘리베이터는 복도 끝 오른쪽에 있습니다.",
        koRomaja: "ellibeiteoneun bokdo kkeut oreunjjoge itseumnida.",
        ja: "エレベーターは廊下の突き当たりの右側にあります。",
        jaReading: "エレベーターはろうかのつきあたりのみぎがわにあります。",
      },
      {
        ko: "제가 검사실까지 안내해 드리겠습니다.",
        koRomaja: "jega geomsasilkkaji annaehae deurigesseumnida.",
        ja: "検査室までご案内いたします。",
        jaReading: "けんさしつまでごあんないいたします。",
      },
      {
        ko: "화장실은 간호사실 바로 옆에 있습니다.",
        koRomaja: "hwajangsireun ganhosasil baro yeope itseumnida.",
        ja: "お手洗いはナースステーションのすぐ隣にあります。",
        jaReading: "おてあらいはナースステーションのすぐとなりにあります。",
      },
      {
        ko: "길을 잃으시면 직원에게 말씀해 주세요.",
        koRomaja: "gireul ireusimyeon jigwonege malsseumhae juseyo.",
        ja: "道に迷われたら、スタッフにお声がけください。",
        jaReading: "みちにまよわれたら、スタッフにおこえがけください。",
      },
    ],
  },
  {
    key: "common-schedule",
    role: "common",
    titleKo: "일정·견학",
    titleJa: "日程・見学",
    emoji: "🗓️",
    phrases: [
      {
        ko: "오늘 견학 일정을 알려 주시겠습니까?",
        koRomaja: "oneul gyeonhak iljeongeul allyeo jusigesseumnikka?",
        ja: "本日の見学スケジュールを教えていただけますか。",
        jaReading: "ほんじつのけんがくスケジュールをおしえていただけますか。",
      },
      {
        ko: "회진을 참관해도 괜찮을까요?",
        koRomaja: "hoejineul chamgwanhaedo gwaenchaneulkkayo?",
        ja: "回診を見学させていただいてもよろしいでしょうか。",
        jaReading: "かいしんをけんがくさせていただいてもよろしいでしょうか。",
      },
      {
        ko: "사진을 촬영해도 괜찮을지 여쭤봐도 될까요?",
        koRomaja: "sajineul chwalyeonghaedo gwaenchaneulji yeojjwobwado doelkkayo?",
        ja: "写真を撮ってもよいか伺ってもよろしいですか。",
        jaReading: "しゃしんをとってもよいかうかがってもよろしいですか。",
        noteKo: "환자 정보 보호를 위해 촬영 전 반드시 허가를 받으세요.",
        noteJa: "患者情報保護のため、撮影前に必ず許可を得てください。",
      },
      {
        ko: "다음 일정은 몇 시에 시작합니까?",
        koRomaja: "daeum iljeongeun myeot sie sijakamnikka?",
        ja: "次のプログラムは何時から始まりますか。",
        jaReading: "つぎのプログラムはなんじからはじまりますか。",
      },
      {
        ko: "점심시간은 한 시간 정도 주어집니다.",
        koRomaja: "jeomsimsiganeun han sigan jeongdo jueojimnida.",
        ja: "昼休みは一時間ほど取っていただけます。",
        jaReading: "ひるやすみはいちじかんほどとっていただけます。",
      },
    ],
  },

  // ────────────────────────────── DOCTOR ──────────────────────────────
  {
    key: "doctor-rounds",
    role: "doctor",
    titleKo: "회진·환자 인계",
    titleJa: "回診・患者引き継ぎ",
    emoji: "🩺",
    phrases: [
      {
        ko: "이 환자분은 어제 입원하셨습니다.",
        koRomaja: "i hwanjabuneun eoje ibwonhasyeotseumnida.",
        ja: "この患者さんは昨日入院されました。",
        jaReading: "このかんじゃさんはきのうにゅういんされました。",
      },
      {
        ko: "혈압과 체온은 안정적입니다.",
        koRomaja: "hyeolapgwa cheoneun anjeongjeogimnida.",
        ja: "血圧と体温は安定しています。",
        jaReading: "けつあつとたいおんはあんていしています。",
      },
      {
        ko: "어젯밤부터 통증을 호소하고 있습니다.",
        koRomaja: "eojetbambuteo tongjeungeul hosohago itseumnida.",
        ja: "昨夜から痛みを訴えておられます。",
        jaReading: "さくやからいたみをうったえておられます。",
      },
      {
        ko: "검사 결과를 보고 치료 방침을 정하겠습니다.",
        koRomaja: "geomsa gyeolgwareul bogo chiryo bangchimeul jeonghagesseumnida.",
        ja: "検査結果を見て治療方針を決めましょう。",
        jaReading: "けんさけっかをみてちりょうほうしんをきめましょう。",
      },
      {
        ko: "수술 후 경과는 양호합니다.",
        koRomaja: "susul hu gyeonggwaneun yanghohamnida.",
        ja: "術後の経過は良好です。",
        jaReading: "じゅつごのけいかはりょうこうです。",
      },
      {
        ko: "다음 회진 때 다시 확인하겠습니다.",
        koRomaja: "daeum hoejin ttae dasi hwaginhagesseumnida.",
        ja: "次の回診で改めて確認いたします。",
        jaReading: "つぎのかいしんであらためてかくにんいたします。",
      },
    ],
  },
  {
    key: "doctor-findings",
    role: "doctor",
    titleKo: "진료·소견 설명",
    titleJa: "診察・所見説明",
    emoji: "📋",
    phrases: [
      {
        ko: "검사 결과 큰 이상은 발견되지 않았습니다.",
        koRomaja: "geomsa gyeolgwa keun isangeun balgyeondoeji anatseumnida.",
        ja: "検査の結果、大きな異常は見られませんでした。",
        jaReading: "けんさのけっか、おおきないじょうはみられませんでした。",
      },
      {
        ko: "염증 수치가 조금 높게 나왔습니다.",
        koRomaja: "yeomjeung suchiga jogeum nopge nawatseumnida.",
        ja: "炎症の数値が少し高めに出ています。",
        jaReading: "えんしょうのすうちがすこしたかめにでています。",
      },
      {
        ko: "당분간 약물 치료를 이어가겠습니다.",
        koRomaja: "dangbungan yangmul chiryoreul ieogagesseumnida.",
        ja: "しばらく薬物療法を続けてまいります。",
        jaReading: "しばらくやくぶつりょうほうをつづけてまいります。",
      },
      {
        ko: "통증이 심해지면 바로 알려 주세요.",
        koRomaja: "tongjeungi simhaejimyeon baro allyeo juseyo.",
        ja: "痛みがひどくなったら、すぐにお知らせください。",
        jaReading: "いたみがひどくなったら、すぐにおしらせください。",
      },
      {
        ko: "궁금한 점이 있으시면 언제든 말씀해 주세요.",
        koRomaja: "gunggeumhan jeomi isseusimyeon eonjedeun malsseumhae juseyo.",
        ja: "ご不明な点があれば、いつでもお尋ねください。",
        jaReading: "ごふめいなてんがあれば、いつでもおたずねください。",
        noteKo: "환자에게 설명할 때는 전문용어를 풀어 쉽게 전달합니다.",
        noteJa: "患者さんへの説明では専門用語をかみ砕いて伝えます。",
      },
      {
        ko: "일주일 후에 다시 진료받으러 오세요.",
        koRomaja: "iljuil hue dasi jillyobadeureo oseyo.",
        ja: "一週間後に再度受診してください。",
        jaReading: "いっしゅうかんごにさいどじゅしんしてください。",
      },
    ],
  },

  // ────────────────────────────── NURSE ──────────────────────────────
  {
    key: "nurse-handover",
    role: "nurse",
    titleKo: "병동 인계",
    titleJa: "申し送り",
    emoji: "🔁",
    phrases: [
      {
        ko: "지금부터 인계 시작하겠습니다.",
        koRomaja: "jigeumbuteo ingye sijakhagesseumnida.",
        ja: "これより申し送りを始めます。",
        jaReading: "これよりもうしおくりをはじめます。",
        noteKo: "일본 병동의 '申し送り(모시오쿠리)'는 한국의 '인계'에 해당하며, 환자별 상태를 순서대로 전달합니다.",
        noteJa: "韓国の「인계(インゲ)」は日本の「申し送り」に当たり、患者ごとに順を追って伝えます。",
      },
      {
        ko: "302호 환자분은 밤사이 특이사항 없었습니다.",
        koRomaja: "sambaegiho hwanjabuneun bamsai teugisahang eopseotseumnida.",
        ja: "302号室の患者さんは夜間、特記事項ありませんでした。",
        jaReading: "さんまるにごうしつのかんじゃさんはやかん、とっきじこうありませんでした。",
      },
      {
        ko: "수액은 오전 10시에 교체 예정입니다.",
        koRomaja: "suaegeun ojeon yeolsie gyoche yejeongimnida.",
        ja: "点滴は午前10時に交換予定です。",
        jaReading: "てんてきはごぜんじゅうじにこうかんよていです。",
      },
      {
        ko: "낙상 위험이 있어 주의가 필요합니다.",
        koRomaja: "naksang wiheomi isseo juuiga piryohamnida.",
        ja: "転倒のリスクがあり、注意が必要です。",
        jaReading: "てんとうのリスクがあり、ちゅういがひつようです。",
      },
      {
        ko: "금식 환자이니 식사 제공하지 마세요.",
        koRomaja: "geumsik hwanjaini siksa jegonghaji maseyo.",
        ja: "絶食の患者さんですので、食事は出さないでください。",
        jaReading: "ぜっしょくのかんじゃさんですので、しょくじはださないでください。",
      },
      {
        ko: "이상으로 인계 마치겠습니다. 잘 부탁드립니다.",
        koRomaja: "isangeuro ingye machigesseumnida. jal butakdeurimnida.",
        ja: "以上で申し送りを終わります。よろしくお願いします。",
        jaReading: "いじょうでもうしおくりをおわります。よろしくおねがいします。",
      },
    ],
  },
  {
    key: "nurse-medication",
    role: "nurse",
    titleKo: "투약·처치",
    titleJa: "投薬・処置",
    emoji: "💉",
    phrases: [
      {
        ko: "성함과 생년월일을 확인하겠습니다.",
        koRomaja: "seonghamgwa saengnyeonworireul hwaginhagesseumnida.",
        ja: "お名前と生年月日を確認させていただきます。",
        jaReading: "おなまえとせいねんがっぴをかくにんさせていただきます。",
        noteKo: "투약 전 환자 본인 확인은 양국 공통 안전 수칙입니다.",
        noteJa: "投薬前の本人確認は両国共通の安全手順です。",
      },
      {
        ko: "지금 혈압을 측정하겠습니다.",
        koRomaja: "jigeum hyeolabeul cheukjeonghagesseumnida.",
        ja: "これから血圧を測ります。",
        jaReading: "これからけつあつをはかります。",
      },
      {
        ko: "주사를 놓겠습니다. 따끔할 수 있습니다.",
        koRomaja: "jusareul nokesseumnida. ttakkeumhal su itseumnida.",
        ja: "注射をします。チクッとします。",
        jaReading: "ちゅうしゃをします。チクッとします。",
      },
      {
        ko: "수액 속도를 조절하겠습니다.",
        koRomaja: "suaek sokdoreul jojeolhagesseumnida.",
        ja: "点滴の速度を調整します。",
        jaReading: "てんてきのそくどをちょうせいします。",
      },
      {
        ko: "이 약은 식후 30분에 복용하시면 됩니다.",
        koRomaja: "i yageun siku samsipbune bogyonghasimyeon doemnida.",
        ja: "この薬は食後30分に服用してください。",
        jaReading: "このくすりはしょくごさんじゅっぷんにふくようしてください。",
      },
      {
        ko: "상처 부위를 소독하겠습니다.",
        koRomaja: "sangcheo buwireul sodokagesseumnida.",
        ja: "傷口を消毒します。",
        jaReading: "きずぐちをしょうどくします。",
      },
    ],
  },
  {
    key: "nurse-patient-care",
    role: "nurse",
    titleKo: "환자·보호자 응대",
    titleJa: "患者・ご家族対応",
    emoji: "🤝",
    phrases: [
      {
        ko: "어디가 불편하신가요?",
        koRomaja: "eodiga bulpyeonhasingayo?",
        ja: "どちらがつらいですか。",
        jaReading: "どちらがつらいですか。",
      },
      {
        ko: "통증을 0에서 10 사이로 표현하면 어느 정도인가요?",
        koRomaja: "tongjeungeul gongeseo sip sairo pyohyeonhamyeon eoneu jeongdoingayo?",
        ja: "痛みを0から10で表すと、どのくらいですか。",
        jaReading: "いたみをゼロからじゅうであらわすと、どのくらいですか。",
      },
      {
        ko: "잠시 후에 다시 살펴보러 오겠습니다.",
        koRomaja: "jamsi hue dasi salpyeoboreo ogesseumnida.",
        ja: "また後ほど様子を見に伺います。",
        jaReading: "またのちほどようすをみにうかがいます。",
      },
      {
        ko: "보호자분은 면회 시간에 와 주시기 바랍니다.",
        koRomaja: "bohojabuneun myeonhoe sigane wa jusigi baramnida.",
        ja: "ご家族は面会時間にお越しください。",
        jaReading: "ごかぞくはめんかいじかんにおこしください。",
      },
      {
        ko: "필요하시면 호출벨을 눌러 주세요.",
        koRomaja: "piryohasimyeon hochulbereul nulleo juseyo.",
        ja: "必要なときはナースコールを押してください。",
        jaReading: "ひつようなときはナースコールをおしてください。",
      },
      {
        ko: "곧 편안해지실 거예요. 걱정 마세요.",
        koRomaja: "got pyeonanhaejisil geoyeyo. geokjeong maseyo.",
        ja: "すぐに楽になりますよ。ご安心ください。",
        jaReading: "すぐにらくになりますよ。ごあんしんください。",
      },
    ],
  },

  // ────────────────────────────── EXAM ──────────────────────────────
  {
    key: "exam-guide",
    role: "exam",
    titleKo: "검사 안내",
    titleJa: "検査案内",
    emoji: "🩻",
    phrases: [
      {
        ko: "지금부터 엑스레이 촬영을 하겠습니다.",
        koRomaja: "jigeumbuteo ekseurei chwalyeongeul hagesseumnida.",
        ja: "これからレントゲン撮影を行います。",
        jaReading: "これからレントゲンさつえいをおこないます。",
      },
      {
        ko: "검사대 위에 똑바로 누워 주세요.",
        koRomaja: "geomsadae wie ttokbaro nuwo juseyo.",
        ja: "検査台にまっすぐ仰向けに寝てください。",
        jaReading: "けんさだいにまっすぐあおむけにねてください。",
      },
      {
        ko: "숨을 크게 들이마시고 잠시 멈춰 주세요.",
        koRomaja: "sumeul keuge deurimasigo jamsi meomchwo juseyo.",
        ja: "大きく息を吸って、少し止めてください。",
        jaReading: "おおきくいきをすって、すこしとめてください。",
      },
      {
        ko: "CT 촬영은 약 10분 정도 걸립니다.",
        koRomaja: "ssiti chwalyeongeun yak sipbun jeongdo geollimnida.",
        ja: "CT撮影はおよそ10分ほどかかります。",
        jaReading: "シーティーさつえいはおよそじゅっぷんほどかかります。",
      },
      {
        ko: "채혈을 하겠습니다. 팔을 펴 주세요.",
        koRomaja: "chaehyeoreul hagesseumnida. pareul pyeo juseyo.",
        ja: "採血をします。腕を伸ばしてください。",
        jaReading: "さいけつをします。うでをのばしてください。",
      },
      {
        ko: "끝났습니다. 천천히 일어나셔도 됩니다.",
        koRomaja: "kkeunnatseumnida. cheoncheonhi ireonasyeodo doemnida.",
        ja: "終わりました。ゆっくり起き上がっていただいて大丈夫です。",
        jaReading: "おわりました。ゆっくりおきあがっていただいてだいじょうぶです。",
      },
    ],
  },
  {
    key: "exam-prep",
    role: "exam",
    titleKo: "검사 준비·주의",
    titleJa: "検査準備・注意",
    emoji: "⚠️",
    phrases: [
      {
        ko: "검사 전날 밤 9시부터 금식해 주세요.",
        koRomaja: "geomsa jeonnal bam ahopsibuteo geumsikae juseyo.",
        ja: "検査前日の夜9時から絶食してください。",
        jaReading: "けんさぜんじつのよるくじからぜっしょくしてください。",
        noteKo: "공복 검사는 시간이 어긋나면 재예약이 필요하므로 정확히 안내하세요.",
        noteJa: "空腹検査は時間がずれると再予約になるため、正確に案内します。",
      },
      {
        ko: "금속이 들어간 물건은 모두 빼 주세요.",
        koRomaja: "geumsogi deureogan mulgeoneun modu ppae juseyo.",
        ja: "金属の付いた物はすべて外してください。",
        jaReading: "きんぞくのついたものはすべてはずしてください。",
      },
      {
        ko: "조영제 알레르기가 있으신가요?",
        koRomaja: "joyeongje allereugiga isseusingayo?",
        ja: "造影剤のアレルギーはありますか。",
        jaReading: "ぞうえいざいのアレルギーはありますか。",
      },
      {
        ko: "검사복으로 갈아입어 주시겠어요?",
        koRomaja: "geomsabogeuro garaibeo jusigesseoyo?",
        ja: "検査着にお着替えいただけますか。",
        jaReading: "けんさぎにおきがえいただけますか。",
      },
      {
        ko: "검사 중 몸을 움직이지 마세요.",
        koRomaja: "geomsa jung momeul umjigiji maseyo.",
        ja: "検査中は体を動かさないでください。",
        jaReading: "けんさちゅうはからだをうごかさないでください。",
      },
      {
        ko: "임신 가능성이 있으면 미리 알려 주세요.",
        koRomaja: "imsin ganeungseongi isseumyeon miri allyeo juseyo.",
        ja: "妊娠の可能性があれば、事前にお知らせください。",
        jaReading: "にんしんのかのうせいがあれば、じぜんにおしらせください。",
      },
    ],
  },

  // ────────────────────────────── PHARMACY ──────────────────────────────
  {
    key: "pharmacy-instructions",
    role: "pharmacy",
    titleKo: "복약 지도",
    titleJa: "服薬指導",
    emoji: "💊",
    phrases: [
      {
        ko: "이 약은 하루 세 번, 식후에 드세요.",
        koRomaja: "i yageun haru se beon, sikue deuseyo.",
        ja: "この薬は一日三回、食後に服用してください。",
        jaReading: "このくすりはいちにちさんかい、しょくごにふくようしてください。",
      },
      {
        ko: "이 약을 드시면 졸릴 수 있으니 운전은 삼가세요.",
        koRomaja: "i yageul deusimyeon jollil su isseuni unjeoneun samgaseyo.",
        ja: "この薬は眠気が出ることがあるので、運転は控えてください。",
        jaReading: "このくすりはねむけがでることがあるので、うんてんはひかえてください。",
        noteKo: "부작용 안내는 환자가 이해했는지 다시 확인하는 것이 좋습니다.",
        noteJa: "副作用の説明は、患者さんが理解できたか再確認すると安心です。",
      },
      {
        ko: "약은 정해진 시간에 잊지 말고 드세요.",
        koRomaja: "yageun jeonghaejin sigane itji malgo deuseyo.",
        ja: "薬は決められた時間に忘れずに飲んでください。",
        jaReading: "くすりはきめられたじかんにわすれずにのんでください。",
      },
      {
        ko: "복용 중 발진이 생기면 즉시 중단하고 연락 주세요.",
        koRomaja: "bogyong jung baljini saenggimyeon jeuksi jungdanhago yeollak juseyo.",
        ja: "服用中に発疹が出たら、すぐに中止してご連絡ください。",
        jaReading: "ふくようちゅうにほっしんがでたら、すぐにちゅうししてごれんらくください。",
      },
      {
        ko: "다른 약과 함께 드시는 약이 있나요?",
        koRomaja: "dareun yakgwa hamkke deusineun yagi innayo?",
        ja: "ほかに併用しているお薬はありますか。",
        jaReading: "ほかにへいようしているおくすりはありますか。",
      },
      {
        ko: "남은 약은 다음 진료 때 가져와 주세요.",
        koRomaja: "nameun yageun daeum jillyo ttae gajyeowa juseyo.",
        ja: "残ったお薬は次回の診察にお持ちください。",
        jaReading: "のこったおくすりはじかいのしんさつにおもちください。",
      },
    ],
  },
  {
    key: "pharmacy-dispensing",
    role: "pharmacy",
    titleKo: "처방·조제 확인",
    titleJa: "処方・調剤確認",
    emoji: "📑",
    phrases: [
      {
        ko: "처방전을 확인하겠습니다.",
        koRomaja: "cheobangjeoneul hwaginhagesseumnida.",
        ja: "処方箋を確認いたします。",
        jaReading: "しょほうせんをかくにんいたします。",
      },
      {
        ko: "이 처방은 용량이 평소보다 높은데 확인 부탁드립니다.",
        koRomaja: "i cheobangeun yongnyangi pyeongsoboda nopeunde hwagin butakdeurimnida.",
        ja: "この処方は用量がいつもより多いので、ご確認をお願いします。",
        jaReading: "このしょほうはようりょうがいつもよりおおいので、ごかくにんをおねがいします。",
        noteKo: "용량 의문점은 반드시 처방의에게 더블체크를 요청합니다.",
        noteJa: "用量の疑問点は必ず処方医にダブルチェックを依頼します。",
      },
      {
        ko: "조제가 끝나면 성함을 불러 드리겠습니다.",
        koRomaja: "jojega kkeunnamyeon seonghameul bulleo deurigesseumnida.",
        ja: "調剤が終わりましたら、お名前をお呼びします。",
        jaReading: "ちょうざいがおわりましたら、おなまえをおよびします。",
      },
      {
        ko: "약물 상호작용 여부를 확인했습니다.",
        koRomaja: "yangmul sanghojagyong yeobureul hwaginhaetseumnida.",
        ja: "薬の相互作用がないか確認しました。",
        jaReading: "くすりのそうごさようがないかかくにんしました。",
      },
      {
        ko: "알레르기 이력이 있으신지 확인하겠습니다.",
        koRomaja: "allereugi iryeogi isseusinji hwaginhagesseumnida.",
        ja: "アレルギー歴があるか確認させていただきます。",
        jaReading: "アレルギーれきがあるかかくにんさせていただきます。",
      },
      {
        ko: "약은 모두 세 종류이며, 봉투에 나누어 담았습니다.",
        koRomaja: "yageun modu se jongnyuimyeo, bongtue nanueo damatseumnida.",
        ja: "お薬は全部で三種類で、袋に分けてお入れしました。",
        jaReading: "おくすりはぜんぶでさんしゅるいで、ふくろにわけておいれしました。",
      },
    ],
  },

  // ────────────────────────────── ADMIN ──────────────────────────────
  {
    key: "admin-reception",
    role: "admin",
    titleKo: "접수·수속",
    titleJa: "受付・手続き",
    emoji: "🧾",
    phrases: [
      {
        ko: "진료 접수를 도와드리겠습니다.",
        koRomaja: "jillyo jeopsureul dowadeurigesseumnida.",
        ja: "受診の受付をお手伝いいたします。",
        jaReading: "じゅしんのうけつけをおてつだいいたします。",
      },
      {
        ko: "보험증을 보여 주시겠어요?",
        koRomaja: "boheomjeungeul boyeo jusigesseoyo?",
        ja: "保険証を見せていただけますか。",
        jaReading: "ほけんしょうをみせていただけますか。",
        noteKo: "한일 의료보험 제도가 달라 외국인 환자는 별도 안내가 필요할 수 있습니다.",
        noteJa: "日韓で医療保険制度が異なるため、外国人患者には別途案内が必要な場合があります。",
      },
      {
        ko: "이 서류에 성함과 연락처를 적어 주세요.",
        koRomaja: "i seoryue seonghamgwa yeollakcheoreul jeogeo juseyo.",
        ja: "こちらの書類にお名前とご連絡先をご記入ください。",
        jaReading: "こちらのしょるいにおなまえとごれんらくさきをごきにゅうください。",
      },
      {
        ko: "입원 수속은 2층 원무과에서 진행됩니다.",
        koRomaja: "ibwon susogeun icheung wonmugwaeseo jinhaengdoemnida.",
        ja: "入院手続きは2階の医事課で行います。",
        jaReading: "にゅういんてつづきはにかいのいじかでおこないます。",
      },
      {
        ko: "수납은 진료 후 1층 창구에서 해 주세요.",
        koRomaja: "sunabeun jillyo hu icheung changgueseo hae juseyo.",
        ja: "お会計は診察後、1階の窓口でお願いします。",
        jaReading: "おかいけいはしんさつご、いっかいのまどぐちでおねがいします。",
      },
      {
        ko: "다음 예약은 언제로 잡아 드릴까요?",
        koRomaja: "daeum yeyageun eonjero jaba deurilkkayo?",
        ja: "次回のご予約はいつにいたしましょうか。",
        jaReading: "じかいのごよやくはいつにいたしましょうか。",
      },
    ],
  },
  {
    key: "admin-exchange",
    role: "admin",
    titleKo: "견학·교류 행정",
    titleJa: "見学・交流の事務",
    emoji: "🌏",
    phrases: [
      {
        ko: "견학 신청서를 미리 제출해 주시기 바랍니다.",
        koRomaja: "gyeonhak sincheongseoreul miri jechulhae jusigi baramnida.",
        ja: "見学申込書を事前にご提出ください。",
        jaReading: "けんがくもうしこみしょをじぜんにごていしゅつください。",
      },
      {
        ko: "출입증을 발급해 드리겠습니다.",
        koRomaja: "churipjeungeul balgeuphae deurigesseumnida.",
        ja: "入館証を発行いたします。",
        jaReading: "にゅうかんしょうをはっこういたします。",
      },
      {
        ko: "비밀유지 서약서에 서명을 부탁드립니다.",
        koRomaja: "bimiryuji seoyakseoe seomyeongeul butakdeurimnida.",
        ja: "守秘義務の誓約書にご署名をお願いします。",
        jaReading: "しゅひぎむのせいやくしょにごしょめいをおねがいします。",
        noteKo: "환자 정보 보호를 위해 견학자도 비밀유지 서약이 필요합니다.",
        noteJa: "患者情報保護のため、見学者にも守秘義務の誓約が必要です。",
      },
      {
        ko: "교류 일정표는 이메일로 보내 드리겠습니다.",
        koRomaja: "gyoryu iljeongpyoneun imeillo bonae deurigesseumnida.",
        ja: "交流のスケジュール表はメールでお送りします。",
        jaReading: "こうりゅうのスケジュールひょうはメールでおおくりします。",
      },
      {
        ko: "통역이 필요하시면 미리 말씀해 주세요.",
        koRomaja: "tongyeogi piryohasimyeon miri malsseumhae juseyo.",
        ja: "通訳が必要でしたら、事前にお知らせください。",
        jaReading: "つうやくがひつようでしたら、じぜんにおしらせください。",
      },
      {
        ko: "방문 후 설문조사에 협조해 주시면 감사하겠습니다.",
        koRomaja: "bangmun hu seolmunjosae hyeopjohae jusimyeon gamsahagesseumnida.",
        ja: "訪問後のアンケートにご協力いただけますと幸いです。",
        jaReading: "ほうもんごのアンケートにごきょうりょくいただけますとさいわいです。",
      },
    ],
  },
];
